//! Runtime, session, and Telnet diagnostics exposed to connected players.
use super::*;

impl Server {
    /// MSSP snapshots are generated by the world owner at confirmed enablement.
    pub(super) fn mssp(&self, id: SessionId) {
        let fields = [
            ("NAME", self.config.server.mud_name.clone()),
            (
                "PLAYERS",
                self.sessions
                    .values()
                    .filter(|s| s.player.is_some())
                    .count()
                    .to_string(),
            ),
            ("UPTIME", self.started_at.to_string()),
            ("CODEBASE", env!("CARGO_PKG_NAME").into()),
            ("PORT", self.listen_port.to_string()),
        ];
        let mut payload = Vec::new();
        for (name, value) in fields {
            payload.push(1);
            payload.extend(name.bytes());
            payload.push(2);
            payload.extend(
                value
                    .chars()
                    .filter(|c| !c.is_control())
                    .collect::<String>()
                    .bytes(),
            );
        }
        if let Some(session) = self.sessions.get(&id) {
            session.protocol(
                vec![telnet::Decoder::sub_reply(telnet::MSSP, &payload)],
                &self.config,
            );
        }
    }
    /// Color overrides never affect another connection or persistent account state.
    pub(super) fn color(&self, id: SessionId, mode: &str) {
        use crate::text::ColorDepth;
        let Some(session) = self.sessions.get(&id) else {
            return;
        };
        let mode = mode.trim().to_ascii_lowercase();
        let reply = if mode.is_empty() {
            format!(
                "Color mode: {}{}. Client capability: {}{}.",
                session
                    .color_override
                    .get()
                    .map_or("auto", ColorDepth::name),
                if session.color_override.get().is_some() {
                    " (override)"
                } else {
                    ""
                },
                ColorDepth::advertised(session.decoder.color_depth).name(),
                if session.decoder.screen_reader {
                    ", screen reader"
                } else {
                    ""
                }
            )
        } else {
            let selected = match mode.as_str() {
                "auto" => None,
                "off" => Some(ColorDepth::None),
                "16" => Some(ColorDepth::Ansi16),
                "256" => Some(ColorDepth::Ansi256),
                "truecolor" => Some(ColorDepth::Truecolor),
                _ => {
                    self.tell(id, "Use color auto, off, 16, 256, or truecolor.\r\n");
                    return;
                }
            };
            session.color_override.set(selected);
            format!(
                "Color mode set to {}.",
                selected.map_or("auto", ColorDepth::name)
            )
        };
        self.tell(id, &format!("{reply}\r\n"));
    }

    /// Read-only, invoking-session-only connection statistics in stable session-ID order.
    pub(super) fn session_diagnostics(&self, id: SessionId, prefix: &str) {
        let mut report = telnet::diagnostics::Report::new(self.config.runtime.output_message_limit);
        let headers = [
            "Player Name",
            "On For",
            "Idle",
            "Session",
            "In Pend",
            "In Lost",
            "In Total",
            "Out Pend",
            "Out Lost",
            "Out Total",
        ];
        let mut rows = Vec::new();
        let world = self.scripts.world.borrow();
        let mut count = 0;
        for (sid, session) in &self.sessions {
            let Some(player) = session.player else {
                continue;
            };
            let name = crate::text::plain_with(&self.scripts.palette, &world.objects[&player].name);
            if !name
                .to_lowercase()
                .starts_with(&prefix.trim().to_lowercase())
            {
                continue;
            }
            count += 1;
            let mut stats = session.stats.snapshot();
            stats.input[0] += session.decoder.pending_text() as u64;
            rows.push([
                telnet::diagnostics::escape(crate::text::literal_prefix(&name, 16).as_bytes()),
                telnet::diagnostics::connected_time(session.connected.elapsed().as_secs()),
                crate::operations::session_idle(session.active.elapsed().as_secs()),
                sid.0.to_string(),
                stats.input[0].to_string(),
                stats.input[1].to_string(),
                stats.input[2].to_string(),
                stats.output[0].to_string(),
                stats.output[1].to_string(),
                stats.output[2].to_string(),
            ]);
        }
        // Size columns from this snapshot so large counters cannot shift later columns.
        let widths: [usize; 10] = std::array::from_fn(|column| {
            rows.iter()
                .map(|row| row[column].len())
                .chain(std::iter::once(headers[column].len()))
                .max()
                .unwrap()
        });
        let format_row = |row: [&str; 10]| {
            row.iter()
                .enumerate()
                .map(|(column, value)| {
                    let width = widths[column];
                    if column == 0 {
                        format!("{value:<width$}")
                    } else {
                        format!("{value:>width$}")
                    }
                })
                .collect::<Vec<_>>()
                .join("  ")
        };
        report.line(&format_row(headers));
        for row in &rows {
            report.line(&format_row(std::array::from_fn(|column| {
                row[column].as_str()
            })));
            if report.full() {
                break;
            }
        }
        report.line(&format!(
            "{count} Player{} logged in, {} record, {} maximum.",
            if count == 1 { "" } else { "s" },
            world.record_players,
            if self.config.mux.max_players == -1 {
                "no".into()
            } else {
                self.config.mux.max_players.to_string()
            }
        ));
        if let Some(session) = self.sessions.get(&id) {
            session.raw(report.finish());
        }
    }
    /// Player lookup follows login identity rules; no object visibility filter hides Wizard diagnostics.
    pub(super) fn telnet_diagnostics(&self, id: SessionId, name: &str) {
        let mut report = telnet::diagnostics::Report::new(self.config.runtime.output_message_limit);
        let world = self.scripts.world.borrow();
        if name.is_empty() {
            report.line("Usage: @telnet <player>");
        } else if let Some(player) = world.find_player(name) {
            let mut found = false;
            for (sid, session) in &self.sessions {
                if session.player == Some(player) {
                    found = true;
                    let ansi = world.objects[&player]
                        .flags
                        .contains(crate::flags::Flag::Ansi);
                    let options = session.render_options(ansi);
                    report.line(&format!(
                        "Color effective: {}; override: {}; OSC capabilities: {}",
                        options.color.name(),
                        session
                            .color_override
                            .get()
                            .map_or("auto", crate::text::ColorDepth::name),
                        options
                            .capabilities
                            .iter()
                            .map(|suffix| {
                                if suffix.is_empty() {
                                    "OSC_HYPERLINKS".to_owned()
                                } else {
                                    format!("OSC_HYPERLINKS_{suffix}")
                                }
                            })
                            .collect::<Vec<_>>()
                            .join(", ")
                    ));
                    report.line(&format!(
                        "Peer: {}; site access: {}; site status: {}",
                        session.peer,
                        if session.site.forbidden {
                            "Forbidden"
                        } else {
                            "Unrestricted"
                        },
                        if session.site.suspect {
                            "Suspected"
                        } else {
                            "Trusted"
                        }
                    ));
                    telnet::diagnostics::telnet(
                        &mut report,
                        &world.objects[&player].name,
                        player.0,
                        sid.0,
                        &session.decoder,
                        &session.stats.snapshot(),
                    );
                    if report.full() {
                        break;
                    }
                }
            }
            if !found {
                report.line("That player is not connected.");
            }
        } else {
            report.line("No such player.");
        }
        if let Some(session) = self.sessions.get(&id) {
            session.raw(report.finish());
        }
    }
}
