#!/bin/sh
#
#	Startmux - Kick off the stompymux process.
#
export LD_LIBRARY_PATH=/usr/local/lib
PATH=/usr/ucb:/bin:/usr/bin:.; export PATH
#

BIN=./bin
DATA=./data
LOGS=./logs
LOGFILE=$LOGS/stompymux.log

#
#	Make sure there isn't aready a MUX running.
#

#nmux=`ps -C stompymux l | egrep "stompymux stompymux.conf"`
numx=`ps ax | sed -e '/grep/d' | grep "stompymux stompymux.toml"`
if [ "$?" -ne 1 ]; then
    echo "Another copy of stompymux is running"
    echo "Check ps ax"
	exit 0
fi

#
#	Kick off MUX
#
ulimit -c unlimited
if [ -f $LOGFILE ]; then
	mv -f $LOGFILE $LOGFILE.old
fi
if [ -x $BIN/stompymux ]; then
	echo Starting stompymux binary.
	$BIN/stompymux stompymux.toml >>$LOGFILE 2>&1
else
	echo No binary found!
	exit 1
fi
	
