//! Public Lua facade construction for the BattleTech package.

use super::*;

/// Publish the canonical namespace with explicit asset/read-only identity operations.
pub(in crate::lua::packages) fn install(lua: &Lua, api: &Table, mux: &Table) -> mlua::Result<()> {
    let native: Table = api.get("btech")?;
    let package = lua.create_table()?;
    // Native key -> C-qualified public spelling ("<group>.<name>"), used by
    // checking-mode restriction to raise C's per-entry unavailability message.
    let qualified_names = lua.create_table()?;
    for (group, name, method) in [
        ("runtime", "runtime_stats", "stats"),
        ("unit", "unit_set_team", "set_team"),
        ("unit", "unit_losemit", "losemit"),
        ("unit", "unit_damage_section", "damage_section"),
        ("unit", "unit_damage", "damage"),
        ("unit", "unit_weight", "weight"),
        ("unit", "unit_setxy", "setxy"),
        ("unit", "unit_fields", "fields"),
        ("unit", "unit_set_field", "set_field"),
        ("unit", "unit_ood", "ood"),
        ("unit", "unit_setmapindex", "setmapindex"),
        ("unit", "unit_markings", "markings"),
        ("unit", "unit_set_markings", "set_markings"),
        ("unit", "unit_view_markings", "view"),
        ("unit", "unit_display_name", "display_name"),
        ("unit", "unit_set_display_name", "set_display_name"),
        ("unit", "unit_set_preferred_id", "set_preferred_id"),
        ("unit", "unit_unregister_contract", "unregister"),
        ("cargo", "cargo_manifest", "manifest"),
        ("cargo", "cargo_stores", "stores"),
        ("cargo", "cargo_load", "load"),
        ("cargo", "cargo_unload", "unload"),
        ("map", "map_cargo_point", "cargo_point"),
        ("map", "map_set_cargo_point", "set_cargo_point"),
        ("inventory", "inventory_part", "part"),
        ("inventory", "inventory_mass", "mass"),
        ("inventory", "inventory_set_named", "set_named"),
        ("inventory", "inventory_read", "read"),
        ("inventory", "inventory_add", "add"),
        ("inventory", "inventory_add_stores", "add_stores"),
        ("inventory", "inventory_remove", "remove"),
        ("inventory", "inventory_clear", "clear"),
        ("inventory", "inventory_fix", "fix"),
        ("inventory", "inventory_set", "set"),
        ("weapon", "weapon_settings", "settings"),
        ("weapon", "weapon_set_recycle", "set_recycle"),
        ("weapon", "weapon_set_battle_value", "set_battle_value"),
        ("unit", "unit_brief", "brief"),
        ("unit", "unit_lateral", "lateral"),
        ("unit", "unit_dump", "dump"),
        ("unit", "unit_masc", "masc"),
        ("unit", "unit_c3i", "c3i"),
        ("unit", "unit_c3", "c3"),
        ("unit", "unit_c3i_message", "c3i_message"),
        ("unit", "unit_c3_message", "c3_message"),
        ("unit", "unit_c3_network", "c3_network"),
        ("unit", "unit_c3_targets", "c3_targets"),
        ("unit", "unit_c3i_network", "c3i_network"),
        ("unit", "unit_c3i_targets", "c3i_targets"),
        ("unit", "unit_supercharger", "supercharger"),
        ("unit", "unit_eta", "eta"),
        ("unit", "unit_bearing", "bearing"),
        ("unit", "unit_range_report", "range_report"),
        ("unit", "unit_vector", "vector"),
        ("unit", "unit_bootlegger", "bootlegger"),
        ("unit", "unit_building_contacts", "building_contacts"),
        ("player", "player_contact_options", "contact_options"),
        ("player", "player_view_dimensions", "view_dimensions"),
        (
            "player",
            "player_contact_preferences",
            "contact_preferences",
        ),
        ("gunner", "gunner_set_field", "set_field"),
        ("gunner", "gunner_view_fields", "view_fields"),
        ("gunner", "gunner_contacts", "contacts"),
        ("gunner", "gunner_status", "status"),
        ("gunner", "gunner_scan", "scan"),
        ("gunner", "gunner_report", "report"),
        ("gunner", "gunner_scan_hex", "scan_hex"),
        ("gunner", "gunner_scan_building", "scan_building"),
        ("gunner", "gunner_scan_terrain", "scan_terrain"),
        ("gunner", "gunner_scan_selected", "scan_selected"),
        ("gunner", "gunner_tactical", "tactical"),
        ("gunner", "gunner_lrsmap", "lrsmap"),
        ("gunner", "gunner_navigate", "navigate"),
        ("gunner", "gunner_bearing", "bearing"),
        ("gunner", "gunner_range_report", "range_report"),
        ("gunner", "gunner_vector", "vector"),
        ("gunner", "gunner_eta", "eta"),
        ("gunner", "gunner_findcenter", "findcenter"),
        ("gunner", "gunner_register", "register"),
        ("gunner", "gunner_initialize", "initialize"),
        ("gunner", "gunner_deinitialize", "deinitialize"),
        ("gunner", "gunner_state", "state"),
        ("gunner", "gunner_gunnery", "gunnery"),
        ("gunner", "gunner_aim", "aim"),
        ("gunner", "gunner_fire", "fire"),
        ("gunner", "gunner_sight", "sight"),
        ("gunner", "gunner_artillery_gunnery", "artillery_gunnery"),
        ("gunner", "gunner_lock", "lock"),
        ("gunner", "gunner_lock_hex", "lock_hex"),
        ("character", "character_state", "state"),
        ("character", "character_list", "list"),
        ("character", "character_skills", "skills"),
        ("character", "character_advantages", "advantages"),
        ("character", "character_threshold", "threshold"),
        ("character", "character_xptop", "xptop"),
        ("database", "database_save", "save"),
        ("inventory", "inventory_forms", "forms"),
        ("character", "character_progress", "progress"),
        ("unit", "unit_evacuate", "evacuate"),
        ("character", "character_set_threshold", "set_threshold"),
        ("template", "template", "inspect"),
        ("template", "template_check", "check"),
        ("template", "loadout", "loadout"),
        ("map", "mapfile", "inspect_file"),
        ("unit", "unit", "inspect"),
        ("unit", "unit_fuel", "fuel"),
        ("unit", "unit_set_fuel", "set_fuel"),
        ("unit", "unit_create", "create"),
        ("unit", "unit_state", "state"),
        ("unit", "unit_towable", "towable"),
        ("unit", "unit_fortified", "fortified"),
        ("unit", "unit_observer", "observer"),
        ("unit", "unit_weapons_hold", "weapons_hold"),
        ("unit", "unit_combat_safe", "combat_safe"),
        ("unit", "unit_visibility", "visibility"),
        ("unit", "unit_kick", "kick"),
        ("unit", "unit_trip", "trip"),
        ("unit", "unit_punch", "punch"),
        ("unit", "unit_axe", "axe"),
        ("unit", "unit_sword", "sword"),
        ("unit", "unit_mace", "mace"),
        ("unit", "unit_saw", "saw"),
        ("unit", "unit_claw", "claw"),
        ("unit", "unit_club", "club"),
        ("unit", "unit_grabclub", "grabclub"),
        ("unit", "unit_charge", "charge"),
        ("unit", "unit_status", "status"),
        ("unit", "unit_place", "place"),
        ("unit", "unit_remove", "remove"),
        ("unit", "unit_pilot", "pilot"),
        ("unit", "unit_release", "release"),
        ("unit", "unit_start", "start"),
        ("unit", "unit_stop", "stop"),
        ("unit", "unit_range", "range"),
        ("unit", "unit_heading", "heading"),
        ("unit", "unit_turret", "turret"),
        ("unit", "unit_fixturret", "fixturret"),
        ("unit", "unit_speed", "speed"),
        ("unit", "unit_rottorso", "rottorso"),
        ("unit", "unit_slite", "slite"),
        ("unit", "unit_stealth", "stealth"),
        ("unit", "unit_nss", "nss"),
        ("unit", "unit_fliparms", "fliparms"),
        ("unit", "unit_auto_fall", "auto_fall"),
        ("unit", "unit_ams", "ams"),
        ("unit", "unit_ecm", "ecm"),
        ("unit", "unit_eccm", "eccm"),
        ("unit", "unit_angelecm", "angelecm"),
        ("unit", "unit_angeleccm", "angeleccm"),
        ("unit", "unit_pods", "pods"),
        ("unit", "unit_removepod", "removepod"),
        ("unit", "unit_removepods", "removepods"),
        ("unit", "unit_extinguish", "extinguish"),
        ("unit", "unit_inarc", "inarc"),
        ("unit", "unit_narc", "narc"),
        ("unit", "unit_explosive", "explosive"),
        ("unit", "unit_friendly_fire_safety", "friendly_fire_safety"),
        ("unit", "unit_mw_safety", "mw_safety"),
        ("unit", "unit_snipe", "snipe"),
        ("unit", "unit_bth_debug", "bth_debug"),
        ("unit", "unit_autocon_shutdown", "autocon_shutdown"),
        ("unit", "unit_armor_warning", "armor_warning"),
        ("unit", "unit_ammunition_warning", "ammunition_warning"),
        ("unit", "unit_searchlight_warning", "searchlight_warning"),
        ("unit", "unit_jump", "jump"),
        ("unit", "unit_dfa", "dfa"),
        ("unit", "unit_land", "land"),
        ("unit", "unit_pickup", "pickup"),
        ("unit", "unit_dropoff", "dropoff"),
        ("unit", "unit_dig", "dig"),
        ("unit", "unit_hulldown", "hulldown"),
        ("unit", "unit_takeoff", "takeoff"),
        ("unit", "unit_enterbase", "enterbase"),
        ("unit", "unit_vertical", "vertical"),
        ("unit", "unit_stand", "stand"),
        ("unit", "unit_prone", "prone"),
        ("unit", "unit_sensors", "sensors"),
        ("unit", "unit_sensor_report", "sensor_report"),
        ("unit", "unit_tag", "tag"),
        ("unit", "unit_spot", "spot"),
        ("unit", "unit_contacts", "contacts"),
        ("unit", "unit_lock", "lock"),
        ("unit", "unit_lock_hex", "lock_hex"),
        ("unit", "unit_gunnery", "gunnery"),
        ("unit", "unit_aim_hex", "aim_hex"),
        ("unit", "unit_fire", "fire"),
        ("unit", "unit_sight", "sight"),
        ("unit", "unit_target", "target"),
        ("unit", "unit_aimed_section", "aimed_section"),
        ("unit", "unit_tic", "tic"),
        ("unit", "unit_tic_fire", "tic_fire"),
        ("unit", "unit_heatcutoff", "heatcutoff"),
        ("unit", "unit_hide", "hide"),
        ("unit", "unit_disable", "disable"),
        ("unit", "unit_usebin", "usebin"),
        ("unit", "unit_autoturret", "autoturret"),
        ("unit", "unit_reactor_explode", "reactor_explode"),
        ("unit", "unit_explode", "explode"),
        ("unit", "unit_explode_safe", "explode_safe"),
        ("unit", "unit_tic_edit", "tic_edit"),
        ("unit", "unit_flamerheat", "flamerheat"),
        ("unit", "unit_lbx", "lbx"),
        ("unit", "unit_cluster", "cluster"),
        ("unit", "unit_cluster", "firecluster"),
        ("unit", "unit_firesmoke", "firesmoke"),
        ("unit", "unit_firemine", "firemine"),
        ("unit", "unit_artemis", "artemis"),
        ("unit", "unit_hotload", "hotload"),
        ("unit", "unit_ultra", "ultra"),
        ("unit", "unit_rapid", "rapidfire"),
        ("unit", "unit_gatling", "gattling"),
        ("unit", "unit_rac", "rac"),
        ("unit", "unit_armor_piercing", "armorpiercing"),
        ("unit", "unit_caseless", "caseless"),
        ("unit", "unit_incendiary", "incendiary"),
        ("unit", "unit_scan", "scan"),
        ("unit", "unit_scan_hex", "scan_hex"),
        ("unit", "unit_report", "report"),
        ("unit", "unit_view_center", "view_center"),
        ("unit", "unit_viewport", "viewport"),
        ("unit", "unit_findcenter", "findcenter"),
        ("unit", "unit_navigate", "navigate"),
        ("unit", "unit_tactical", "tactical"),
        ("unit", "unit_lrsmap", "lrsmap"),
        ("unit", "unit_scan_selected", "scan_selected"),
        ("unit", "unit_scan_terrain", "scan_terrain"),
        ("unit", "unit_scan_building", "scan_building"),
        ("unit", "unit_radio_target", "radio_target"),
        ("unit", "unit_radio_send", "radio_send"),
        ("unit", "unit_radio_frequency", "radio_frequency"),
        ("unit", "unit_radio_title", "radio_title"),
        ("unit", "unit_radio_mode", "radio_mode"),
        ("unit", "unit_inferno", "inferno"),
        ("unit", "unit_precision", "precision"),
        ("unit", "unit_sguided", "sguided"),
        ("unit", "unit_fireswarm", "fireswarm"),
        ("unit", "unit_fireswarm1", "fireswarm1"),
        ("unit", "unit_mml", "mml"),
        ("unit", "unit_atmrange", "atmrange"),
        ("unit", "unit_atmexplosive", "atmexplosive"),
        ("unit", "unit_stinger", "stinger"),
        ("unit", "unit_flechette", "flechette"),
        ("unit", "unit_unjam", "unjam"),
        ("unit", "unit_weapons", "weapons"),
        ("unit", "unit_weapon_diagnostics", "weapon_diagnostics"),
        ("unit", "unit_criticals", "criticals"),
        (
            "unit",
            "unit_weapon_specifications",
            "weapon_specifications",
        ),
        ("map", "map", "inspect"),
        ("map", "map_hex", "hex"),
        ("map", "map_emit", "emit"),
        ("map", "map_clear_units", "clear_units"),
        ("map", "map_resize", "resize"),
        ("map", "map_save", "save"),
        ("map", "map_load", "load"),
        ("map", "map_view", "view"),
        ("map", "map_check", "check"),
        ("map", "map_fields", "fields"),
        ("map", "map_set_field", "set_field"),
        ("map", "map_add_mine", "add_mine"),
        ("map", "map_add_fire", "add_fire"),
        ("map", "map_add_smoke", "add_smoke"),
        ("map", "map_link", "link"),
        ("map", "map_set_link", "set_link"),
        ("map", "map_update_links", "update_links"),
        ("map", "map_list", "list"),
        ("map", "map_delete_objects", "delete_objects"),
        ("map", "map_add_block", "add_block"),
        ("map", "map_set_hex", "set_hex"),
        ("map", "map_create", "create"),
        ("map", "map_reload", "reload"),
        ("map", "map_conditions", "conditions"),
        ("map", "map_cloud", "cloud_base"),
        ("map", "map_environment", "environment"),
        ("map", "map_add_ice", "add_ice"),
        ("map", "map_remove_ice", "remove_ice"),
        ("map", "map_wrapping", "wrapping"),
    ] {
        let table = match package.get::<Value>(group)? {
            Value::Table(table) => table,
            _ => lua.create_table()?,
        };
        // Resolve through the private table so checking restrictions cannot leave a live closure behind.
        let dispatch: mlua::Function = lua
            .load("local native,key=...; return function(...) return native[key](...) end")
            .call((native.clone(), name))?;
        table.set(method, dispatch)?;
        package.set(group, table)?;
        qualified_names.raw_set(name, format!("{group}.{method}"))?;
    }
    native.raw_set("__qualified_names", qualified_names)?;
    let errors: Table = mux.get("error")?;
    let codes: mlua::Function = errors.get("code_tree")?;
    let btech_codes = codes.call::<Value>("btech")?;
    package.set("errors", btech_codes.clone())?;
    let error_namespace = lua.create_table()?;
    error_namespace.set("codes", btech_codes)?;
    package.set("error", error_namespace)?;
    constants::install(lua, &package)?;
    contract::install(lua, &native, &package)?;
    lua.globals().set("btech", package.clone())?;
    lua.globals()
        .get::<Table>("package")?
        .get::<Table>("loaded")?
        .set("btech", package)?;
    Ok(())
}
