[package]
name = "stompymux-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.31.3", default-features = false, features = ["resource", "feature"] }
flate2 = { version = "1.1.10", default-features = false, features = ["rust_backend"] }
anyhow = "1.0.104"
argon2 = "0.6.0"
clap = { version = "4.6.6", features = ["derive"] }
mlua = { version = "0.12.1", features = ["luajit", "vendored", "serialize"] }
rand = "0.10.2"
regex = "1.13.1"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
toml = { version = "1.1.5", features = ["preserve_order"] }
unicode-width = "0.2.2"
zeroize = { version = "1.9.0", features = ["derive"] }
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
unicode-segmentation = "1.13.3"
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }

[dev-dependencies]
tempfile = "3.27.0"
