#pragma once

#include "mech_api_types.h"

#include <stdbool.h>

#include "mux/objects/db.h"

typedef enum MechScriptValueKey : int {
  MECH_SCRIPT_MAP_DBREF,
  MECH_SCRIPT_NAME,
  MECH_SCRIPT_MAXIMUM_SPEED,
  MECH_SCRIPT_ERA,
  MECH_SCRIPT_TRO,
  MECH_SCRIPT_TEMPLATE_SPEED,
  MECH_SCRIPT_PILOT_DBREF,
  MECH_SCRIPT_EXPERIENCE_MODIFIER,
  MECH_SCRIPT_PILOT_DAMAGE,
  MECH_SCRIPT_STRUCTURAL_INTEGRITY,
  MECH_SCRIPT_ORIGINAL_STRUCTURAL_INTEGRITY,
  MECH_SCRIPT_SPEED,
  MECH_SCRIPT_BASE_WALK_SPEED,
  MECH_SCRIPT_BASE_RUN_SPEED,
  MECH_SCRIPT_HEADING,
  MECH_SCRIPT_STALL,
  MECH_SCRIPT_STATUS,
  MECH_SCRIPT_STATUS_SECONDARY,
  MECH_SCRIPT_CRITICAL_STATUS,
  MECH_SCRIPT_CRITICAL_STATUS_SECONDARY,
  MECH_SCRIPT_VEHICLE_CRITICAL_STATUS,
  MECH_SCRIPT_TARGET_DBREF,
  MECH_SCRIPT_TEAM,
  MECH_SCRIPT_TONNAGE,
  MECH_SCRIPT_TOWING_DBREF,
  MECH_SCRIPT_HEAT_PRODUCTION,
  MECH_SCRIPT_DISABLED_HEAT_SINKS,
  MECH_SCRIPT_HEAT,
  MECH_SCRIPT_HEAT_DISSIPATION,
  MECH_SCRIPT_ENGINE_HEAT_SINK_OVERRIDE,
  MECH_SCRIPT_HEAT_SINKS,
  MECH_SCRIPT_LAST_STARTUP,
  MECH_SCRIPT_C3I_NETWORK_SIZE,
  MECH_SCRIPT_MAXIMUM_BATTLE_SUITS,
  MECH_SCRIPT_REAL_WEIGHT,
  MECH_SCRIPT_STAGGER_DAMAGE,
  MECH_SCRIPT_PREFERENCES,
  MECH_SCRIPT_SWARM_TARGET,
  MECH_SCRIPT_SWARMER,
  MECH_SCRIPT_FUEL,
  MECH_SCRIPT_ORIGINAL_FUEL,
  MECH_SCRIPT_COCOON,
  MECH_SCRIPT_SEEN_COUNT,
  MECH_SCRIPT_REAL_X,
  MECH_SCRIPT_REAL_Y,
  MECH_SCRIPT_REAL_Z,
  MECH_SCRIPT_X,
  MECH_SCRIPT_Y,
  MECH_SCRIPT_Z,
  MECH_SCRIPT_TARGETING_COMPUTER,
  MECH_SCRIPT_LONG_RANGE_SENSOR_RANGE,
  MECH_SCRIPT_RADIO_RANGE,
  MECH_SCRIPT_SCAN_RANGE,
  MECH_SCRIPT_TACTICAL_SENSOR_RANGE,
  MECH_SCRIPT_RADIO_TYPE,
  MECH_SCRIPT_CARGO_SPACE,
  MECH_SCRIPT_CARRIER_MAXIMUM_TONNAGE,
  MECH_SCRIPT_BAY_0,
  MECH_SCRIPT_BAY_1,
  MECH_SCRIPT_BAY_2,
  MECH_SCRIPT_BAY_3,
  MECH_SCRIPT_TURRET_0,
  MECH_SCRIPT_TURRET_1,
  MECH_SCRIPT_TURRET_2,
  MECH_SCRIPT_UNUSABLE_ARCS,
  MECH_SCRIPT_MAXIMUM_JUMP_SPEED,
  MECH_SCRIPT_JUMP_HEADING,
  MECH_SCRIPT_JUMP_LENGTH,
  MECH_SCRIPT_RADIO,
  MECH_SCRIPT_COMPUTER,
  MECH_SCRIPT_PERCEPTION,
  MECH_SCRIPT_SHOTS_FIRED,
  MECH_SCRIPT_SHOTS_MISSED,
  MECH_SCRIPT_SHOTS_HIT,
  MECH_SCRIPT_DAMAGE_TAKEN,
  MECH_SCRIPT_DAMAGE_INFLICTED,
  MECH_SCRIPT_UNITS_KILLED,
  MECH_SCRIPT_HEXES_WALKED,
} MechScriptValueKey;

typedef union MechScriptValue {
  const char *string;
  DbRef dbref;
  int integer;
  float floating;
} MechScriptValue;

bool mech_script_value_read(const Mech *mech, MechScriptValueKey key,
                            MechScriptValue *value);
bool mech_script_value_write(Mech *mech, MechScriptValueKey key,
                             MechScriptValue value);
