#pragma once

#include "mech_api_types.h"

#include <stdbool.h>

typedef struct MechConditionSummary {
  bool combat_safe;
  bool partial_cover;
  bool fortified;
  bool fallen;
  bool weapons_hold;
  bool hull_down;
  bool dug_in;
  bool digging;
  bool staggering;
  bool searchlight_destroyed;
  bool searchlight_on;
  bool illuminated;
  bool hidden;
  bool dodging;
  bool evading;
  bool sprinting;
  bool stunned;
  bool performing_action;
  bool auto_fall;
  bool to_hit_debug;
  bool ecm_disturbed;
  bool ecm_protected;
  bool angel_ecm_protected;
  bool angel_ecm_disturbed;
  bool ecm_countered;
  bool ecm_destroyed;
  bool ecm_enabled;
  bool ecm_active;
  bool eccm_enabled;
  bool angel_ecm_destroyed;
  bool angel_ecm_enabled;
  bool angel_ecm_active;
  bool angel_eccm_enabled;
  bool personal_ecm_enabled;
  bool personal_ecm_active;
  bool personal_eccm_enabled;
  bool stealth_armor_active;
  bool null_signature_active;
  bool null_signature_destroyed;
  bool c3_destroyed;
  bool c3i_destroyed;
  bool sensors_damaged;
  bool beagle_probe_destroyed;
  bool bloodhound_probe_destroyed;
  bool light_beagle_probe_destroyed;
  bool turret_auto_turn;
  bool arms_flipped;
  bool targeting_computer_destroyed;
  bool ams_enabled;
  bool supercharger_enabled;
  bool masc_enabled;
  bool player_killer;
  bool tight_turn_mode;
  bool dfa_attacking;
  bool turret_jammed;
  bool turret_locked;
  bool tail_rotor_destroyed;
  bool hip_damaged;
  bool hip_destroyed;
  bool gyro_damaged;
  bool hardened_gyro_damaged;
  bool torso_right;
  bool torso_left;
  bool spinning;
  bool self_destruct_safe;
  DbRef swarm_target;
  int supercharger_counter;
  int masc_counter;
} MechConditionSummary;

typedef enum MechTorsoTwist {
  MECH_TORSO_CENTER,
  MECH_TORSO_LEFT,
  MECH_TORSO_RIGHT,
} MechTorsoTwist;

MechConditionSummary mech_condition_summary(const Mech *mech);
bool mech_supercharger_movement_mode_is_enabled(const Mech *mech);
bool mech_ecm_mode_toggle(Mech *mech, bool eccm);
bool mech_personal_ecm_mode_toggle(Mech *mech, bool eccm);
bool mech_angel_ecm_mode_toggle(Mech *mech, bool eccm);
void mech_torso_twist_set(Mech *mech, MechTorsoTwist twist);
void mech_arms_center(Mech *mech);
void mech_arms_flip(Mech *mech);
void mech_ams_enabled_set(Mech *mech, bool enabled);
void mech_evading_set(Mech *mech, bool evading);
void mech_sprinting_set(Mech *mech, bool sprinting);
void mech_dfa_attacking_set(Mech *mech, bool attacking);
void mech_turret_auto_turn_set(Mech *mech, bool enabled);
void mech_tight_turn_mode_set(Mech *mech, bool enabled);
void mech_player_killer_set(Mech *mech, bool enabled);
void mech_partial_cover_set(Mech *mech, bool covered);
DbRef mech_swarm_target(const Mech *mech);
void mech_swarm_target_set(Mech *mech, DbRef target);
DbRef mech_swarmed_by(const Mech *mech);
void mech_swarmed_by_set(Mech *mech, DbRef swarmer);
bool mech_is_mounting(const Mech *mech);
void mech_mounting_set(Mech *mech, bool mounting);
bool mech_is_mounted(const Mech *mech);
void mech_mounted_set(Mech *mech, bool mounted);
void mech_fallen_set(Mech *mech, bool fallen);
void mech_hull_down_set(Mech *mech, bool hull_down);
void mech_dug_in_set(Mech *mech, bool dug_in);
void mech_digging_set(Mech *mech, bool digging);
void mech_hidden_set(Mech *mech, bool hidden);
void mech_spinning_set(Mech *mech, bool spinning);
void mech_masc_enabled_set(Mech *mech, bool enabled);
void mech_supercharger_enabled_set(Mech *mech, bool enabled);
int mech_masc_counter_advance(Mech *mech);
bool mech_masc_counter_regenerate(Mech *mech);
int mech_supercharger_counter_advance(Mech *mech);
bool mech_supercharger_counter_regenerate(Mech *mech);
void mech_hip_damage_set(Mech *mech, bool damaged, bool destroyed);
void mech_turret_jammed_set(Mech *mech, bool jammed);
void mech_turret_locked_set(Mech *mech, bool locked);
void mech_crew_stunned_set(Mech *mech, bool stunned);
void mech_tail_rotor_destroyed_set(Mech *mech, bool destroyed);
void mech_life_support_destroyed_set(Mech *mech, bool destroyed);
void mech_sensors_damaged_set(Mech *mech, bool damaged);
void mech_targeting_computer_destroyed_set(Mech *mech, bool destroyed);
void mech_gyro_damage_set(Mech *mech, bool damaged, bool destroyed);
void mech_hardened_gyro_damaged_set(Mech *mech, bool damaged);
void mech_c3_destroyed_set(Mech *mech, bool destroyed);
void mech_c3i_destroyed_set(Mech *mech, bool destroyed);
void mech_tag_destroyed_set(Mech *mech, bool destroyed);
void mech_ecm_destroyed_set(Mech *mech, bool destroyed);
void mech_angel_ecm_destroyed_set(Mech *mech, bool destroyed);
void mech_ecm_modes_disable(Mech *mech);
void mech_angel_ecm_modes_disable(Mech *mech);
void mech_beagle_probe_destroyed_set(Mech *mech, bool destroyed);
void mech_bloodhound_probe_destroyed_set(Mech *mech, bool destroyed);
void mech_light_beagle_probe_destroyed_set(Mech *mech, bool destroyed);
void mech_null_signature_destroyed_set(Mech *mech, bool destroyed);
bool mech_section_is_underwater(const Mech *mech, int section);
void mech_stunned_set(Mech *mech, bool stunned);
void mech_searchlight_set(Mech *mech, bool enabled);
void mech_stealth_armor_active_set(Mech *mech, bool active);
void mech_null_signature_active_set(Mech *mech, bool active);
