#include "template_internal.h"

#include "mux/support/checked_storage.h"
#include <stddef.h>

static const char *const CARGO_NAMES[] = {"Ammo_LBX2",
                                          "Ammo_LBX5_LBX",
                                          "Ammo_LBX10_LBX",
                                          "Ammo_LBX20_LBX",
                                          "Ammo_LRM",
                                          "Ammo_SRM",
                                          "Ammo_SSRM",
                                          "Ammo_LRM_NARC",
                                          "Ammo_SRM_NARC",
                                          "Ammo_SSRM_NARC",
                                          "Ammo_LRM_Artemis",
                                          "Ammo_SRM_Artemis",
                                          "Ammo_SSRM_Artemis",
                                          "Petroleum",
                                          "Phosphorus",
                                          "Hydrogen",
                                          "Gold",
                                          "Natural_Extracts",
                                          "Marijuana",
                                          "Sulfur",
                                          "Sodium",
                                          "Plutonium",
                                          "Ore",
                                          "Steel",
                                          "Plastics",
                                          "Medical_Supplies",
                                          "Computers",
                                          "Explosives",
                                          "ES_Internal",
                                          "FF_Armor",
                                          "XL_Engine",
                                          "Double_HeatSink",
                                          "ICE_Engine",
                                          "Electric",
                                          "Internal",
                                          "Armor",
                                          "Actuator",
                                          "Aero_Fuel",
                                          "DS_Fuel",
                                          "VTOL_Fuel",
                                          "Ammo_LRM_Swarm",
                                          "Ammo_LRM_Swarm1",
                                          "Ammo_SRM_Inferno",
                                          "XXL_Engine",
                                          "Compact_Engine",
                                          "HD_Armor",
                                          "RE_Internals",
                                          "CO_Internals",
                                          "Ammo_MRM",
                                          "Light_Engine",
                                          "CASE-II",
                                          "STH_Armor",
                                          "NullSigSys",
                                          "Silicon",
                                          "HVY_FF_Armor",
                                          "LT_FF_Armor",
                                          "Ammo_iNARC_Explosive",
                                          "Ammo_iNARC_Haywire",
                                          "Ammo_iNARC_ECM",
                                          "Ammo_iNARC_Nemesis",
                                          "Ammo_AC2_Pierce",
                                          "Ammo_AC5_Pierce",
                                          "Ammo_AC10_Pierce",
                                          "Ammo_AC20_Pierce",
                                          "Ammo_LAC2_Pierce",
                                          "Ammo_LAC5_Pierce",
                                          "Ammo_AC2_Flechette",
                                          "Ammo_AC5_Flechette",
                                          "Ammo_AC10_Flechette",
                                          "Ammo_AC20_Flechette",
                                          "Ammo_LAC2_Flechette",
                                          "Ammo_LAC5_Flechette",
                                          "Ammo_AC2_Incendiary",
                                          "Ammo_AC5_Incendiary",
                                          "Ammo_AC10_Incendiary",
                                          "Ammo_AC20_Incendiary",
                                          "Ammo_LAC2_Incendiary",
                                          "Ammo_LAC5_Incendiary",
                                          "Ammo_AC2_Precision",
                                          "Ammo_AC5_Precision",
                                          "Ammo_AC10_Precision",
                                          "Ammo_AC20_Precision",
                                          "Ammo_LAC2_Precision",
                                          "Ammo_LAC5_Precision",
                                          "Ammo_LR_DFM",
                                          "Ammo_SR_DFM",
                                          "Ammo_SLRM",
                                          "Ammo_ELRM",
                                          "BSuit_Sensor",
                                          "BSuit_LifeSupport",
                                          "BSuit_Electronic",
                                          "Oil",
                                          "Water",
                                          "Earth",
                                          "Oxygen",
                                          "Nitrogen",
                                          "Nickel",
                                          "Steel",
                                          "Iron",
                                          "Brass",
                                          "Platinum",
                                          "Copper",
                                          "Aluminum",
                                          "Consumer_Good",
                                          "Machinery",
                                          "Slaves",
                                          "Timbiqui_Dark",
                                          "Cocaine",
                                          "Heroine",
                                          "Marble",
                                          "Glass",
                                          "Diamond",
                                          "Coal",
                                          "Food",
                                          "Zinc",
                                          "Fabric",
                                          "Clothing",
                                          "Wood",
                                          "Pulp",
                                          "Lumber",
                                          "Rubber",
                                          "Seeds",
                                          "Fertilizer",
                                          "Salt",
                                          "Lithium",
                                          "Helium",
                                          "Larium",
                                          "Uranium",
                                          "Iridium",
                                          "Titanium",
                                          "Concrete",
                                          "FerroCrete",
                                          "Building_Supplies",
                                          "Kevlar",
                                          "Waste",
                                          "Livestock",
                                          "Paper",
                                          "XL_Gyro",
                                          "HeavyDuty_Gyro",
                                          "Compact_Gyro",
                                          "Compact_HeatSink",
                                          "Ammo_LRM_Stinger",
                                          "Ammo_AC2_Caseless",
                                          "Ammo_AC5_Caseless",
                                          "Ammo_AC10_Caseless",
                                          "Ammo_AC20_Caseless",
                                          "Ammo_LAC2_Caseless",
                                          "Ammo_LAC5_Caseless",
                                          "Ammo_LRM_Sguided",
                                          "Ammo_ATM3_ER",
                                          "Ammo_ATM3_HE",
                                          "Ammo_ATM6_ER",
                                          "Ammo_ATM6_HE",
                                          "Ammo_ATM9_ER",
                                          "Ammo_ATM9_HE",
                                          "Ammo_ATM12_ER",
                                          "Ammo_ATM12_HE",
                                          "SearchLight",
                                          nullptr};

const int TEMPLATE_CARGO_COUNT =
    (sizeof(CARGO_NAMES) / sizeof(*CARGO_NAMES)) - 1;

const char *const *template_cargo_names(void) { return CARGO_NAMES; }

const char *template_cargo_name(int index) {
  if (index < 0)
    return nullptr;
  const char *const *name = (const char *const *)checked_storage_at_const(
      (const void *)CARGO_NAMES, (size_t)TEMPLATE_CARGO_COUNT,
      sizeof(*CARGO_NAMES), (size_t)index);
  return *name;
}
