//! Procedural BattleTech battlefield generation for stompymux.
//!
//! Describe the battlefield with a [`MapSpec`] (biome, size, relief, how much water, woods and
//! rough ground, rivers, settlements and roads) and [`generate`] builds a [`HexMap`] that
//! [`GeneratedMap::to_toml`] writes in the stompymux map file format.
//!
//! The spec is plain serde data with a [JSON Schema](spec_schema), so the same description
//! can come from command-line flags, a JSON or TOML file, a map editor, or an LLM tool call.
//! Generation is deterministic: the same spec and seed always produce the same map, and the
//! resolved spec is embedded in the map file so it can be regenerated or tweaked later.
//!
//! ```
//! use stompymux_mapgen::{Biome, MapSize, MapSpec, SettlementSize, SettlementSpec, generate};
//!
//! let spec = MapSpec {
//!     seed: Some(7),
//!     biome: Some(Biome::Desert),
//!     size: Some(MapSize::Small),
//!     settlements: vec![SettlementSpec::new(SettlementSize::Village)],
//!     ..MapSpec::default()
//! };
//! let generated = generate(&spec).unwrap();
//! assert_eq!(generated.report.settlements.len(), 1);
//! let file = generated.to_toml().unwrap();
//! assert!(file.contains("terrain = '''"));
//! ```
//!
//! Generation runs in stages, each drawing from its own seeded random stream: elevation and
//! water, rivers, ground cover, settlements, roads, then fire and freezing.
mod biome;
mod map;
mod noise;
mod path;
mod report;
mod rng;
mod roads;
mod settlement;
mod spec;
mod terrain;

pub use biome::{BiomeInfo, biome_catalog};
pub use map::{Hex, HexMap, Terrain};
pub use report::{Coverage, Report, RoadReport, SettlementReport};
pub use spec::{
    Amount, Biome, EnvironmentSpec, MAX_DIMENSION, MIN_DIMENSION, MapSize, MapSpec, Position,
    Relief, RoadSpec, SettlementKind, SettlementLayout, SettlementSize, SettlementSpec,
    spec_schema,
};

pub use stompymux_map::{DecorationKind, MapAsset, MapFlag};

use anyhow::{Context, Result};

/// The comment prefix that carries the resolved spec inside a generated map file.
const SPEC_COMMENT: &str = "# mapgen-spec: ";

/// A generated map with the resolved spec that reproduces it and a report of what was built.
#[derive(Debug, Clone)]
pub struct GeneratedMap {
    /// The spec with its seed and every default filled in.
    pub spec: MapSpec,
    pub map: HexMap,
    pub report: Report,
}

impl GeneratedMap {
    /// The map in the stompymux map file format, headed by a comment holding the resolved
    /// spec; see [`embedded_spec`].
    pub fn to_toml(&self) -> Result<String> {
        let spec = serde_json::to_string(&self.spec)?;
        Ok(format!(
            "# Generated by stompymux mapgen. The spec below regenerates this map exactly.\n\
             {SPEC_COMMENT}{spec}\n{}",
            self.map.to_toml()?
        ))
    }
}

/// The resolved spec embedded in a generated map file, or `None` for a map that was not
/// generated (or whose header was removed).
pub fn embedded_spec(map_file: &str) -> Option<Result<MapSpec>> {
    let line = map_file
        .lines()
        .find_map(|line| line.strip_prefix(SPEC_COMMENT))?;
    Some(serde_json::from_str(line).context("invalid embedded mapgen spec"))
}

/// Every setting generation runs with, resolved from the spec.
#[derive(Debug, Clone)]
pub(crate) struct Params {
    seed: u64,
    profile: biome::Profile,
    relief: Relief,
    water: Amount,
    woods: Amount,
    rough: Amount,
    fire: Amount,
    rivers: u8,
    connect_settlements: bool,
    through_roads: u8,
    road_width: u8,
}

/// Generate the battlefield `spec` describes.
pub fn generate(spec: &MapSpec) -> Result<GeneratedMap> {
    let spec = spec.resolve()?;
    // Resolution fills every field, so the expects below cannot fail.
    let roads = spec.roads.clone().expect("resolved");
    let environment = spec.environment.clone().expect("resolved");
    let biome = spec.biome.expect("resolved");
    let params = Params {
        seed: spec.seed.expect("resolved"),
        profile: biome::profile(biome),
        relief: spec.relief.expect("resolved"),
        water: spec.water.expect("resolved"),
        woods: spec.woods.expect("resolved"),
        rough: spec.rough.expect("resolved"),
        fire: spec.fire.expect("resolved"),
        rivers: spec.rivers.expect("resolved"),
        connect_settlements: roads.connect_settlements.expect("resolved"),
        through_roads: roads.through_roads.expect("resolved"),
        road_width: roads.width.expect("resolved"),
    };
    let (width, height) = spec.dimensions();
    let mut map = HexMap::new(width, height);
    map.gravity = environment.gravity.expect("resolved");
    map.temperature = environment.temperature.expect("resolved");
    map.flags = environment.flags.expect("resolved");
    let mut warnings = Vec::new();
    let elevation = terrain::elevation(&map, &params);
    terrain::shape(&mut map, &elevation, &params);
    let rivers = terrain::rivers(&mut map, &elevation, &params);
    terrain::cover(&mut map, &elevation, &params);
    let settlements = settlement::build_all(&mut map, &spec.settlements, &params, &mut warnings);
    let roads = roads::build(&mut map, &settlements, &params, &mut warnings);
    terrain::burn(&mut map, &elevation, &params);
    if spec.frozen.expect("resolved") {
        terrain::freeze(&mut map);
    }
    map.validate()?;
    let report = Report {
        seed: params.seed,
        biome,
        width,
        height,
        coverage: Coverage::of(&map),
        rivers,
        settlements: settlements.into_iter().map(|built| built.report).collect(),
        roads,
        fire_hexes: count_overlay(&map, DecorationKind::Fire),
        smoke_hexes: count_overlay(&map, DecorationKind::Smoke),
        warnings,
    };
    Ok(GeneratedMap { spec, map, report })
}

/// How many hexes carry `overlay`.
fn count_overlay(map: &HexMap, overlay: DecorationKind) -> usize {
    map.hexes
        .iter()
        .filter(|hex| hex.overlay == Some(overlay))
        .count()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A spec exercising every biome, settlement kind and layout on a medium map.
    fn busy(biome: Biome, seed: u64) -> MapSpec {
        let settlement = |size, kind, layout, position| SettlementSpec {
            kind: Some(kind),
            layout: Some(layout),
            position: Some(position),
            ..SettlementSpec::new(size)
        };
        MapSpec {
            seed: Some(seed),
            biome: Some(biome),
            size: Some(MapSize::Medium),
            settlements: vec![
                settlement(
                    SettlementSize::Town,
                    SettlementKind::Civilian,
                    SettlementLayout::Grid,
                    Position::Center,
                ),
                settlement(
                    SettlementSize::Village,
                    SettlementKind::Ruins,
                    SettlementLayout::Organic,
                    Position::Northwest,
                ),
                settlement(
                    SettlementSize::Village,
                    SettlementKind::Military,
                    SettlementLayout::Compound,
                    Position::Southeast,
                ),
                settlement(
                    SettlementSize::Hamlet,
                    SettlementKind::Civilian,
                    SettlementLayout::Scattered,
                    Position::Northeast,
                ),
            ],
            roads: Some(RoadSpec {
                through_roads: Some(2),
                width: Some(2),
                ..RoadSpec::default()
            }),
            ..MapSpec::default()
        }
    }

    #[test]
    fn every_biome_generates_a_valid_map() {
        for biome in Biome::ALL {
            let generated = generate(&busy(biome, 11)).unwrap();
            let map = &generated.map;
            assert_eq!((map.width, map.height), (50, 50));
            map.validate().unwrap();
            assert_eq!(generated.report.settlements.len(), 4, "{biome:?}");
            assert!(
                generated.report.settlements.iter().all(|s| s.buildings > 0),
                "{biome:?}: {:?}",
                generated.report.settlements
            );
            assert!(generated.report.coverage.road > 0.0, "{biome:?}");
        }
    }

    /// Every biome, with every kind of settlement, writes a map file that loads with the same
    /// hexes and heights within a battlefield's limits.
    #[test]
    fn generated_maps_load() {
        let settlement = |size, kind| SettlementSpec {
            kind: Some(kind),
            walled: Some(true),
            ..SettlementSpec::new(size)
        };
        for biome in Biome::ALL {
            let spec = MapSpec {
                seed: Some(1),
                biome: Some(biome),
                size: Some(MapSize::Medium),
                fire: Some(Amount::Low),
                settlements: vec![
                    settlement(SettlementSize::City, SettlementKind::Civilian),
                    settlement(SettlementSize::Village, SettlementKind::Ruins),
                    settlement(SettlementSize::Hamlet, SettlementKind::Industrial),
                    settlement(SettlementSize::Outpost, SettlementKind::Military),
                ],
                roads: Some(RoadSpec {
                    width: Some(2),
                    through_roads: Some(2),
                    ..RoadSpec::default()
                }),
                ..MapSpec::default()
            };
            let generated = generate(&spec).unwrap();
            let map = MapAsset::parse(&generated.to_toml().unwrap())
                .unwrap_or_else(|error| panic!("{biome:?}: {error:#}"));
            assert_eq!(map, generated.map.to_asset().unwrap(), "{biome:?}");
            for (index, hex) in generated.map.hexes.iter().enumerate() {
                let (x, y) = generated.map.coordinate(index);
                let loaded = map.hex(x, y).unwrap();
                assert_eq!(loaded.level(), hex.level, "{biome:?} at {x},{y}");
                assert_eq!(loaded.deck_clearance(), hex.bridge, "{biome:?} at {x},{y}");
                assert_eq!(loaded.overlay(), hex.overlay, "{biome:?} at {x},{y}");
                loaded
                    .validate()
                    .unwrap_or_else(|error| panic!("{biome:?} at {x},{y}: {error:#}"));
            }
        }
    }

    #[test]
    fn generation_is_deterministic() {
        let spec = busy(Biome::Temperate, 99);
        let first = generate(&spec).unwrap().to_toml().unwrap();
        assert_eq!(first, generate(&spec).unwrap().to_toml().unwrap());
        let other = generate(&busy(Biome::Temperate, 100)).unwrap();
        assert_ne!(first, other.to_toml().unwrap());
    }

    #[test]
    fn embedded_spec_regenerates_the_map() {
        let spec = MapSpec {
            biome: Some(Biome::Arctic),
            size: Some(MapSize::Small),
            ..MapSpec::default()
        };
        let file = generate(&spec).unwrap().to_toml().unwrap();
        let embedded = embedded_spec(&file).unwrap().unwrap();
        assert!(embedded.seed.is_some());
        assert_eq!(generate(&embedded).unwrap().to_toml().unwrap(), file);
        assert!(embedded_spec("terrain = '.'\nlevel = '0'\n").is_none());
    }

    #[test]
    fn amounts_steer_the_terrain_mix() {
        let with = |water, woods| MapSpec {
            seed: Some(5),
            biome: Some(Biome::Temperate),
            water: Some(water),
            woods: Some(woods),
            rivers: Some(0),
            ..MapSpec::default()
        };
        let dry = generate(&with(Amount::None, Amount::Extreme))
            .unwrap()
            .report
            .coverage;
        let wet = generate(&with(Amount::High, Amount::None))
            .unwrap()
            .report
            .coverage;
        assert_eq!(dry.water, 0.0);
        assert!(dry.light_woods + dry.heavy_woods > 50.0, "{dry:?}");
        assert!((25.0..35.0).contains(&wet.water), "{wet:?}");
        assert_eq!(wet.light_woods + wet.heavy_woods, 0.0);
    }

    #[test]
    fn biomes_set_climate_and_cover() {
        let report = |biome| {
            let spec = MapSpec {
                seed: Some(3),
                biome: Some(biome),
                ..MapSpec::default()
            };
            generate(&spec).unwrap()
        };
        let arctic = report(Biome::Arctic);
        assert!(arctic.map.temperature < 0);
        assert!(arctic.report.coverage.snow > 30.0);
        assert_eq!(arctic.report.coverage.water, 0.0);
        assert!(arctic.report.coverage.ice > 0.0);
        let desert = report(Biome::Desert);
        assert!(desert.report.coverage.sand > 30.0);
        let lunar = report(Biome::Lunar);
        assert!(lunar.map.flags.contains(&MapFlag::Vacuum));
        let volcanic = report(Biome::Volcanic);
        assert!(volcanic.report.fire_hexes > 0 && volcanic.report.smoke_hexes > 0);
    }

    #[test]
    fn settlements_honor_exact_positions_and_walls() {
        let spec = MapSpec {
            seed: Some(8),
            settlements: vec![SettlementSpec {
                at: Some([20, 22]),
                walled: Some(true),
                ..SettlementSpec::new(SettlementSize::Town)
            }],
            ..MapSpec::default()
        };
        let generated = generate(&spec).unwrap();
        let town = &generated.report.settlements[0];
        assert_eq!(town.center, [20, 22]);
        assert!(town.walled && !town.gates.is_empty());
        assert!(generated.report.coverage.wall > 0.0);
        // Each gate is a road or bridge hex on the wall line.
        for &[x, y] in &town.gates {
            let hex = generated.map.hex(i32::from(x), i32::from(y)).unwrap();
            assert!(hex.terrain == Terrain::Road || hex.bridge.is_some());
        }
    }

    #[test]
    fn oversized_settlements_shrink_with_a_warning() {
        let spec = MapSpec {
            seed: Some(2),
            width: Some(16),
            height: Some(16),
            settlements: vec![SettlementSpec::new(SettlementSize::Metropolis)],
            ..MapSpec::default()
        };
        let generated = generate(&spec).unwrap();
        assert!(generated.report.warnings[0].contains("shrunk"));
        generated.map.validate().unwrap();
    }

    #[test]
    fn roads_link_settlements_and_cross_the_map() {
        let spec = MapSpec {
            seed: Some(4),
            size: Some(MapSize::Large),
            settlements: vec![SettlementSpec {
                count: Some(3),
                ..SettlementSpec::new(SettlementSize::Village)
            }],
            roads: Some(RoadSpec {
                through_roads: Some(2),
                ..RoadSpec::default()
            }),
            ..MapSpec::default()
        };
        let report = generate(&spec).unwrap().report;
        assert!(report.warnings.is_empty(), "{:?}", report.warnings);
        let links = report
            .roads
            .iter()
            .filter(|road| !road.from.contains("edge"));
        assert_eq!(links.count(), 2);
        assert!(report.roads.iter().any(|road| road.from == "west edge"));
        assert!(report.roads.iter().any(|road| road.from == "north edge"));
        let names: Vec<_> = report.settlements.iter().map(|s| s.name.as_str()).collect();
        assert_eq!(names, ["village 1", "village 2", "village 3"]);
    }
}
