//! Procedural BattleTech battlefield generation for stompymux.
//!
//! Describe the battlefield with a [`MapSpec`] (biome, size, relief, how much water, woods and
//! rough ground, rivers, settlements and roads) and [`generate`] builds a [`HexMap`] that
//! [`GeneratedMap::to_toml`] writes in the stompymux map file format.
//!
//! The spec is plain serde data with a [JSON Schema](spec_schema), so the same description
//! can come from command-line flags, a JSON or TOML file, a map editor, or an LLM tool call.
//! Generation is deterministic: the same spec and seed always produce the same map, and the
//! resolved spec is embedded in the map file so it can be regenerated or tweaked later.
//!
//! ```
//! use stompymux_mapgen::{Biome, MapSize, MapSpec, SettlementSize, SettlementSpec, generate};
//!
//! let spec = MapSpec {
//!     seed: Some(7),
//!     biome: Some(Biome::Desert),
//!     size: Some(MapSize::Small),
//!     settlements: vec![SettlementSpec::new(SettlementSize::Village)],
//!     ..MapSpec::default()
//! };
//! let generated = generate(&spec).unwrap();
//! assert_eq!(generated.report.settlements.len(), 1);
//! let file = generated.to_toml().unwrap();
//! assert!(file.contains("terrain = '''"));
//! ```
//!
//! Generation runs in stages, each drawing from its own seeded random stream: elevation and
//! water, rivers, ground cover, settlements, roads, then fire and freezing.
//!
//! The map is made of `stompymux-map`'s layered [`Hex`]es, so it uses the same layers as the
//! game: [`Ground`] (clear, pavement, rough, ultra-rough peaks, rubble, sand, tundra, swamp),
//! [`Water`] with its [`Flow`], [`Foliage`] (woods, jungle and planted fields), road
//! [`Route`]s, [`Structure`]s (buildings, walls and bridges with a construction class) and
//! weather [`Condition`]s (deep and thin snow, and ice over frozen water).
mod biome;
mod map;
mod noise;
mod path;
mod report;
mod rng;
mod roads;
mod settlement;
mod spec;
mod terrain;

pub use biome::{BiomeInfo, biome_catalog};
pub use map::HexMap;
pub use report::{Coverage, Report, RoadReport, SettlementReport};
pub use spec::{
    Amount, Biome, EnvironmentSpec, MAX_DIMENSION, MIN_DIMENSION, MapSize, MapSpec, Position,
    Relief, RoadSpec, SettlementKind, SettlementLayout, SettlementSize, SettlementSpec,
    spec_schema,
};

pub use stompymux_map::{
    Condition, ConstructionClass, DecorationKind, Flow, Foliage, Ground, Hex, MapAsset, MapFlag,
    Route, Structure, StructureKind, Terrain, Water,
};

use anyhow::{Context, Result};

/// The comment prefix that carries the resolved spec inside a generated map file.
const SPEC_COMMENT: &str = "# mapgen-spec: ";

/// A generated map with the resolved spec that reproduces it and a report of what was built.
#[derive(Debug, Clone)]
pub struct GeneratedMap {
    /// The spec with its seed and every default filled in.
    pub spec: MapSpec,
    pub map: HexMap,
    pub report: Report,
}

impl GeneratedMap {
    /// The map in the stompymux map file format, headed by a comment holding the resolved
    /// spec; see [`embedded_spec`].
    pub fn to_toml(&self) -> Result<String> {
        let file = embed_spec(&self.spec, &self.map.to_toml()?)?;
        Ok(format!(
            "# Generated by stompymux mapgen. The spec below regenerates this map exactly.\n{file}"
        ))
    }
}

/// `map_file` headed by a comment holding `spec`, which [`embedded_spec`] reads back. Map
/// editors use this to keep the spec a map was generated from when they save it.
pub fn embed_spec(spec: &MapSpec, map_file: &str) -> Result<String> {
    let spec = serde_json::to_string(spec)?;
    Ok(format!("{SPEC_COMMENT}{spec}\n{map_file}"))
}

/// The resolved spec embedded in a generated map file, or `None` for a map that was not
/// generated (or whose header was removed).
pub fn embedded_spec(map_file: &str) -> Option<Result<MapSpec>> {
    let line = map_file
        .lines()
        .find_map(|line| line.strip_prefix(SPEC_COMMENT))?;
    Some(serde_json::from_str(line).context("invalid embedded mapgen spec"))
}

/// Every setting generation runs with, resolved from the spec.
#[derive(Debug, Clone)]
pub(crate) struct Params {
    seed: u64,
    profile: biome::Profile,
    relief: Relief,
    water: Amount,
    woods: Amount,
    rough: Amount,
    fire: Amount,
    rivers: u8,
    connect_settlements: bool,
    through_roads: u8,
    road_width: u8,
}

/// Generate the battlefield `spec` describes.
pub fn generate(spec: &MapSpec) -> Result<GeneratedMap> {
    let spec = spec.resolve()?;
    // Resolution fills every field, so the expects below cannot fail.
    let roads = spec.roads.clone().expect("resolved");
    let environment = spec.environment.clone().expect("resolved");
    let biome = spec.biome.expect("resolved");
    let params = Params {
        seed: spec.seed.expect("resolved"),
        profile: biome::profile(biome),
        relief: spec.relief.expect("resolved"),
        water: spec.water.expect("resolved"),
        woods: spec.woods.expect("resolved"),
        rough: spec.rough.expect("resolved"),
        fire: spec.fire.expect("resolved"),
        rivers: spec.rivers.expect("resolved"),
        connect_settlements: roads.connect_settlements.expect("resolved"),
        through_roads: roads.through_roads.expect("resolved"),
        road_width: roads.width.expect("resolved"),
    };
    let (width, height) = spec.dimensions();
    let mut map = HexMap::new(width, height);
    map.gravity = environment.gravity.expect("resolved");
    map.temperature = environment.temperature.expect("resolved");
    map.flags = environment.flags.expect("resolved");
    let mut warnings = Vec::new();
    let elevation = terrain::elevation(&map, &params);
    terrain::shape(&mut map, &elevation, &params);
    let rivers = terrain::rivers(&mut map, &elevation, &params);
    terrain::cover(&mut map, &elevation, &params);
    let settlements = settlement::build_all(&mut map, &spec.settlements, &params, &mut warnings);
    let roads = roads::build(&mut map, &settlements, &params, &mut warnings);
    terrain::burn(&mut map, &elevation, &params);
    if spec.frozen.expect("resolved") {
        terrain::freeze(&mut map);
    }
    map.validate()?;
    let report = Report {
        seed: params.seed,
        biome,
        width,
        height,
        coverage: Coverage::of(&map),
        rivers,
        settlements: settlements.into_iter().map(|built| built.report).collect(),
        roads,
        fire_hexes: count_overlay(&map, DecorationKind::Fire),
        smoke_hexes: count_overlay(&map, DecorationKind::Smoke),
        warnings,
    };
    Ok(GeneratedMap { spec, map, report })
}

/// How many hexes carry `overlay`.
fn count_overlay(map: &HexMap, overlay: DecorationKind) -> usize {
    map.hexes
        .iter()
        .filter(|hex| hex.overlay() == Some(overlay))
        .count()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A spec exercising every biome, settlement kind and layout on a medium map.
    fn busy(biome: Biome, seed: u64) -> MapSpec {
        let settlement = |size, kind, layout, position| SettlementSpec {
            kind: Some(kind),
            layout: Some(layout),
            position: Some(position),
            ..SettlementSpec::new(size)
        };
        MapSpec {
            seed: Some(seed),
            biome: Some(biome),
            size: Some(MapSize::Medium),
            settlements: vec![
                settlement(
                    SettlementSize::Town,
                    SettlementKind::Civilian,
                    SettlementLayout::Grid,
                    Position::Center,
                ),
                settlement(
                    SettlementSize::Village,
                    SettlementKind::Ruins,
                    SettlementLayout::Organic,
                    Position::Northwest,
                ),
                settlement(
                    SettlementSize::Village,
                    SettlementKind::Military,
                    SettlementLayout::Compound,
                    Position::Southeast,
                ),
                settlement(
                    SettlementSize::Hamlet,
                    SettlementKind::Civilian,
                    SettlementLayout::Scattered,
                    Position::Northeast,
                ),
            ],
            roads: Some(RoadSpec {
                through_roads: Some(2),
                width: Some(2),
                ..RoadSpec::default()
            }),
            ..MapSpec::default()
        }
    }

    #[test]
    fn every_biome_generates_a_valid_map() {
        for biome in Biome::ALL {
            let generated = generate(&busy(biome, 11)).unwrap();
            let map = &generated.map;
            assert_eq!((map.width, map.height), (50, 50));
            map.validate().unwrap();
            assert_eq!(generated.report.settlements.len(), 4, "{biome:?}");
            assert!(
                generated.report.settlements.iter().all(|s| s.buildings > 0),
                "{biome:?}: {:?}",
                generated.report.settlements
            );
            assert!(generated.report.coverage.road() > 0.0, "{biome:?}");
        }
    }

    /// Every biome, with every kind of settlement, writes a map file that loads with the same
    /// hexes and heights within a battlefield's limits.
    #[test]
    fn generated_maps_load() {
        let settlement = |size, kind| SettlementSpec {
            kind: Some(kind),
            walled: Some(true),
            ..SettlementSpec::new(size)
        };
        for biome in Biome::ALL {
            let spec = MapSpec {
                seed: Some(1),
                biome: Some(biome),
                size: Some(MapSize::Medium),
                fire: Some(Amount::Low),
                settlements: vec![
                    settlement(SettlementSize::City, SettlementKind::Civilian),
                    settlement(SettlementSize::Village, SettlementKind::Ruins),
                    settlement(SettlementSize::Hamlet, SettlementKind::Industrial),
                    settlement(SettlementSize::Outpost, SettlementKind::Military),
                ],
                roads: Some(RoadSpec {
                    width: Some(2),
                    through_roads: Some(2),
                    ..RoadSpec::default()
                }),
                ..MapSpec::default()
            };
            let generated = generate(&spec).unwrap();
            let map = MapAsset::parse(&generated.to_toml().unwrap())
                .unwrap_or_else(|error| panic!("{biome:?}: {error:#}"));
            assert_eq!(map, generated.map.to_asset().unwrap(), "{biome:?}");
            for (index, hex) in generated.map.hexes.iter().enumerate() {
                let (x, y) = generated.map.coordinate(index);
                let loaded = map.hex(x, y).unwrap();
                assert_eq!(loaded, *hex, "{biome:?} at {x},{y}");
                loaded
                    .validate()
                    .unwrap_or_else(|error| panic!("{biome:?} at {x},{y}: {error:#}"));
            }
        }
    }

    #[test]
    fn generation_is_deterministic() {
        let spec = busy(Biome::Temperate, 99);
        let first = generate(&spec).unwrap().to_toml().unwrap();
        assert_eq!(first, generate(&spec).unwrap().to_toml().unwrap());
        let other = generate(&busy(Biome::Temperate, 100)).unwrap();
        assert_ne!(first, other.to_toml().unwrap());
    }

    #[test]
    fn embedded_spec_regenerates_the_map() {
        let spec = MapSpec {
            biome: Some(Biome::Arctic),
            size: Some(MapSize::Small),
            ..MapSpec::default()
        };
        let file = generate(&spec).unwrap().to_toml().unwrap();
        let embedded = embedded_spec(&file).unwrap().unwrap();
        assert!(embedded.seed.is_some());
        assert_eq!(generate(&embedded).unwrap().to_toml().unwrap(), file);
        assert!(embedded_spec("terrain = '.'\nlevel = '0'\n").is_none());
    }

    /// A spec embedded into any map file reads back unchanged.
    #[test]
    fn embed_spec_round_trips() {
        let spec = MapSpec {
            seed: Some(3),
            biome: Some(Biome::Lunar),
            ..MapSpec::default()
        };
        let file = embed_spec(&spec, "terrain = '.'\nlevel = '0'\n").unwrap();
        assert_eq!(embedded_spec(&file).unwrap().unwrap(), spec);
    }

    #[test]
    fn amounts_steer_the_terrain_mix() {
        let with = |water, woods| MapSpec {
            seed: Some(5),
            biome: Some(Biome::Temperate),
            water: Some(water),
            woods: Some(woods),
            rivers: Some(0),
            ..MapSpec::default()
        };
        let dry = generate(&with(Amount::None, Amount::Extreme))
            .unwrap()
            .report
            .coverage;
        let wet = generate(&with(Amount::High, Amount::None))
            .unwrap()
            .report
            .coverage;
        assert_eq!(dry.water, 0.0);
        assert!(dry.trees() > 50.0, "{dry:?}");
        assert!((25.0..35.0).contains(&wet.water), "{wet:?}");
        assert_eq!(wet.trees(), 0.0);
    }

    #[test]
    fn biomes_set_climate_and_cover() {
        let report = |biome| {
            let spec = MapSpec {
                seed: Some(3),
                biome: Some(biome),
                ..MapSpec::default()
            };
            generate(&spec).unwrap()
        };
        let arctic = report(Biome::Arctic);
        assert!(arctic.map.temperature < 0);
        let coverage = &arctic.report.coverage;
        assert!(coverage.snow() > 30.0, "{coverage:?}");
        assert!(coverage.deep_snow > coverage.thin_snow, "{coverage:?}");
        assert!(coverage.tundra > coverage.clear, "{coverage:?}");
        assert!(
            coverage.ice > 0.0 && coverage.ice == coverage.water,
            "{coverage:?}"
        );
        let desert = report(Biome::Desert);
        assert!(desert.report.coverage.sand > 30.0);
        let jungle = report(Biome::Jungle).report.coverage;
        assert!(
            jungle.light_jungle > 0.0 && jungle.heavy_jungle > 0.0,
            "{jungle:?}"
        );
        assert!(jungle.ultra_heavy_jungle > 0.0, "{jungle:?}");
        assert_eq!(jungle.light_woods + jungle.heavy_woods, 0.0, "{jungle:?}");
        let forest = report(Biome::Forest).report.coverage;
        assert!(forest.ultra_heavy_woods > 0.0, "{forest:?}");
        assert!(forest.ultra_heavy_woods < forest.heavy_woods, "{forest:?}");
        let swamp = report(Biome::Swamp).report.coverage;
        assert!(swamp.swamp > 20.0, "{swamp:?}");
        let lunar = report(Biome::Lunar);
        assert!(lunar.map.flags.contains(&MapFlag::Vacuum));
        let volcanic = report(Biome::Volcanic);
        assert!(volcanic.report.fire_hexes > 0 && volcanic.report.smoke_hexes > 0);
    }

    #[test]
    fn settlements_honor_exact_positions_and_walls() {
        let spec = MapSpec {
            seed: Some(8),
            settlements: vec![SettlementSpec {
                at: Some([20, 22]),
                walled: Some(true),
                ..SettlementSpec::new(SettlementSize::Town)
            }],
            ..MapSpec::default()
        };
        let generated = generate(&spec).unwrap();
        let town = &generated.report.settlements[0];
        assert_eq!(town.center, [20, 22]);
        assert!(town.walled && !town.gates.is_empty());
        assert!(generated.report.coverage.wall > 0.0);
        // Each gate is a paved street or a bridge on the wall line, and the wall is heavy.
        for &[x, y] in &town.gates {
            let hex = generated.map.hex(i32::from(x), i32::from(y)).unwrap();
            assert!(
                hex.route() == Some(Route::PavedRoad) || hex.has_bridge(),
                "{hex:?}"
            );
        }
        let walls = generated
            .map
            .hexes
            .iter()
            .filter_map(|hex| hex.structure())
            .filter(|structure| structure.kind == StructureKind::Wall);
        for wall in walls {
            assert_eq!(wall.class, ConstructionClass::Heavy);
        }
    }

    #[test]
    fn oversized_settlements_shrink_with_a_warning() {
        let spec = MapSpec {
            seed: Some(2),
            width: Some(16),
            height: Some(16),
            settlements: vec![SettlementSpec::new(SettlementSize::Metropolis)],
            ..MapSpec::default()
        };
        let generated = generate(&spec).unwrap();
        assert!(generated.report.warnings[0].contains("shrunk"));
        generated.map.validate().unwrap();
    }

    #[test]
    fn roads_link_settlements_and_cross_the_map() {
        let spec = MapSpec {
            seed: Some(4),
            size: Some(MapSize::Large),
            settlements: vec![SettlementSpec {
                count: Some(3),
                ..SettlementSpec::new(SettlementSize::Village)
            }],
            roads: Some(RoadSpec {
                through_roads: Some(2),
                ..RoadSpec::default()
            }),
            ..MapSpec::default()
        };
        let report = generate(&spec).unwrap().report;
        assert!(report.warnings.is_empty(), "{:?}", report.warnings);
        let links = report
            .roads
            .iter()
            .filter(|road| !road.from.contains("edge"));
        assert_eq!(links.count(), 2);
        assert!(report.roads.iter().any(|road| road.from == "west edge"));
        assert!(report.roads.iter().any(|road| road.from == "north edge"));
        let names: Vec<_> = report.settlements.iter().map(|s| s.name.as_str()).collect();
        assert_eq!(names, ["village 1", "village 2", "village 3"]);
    }

    /// Mountain peaks are ultra-rough, and snow lies over peaks, woods and rough ground alike
    /// above the snow line, with thin snow just below it.
    #[test]
    fn mountains_have_ultra_rough_peaks_under_snow() {
        let generated = generate(&MapSpec {
            seed: Some(6),
            biome: Some(Biome::Mountains),
            ..MapSpec::default()
        })
        .unwrap();
        let coverage = &generated.report.coverage;
        assert!(coverage.ultra_rough > 5.0, "{coverage:?}");
        assert!(
            coverage.deep_snow > 0.0 && coverage.thin_snow > 0.0,
            "{coverage:?}"
        );
        let hexes = &generated.map.hexes;
        let snowy = |hex: &&Hex| hex.condition() == Some(Condition::DeepSnow);
        assert!(
            hexes
                .iter()
                .filter(snowy)
                .any(|hex| hex.foliage().is_some())
        );
        assert!(
            hexes
                .iter()
                .filter(snowy)
                .any(|hex| hex.ground() == Ground::Rough)
        );
        assert!(
            hexes
                .iter()
                .filter(snowy)
                .any(|hex| hex.ground() == Ground::UltraRough)
        );
        let snow_line = hexes.iter().filter(snowy).map(|hex| hex.level()).min();
        assert!(
            hexes
                .iter()
                .filter(|hex| !hex.holds_water() && Some(hex.level()) >= snow_line)
                .all(|hex| hex.condition() == Some(Condition::DeepSnow) || hex.is_road()),
            "deep snow covers all dry land above the snow line except plowed roads"
        );
    }

    /// `frozen` lays ice over every lake and river, bridged or not, and nothing else.
    #[test]
    fn frozen_maps_ice_over_their_water() {
        let with = |biome, frozen| {
            generate(&MapSpec {
                seed: Some(12),
                biome: Some(biome),
                frozen: Some(frozen),
                settlements: vec![SettlementSpec::new(SettlementSize::Town)],
                ..MapSpec::default()
            })
            .unwrap()
            .map
        };
        let frozen = with(Biome::Temperate, true);
        assert!(frozen.hexes.iter().any(|hex| hex.holds_water()));
        for hex in &frozen.hexes {
            assert_eq!(hex.is_frozen(), hex.holds_water(), "{hex:?}");
            assert_eq!(hex.is_icy(), hex.holds_water(), "{hex:?}");
        }
        let thawed = with(Biome::Arctic, false);
        assert!(thawed.hexes.iter().all(|hex| !hex.is_icy()));
    }

    /// Roads are routes through the terrain they cross: woods stay standing, highways are
    /// paved, links between villages are dirt, and bridges match the road.
    #[test]
    fn roads_run_through_the_land_they_cross() {
        let generated = generate(&MapSpec {
            seed: Some(4),
            biome: Some(Biome::Forest),
            size: Some(MapSize::Large),
            rivers: Some(2),
            settlements: vec![SettlementSpec {
                count: Some(3),
                ..SettlementSpec::new(SettlementSize::Village)
            }],
            roads: Some(RoadSpec {
                through_roads: Some(2),
                ..RoadSpec::default()
            }),
            ..MapSpec::default()
        })
        .unwrap();
        for road in &generated.report.roads {
            let expected = if road.from.contains("edge") {
                Route::PavedRoad
            } else {
                Route::DirtRoad
            };
            assert_eq!(road.surface, expected, "{road:?}");
        }
        let coverage = &generated.report.coverage;
        assert!(
            coverage.dirt_road > 0.0 && coverage.paved_road > 0.0,
            "{coverage:?}"
        );
        let hexes = &generated.map.hexes;
        assert!(
            hexes
                .iter()
                .any(|hex| hex.route().is_some() && hex.is_woods()),
            "a road runs through woods"
        );
        for hex in hexes.iter().filter(|hex| hex.has_bridge()) {
            let class = hex.construction_class().unwrap();
            assert!(class != ConstructionClass::Hardened, "{hex:?}");
        }
    }

    /// Settlements pave their lots when large, build to a construction class that suits them,
    /// leave rubble and damaged buildings when ruined, and farm the land around them.
    #[test]
    fn settlements_build_to_suit_their_kind() {
        let generated = generate(&MapSpec {
            seed: Some(21),
            biome: Some(Biome::Temperate),
            size: Some(MapSize::Large),
            settlements: vec![
                SettlementSpec {
                    position: Some(Position::West),
                    ..SettlementSpec::new(SettlementSize::City)
                },
                SettlementSpec {
                    kind: Some(SettlementKind::Military),
                    position: Some(Position::Northeast),
                    ..SettlementSpec::new(SettlementSize::Village)
                },
                SettlementSpec {
                    kind: Some(SettlementKind::Ruins),
                    position: Some(Position::Southeast),
                    ..SettlementSpec::new(SettlementSize::Town)
                },
                SettlementSpec {
                    position: Some(Position::North),
                    ..SettlementSpec::new(SettlementSize::Hamlet)
                },
            ],
            ..MapSpec::default()
        })
        .unwrap();
        let map = &generated.map;
        let report = &generated.report;
        let structures_in = |index: usize| {
            let settlement = &report.settlements[index];
            let [cx, cy] = settlement.center;
            let center = (i32::from(cx), i32::from(cy));
            let radius = i32::from(settlement.radius);
            map.hexes
                .iter()
                .enumerate()
                .filter(move |&(at, _)| HexMap::distance(map.coordinate(at), center) <= radius)
                .filter_map(|(_, hex)| hex.structure())
                .filter(|structure| structure.is_standing())
                .collect::<Vec<_>>()
        };
        let city = structures_in(0);
        assert!(city.iter().any(|s| s.class == ConstructionClass::Heavy));
        assert!(city.iter().all(|s| s.class != ConstructionClass::Light));
        let base = structures_in(1);
        let walls = base.iter().filter(|s| s.kind == StructureKind::Wall);
        assert!(walls.clone().count() > 0);
        assert!(
            walls
                .into_iter()
                .all(|s| s.class == ConstructionClass::Hardened)
        );
        assert!(
            base.iter()
                .filter(|s| s.kind == StructureKind::Building)
                .all(|s| s.class == ConstructionClass::Heavy)
        );
        assert!(structures_in(2).iter().any(|s| !s.is_intact()));
        assert!(
            structures_in(3)
                .iter()
                .all(|s| s.class == ConstructionClass::Light)
        );
        let coverage = &report.coverage;
        assert!(
            coverage.pavement > 0.0 && coverage.rubble > 0.0,
            "{coverage:?}"
        );
        assert!(coverage.planted_fields > 0.0, "{coverage:?}");
    }

    /// Rivers dropping down mountainsides run as rapids or torrents.
    #[test]
    fn mountain_rivers_run_fast() {
        let rapids = (0..8).any(|seed| {
            let generated = generate(&MapSpec {
                seed: Some(seed),
                biome: Some(Biome::Mountains),
                rivers: Some(2),
                ..MapSpec::default()
            })
            .unwrap();
            generated.report.coverage.rapids > 0.0
        });
        assert!(rapids);
    }
}
