/* gamedb_sqlite.c -- SQLite game-database persistence */

#include "mux/persistence/gamedb_sqlite_internal.h"

// Increment whenever an incompatible schema change is made.
const int GAMEDB_SCHEMA_VERSION = 32;

// Identifies SQLite as the storage implementation in snapshot metadata.
const int GAMEDB_SOURCE_FORMAT_SQLITE = 1;

/*
 * Each file holds one complete game snapshot. Typed Lua object state is
 * normalized so a future incremental store can use the same representation.
 */
const char SCHEMA_OBJECTS_SQL[] =
    "CREATE TABLE snapshot ("
    " id INTEGER PRIMARY KEY CHECK (id = 1),"
    " schema_version INTEGER NOT NULL,"
    " storage_format INTEGER NOT NULL,"
    " storage_version INTEGER NOT NULL,"
    " dump_type INTEGER NOT NULL,"
    " dump_time INTEGER NOT NULL,"
    " db_top INTEGER NOT NULL,"
    " min_size INTEGER NOT NULL,"
    " record_players INTEGER NOT NULL"
    ");"
    "CREATE TABLE objects ("
    " dbref INTEGER PRIMARY KEY,"
    " name TEXT NOT NULL,"
    " location INTEGER NOT NULL,"
    " zone INTEGER NOT NULL,"
    " affiliation INTEGER NOT NULL DEFAULT -1,"
    " contents INTEGER NOT NULL,"
    " exits INTEGER NOT NULL,"
    " link INTEGER NOT NULL,"
    " next INTEGER NOT NULL,"
    " type INTEGER NOT NULL CHECK (type IN (0, 1, 2, 3, 5)),"
    " lua_parent TEXT NOT NULL DEFAULT '',"
    " description TEXT, internal_description TEXT,"
    " has_ansi_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_ansi_flag IN (0, 1)),"
    " has_audible_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_audible_flag IN "
    "(0, 1)),"
    " has_auditorium_flag INTEGER NOT NULL DEFAULT 0 CHECK "
    "(has_auditorium_flag IN (0, 1)),"
    " has_blind_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_blind_flag IN (0, "
    "1)),"
    " has_connected_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_connected_flag "
    "IN (0, 1)),"
    " has_dark_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_dark_flag IN (0, 1)),"
    " has_floating_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_floating_flag IN "
    "(0, 1)),"
    " has_gagged_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_gagged_flag IN (0, "
    "1)),"
    " has_going_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_going_flag IN (0, "
    "1)),"
    " has_halted_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_halted_flag IN (0, "
    "1)),"
    " has_in_character_flag INTEGER NOT NULL DEFAULT 0 CHECK "
    "(has_in_character_flag IN (0, 1)),"
    " has_light_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_light_flag IN (0, "
    "1)),"
    " has_monitor_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_monitor_flag IN "
    "(0, 1)),"
    " has_no_command_flag INTEGER NOT NULL DEFAULT 0 CHECK "
    "(has_no_command_flag IN (0, 1)),"
    " has_safe_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_safe_flag IN (0, 1)),"
    " has_suspect_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_suspect_flag IN "
    "(0, 1)),"
    " has_transparent_flag INTEGER NOT NULL DEFAULT 0 CHECK "
    "(has_transparent_flag IN (0, 1)),"
    " has_wizard_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_wizard_flag IN (0, "
    "1)),"
    " has_zombie_flag INTEGER NOT NULL DEFAULT 0 CHECK (has_zombie_flag IN (0, "
    "1)),"
    " has_idle_power INTEGER NOT NULL DEFAULT 0 CHECK (has_idle_power IN (0, "
    "1))"
    ");";

const char SCHEMA_STATE_SQL[] =
    "CREATE TABLE player_state ("
    " object_dbref INTEGER PRIMARY KEY REFERENCES objects(dbref),"
    " password_hash TEXT, alias TEXT, last_login INTEGER, last_site TEXT,"
    " successful_login_count INTEGER NOT NULL DEFAULT 0 CHECK "
    "(successful_login_count >= 0),"
    " failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK "
    "(failed_login_count >= 0),"
    " unreported_failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK "
    "(unreported_failed_login_count >= 0 AND "
    "unreported_failed_login_count <= failed_login_count)"
    ");"
    "CREATE TABLE player_login_history ("
    " player_dbref INTEGER NOT NULL REFERENCES player_state(object_dbref) "
    "ON DELETE CASCADE,"
    " outcome INTEGER NOT NULL CHECK (outcome IN (0, 1)),"
    " position INTEGER NOT NULL CHECK (position >= 0 AND "
    "((outcome = 0 AND position < 4) OR (outcome = 1 AND position < 3))),"
    " occurred_at INTEGER NOT NULL, host TEXT NOT NULL,"
    " PRIMARY KEY (player_dbref, outcome, position)"
    ") WITHOUT ROWID;"
    "CREATE TABLE player_last_page_recipients ("
    " player_dbref INTEGER NOT NULL REFERENCES player_state(object_dbref) "
    "ON DELETE CASCADE,"
    " position INTEGER NOT NULL CHECK (position >= 0),"
    " recipient_dbref INTEGER NOT NULL,"
    " PRIMARY KEY (player_dbref, position)"
    ") WITHOUT ROWID;"
    "CREATE TABLE btech_character_state ("
    " player_dbref INTEGER PRIMARY KEY REFERENCES objects(dbref) ON DELETE "
    "CASCADE,"
    " bruise INTEGER NOT NULL CHECK (bruise BETWEEN 0 AND 255),"
    " lethal INTEGER NOT NULL CHECK (lethal BETWEEN 0 AND 255),"
    " build INTEGER NOT NULL CHECK (build BETWEEN 0 AND 255),"
    " reflexes INTEGER NOT NULL CHECK (reflexes BETWEEN 0 AND 255),"
    " intuition INTEGER NOT NULL CHECK (intuition BETWEEN 0 AND 255),"
    " learn INTEGER NOT NULL CHECK (learn BETWEEN 0 AND 255),"
    " charisma INTEGER NOT NULL CHECK (charisma BETWEEN 0 AND 255)"
    ");"
    "CREATE TABLE btech_character_values ("
    " player_dbref INTEGER NOT NULL REFERENCES "
    "btech_character_state(player_dbref) ON DELETE CASCADE,"
    " value_name TEXT NOT NULL CHECK (length(value_name) BETWEEN 1 AND 255),"
    " value INTEGER NOT NULL CHECK (value BETWEEN 0 AND 255),"
    " xp INTEGER NOT NULL CHECK (xp >= 0), last_used INTEGER NOT NULL,"
    " PRIMARY KEY (player_dbref, value_name)"
    ") WITHOUT ROWID;"
    "CREATE TABLE btech_economy_parts ("
    " object_dbref INTEGER NOT NULL REFERENCES objects(dbref) ON DELETE "
    "CASCADE,"
    " part_id INTEGER NOT NULL, brand_id INTEGER NOT NULL,"
    " quantity INTEGER NOT NULL CHECK (quantity > 0),"
    " PRIMARY KEY (object_dbref, part_id, brand_id)"
    ") WITHOUT ROWID;"
    "CREATE TABLE object_state ("
    " object_dbref INTEGER NOT NULL REFERENCES objects(dbref),"
    " namespace TEXT NOT NULL,"
    " key TEXT NOT NULL,"
    " value_type INTEGER NOT NULL CHECK (value_type BETWEEN 1 AND 4),"
    " value BLOB NOT NULL,"
    " PRIMARY KEY (object_dbref, namespace, key)"
    ") WITHOUT ROWID;";

/* Log either the SQLite error or the current operating-system error. */
