---@meta _

---Generated by `lua-type-generator` from LuaLS contracts in native C.
---Do not edit; run `just update-lua-types`.

---@alias BtechAutopilotOrder BtechAutopilotTargetOrder|BtechAutopilotDestinationOrder|BtechAutopilotEnterBaseOrder|BtechAutopilotLeaveBaseOrder|BtechAutopilotMapRoamOrder|BtechAutopilotRadiusRoamOrder|BtechAutopilotAutomaticAutogunOrder|BtechAutopilotTargetAutogunOrder|BtechAutopilotSimpleOrder|BtechAutopilotSpeedOrder
---@alias BtechAutopilotStatusOrder BtechAutopilotResolvedTargetOrder|BtechAutopilotDestinationOrder|BtechAutopilotEnterBaseOrder|BtechAutopilotLeaveBaseOrder|BtechAutopilotMapRoamOrder|BtechAutopilotRadiusRoamOrder|BtechAutopilotAutomaticAutogunOrder|BtechAutopilotResolvedTargetAutogunOrder|BtechAutopilotSimpleOrder|BtechAutopilotSpeedOrder

---@alias BtechLineOfSight "none"|"blocked"|"clear"

---@alias BtechMapEntrance BtechMapOffsetEntrance|BtechMapExactEntrance

---@alias BtechPartRef BtechPart|integer|string

---@alias BtechBuildingContactMode "follow_brief"|"include"|"exclude"

---@alias BtechImmediateRepair BtechRepairArmorRequest|BtechRepairInternalRequest|BtechRepairRearArmorRequest|BtechRepairPartRequest|BtechRepairReattachRequest

---@alias BtechTerrain "grassland"|"road"|"light_forest"|"heavy_forest"|"water"|"ice"|"bridge"|"high_water"|"rough"|"mountains"|"fire"|"smoke"|"snow"|"building"|"wall"

---@alias ArmorStatusField 0|1|2 Armor field: current armor, internal structure, or rear armor.

---@alias CriticalSlotField "NAME"|"STATUS"|"DATA"|"MAXAMMO"|"AMMOTYPE"|"MODE"|"HALFTON" Canonical critical-slot field; native matching is ASCII-case-insensitive.

---Typed order-name constant from [`btech.autopilot.orders`](lua://btech.autopilot.orders).
---@class BtechAutopilotOrderName
---Typed base-entry direction from [`btech.autopilot.directions`](lua://btech.autopilot.directions).
---@class BtechAutopilotDirection
---Typed roaming mode from [`btech.autopilot.roam_modes`](lua://btech.autopilot.roam_modes).
---@class BtechAutopilotRoamMode
---Typed automatic-gunnery mode from [`btech.autopilot.autogun_modes`](lua://btech.autopilot.autogun_modes).
---@class BtechAutopilotAutogunMode
---@class (exact) BtechAutopilotOrderNamespace
---@field CHASE_TARGET BtechAutopilotOrderName
---@field DUMB_FOLLOW BtechAutopilotOrderName
---@field FOLLOW BtechAutopilotOrderName
---@field EMBARK BtechAutopilotOrderName
---@field PICK_UP BtechAutopilotOrderName
---@field DUMB_GOTO BtechAutopilotOrderName
---@field GOTO BtechAutopilotOrderName
---@field OLD_GOTO BtechAutopilotOrderName
---@field ENTER_BASE BtechAutopilotOrderName
---@field LEAVE_BASE BtechAutopilotOrderName
---@field ROAM BtechAutopilotOrderName
---@field AUTO_GUN BtechAutopilotOrderName
---@field DROP_OFF BtechAutopilotOrderName
---@field SHUT_DOWN BtechAutopilotOrderName
---@field START_UP BtechAutopilotOrderName
---@field UNIT_DISEMBARK BtechAutopilotOrderName
---@field SPEED BtechAutopilotOrderName
---@class (exact) BtechAutopilotDirectionNamespace
---@field NORTH BtechAutopilotDirection
---@field EAST BtechAutopilotDirection
---@field SOUTH BtechAutopilotDirection
---@field WEST BtechAutopilotDirection
---@class (exact) BtechAutopilotRoamModeNamespace
---@field MAP BtechAutopilotRoamMode
---@field RADIUS BtechAutopilotRoamMode
---@class (exact) BtechAutopilotAutogunModeNamespace
---@field AUTOMATIC BtechAutopilotAutogunMode
---@field OFF BtechAutopilotAutogunMode
---@field TARGET BtechAutopilotAutogunMode
---@class BtechAutopilotTargetOrder
---@field name BtechAutopilotOrderName
---@field target DbRef|Object
---@class BtechAutopilotDestinationOrder
---@field name BtechAutopilotOrderName
---@field x integer Nonnegative coordinate (0 through 2147483647).
---@field y integer Nonnegative coordinate (0 through 2147483647).
---@class BtechAutopilotEnterBaseOrder
---@field name BtechAutopilotOrderName
---@field direction BtechAutopilotDirection
---@class BtechAutopilotLeaveBaseOrder
---@field name BtechAutopilotOrderName
---@field heading integer Heading from 0 through 359.
---@class BtechAutopilotMapRoamOrder
---@field name BtechAutopilotOrderName
---@field mode BtechAutopilotRoamMode
---@class BtechAutopilotRadiusRoamOrder
---@field name BtechAutopilotOrderName
---@field mode BtechAutopilotRoamMode
---@field x integer Nonnegative coordinate (0 through 2147483647).
---@field y integer Nonnegative coordinate (0 through 2147483647).
---@field radius integer Radius from 1 through 30.
---@class BtechAutopilotAutomaticAutogunOrder
---@field name BtechAutopilotOrderName
---@field mode BtechAutopilotAutogunMode
---@class BtechAutopilotTargetAutogunOrder
---@field name BtechAutopilotOrderName
---@field mode BtechAutopilotAutogunMode
---@field target DbRef|Object
---@class BtechAutopilotSimpleOrder
---@field name BtechAutopilotOrderName
---@class BtechAutopilotSpeedOrder
---@field name BtechAutopilotOrderName
---@field percent integer Speed percentage from 1 through 100.
---@class BtechAutopilotResolvedTargetOrder: BtechAutopilotTargetOrder
---@field target Object
---@class BtechAutopilotResolvedTargetAutogunOrder: BtechAutopilotTargetAutogunOrder
---@field target Object

---@class BtechAutopilotModes
---@field autogun_enabled boolean
---@field autogun_suspended boolean
---@field piloting_suspended boolean
---@field roaming boolean
---@field manual_sensors boolean
---@field chasing_target boolean
---@field chase_resume_pending boolean
---@field swarm_charging boolean
---@field assigned_target boolean
---@class BtechAutopilotStatus
---@field container_unit? Object
---@field associated_unit? Object
---@field map? Object
---@field association "none"|"ready"|"associated"|"conflict"
---@field engaged boolean
---@field speed_percent integer
---@field order_count integer
---@field order_capacity integer Always 100.
---@field orders BtechAutopilotStatusOrder[]
---@field modes BtechAutopilotModes
---@class BtechAutopilotEventStats
---@field goto integer
---@field leave integer
---@field command integer
---@field autogun integer
---@field sensor integer
---@field follow integer
---@field enter_base integer
---@field reply integer
---@field profile integer
---@field roam integer
---@field total integer

---Typed repair operation from [`btech.repair.operations`](lua://btech.repair.operations).
---@class BtechRepairOperation
---Typed unit class from [`btech.unit.types`](lua://btech.unit.types).
---@class BtechUnitType
---Typed movement class from [`btech.unit.movement_types`](lua://btech.unit.movement_types).
---@class BtechMovementType
---Typed unit-layout section from [`btech.unit.sections`](lua://btech.unit.sections).
---@class BtechSection
---Typed technology code from [`btech.unit.technology`](lua://btech.unit.technology).
---@class BtechTechnologyCode
---Typed technology group from [`btech.unit.technology_groups`](lua://btech.unit.technology_groups).
---@class BtechTechnologyGroup
---Typed weapon fire mode from [`btech.unit.fire_modes`](lua://btech.unit.fire_modes).
---@class BtechFireMode
---Typed ammunition mode from [`btech.unit.ammunition_modes`](lua://btech.unit.ammunition_modes).
---@class BtechAmmunitionMode

---@class BtechCargoTransferPoint
---@field x integer
---@field y integer
---@field reveal_hint boolean
---@class BtechMapOffsetEntrance
---@field mode "offset"
---@field offset integer
---@class BtechMapExactEntrance
---@field mode "exact"
---@field x integer
---@field y integer
---@class BtechMapEntrances
---@field north? BtechMapEntrance
---@field east? BtechMapEntrance
---@field south? BtechMapEntrance
---@field west? BtechMapEntrance
---@class BtechMapLink
---@field parent DbRef|Object
---@field x integer
---@field y integer
---@field entrances? BtechMapEntrances

---@class BtechPersonalCombatArmor
---@field head integer
---@field torso integer
---@field hands integer
---@field feet integer

---@class BtechPersonalCombatEquipment
---@field weapon BtechPart
---@field ammunition? integer

---@class BtechPersonalCombatLoadout
---@field armor BtechPersonalCombatArmor
---@field right? BtechPersonalCombatEquipment
---@field left? BtechPersonalCombatEquipment

---@class BtechUiPreferencesState
---@field tactical_height integer
---@field tactical_width integer
---@field lrs_height integer
---@field include_dead boolean
---@field include_shutdown boolean
---@field include_enemies boolean
---@field include_allies boolean
---@field include_target boolean
---@field buildings BtechBuildingContactMode
---@field configured boolean

---@class (exact) BtechRepairOperationNamespace
---@field REATTACH BtechRepairOperation
---@field REPAIR_PART BtechRepairOperation
---@field REPAIR_WEAPON_TEMPORARY BtechRepairOperation
---@field REPAIR_ENHANCEMENT BtechRepairOperation
---@field REPAIR_FOCUS BtechRepairOperation
---@field REPAIR_CRYSTAL BtechRepairOperation
---@field REPAIR_BARREL BtechRepairOperation
---@field REPAIR_AMMO_FEED BtechRepairOperation
---@field REPAIR_RANGING BtechRepairOperation
---@field REPAIR_AMMO_MOUNT BtechRepairOperation
---@field REPLACE_WEAPON BtechRepairOperation
---@field RELOAD BtechRepairOperation
---@field REPAIR_ARMOR BtechRepairOperation
---@field REPAIR_REAR_ARMOR BtechRepairOperation
---@field REPAIR_INTERNAL BtechRepairOperation
---@field DETACH BtechRepairOperation
---@field SCRAP_PART BtechRepairOperation
---@field SCRAP_WEAPON BtechRepairOperation
---@field UNLOAD BtechRepairOperation
---@field RESEAL BtechRepairOperation
---@field REPLACE_SUIT BtechRepairOperation
---@class BtechRepairArmorRequest
---@field operation BtechRepairOperation
---@field section BtechSection
---@field value integer
---@class BtechRepairInternalRequest
---@field operation BtechRepairOperation
---@field section BtechSection
---@field value integer
---@class BtechRepairRearArmorRequest
---@field operation BtechRepairOperation
---@field section BtechSection
---@field value integer
---@class BtechRepairPartRequest
---@field operation BtechRepairOperation
---@field section BtechSection
---@field slot integer
---@class BtechRepairReattachRequest
---@field operation BtechRepairOperation
---@field section BtechSection

---@class BtechCharacterValueDefinition
---@field code integer
---@field name string
---@field kind string
---@field default_experience_threshold integer
---@class BtechCharacterValue
---@field definition BtechCharacterValueDefinition
---@field amount integer
---@field target? integer
---@field experience? integer
---@field experience_to_next_level? integer
---@class BtechWeaponStats
---@field kind string
---@field heat integer
---@field damage integer
---@field minimum_range integer
---@field short_range integer
---@field medium_range integer
---@field long_range integer
---@field critical_slots integer
---@field ammunition_per_ton integer
---@field recycle_time integer
---@field battle_value integer
---@class BtechPart
---@field id integer
---@field brand integer
---@field packed_id integer
---@field short_name string
---@field long_name string
---@field very_long_name string
---@field category string
---@field weight_tons number
---@field cost integer
---@field weapon? BtechWeaponStats
---@class BtechPartStack
---@field part BtechPart
---@field quantity integer
---@class BtechValuePair
---@field current integer
---@field original integer
---@class BtechArmorStatus
---@field section? BtechSection
---@field armor BtechValuePair
---@field internal BtechValuePair
---@field rear_armor BtechValuePair
---@class BtechAmmunitionStatus
---@field rounds integer
---@field capacity integer
---@class BtechCriticalSlot
---@field section BtechSection
---@field slot integer
---@field kind string
---@field part? BtechPart
---@field operational boolean
---@field temporary_failure boolean
---@field auxiliary_data integer
---@field ammunition? BtechAmmunitionStatus
---@field fire_modes BtechFireMode[]
---@field ammunition_modes BtechAmmunitionMode[]
---@class BtechMountedWeapon
---@field number integer
---@field section BtechSection
---@field first_slot integer
---@field part BtechPart
---@field slot_count integer
---@field recycle integer
---@field recycle_time integer
---@field operational boolean
---@class BtechEngine
---@field rating integer
---@field suspension_factor integer
---@class BtechRadioChannel
---@field channel integer
---@field frequency integer
---@field title string
---@field modes string[]
---@class BtechBattleValue
---@field total number
---@field offensive number
---@field defensive number
---@class BtechTechnology
---@field code BtechTechnologyCode
---@field name string
---@field group "primary"|"secondary"|"infantry"
---@field source "configured"|"inferred"
---@class BtechRepairNeed
---@field operation BtechRepairOperation
---@field section BtechSection
---@field slot? integer
---@field amount? integer
---@field in_progress boolean
---@class BtechHex
---@field x integer
---@field y integer
---@class BtechPosition: BtechHex
---@field z? integer
---@class BtechPartCategory
---@field code string
---@field name string
---@class BtechBlastZone
---@field x integer
---@field y integer
---@field radius integer
---@class BtechMapEmitOptions
---@field audience? "all"|"range"|"line_of_sight"
---@field origin? BtechPosition
---@field range? number

---@class BtechWeaponInstall
---@field part BtechPartRef
---@field section BtechSection
---@field slots integer[]
---@field rear_facing? boolean
---@field targeting_computer? boolean
---@field one_shot? boolean
---@class BtechAmmunitionConfiguration
---@field weapon BtechPartRef
---@field section BtechSection
---@field slot integer
---@field half_ton? boolean
---@field ammunition_modes? BtechAmmunitionMode[]
---@class BtechWeaponModes
---@field fire_modes? BtechFireMode[]
---@field ammunition_modes? BtechAmmunitionMode[]
---@class BtechSpecialInstall
---@field part? BtechPartRef Omit to empty the slot.
---@field section BtechSection
---@field slot integer
---@field auxiliary_data? integer

---@class (exact) BtechUnitTypeNamespace
---@field MECH BtechUnitType
---@field VEHICLE BtechUnitType
---@field VTOL BtechUnitType
---@field NAVAL BtechUnitType
---@field SPHEROID_DROPSHIP BtechUnitType
---@field AERO_FIGHTER BtechUnitType
---@field MECHWARRIOR BtechUnitType
---@field AERODYNE_DROPSHIP BtechUnitType
---@field BATTLESUIT BtechUnitType
---@class (exact) BtechMovementTypeNamespace
---@field BIPED BtechMovementType
---@field TRACK BtechMovementType
---@field WHEEL BtechMovementType
---@field HOVER BtechMovementType
---@field VTOL BtechMovementType
---@field HULL BtechMovementType
---@field FOIL BtechMovementType
---@field FLY BtechMovementType
---@field QUAD BtechMovementType
---@field SUB BtechMovementType
---@field NONE BtechMovementType
---@class (exact) BtechSectionNamespace
---@field FRONT_LEFT_LEG BtechSection
---@field FRONT_RIGHT_LEG BtechSection
---@field LEFT_TORSO BtechSection
---@field RIGHT_TORSO BtechSection
---@field CENTER_TORSO BtechSection
---@field REAR_LEFT_LEG BtechSection
---@field REAR_RIGHT_LEG BtechSection
---@field HEAD BtechSection
---@field LEFT_ARM BtechSection
---@field RIGHT_ARM BtechSection
---@field LEFT_LEG BtechSection
---@field RIGHT_LEG BtechSection
---@field SUIT_1 BtechSection
---@field SUIT_2 BtechSection
---@field SUIT_3 BtechSection
---@field SUIT_4 BtechSection
---@field SUIT_5 BtechSection
---@field SUIT_6 BtechSection
---@field SUIT_7 BtechSection
---@field SUIT_8 BtechSection
---@field LEFT_SIDE BtechSection
---@field RIGHT_SIDE BtechSection
---@field FRONT_SIDE BtechSection
---@field AFT_SIDE BtechSection
---@field TURRET BtechSection
---@field ROTOR BtechSection
---@field NOSE BtechSection
---@field LEFT_WING BtechSection
---@field RIGHT_WING BtechSection
---@field LEFT_REAR_WING BtechSection
---@field RIGHT_REAR_WING BtechSection
---@field AFT BtechSection
---@field FRONT_RIGHT_SIDE BtechSection
---@field FRONT_LEFT_SIDE BtechSection
---@field REAR_LEFT_SIDE BtechSection
---@field REAR_RIGHT_SIDE BtechSection
---@class (exact) BtechTechnologyCodeNamespace
---@field TRIPLE_STRENGTH_MYOMER BtechTechnologyCode
---@field CLAN_ANTI_MISSILE BtechTechnologyCode
---@field INNER_SPHERE_ANTI_MISSILE BtechTechnologyCode
---@field DOUBLE_HEAT_SINKS BtechTechnologyCode
---@field MASC BtechTechnologyCode
---@field CLAN BtechTechnologyCode
---@field FLIPPABLE_ARMS BtechTechnologyCode
---@field C3_MASTER BtechTechnologyCode
---@field C3_SLAVE BtechTechnologyCode
---@field ARTEMIS_IV BtechTechnologyCode
---@field ECM BtechTechnologyCode
---@field BEAGLE_PROBE BtechTechnologyCode
---@field SALVAGE BtechTechnologyCode
---@field CARGO BtechTechnologyCode
---@field SEARCH_LIGHT BtechTechnologyCode
---@field LIGHT_ACTIVE_PROBE BtechTechnologyCode
---@field ANTI_AIRCRAFT BtechTechnologyCode
---@field NO_SENSORS BtechTechnologyCode
---@field SIXTH_SENSE BtechTechnologyCode
---@field FERRO_FIBROUS BtechTechnologyCode
---@field ENDO_STEEL BtechTechnologyCode
---@field XL_ENGINE BtechTechnologyCode
---@field ICE_ENGINE BtechTechnologyCode
---@field SINGLE_HEAT_SINKS BtechTechnologyCode
---@field LIGHT_ENGINE BtechTechnologyCode
---@field XXL_ENGINE BtechTechnologyCode
---@field COMPACT_ENGINE BtechTechnologyCode
---@field REINFORCED_INTERNAL BtechTechnologyCode
---@field COMPOSITE_INTERNAL BtechTechnologyCode
---@field HARDENED_ARMOR BtechTechnologyCode
---@field CRITICAL_PROOF BtechTechnologyCode
---@field STEALTH_ARMOR BtechTechnologyCode
---@field HEAVY_FERRO_FIBROUS BtechTechnologyCode
---@field LASER_REFLECTIVE_ARMOR BtechTechnologyCode
---@field REACTIVE_ARMOR BtechTechnologyCode
---@field NULL_SIGNATURE_SYSTEM BtechTechnologyCode
---@field C3I BtechTechnologyCode
---@field SUPERCHARGER BtechTechnologyCode
---@field IMPROVED_JUMP_JETS BtechTechnologyCode
---@field MECHANICAL_JUMP_JETS BtechTechnologyCode
---@field COMPACT_HEAT_SINKS BtechTechnologyCode
---@field LASER_HEAT_SINKS BtechTechnologyCode
---@field BLOODHOUND_PROBE BtechTechnologyCode
---@field ANGEL_ECM BtechTechnologyCode
---@field WATCHDOG BtechTechnologyCode
---@field LIGHT_FERRO_FIBROUS BtechTechnologyCode
---@field TAG BtechTechnologyCode
---@field OMNIMECH BtechTechnologyCode
---@field ARTEMIS_V BtechTechnologyCode
---@field CAMOUFLAGE BtechTechnologyCode
---@field CARRIER BtechTechnologyCode
---@field WATERPROOF BtechTechnologyCode
---@field XL_GYRO BtechTechnologyCode
---@field HEAVY_DUTY_GYRO BtechTechnologyCode
---@field COMPACT_GYRO BtechTechnologyCode
---@field TARGETING_COMPUTER BtechTechnologyCode
---@field SMALL_COCKPIT BtechTechnologyCode
---@field SWARM_ATTACK BtechTechnologyCode
---@field MOUNT_FRIENDS BtechTechnologyCode
---@field ANTI_LEG_ATTACK BtechTechnologyCode
---@field PURIFIER_STEALTH BtechTechnologyCode
---@field KAGE_STEALTH BtechTechnologyCode
---@field ACHILEUS_STEALTH BtechTechnologyCode
---@field INFILTRATOR_STEALTH BtechTechnologyCode
---@field INFILTRATOR_II_STEALTH BtechTechnologyCode
---@field MUST_JETTISON_PACK BtechTechnologyCode
---@field CAN_JETTISON_PACK BtechTechnologyCode
---@class (exact) BtechTechnologyGroupNamespace
---@field UNIT BtechTechnologyGroup
---@field INFANTRY BtechTechnologyGroup
---@field ALL BtechTechnologyGroup
---@class (exact) BtechFireModeNamespace
---@field DESTROYED BtechFireMode
---@field DISABLED BtechFireMode
---@field BROKEN BtechFireMode
---@field DAMAGED BtechFireMode
---@field TARGETING_COMPUTER BtechFireMode
---@field REAR_MOUNT BtechFireMode
---@field HOTLOAD BtechFireMode
---@field HALF_TON BtechFireMode
---@field ONE_SHOT BtechFireMode
---@field ONE_SHOT_USED BtechFireMode
---@field ULTRA BtechFireMode
---@field RAPID_FIRE BtechFireMode
---@field GATLING BtechFireMode
---@field ROTARY_TWO_SHOT BtechFireMode
---@field ROTARY_FOUR_SHOT BtechFireMode
---@field ROTARY_SIX_SHOT BtechFireMode
---@field HEAT BtechFireMode
---@field BACKPACK BtechFireMode
---@field JETTISONED BtechFireMode
---@field OMNI_BASE BtechFireMode
---@field ROCKET_FIRED BtechFireMode
---@class (exact) BtechAmmunitionModeNamespace
---@field LBX_CLUSTER BtechAmmunitionMode
---@field ARTEMIS_MINE BtechAmmunitionMode
---@field NARC_SMOKE BtechAmmunitionMode
---@field CLUSTER BtechAmmunitionMode
---@field MINE BtechAmmunitionMode
---@field SMOKE BtechAmmunitionMode
---@field INFERNO BtechAmmunitionMode
---@field SWARM BtechAmmunitionMode
---@field SWARM_1 BtechAmmunitionMode
---@field INARC_EXPLOSIVE BtechAmmunitionMode
---@field INARC_HAYWIRE BtechAmmunitionMode
---@field INARC_ECM BtechAmmunitionMode
---@field INARC_NEMESIS BtechAmmunitionMode
---@field ARMOR_PIERCING BtechAmmunitionMode
---@field FLECHETTE BtechAmmunitionMode
---@field INCENDIARY BtechAmmunitionMode
---@field PRECISION BtechAmmunitionMode
---@field STINGER BtechAmmunitionMode
---@field CASELESS BtechAmmunitionMode
---@field SEMI_GUIDED BtechAmmunitionMode
---@field EXTENDED_RANGE BtechAmmunitionMode
---@field HIGH_EXPLOSIVE BtechAmmunitionMode
---@field MML_LRM BtechAmmunitionMode

---@class BtechErrorPackage
---@field codes BtechErrorCodes Checked native BattleTech code tree.

---Checked native BattleTech error-code tree.
---@class BtechPartNotFoundErrorCode: ErrorCode
---@field code "btech.part.not_found"
---@class BtechPartAmbiguousErrorCode: ErrorCode
---@field code "btech.part.ambiguous"
---@class BtechPartWrongKindErrorCode: ErrorCode
---@field code "btech.part.wrong_kind"
---@class BtechPartErrorCodes: ErrorCode
---@field not_found BtechPartNotFoundErrorCode `btech.part.not_found`.
---@field ambiguous BtechPartAmbiguousErrorCode `btech.part.ambiguous`.
---@field wrong_kind BtechPartWrongKindErrorCode `btech.part.wrong_kind`.
---@class BtechTemplateNotFoundErrorCode: ErrorCode
---@field code "btech.template.not_found"
---@class BtechTemplateInvalidErrorCode: ErrorCode
---@field code "btech.template.invalid"
---@class BtechTemplateErrorCodes: ErrorCode
---@field not_found BtechTemplateNotFoundErrorCode `btech.template.not_found`.
---@field invalid BtechTemplateInvalidErrorCode `btech.template.invalid`.
---@class BtechOperationFailedErrorCode: ErrorCode
---@field code "btech.operation.failed"
---@class BtechOperationErrorCodes: ErrorCode
---@field failed BtechOperationFailedErrorCode `btech.operation.failed`.
---@class BtechErrorCodes: ErrorCode
---@field part BtechPartErrorCodes Part resolution errors.
---@field template BtechTemplateErrorCodes Template resolution errors.
---@field operation BtechOperationErrorCodes Operational failures.

---The native BattleTech host API. All functions are unavailable during `@lua/check`.
---@class BtechPackage
---@field autopilot BtechAutopilotPackage
---@field character BtechCharacterPackage
---@field map BtechMapPackage
---@field parts BtechPartsPackage
---@field player BtechPlayerPackage
---@field repair BtechRepairPackage
---@field system BtechSystemPackage
---@field template BtechTemplatePackage
---@field unit BtechUnitPackage
---@field error BtechErrorPackage
btech = {}

---@class BtechAutopilotPackage
---@field orders BtechAutopilotOrderNamespace
---@field directions BtechAutopilotDirectionNamespace
---@field roam_modes BtechAutopilotRoamModeNamespace
---@field autogun_modes BtechAutopilotAutogunModeNamespace
local btech_autopilot = {}

---@class BtechCharacterPackage
local btech_character = {}

---@class BtechMapPackage
local btech_map = {}

---@class BtechPartsPackage
local btech_parts = {}

---@class BtechPlayerPackage
local btech_player = {}

---@class BtechRepairPackage
---@field operations BtechRepairOperationNamespace
local btech_repair = {}

---@class BtechSystemPackage
local btech_system = {}

---@class BtechTemplatePackage
local btech_template = {}

---@class BtechUnitPackage
---@field types BtechUnitTypeNamespace
---@field movement_types BtechMovementTypeNamespace
---@field sections BtechSectionNamespace
---@field technology BtechTechnologyCodeNamespace
---@field technology_groups BtechTechnologyGroupNamespace
---@field fire_modes BtechFireModeNamespace
---@field ammunition_modes BtechAmmunitionModeNamespace
local btech_unit = {}

---@param autopilot DbRef|Object
---@param order BtechAutopilotOrder
function btech_autopilot.add_order(autopilot, order, ...) end

---@param autopilot DbRef|Object
function btech_autopilot.clear_orders(autopilot, ...) end

---@param autopilot DbRef|Object
function btech_autopilot.disengage(autopilot, ...) end

---@param autopilot DbRef|Object
function btech_autopilot.engage(autopilot, ...) end

---@param autopilot DbRef|Object
---@return BtechAutopilotEventStats stats
function btech_autopilot.event_stats(autopilot, ...) end

---@param autopilot DbRef|Object
---@param position integer
function btech_autopilot.remove_order(autopilot, position, ...) end

---@param autopilot DbRef|Object
---@return BtechAutopilotStatus status
function btech_autopilot.status(autopilot, ...) end

---@param character Object
---@param skill string
---@param amount integer
function btech_character.add_skill_experience(character, skill, amount) end

---@param kind string
---@param character? Object
---@return BtechCharacterValueDefinition[] definitions
function btech_character.catalog(kind, character) end

---@param skill string
---@return integer threshold
function btech_character.experience_threshold(skill) end

---@param character Object
---@param skill string
---@param experience integer
function btech_character.set_skill_experience(character, skill, experience) end

---@param character Object
---@param skill string
---@param target integer
function btech_character.set_skill_target(character, skill, target) end

---@param character Object
---@param value string
---@param amount integer
function btech_character.set_value(character, value, amount) end

---@param character Object
---@param value string|integer
---@return BtechCharacterValue result
function btech_character.value(character, value) end

---@param map DbRef|Object
---@return BtechBlastZone[] zones
function btech_map.blast_zones(map) end

---@param map DbRef|Object
---@return BtechCargoTransferPoint|nil point
function btech_map.cargo_transfer_point(map) end

---@param map DbRef|Object
---@param hex BtechHex
---@return integer elevation
function btech_map.elevation(map, hex) end

---@param map DbRef|Object
---@param message string
---@param options? BtechMapEmitOptions
function btech_map.emit(map, message, options) end

---@param map DbRef|Object
---@param hex BtechHex
---@return boolean inside
function btech_map.in_blast_zone(map, hex) end

---@param observer DbRef|Object
---@param target DbRef|Object|BtechHex
---@return BtechLineOfSight state
function btech_map.line_of_sight(observer, target) end

---@param child DbRef|Object
---@return BtechMapLink|nil link
function btech_map.link(child) end

---@param map DbRef|Object
---@param name string
function btech_map.load(map, name) end

---@param unit DbRef|Object
---@param map DbRef|Object
---@param position BtechPosition
function btech_map.place_unit(unit, map, position) end

---@param map DbRef|Object
---@param from DbRef|Object|BtechPosition
---@param to DbRef|Object|BtechPosition
---@return number range
function btech_map.range(map, from, to) end

---@param map DbRef|Object
---@param point BtechCargoTransferPoint|nil
function btech_map.set_cargo_transfer_point(map, point) end

---@param child DbRef|Object
---@param link BtechMapLink|nil
function btech_map.set_link(child, link) end

---@param map DbRef|Object
---@param hex BtechHex
---@return BtechTerrain terrain
function btech_map.terrain(map, hex) end

---@param origin DbRef|Object
---@param id string
---@return Object|nil unit
function btech_map.unit_by_id(origin, id) end

---@param map DbRef|Object
---@param filter? table
---@return Object[] units
function btech_map.units(map, filter) end

---@param map DbRef|Object
function btech_map.update_links(map) end

---@param target DbRef|Object
---@param part BtechPartRef
---@param delta integer
function btech_parts.adjust_stores(target, part, delta) end

---@return BtechPartCategory[] categories
function btech_parts.categories() end

---@param category? string
---@return BtechPart[] parts
function btech_parts.list(category) end

---@param part BtechPartRef
---@return BtechPart|nil part
function btech_parts.resolve(part) end

---@param query string
---@return BtechPart[] parts
function btech_parts.search(query) end

---@param part BtechPartRef
---@param cost integer
function btech_parts.set_cost(part, cost) end

---@param target DbRef|Object
---@param part BtechPartRef
---@return integer quantity
function btech_parts.store_quantity(target, part) end

---@param target DbRef|Object
---@return BtechPartStack[] stores
function btech_parts.stores(target) end

---@param player DbRef|Object
---@return BtechPersonalCombatLoadout|nil loadout
function btech_player.loadout(player) end

---@param player DbRef|Object
---@return string|nil reference
function btech_player.mechwarrior_template(player) end

---@param player DbRef|Object
---@param loadout BtechPersonalCombatLoadout|nil
function btech_player.set_loadout(player, loadout) end

---@param player DbRef|Object
---@param reference string|nil
function btech_player.set_mechwarrior_template(player, reference) end

---@param player DbRef|Object
---@param preferences BtechUiPreferencesState|nil
function btech_player.set_ui_preferences(player, preferences) end

---@param player DbRef|Object
---@return BtechUiPreferencesState preferences
function btech_player.ui_preferences(player) end

---@param unit DbRef|Object
---@param repair BtechImmediateRepair
function btech_repair.apply(unit, repair) end

---@param unit DbRef|Object
---@return boolean fixable
function btech_repair.is_fixable(unit) end

---@param unit DbRef|Object
---@return boolean under_repair
function btech_repair.is_under_repair(unit) end

---@param unit DbRef|Object
---@return BtechRepairNeed[] needs
function btech_repair.needs(unit) end

---@param player DbRef|Object
---@return integer seconds
function btech_repair.technician_available_in(player) end

---@return integer seconds
function btech_system.event_lag() end

---@param zone DbRef|Object
---@return Object[] units
function btech_system.units_in_zone(zone) end

---@param reference string
---@param section? BtechSection
---@return BtechArmorStatus status
function btech_template.armor(reference, section) end

---@param reference string
---@return integer cost
function btech_template.base_cost(reference) end

---@param reference string
---@return BtechBattleValue value
function btech_template.battle_value(reference) end

---@param reference string
---@param section BtechSection
---@return BtechCriticalSlot[] slots
function btech_template.critical_slots(reference, section) end

---@param reference string
---@return BtechEngine engine
function btech_template.engine(reference) end

---@param reference string
---@return boolean exists
function btech_template.exists(reference) end

---@param reference string
---@return BtechPartStack[] parts
function btech_template.installed_parts(reference) end

---@param reference string
---@return BtechPartStack[] parts
function btech_template.payload(reference) end

---@param reference string
---@param player DbRef|Object
---@param section BtechSection
function btech_template.show_critical_status(reference, player, section) end

---@param reference string
---@param player DbRef|Object
function btech_template.show_status(reference, player) end

---@param reference string
---@param player DbRef|Object
function btech_template.show_weapon_specs(reference, player) end

---@param reference string
---@return BtechTechnology[] technologies
function btech_template.technologies(reference) end

---@param reference string
---@param section? BtechSection
---@return BtechMountedWeapon[] weapons
function btech_template.weapons(reference, section) end

---@param unit DbRef|Object
---@param technology BtechTechnologyCode
function btech_unit.add_technology(unit, technology) end

---@param unit DbRef|Object
---@param request table
function btech_unit.apply_damage(unit, request) end

---@param unit DbRef|Object
---@param section? BtechSection
---@return BtechArmorStatus status
function btech_unit.armor(unit, section) end

---@param unit DbRef|Object
---@return Object|nil pilot
function btech_unit.assigned_pilot(unit) end

---@param unit DbRef|Object
---@return BtechBattleValue value
function btech_unit.battle_value(unit) end

---@param unit DbRef|Object
---@param group BtechTechnologyGroup
function btech_unit.clear_technologies(unit, group) end

---@param unit DbRef|Object
---@param request BtechAmmunitionConfiguration
function btech_unit.configure_ammunition(unit, request) end

---@param unit DbRef|Object
---@param section BtechSection
---@return BtechCriticalSlot[] slots
function btech_unit.critical_slots(unit, section) end

---@param unit DbRef|Object
---@return string|nil name
function btech_unit.display_name(unit) end

---@param unit DbRef|Object
---@return number movement_points
function btech_unit.effective_max_speed(unit) end

---@param unit DbRef|Object
---@return number kilometers_per_hour
function btech_unit.effective_max_speed_kph(unit) end

---@param unit DbRef|Object
---@return BtechEngine engine
function btech_unit.engine(unit) end

---@param unit DbRef|Object
---@param request BtechSpecialInstall
function btech_unit.install_special(unit, request) end

---@param unit DbRef|Object
---@param request BtechWeaponInstall
function btech_unit.install_weapon(unit, request) end

---@param unit DbRef|Object
---@return BtechPartStack[] parts
function btech_unit.installed_parts(unit) end

---@param unit DbRef|Object
---@param reference string
function btech_unit.load_template(unit, reference) end

---@param unit DbRef|Object
---@return string|nil markings
function btech_unit.markings(unit) end

---@param unit DbRef|Object
---@return BtechPartStack[] parts
function btech_unit.payload(unit) end

---@param unit DbRef|Object
---@param options table
---@return boolean succeeded
function btech_unit.piloting_check(unit, options) end

---@param unit DbRef|Object
---@return string|nil id
function btech_unit.preferred_id(unit) end

---@param unit DbRef|Object
---@return BtechRadioChannel[] channels
function btech_unit.radio_channels(unit) end

---@param unit DbRef|Object
---@param technology BtechTechnologyCode
function btech_unit.remove_technology(unit, technology) end

---@param unit DbRef|Object
function btech_unit.reset_critical_slots(unit) end

---@param unit DbRef|Object
---@param section BtechSection
---@param slot integer
function btech_unit.restock_ammunition(unit, section, slot) end

---@param unit DbRef|Object
function btech_unit.restore(unit) end

---@param unit DbRef|Object
---@param reference string
function btech_unit.save_template(unit, reference) end

---@param unit DbRef|Object
---@param section BtechSection
---@return "operational"|"destroyed"|"flooded" condition
function btech_unit.section_condition(unit, section) end

---@param unit DbRef|Object
---@param section BtechSection
---@param patch table
function btech_unit.set_armor(unit, section, patch) end

---@param unit DbRef|Object
---@param pilot DbRef|Object|nil
function btech_unit.set_assigned_pilot(unit, pilot) end

---@param unit DbRef|Object
---@param space integer
---@param maximum_tons integer
function btech_unit.set_cargo_capacity(unit, space, maximum_tons) end

---@param unit DbRef|Object
---@param name string|nil
function btech_unit.set_display_name(unit, name) end

---@param unit DbRef|Object
---@param count integer
function btech_unit.set_heat_sinks(unit, count) end

---@param unit DbRef|Object
---@param movement_points number
function btech_unit.set_jump_speed(unit, movement_points) end

---@param unit DbRef|Object
---@param range integer
function btech_unit.set_long_range_sensor_range(unit, range) end

---@param unit DbRef|Object
---@param markings string|nil
function btech_unit.set_markings(unit, markings) end

---@param unit DbRef|Object
---@param movement_points number
function btech_unit.set_max_speed(unit, movement_points) end

---@param unit DbRef|Object
---@param movement_type BtechMovementType
function btech_unit.set_movement_type(unit, movement_type) end

---@param unit DbRef|Object
---@param id string|nil
function btech_unit.set_preferred_id(unit, id) end

---@param unit DbRef|Object
---@param quality integer
function btech_unit.set_radio_quality(unit, quality) end

---@param unit DbRef|Object
---@param range integer
function btech_unit.set_radio_range(unit, range) end

---@param unit DbRef|Object
---@param range integer
function btech_unit.set_scan_range(unit, range) end

---@param unit DbRef|Object
---@param range integer
function btech_unit.set_tactical_range(unit, range) end

---@param unit DbRef|Object
---@param tons integer
function btech_unit.set_tonnage(unit, tons) end

---@param unit DbRef|Object
---@param unit_type BtechUnitType
function btech_unit.set_unit_type(unit, unit_type) end

---@param unit DbRef|Object
---@param weapon_number integer
---@param modes BtechWeaponModes
function btech_unit.set_weapon_modes(unit, weapon_number, modes) end

---@param unit DbRef|Object
---@return BtechTechnology[] technologies
function btech_unit.technologies(unit) end

---@param unit DbRef|Object
---@param tic integer
---@return BtechMountedWeapon[] weapons
function btech_unit.tic_weapons(unit, tic) end

---@param unit DbRef|Object
---@param section? BtechSection
---@return BtechMountedWeapon[] weapons
function btech_unit.weapons(unit, section) end

btech.autopilot = btech_autopilot
btech.character = btech_character
btech.map = btech_map
btech.parts = btech_parts
btech.player = btech_player
btech.repair = btech_repair
btech.system = btech_system
btech.template = btech_template
btech.unit = btech_unit

return btech
