/* configuration.c - Configuration parsing and defaults */

#include <stddef.h>
#include <stdint.h>

#include "mux/commands/command.h"
#include "mux/objects/flags.h" // IWYU pragma: keep
#include "mux/server/configuration.h"
#include "mux/server/configuration_context.h" // IWYU pragma: keep
#include "mux/server/configuration_internal.h"
#include "mux/server/platform.h"
#include "mux/server/server_config.h"
#include "mux/server/server_registries.h"
#include "mux/support/hash_table.h"

typedef int (*ConfigurationIntInterpreter)(int *value, char *text, long extra,
                                           DbRef player, char *command,
                                           ConfigurationContext *context);
typedef int (*ConfigurationListInterpreter)(long **value, char *text,
                                            long extra, DbRef player,
                                            char *command,
                                            ConfigurationContext *context);

static int configuration_call_int(ConfigurationIntInterpreter interpreter,
                                  void *value, char *text, long extra,
                                  DbRef player, char *command,
                                  ConfigurationContext *context) {
  return interpreter(value, text, extra, player, command, context);
}

static int configuration_call_list(ConfigurationListInterpreter interpreter,
                                   void *value, char *text, long extra,
                                   DbRef player, char *command,
                                   ConfigurationContext *context) {
  return interpreter(value, text, extra, player, command, context);
}

static int configuration_call_direct(ConfigurationInterpreter interpreter,
                                     void *value, char *text, long extra,
                                     DbRef player, char *command,
                                     ConfigurationContext *context) {
  return interpreter(value, text, extra, player, command, context);
}

#define DEFINE_CONFIGURATION_ADAPTER(function)                                 \
  static int function##_configuration_adapter(                                 \
      void *value, char *text, long extra, DbRef player, char *command,        \
      ConfigurationContext *context) {                                         \
    return _Generic((function),                                                \
        ConfigurationIntInterpreter: configuration_call_int,                   \
        ConfigurationListInterpreter: configuration_call_list,                 \
        ConfigurationInterpreter: configuration_call_direct)(                  \
        function, value, text, extra, player, command, context);               \
  }

#define CONFIG_LOC(member)                                                     \
  ((int *)(uintptr_t)(offsetof(ServerConfiguration, member) + 1))
#define COMMAND_LOC(member)                                                    \
  ((int *)(uintptr_t)(sizeof(ServerConfiguration) +                            \
                      offsetof(CommandRegistry, member) + 1))
#define ACCESS_LOC(member)                                                     \
  ((int *)(uintptr_t)(sizeof(ServerConfiguration) + sizeof(CommandRegistry) +  \
                      sizeof(WorldIndexes) +                                   \
                      offsetof(AccessControlStore, member) + 1))

DEFINE_CONFIGURATION_ADAPTER(cf_access)
DEFINE_CONFIGURATION_ADAPTER(cf_badname)
DEFINE_CONFIGURATION_ADAPTER(cf_bool)
DEFINE_CONFIGURATION_ADAPTER(cf_bool_bit)
DEFINE_CONFIGURATION_ADAPTER(cf_cf_access)
DEFINE_CONFIGURATION_ADAPTER(cf_cmd_alias)
DEFINE_CONFIGURATION_ADAPTER(cf_flagalias)
DEFINE_CONFIGURATION_ADAPTER(cf_int)
DEFINE_CONFIGURATION_ADAPTER(cf_ntab_access)
DEFINE_CONFIGURATION_ADAPTER(cf_named_color)
DEFINE_CONFIGURATION_ADAPTER(cf_osc8_preset)
DEFINE_CONFIGURATION_ADAPTER(cf_set_flags)
DEFINE_CONFIGURATION_ADAPTER(cf_site)
DEFINE_CONFIGURATION_ADAPTER(cf_string)
DEFINE_CONFIGURATION_ADAPTER(configuration_modify_bits)

CONF conftable[] = {
    {"access", cf_access_configuration_adapter, CA_GOD, nullptr,
     (long)access_nametab},
    {"alias", cf_cmd_alias_configuration_adapter, CA_GOD, COMMAND_LOC(commands),
     0},
    {"bad_name", cf_badname_configuration_adapter, CA_GOD, nullptr, 0},
    {"badsite_file", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(site_file), 32},
    {"named_color", cf_named_color_configuration_adapter, CA_DISABLED, nullptr,
     0},
    {"osc8_preset", cf_osc8_preset_configuration_adapter, CA_DISABLED, nullptr,
     0},
    {"btech_explode_reactor", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_explode_reactor), 0},
    {"btech_explode_time", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_explode_time), 0},
    {"btech_explode_ammo", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_explode_ammo), 0},
    {"btech_explode_stop", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_explode_stop), 0},
    {"btech_parts", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_parts), 0},
    {"btech_ic", cf_int_configuration_adapter, CA_GOD, CONFIG_LOC(btech_ic), 0},
    {"btech_afterlife_dbref", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(afterlife_dbref), 0},
    {"btech_vcrit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_vcrit), 0},
    {"btech_dynspeed", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_dynspeed), 0},
    {"btech_slowdown", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_slowdown), 0},
    {"btech_fasaturn", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_fasaturn), 0},
    {"btech_fasacrit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_fasacrit), 0},
    {"btech_fasaadvvtolcrit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_fasaadvvtolcrit), 0},
    {"btech_fasaadvvhlcrit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_fasaadvvhlcrit), 0},
    {"btech_fasaadvvhlfire", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_fasaadvvhlfire), 0},
    {"btech_divrotordamage", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_divrotordamage), 0},
    {"btech_moddamagewithrange", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_moddamagewithrange), 0},
    {"btech_moddamagewithwoods", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_moddamagewithwoods), 0},
    {"btech_hotloadaddshalfbthmod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_hotloadaddshalfbthmod), 0},
    {"btech_nofusionvtolfuel", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_nofusionvtolfuel), 0},
    {"btech_tankfriendly", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_tankfriendly), 0},
    {"btech_newcharge", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_newcharge), 0},
    {"btech_tl3_charge", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_tl3_charge), 0},
    {"btech_newterrain", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_newterrain), 0},
    {"btech_xploss", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xploss), 0},
    {"btech_critlevel", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_critlevel), 0},
    {"btech_tankshield", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_tankshield), 0},
    {"btech_newstagger", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_newstagger), 0},
    {"btech_newstaggertons", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_newstaggertons), 0},
    {"btech_newstaggertime", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_newstaggertime), 0},
    {"allow_chanlurking", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(allow_chanlurking), 0},
    {"btech_skidcliff", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_skidcliff), 0},
    {"btech_xp_bthmod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_bthmod), 0},
    {"btech_xp_missilemod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_missilemod), 0},
    {"btech_xp_ammomod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_ammomod), 0},
    {"btech_defaultweapdam", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_defaultweapdam), 0},
    {"btech_xp_modifier", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_modifier), 0},
    {"btech_defaultweapbv", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_defaultweapbv), 0},
    {"btech_xp_usePilotBVMod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_usePilotBVMod), 0},
    {"btech_oldxpsystem", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_oldxpsystem), 0},
    {"btech_xp_vrtmod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xp_vrtmod), 0},
    {"btech_extendedmovemod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_extendedmovemod), 0},
    {"btech_stacking", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_stacking), 0},
    {"btech_stackdamage", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_stackdamage), 0},
    {"btech_mw_losmap", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_mw_losmap), 0},
    {"btech_exile_stun_code", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_exile_stun_code), 0},
    {"btech_roll_on_backwalk", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_roll_on_backwalk), 0},
    {"btech_usedmechstore", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_usedmechstore), 0},
    {"btech_ooc_comsys", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_ooc_comsys), 0},
    {"btech_idf_requires_spotter", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_idf_requires_spotter), 0},
    {"btech_perunit_xpmod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_perunit_xpmod), 0},
    {"btech_tsm_tow_bonus", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_tsm_tow_bonus), 0},
    {"btech_heatcutoff", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_heatcutoff), 0},
    {"btech_cost_debug", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_cost_debug), 0},
    {"btech_noisy_xpgain", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_noisy_xpgain), 0},
    {"btech_xpgain_cap", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xpgain_cap), 0},
    {"btech_transported_unit_death", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_transported_unit_death), 0},
    {"btech_mwpickup_action", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_mwpickup_action), 0},
    {"btech_standcareful", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_standcareful), 0},
    {"btech_maxtechtime", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_maxtechtime), 0},
    {"btech_sprint_bth", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_sprint_bth), 0},
    {"btech_tsm_sprint_bonus", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_tsm_sprint_bonus), 0},
    {"btech_vtol_ice_causes_fire", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_vtol_ice_causes_fire), 0},
    {"btech_glancing_blows", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_glancing_blows), 0},
    {"btech_inferno_penalty", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_inferno_penalty), 0},
    {"btech_blzmapmode", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_blzmapmode), 0},
    {"btech_extended_piloting", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_extended_piloting), 0},
    {"btech_extended_gunnery", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_extended_gunnery), 0},
    {"btech_xploss_for_mw", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_xploss_for_mw), 0},
    {"btech_variable_techtime", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_variable_techtime), 0},
    {"btech_techtime_mod", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_techtime_mod), 0},
    {"btech_statengine_obj", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_statengine_obj), 0},
#ifdef BT_FREETECHTIME
    {"btech_freetechtime", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_freetechtime), 0},
#endif
#ifdef BT_COMPLEXREPAIRS
    {"btech_complexrepair", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_complexrepair), 0},
#endif
    {"btech_seismic_see_stopped", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_seismic_see_stopped), 0},
    {"btech_limitedrepairs", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_limitedrepairs), 0},
    {"btech_stackpole", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_stackpole), 0},
    {"btech_phys_use_pskill", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_phys_use_pskill), 0},
    {"btech_erange", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_erange), 0},
    {"btech_hit_arcs", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_hit_arcs), 0},
    {"btech_dig_only_fs", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_dig_only_fs), 0},
    {"btech_digbonus", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(btech_digbonus), 0},
    {"cache_depth", cf_int_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(cache_depth), 0},
    {"cache_names", cf_bool_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(cache_names), 0},
    {"cache_trim", cf_bool_configuration_adapter, CA_GOD,
     CONFIG_LOC(cache_trim), 0},
    {"cache_width", cf_int_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(cache_width), 0},
    {"check_interval", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(check_interval), 0},
    {"check_offset", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(check_offset), 0},
    {"command_quota_increment", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_quota_increment), 0},
    {"command_quota_max", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_quota_max), 0},
    {"config_access", cf_cf_access_configuration_adapter, CA_GOD, nullptr,
     (long)access_nametab},
    {"conn_timeout", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(conn_timeout), 0},
    {"connect_dir", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(conn_dir), 32},
    {"connect_file", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(conn_file), 32},
    {"default_home", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(default_home), 0},
    {"down_file", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(down_file), 32},
    {"down_message", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(down_msg), 4096},
    {"dump_interval", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.dump_interval), 0},
    {"dump_message", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.dump_msg), 128},
    {"postdump_message", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.postdump_msg), 128},
    {"dump_offset", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(dump_offset), 0},
    {"default_exit_flags", cf_set_flags_configuration_adapter, CA_GOD,
     (int *)CONFIG_LOC(default_exit_flags), 0},
    {"flag_alias", cf_flagalias_configuration_adapter, CA_GOD, nullptr, 0},
    {"forbid_site", cf_site_configuration_adapter, CA_GOD,
     ACCESS_LOC(access_sites), H_FORBIDDEN},
    {"fork_dump", cf_bool_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.fork_dump), 0},
    {"full_file", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(full_file), 32},
    {"full_message", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(full_msg), 4096},
    {"game_database", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(database.gamedb),
     sizeof(((ServerConfiguration *)nullptr)->database.gamedb)},
    {"good_name", cf_badname_configuration_adapter, CA_GOD, nullptr, 1},
    {"help_directory", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(help_dir), sizeof(((ServerConfiguration *)nullptr)->help_dir)},
    {"idle_interval", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(idle_interval), 0},
    {"idle_timeout", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(idle_timeout), 0},
    {"initial_size", cf_int_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(init_size), 0},
    {"list_access", cf_ntab_access_configuration_adapter, CA_GOD,
     (int *)list_names, (long)access_nametab},
    {"lua_directory", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(lua.directory),
     sizeof(((ServerConfiguration *)nullptr)->lua.directory)},
    {"lua_memory_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(lua.memory_limit), 0},
    {"lua_state_value_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(lua.state_value_limit), 0},
    {"lua_state_entry_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(lua.state_entry_limit), 0},
    {"lua_state_object_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(lua.state_object_limit), 0},
    {"accounting", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_ACCOUNTING},
    {"all_commands", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_ALLCOMMANDS},
    {"suspect_commands", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_SUSPECTCMDS},
    {"bad_commands", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_BADCOMMANDS},
    {"buffer_alloc", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_ALLOCATE},
    {"bugs", cf_bool_bit_configuration_adapter, CA_GOD, CONFIG_LOC(log_options),
     LOG_BUGS},
    {"checkpoints", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_DBSAVES},
    {"config_changes", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_CONFIGMODS},
    {"create", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_PCREATES},
    {"logins", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_LOGIN},
    {"network", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_NET},
    {"problems", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_PROBLEMS},
    {"security", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_SECURITY},
    {"shouts", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_SHOUTS},
    {"startup", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_STARTUP},
    {"wizard", cf_bool_bit_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_options), LOG_WIZARD},
    {"log_options", configuration_modify_bits_configuration_adapter, CA_GOD,
     CONFIG_LOC(log_info), (long)logdata_nametab},
    {"map_database", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.map_db),
     sizeof(((ServerConfiguration *)nullptr)->database.map_db)},
    {"default_thing_lua_parent", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(default_thing_lua_parent),
     sizeof(((ServerConfiguration *)nullptr)->default_thing_lua_parent)},
    {"default_room_lua_parent", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(default_room_lua_parent),
     sizeof(((ServerConfiguration *)nullptr)->default_room_lua_parent)},
    {"default_exit_lua_parent", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(default_exit_lua_parent),
     sizeof(((ServerConfiguration *)nullptr)->default_exit_lua_parent)},
    {"default_player_lua_parent", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(default_player_lua_parent),
     sizeof(((ServerConfiguration *)nullptr)->default_player_lua_parent)},
    {"max_players", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(max_players), 0},
    {"mech_database", cf_string_configuration_adapter, CA_GOD,
     CONFIG_LOC(database.mech_db),
     sizeof(((ServerConfiguration *)nullptr)->database.mech_db)},
    {"mud_name", cf_string_configuration_adapter, CA_GOD, CONFIG_LOC(mud_name),
     32},
    {"notify_recursion_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(ntfy_nest_lim), 0},
    {"output_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(output_limit), 0},
    {"password_hash_memlimit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(password_hash_memlimit), 0},
    {"password_hash_opslimit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(password_hash_opslimit), 0},
    {"permit_site", cf_site_configuration_adapter, CA_GOD,
     ACCESS_LOC(access_sites), 0},
    {"default_player_flags", cf_set_flags_configuration_adapter, CA_GOD,
     (int *)CONFIG_LOC(default_player_flags), 0},
    {"player_password_length_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(player_password_length_limit), 0},
    {"player_name_spaces", cf_bool_configuration_adapter, CA_GOD,
     CONFIG_LOC(name_spaces), 0},
    {"command_queue_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_queue_limit), 0},
    {"player_starting_home", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(start_home), 0},
    {"player_starting_room", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(start_room), 0},
    {"public_channel", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(public_channel), 32},
    {"port", cf_int_configuration_adapter, CA_DISABLED, CONFIG_LOC(port), 0},
    {"command_queue_active_chunk", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_queue_active_chunk), 0},
    {"command_queue_idle_chunk", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_queue_idle_chunk), 0},
    {"quit_file", cf_string_configuration_adapter, CA_DISABLED,
     CONFIG_LOC(quit_file), 32},
    {"retry_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(retry_limit), 0},
    {"login_attempt_burst", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(login_attempt_burst), 0},
    {"login_attempt_refill", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(login_attempt_refill), 0},
    {"login_hash_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(login_hash_limit), 0},
    {"default_room_flags", cf_set_flags_configuration_adapter, CA_GOD,
     (int *)CONFIG_LOC(default_room_flags), 0},
    {"space_compress", cf_bool_configuration_adapter, CA_GOD,
     CONFIG_LOC(space_compress), 0},
    {"stack_limit", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(stack_limit), 0},
    {"suspect_site", cf_site_configuration_adapter, CA_GOD,
     ACCESS_LOC(suspect_sites), H_SUSPECT},
    {"default_thing_flags", cf_set_flags_configuration_adapter, CA_GOD,
     (int *)CONFIG_LOC(default_thing_flags), 0},
    {"command_quota_interval", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(command_quota_interval), 0},
    {"trust_site", cf_site_configuration_adapter, CA_GOD,
     ACCESS_LOC(suspect_sites), 0},
    {"player_zone", cf_int_configuration_adapter, CA_GOD,
     CONFIG_LOC(player_zone), 0},
    {nullptr, nullptr, 0, nullptr, 0}};

/*
 * ---------------------------------------------------------------------------
 * * configuration_set: Set config parameter.
 */
