---@meta _

---Generated by `lua-type-generator` from LuaLS contracts in native C.
---Do not edit; run `just update-lua-types`.

---@alias BtechLineOfSight "none"|"blocked"|"clear"

---@alias BtechMapEntrance BtechMapOffsetEntrance|BtechMapExactEntrance

---@alias BtechPartRef BtechPart|integer|string

---@alias BtechBuildingContactMode "follow_brief"|"include"|"exclude"

---@alias BtechRepairOperation "reattach"|"repair_part"|"repair_weapon_temporary"|"repair_enhancement"|"repair_focus"|"repair_crystal"|"repair_barrel"|"repair_ammo_feed"|"repair_ranging"|"repair_ammo_mount"|"replace_weapon"|"reload"|"repair_armor"|"repair_rear_armor"|"repair_internal"|"detach"|"scrap_part"|"scrap_weapon"|"unload"|"reseal"|"replace_suit"

---@alias BtechTerrain "grassland"|"road"|"light_forest"|"heavy_forest"|"water"|"ice"|"bridge"|"high_water"|"rough"|"mountains"|"fire"|"smoke"|"snow"|"building"|"wall"

---@alias ArmorStatusField 0|1|2 Armor field: current armor, internal structure, or rear armor.

---@alias CriticalSlotField "NAME"|"STATUS"|"DATA"|"MAXAMMO"|"AMMOTYPE"|"MODE"|"HALFTON" Canonical critical-slot field; native matching is ASCII-case-insensitive.

---@class BtechCargoTransferPoint
---@field x integer
---@field y integer
---@field reveal_hint boolean
---@class BtechMapOffsetEntrance
---@field mode "offset"
---@field offset integer
---@class BtechMapExactEntrance
---@field mode "exact"
---@field x integer
---@field y integer
---@class BtechMapEntrances
---@field north? BtechMapEntrance
---@field east? BtechMapEntrance
---@field south? BtechMapEntrance
---@field west? BtechMapEntrance
---@class BtechMapLink
---@field parent DbRef|Object
---@field x integer
---@field y integer
---@field entrances? BtechMapEntrances

---@class BtechPersonalCombatArmor
---@field head integer
---@field torso integer
---@field hands integer
---@field feet integer

---@class BtechPersonalCombatEquipment
---@field weapon BtechPart
---@field ammunition? integer

---@class BtechPersonalCombatLoadout
---@field armor BtechPersonalCombatArmor
---@field right? BtechPersonalCombatEquipment
---@field left? BtechPersonalCombatEquipment

---@class BtechUiPreferencesState
---@field tactical_height integer
---@field tactical_width integer
---@field lrs_height integer
---@field include_dead boolean
---@field include_shutdown boolean
---@field include_enemies boolean
---@field include_allies boolean
---@field include_target boolean
---@field buildings BtechBuildingContactMode
---@field configured boolean

---@class BtechCharacterValueDefinition
---@field code integer
---@field name string
---@field kind string
---@field default_experience_threshold integer
---@class BtechCharacterValue
---@field definition BtechCharacterValueDefinition
---@field amount integer
---@field target? integer
---@field experience? integer
---@field experience_to_next_level? integer
---@class BtechWeaponStats
---@field kind string
---@field heat integer
---@field damage integer
---@field minimum_range integer
---@field short_range integer
---@field medium_range integer
---@field long_range integer
---@field critical_slots integer
---@field ammunition_per_ton integer
---@field recycle_time integer
---@field battle_value integer
---@class BtechPart
---@field id integer
---@field brand integer
---@field packed_id integer
---@field short_name string
---@field long_name string
---@field very_long_name string
---@field category string
---@field weight_tons number
---@field cost integer
---@field weapon? BtechWeaponStats
---@class BtechPartStack
---@field part BtechPart
---@field quantity integer
---@class BtechValuePair
---@field current integer
---@field original integer
---@class BtechArmorStatus
---@field section? string
---@field armor BtechValuePair
---@field internal BtechValuePair
---@field rear_armor BtechValuePair
---@class BtechAmmunitionStatus
---@field rounds integer
---@field capacity integer
---@class BtechCriticalSlot
---@field section string
---@field slot integer
---@field kind string
---@field part? BtechPart
---@field operational boolean
---@field temporary_failure boolean
---@field auxiliary_data integer
---@field ammunition? BtechAmmunitionStatus
---@field fire_modes string[]
---@field ammunition_modes string[]
---@class BtechMountedWeapon
---@field number integer
---@field section string
---@field first_slot integer
---@field part BtechPart
---@field slot_count integer
---@field recycle integer
---@field recycle_time integer
---@field operational boolean
---@class BtechEngine
---@field rating integer
---@field suspension_factor integer
---@class BtechRadioChannel
---@field channel integer
---@field frequency integer
---@field title string
---@field modes string[]
---@class BtechBattleValue
---@field rules "bv2"|"legacy"
---@field total number
---@field offensive? number
---@field defensive? number
---@field gunnery? integer
---@field piloting? integer
---@class BtechBattleValueOptions
---@field rules? "bv2"|"legacy"
---@field gunnery? integer
---@field piloting? integer
---@class BtechTechnology
---@field code string
---@field name string
---@field group string
---@field source "configured"|"inferred"
---@class BtechRepairNeed
---@field operation BtechRepairOperation
---@field section string
---@field slot? integer
---@field amount? integer
---@field in_progress boolean
---@class BtechHex
---@field x integer
---@field y integer
---@class BtechPosition: BtechHex
---@field z? integer
---@class BtechPartCategory
---@field code string
---@field name string
---@class BtechBlastZone
---@field x integer
---@field y integer
---@field radius integer
---@class BtechMapEmitOptions
---@field audience? "all"|"range"|"line_of_sight"
---@field origin? BtechPosition
---@field range? number

---@class BtechErrorPackage
---@field codes BtechErrorCodes Checked native BattleTech code tree.

---Checked native BattleTech error-code tree.
---@class BtechPartNotFoundErrorCode: ErrorCode
---@field code "btech.part.not_found"
---@class BtechPartAmbiguousErrorCode: ErrorCode
---@field code "btech.part.ambiguous"
---@class BtechPartWrongKindErrorCode: ErrorCode
---@field code "btech.part.wrong_kind"
---@class BtechPartErrorCodes: ErrorCode
---@field not_found BtechPartNotFoundErrorCode `btech.part.not_found`.
---@field ambiguous BtechPartAmbiguousErrorCode `btech.part.ambiguous`.
---@field wrong_kind BtechPartWrongKindErrorCode `btech.part.wrong_kind`.
---@class BtechTemplateNotFoundErrorCode: ErrorCode
---@field code "btech.template.not_found"
---@class BtechTemplateInvalidErrorCode: ErrorCode
---@field code "btech.template.invalid"
---@class BtechTemplateErrorCodes: ErrorCode
---@field not_found BtechTemplateNotFoundErrorCode `btech.template.not_found`.
---@field invalid BtechTemplateInvalidErrorCode `btech.template.invalid`.
---@class BtechOperationFailedErrorCode: ErrorCode
---@field code "btech.operation.failed"
---@class BtechOperationErrorCodes: ErrorCode
---@field failed BtechOperationFailedErrorCode `btech.operation.failed`.
---@class BtechErrorCodes: ErrorCode
---@field part BtechPartErrorCodes Part resolution errors.
---@field template BtechTemplateErrorCodes Template resolution errors.
---@field operation BtechOperationErrorCodes Operational failures.

---The native BattleTech host API. All functions are unavailable during `@lua/check`.
---@class BtechPackage
---@field character BtechCharacterPackage
---@field map BtechMapPackage
---@field parts BtechPartsPackage
---@field player BtechPlayerPackage
---@field repair BtechRepairPackage
---@field system BtechSystemPackage
---@field template BtechTemplatePackage
---@field unit BtechUnitPackage
---@field error BtechErrorPackage
btech = {}

---@class BtechCharacterPackage
local btech_character = {}

---@class BtechMapPackage
local btech_map = {}

---@class BtechPartsPackage
local btech_parts = {}

---@class BtechPlayerPackage
local btech_player = {}

---@class BtechRepairPackage
local btech_repair = {}

---@class BtechSystemPackage
local btech_system = {}

---@class BtechTemplatePackage
local btech_template = {}

---@class BtechUnitPackage
local btech_unit = {}

---@param character Object
---@param skill string
---@param amount integer
function btech_character.add_skill_experience(character, skill, amount) end

---@param kind string
---@param character? Object
---@return BtechCharacterValueDefinition[] definitions
function btech_character.catalog(kind, character) end

---@param skill string
---@return integer threshold
function btech_character.experience_threshold(skill) end

---@param character Object
---@param skill string
---@param experience integer
function btech_character.set_skill_experience(character, skill, experience) end

---@param character Object
---@param skill string
---@param target integer
function btech_character.set_skill_target(character, skill, target) end

---@param character Object
---@param value string
---@param amount integer
function btech_character.set_value(character, value, amount) end

---@param character Object
---@param value string|integer
---@return BtechCharacterValue result
function btech_character.value(character, value) end

---@param map DbRef|Object
---@return BtechBlastZone[] zones
function btech_map.blast_zones(map) end

---@param map DbRef|Object
---@return BtechCargoTransferPoint|nil point
function btech_map.cargo_transfer_point(map) end

---@param map DbRef|Object
---@param hex BtechHex
---@return integer elevation
function btech_map.elevation(map, hex) end

---@param map DbRef|Object
---@param message string
---@param options? BtechMapEmitOptions
function btech_map.emit(map, message, options) end

---@param map DbRef|Object
---@param hex BtechHex
---@return boolean inside
function btech_map.in_blast_zone(map, hex) end

---@param observer DbRef|Object
---@param target DbRef|Object|BtechHex
---@return BtechLineOfSight state
function btech_map.line_of_sight(observer, target) end

---@param child DbRef|Object
---@return BtechMapLink|nil link
function btech_map.link(child) end

---@param map DbRef|Object
---@param name string
function btech_map.load(map, name) end

---@param unit DbRef|Object
---@param map DbRef|Object
---@param position BtechPosition
function btech_map.place_unit(unit, map, position) end

---@param map DbRef|Object
---@param from DbRef|Object|BtechPosition
---@param to DbRef|Object|BtechPosition
---@return number range
function btech_map.range(map, from, to) end

---@param map DbRef|Object
---@param point BtechCargoTransferPoint|nil
function btech_map.set_cargo_transfer_point(map, point) end

---@param child DbRef|Object
---@param link BtechMapLink|nil
function btech_map.set_link(child, link) end

---@param map DbRef|Object
---@param hex BtechHex
---@return BtechTerrain terrain
function btech_map.terrain(map, hex) end

---@param origin DbRef|Object
---@param id string
---@return Object|nil unit
function btech_map.unit_by_id(origin, id) end

---@param map DbRef|Object
---@param filter? table
---@return Object[] units
function btech_map.units(map, filter) end

---@param map DbRef|Object
function btech_map.update_links(map) end

---@param target DbRef|Object
---@param part BtechPartRef
---@param delta integer
function btech_parts.adjust_stores(target, part, delta) end

---@return BtechPartCategory[] categories
function btech_parts.categories() end

---@param category? string
---@return BtechPart[] parts
function btech_parts.list(category) end

---@param part BtechPartRef
---@return BtechPart|nil part
function btech_parts.resolve(part) end

---@param query string
---@return BtechPart[] parts
function btech_parts.search(query) end

---@param part BtechPartRef
---@param cost integer
function btech_parts.set_cost(part, cost) end

---@param target DbRef|Object
---@param part BtechPartRef
---@return integer quantity
function btech_parts.store_quantity(target, part) end

---@param target DbRef|Object
---@return BtechPartStack[] stores
function btech_parts.stores(target) end

---@param player DbRef|Object
---@return BtechPersonalCombatLoadout|nil loadout
function btech_player.loadout(player) end

---@param player DbRef|Object
---@return string|nil reference
function btech_player.mechwarrior_template(player) end

---@param player DbRef|Object
---@param loadout BtechPersonalCombatLoadout|nil
function btech_player.set_loadout(player, loadout) end

---@param player DbRef|Object
---@param reference string|nil
function btech_player.set_mechwarrior_template(player, reference) end

---@param player DbRef|Object
---@param preferences BtechUiPreferencesState|nil
function btech_player.set_ui_preferences(player, preferences) end

---@param player DbRef|Object
---@return BtechUiPreferencesState preferences
function btech_player.ui_preferences(player) end

---@param unit DbRef|Object
---@return boolean fixable
function btech_repair.is_fixable(unit) end

---@param unit DbRef|Object
---@return boolean under_repair
function btech_repair.is_under_repair(unit) end

---@param unit DbRef|Object
---@return BtechRepairNeed[] needs
function btech_repair.needs(unit) end

---@param player DbRef|Object
---@return integer seconds
function btech_repair.technician_available_in(player) end

---@return integer seconds
function btech_system.event_lag() end

---@param zone DbRef|Object
---@return Object[] units
function btech_system.units_in_zone(zone) end

---@param reference string
---@param section? string
---@return BtechArmorStatus status
function btech_template.armor(reference, section) end

---@param reference string
---@return integer cost
function btech_template.base_cost(reference) end

---@param reference string
---@param options? BtechBattleValueOptions
---@return BtechBattleValue value
function btech_template.battle_value(reference, options) end

---@param reference string
---@param section string
---@return BtechCriticalSlot[] slots
function btech_template.critical_slots(reference, section) end

---@param reference string
---@return BtechEngine engine
function btech_template.engine(reference) end

---@param reference string
---@return boolean exists
function btech_template.exists(reference) end

---@param reference string
---@return BtechPartStack[] parts
function btech_template.installed_parts(reference) end

---@param reference string
---@return BtechPartStack[] parts
function btech_template.payload(reference) end

---@param reference string
---@param player DbRef|Object
---@param section string
function btech_template.show_critical_status(reference, player, section) end

---@param reference string
---@param player DbRef|Object
function btech_template.show_status(reference, player) end

---@param reference string
---@param player DbRef|Object
function btech_template.show_weapon_specs(reference, player) end

---@param reference string
---@return BtechTechnology[] technologies
function btech_template.technologies(reference) end

---@param reference string
---@param section? string
---@return BtechMountedWeapon[] weapons
function btech_template.weapons(reference, section) end

---@param unit DbRef|Object
---@param request table
function btech_unit.apply_damage(unit, request) end

---@param unit DbRef|Object
---@param section? string
---@return BtechArmorStatus status
function btech_unit.armor(unit, section) end

---@param unit DbRef|Object
---@return Object|nil pilot
function btech_unit.assigned_pilot(unit) end

---@param unit DbRef|Object
---@param options? BtechBattleValueOptions
---@return BtechBattleValue value
function btech_unit.battle_value(unit, options) end

---@param unit DbRef|Object
---@param section string
---@return BtechCriticalSlot[] slots
function btech_unit.critical_slots(unit, section) end

---@param unit DbRef|Object
---@return string|nil name
function btech_unit.display_name(unit) end

---@param unit DbRef|Object
---@return number speed
function btech_unit.effective_max_speed(unit) end

---@param unit DbRef|Object
---@return BtechEngine engine
function btech_unit.engine(unit) end

---@param unit DbRef|Object
---@return BtechPartStack[] parts
function btech_unit.installed_parts(unit) end

---@param unit DbRef|Object
---@param reference string
function btech_unit.load_template(unit, reference) end

---@param unit DbRef|Object
---@return string|nil markings
function btech_unit.markings(unit) end

---@param unit DbRef|Object
---@return BtechPartStack[] parts
function btech_unit.payload(unit) end

---@param unit DbRef|Object
---@param options table
---@return boolean succeeded
function btech_unit.piloting_check(unit, options) end

---@param unit DbRef|Object
---@return string|nil id
function btech_unit.preferred_id(unit) end

---@param unit DbRef|Object
---@return BtechRadioChannel[] channels
function btech_unit.radio_channels(unit) end

---@param unit DbRef|Object
---@param section string
---@return "operational"|"destroyed"|"flooded" condition
function btech_unit.section_condition(unit, section) end

---@param unit DbRef|Object
---@param section string
---@param patch table
function btech_unit.set_armor(unit, section, patch) end

---@param unit DbRef|Object
---@param pilot DbRef|Object|nil
function btech_unit.set_assigned_pilot(unit, pilot) end

---@param unit DbRef|Object
---@param name string|nil
function btech_unit.set_display_name(unit, name) end

---@param unit DbRef|Object
---@param markings string|nil
function btech_unit.set_markings(unit, markings) end

---@param unit DbRef|Object
---@param speed number
function btech_unit.set_max_speed(unit, speed) end

---@param unit DbRef|Object
---@param id string|nil
function btech_unit.set_preferred_id(unit, id) end

---@param unit DbRef|Object
---@param tons integer
function btech_unit.set_tonnage(unit, tons) end

---@param unit DbRef|Object
---@return BtechTechnology[] technologies
function btech_unit.technologies(unit) end

---@param unit DbRef|Object
---@param tic integer
---@return BtechMountedWeapon[] weapons
function btech_unit.tic_weapons(unit, tic) end

---@param unit DbRef|Object
---@param section? string
---@return BtechMountedWeapon[] weapons
function btech_unit.weapons(unit, section) end

btech.character = btech_character
btech.map = btech_map
btech.parts = btech_parts
btech.player = btech_player
btech.repair = btech_repair
btech.system = btech_system
btech.template = btech_template
btech.unit = btech_unit

return btech
