---@meta _

---Generated by `lua-type-generator` from LuaLS contracts in native C.
---Do not edit; run `just update-lua-types`.

---@alias CharacterListKind "skills"|"advantages"|"attributes" Canonical character-value category; native matching is ASCII-case-insensitive.

---@alias CharacterRef integer|string Character dbref or legacy character reference.

---@alias CharacterValueMode 0|1|2|3|4 Legacy character-value lookup or mutation mode.

---@alias BtechListItem string|number Item returned by a legacy BattleTech list result.

---@alias BtechMapEntrance BtechMapOffsetEntrance|BtechMapExactEntrance

---@alias PartCategory "ammo"|"weapon"|"weapons"|"weap"|"bomb"|"bombs"|"special"|"specials"|"cargo"|"carg"|"part"|"parts" Canonical or legacy spelling; native matching is ASCII-case-insensitive.

---@alias PartNameSize "short"|"long"|"vlong" Canonical name length; native matching inspects only the first letter, case-insensitively.

---@alias PartType "WEAP"|"AMMO"|"BOMB"|"PART"|"CARG"|"OTHER" Broad category returned by [`btech.parts.type`](lua://btech.parts.type).

---@alias WeaponStat "VRT"|"TYPE"|"HEAT"|"DAMAGE"|"MIN"|"SR"|"MR"|"LR"|"CRIT"|"AMMO"|"WEIGHT"|"BV" Canonical weapon statistic; native matching is ASCII-case-insensitive.

---@alias BtechBuildingContactMode "follow_brief"|"include"|"exclude"

---@alias ArmorStatusField 0|1|2 Armor field: current armor, internal structure, or rear armor.

---@alias CriticalSlotField "NAME"|"STATUS"|"DATA"|"MAXAMMO"|"AMMOTYPE"|"MODE"|"HALFTON" Canonical critical-slot field; native matching is ASCII-case-insensitive.

---@class BtechCargoTransferPoint
---@field x integer
---@field y integer
---@field reveal_hint boolean

---@class BtechMapEntrances
---@field north? BtechMapEntrance
---@field east? BtechMapEntrance
---@field south? BtechMapEntrance
---@field west? BtechMapEntrance

---@class BtechMapExactEntrance
---@field mode "exact"
---@field x integer
---@field y integer

---@class BtechMapLink
---@field parent DbRef|Object
---@field x integer
---@field y integer
---@field entrances? BtechMapEntrances

---@class BtechMapOffsetEntrance
---@field mode "offset"
---@field offset integer

---@class BtechPersonalCombatArmor
---@field head integer
---@field torso integer
---@field hands integer
---@field feet integer

---@class BtechPersonalCombatEquipment
---@field weapon string
---@field ammunition? integer

---@class BtechPersonalCombatLoadout
---@field armor BtechPersonalCombatArmor
---@field right? BtechPersonalCombatEquipment
---@field left? BtechPersonalCombatEquipment

---@class BtechPlayerUiPreferences
---@field tactical_height integer
---@field tactical_width integer
---@field lrs_height integer
---@field include_dead boolean
---@field include_shutdown boolean
---@field include_enemies boolean
---@field include_allies boolean
---@field include_target boolean
---@field buildings BtechBuildingContactMode

---@class BtechErrorPackage
---@field codes BtechErrorCodes Checked native BattleTech code tree.

---Checked `btech.unavailable` error-code node.
---@class BtechUnavailableErrorCode: ErrorCode
---@field code "btech.unavailable"

---Checked `btech.failed` error-code node.
---@class BtechFailedErrorCode: ErrorCode
---@field code "btech.failed"

---Checked native BattleTech error-code tree.
---@class BtechErrorCodes: ErrorCode
---@field unavailable BtechUnavailableErrorCode `btech.unavailable`, raised during `@lua/check`.
---@field failed BtechFailedErrorCode `btech.failed`, raised for a BattleTech domain failure, such as a wrong object kind or a failed legacy handler.

---Character values, skills, experience, and piloting rolls.
---@class BtechCharacterPackage
local btech_character = {}

---Battle maps, geometry, line of sight, and map messaging.
---@class BtechMapPackage
local btech_map = {}

---The native BattleTech host API. All functions are unavailable during `@lua/check`.
---@class BtechPackage
---@field unit BtechUnitPackage Live units, templates, combat values, and status.
---@field map BtechMapPackage Maps, geometry, line of sight, and map messaging.
---@field player BtechPlayerPackage Player-owned BattleTech configuration.
---@field parts BtechPartsPackage Part catalogues, installed parts, stores, and costs.
---@field character BtechCharacterPackage Character values, skills, experience, and piloting rolls.
---@field repair BtechRepairPackage Damage and technician-status queries.
---@field system BtechSystemPackage Special-object fields and server-wide queries.
---@field error BtechErrorPackage BattleTech checked error codes.
btech = {}

---Part catalogues, installed parts, stores, and costs.
---@class BtechPartsPackage
local btech_parts = {}

---Player-owned BattleTech configuration.
---@class BtechPlayerPackage
local btech_player = {}

---Damage and technician-status queries.
---@class BtechRepairPackage
local btech_repair = {}

---Special-object fields and server-wide BattleTech queries.
---@class BtechSystemPackage
local btech_system = {}

---Live units, templates, combat values, and status.
---@class BtechUnitPackage
local btech_unit = {}

---Lists character-value names in a category, optionally filtered by learned values.
---@param kind CharacterListKind
---@param character CharacterRef Learned-value filter; explicit `nil` is rejected by the Lua bridge.
---@return BtechListItem[] values
---@overload fun(kind: CharacterListKind): BtechListItem[]
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_character.list(kind, character) end

---Sets a character value or adjusts skill experience.
---@param character CharacterRef
---@param value integer|string
---@param amount integer
---@param mode integer `0` sets value, `1` target, `3` XP; other nonzero modes add XP.
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_character.set_value(character, value, amount, mode) end

---Returns the configured experience threshold for a skill.
---@param skill string
---@return number threshold
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_character.threshold(skill) end

---Gets a character attribute, skill level, target, experience, or threshold.
---@param character CharacterRef
---@param value integer|string Character-value code or name.
---@param mode CharacterValueMode
---@return number result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_character.value(character, value, mode) end

---Lists blast-zone data as repeating x, y, and radius numbers.
---@param map integer
---@return number[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.blast_zones(map) end

---Returns a map's cargo-transfer point, or nil.
---@param map DbRef|Object
---@return BtechCargoTransferPoint|nil point
function btech_map.cargo_transfer_point(map) end

---Returns the elevation of a map hex.
---@param map integer
---@param x integer
---@param y integer
---@return number elevation
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.elevation(map, x, y) end

---Broadcasts a non-empty message to all or nearby units on a map.
---@param map integer
---@param message string
---@return true success
---@overload fun(map: integer, x: integer, y: integer, range: number, message: string): true
---@overload fun(map: integer, x: integer, y: integer, z: number, range: number, message: string): true
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.emit(map, message) end

---Broadcasts a non-empty message from one map hex.
---@param map integer
---@param x integer
---@param y integer
---@param message string
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.hex_emit(map, x, y, message) end

---Tests whether a map hex lies in a configured blast zone.
---@param map integer
---@param x integer
---@param y integer
---@return boolean inside
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.hex_in_blast_zone(map, x, y) end

---Tests a live unit's line of sight to a map hex.
---@param unit integer
---@param x integer
---@param y integer
---@return boolean visible
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.hex_line_of_sight(unit, x, y) end

---Resolves a two-character tactical ID on a unit's map.
---@param unit_or_map integer
---@param id string
---@return 0 value The numeric adapter currently converts the handler's leading-`#` dbref text to zero.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.id_to_dbref(unit_or_map, id) end

---Returns a child map's configured parent link, or nil.
---@param child DbRef|Object
---@return BtechMapLink|nil link
function btech_map.link(child) end

---Loads a map file and clears units and map objects from the target map.
---@param map integer
---@param name string
---@param clear boolean Ignored compatibility argument; explicit `nil` is rejected by the Lua bridge.
---@return 1 success Numeric one returned by the handler's `BTECH_SCRIPT_NUMBER` conversion.
---@overload fun(map: integer, name: string): 1
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.load(map, name, clear) end

---Calculates three-dimensional range between two units on a map.
---For the four-argument forms, an integer in the first overloaded position
---selects coordinate-first dispatch, so unit-first requires a non-integer
---textual reference. For the five-argument forms, dispatch treats a leading
---digit or `.` as numeric, making numeric-looking unit references ambiguous.
---@param map integer
---@param unit_a integer
---@param unit_b integer
---@return number range
---@overload fun(map: integer, unit: integer, x: integer, y: integer): number
---@overload fun(map: integer, x: integer, y: integer, unit: integer): number
---@overload fun(map: integer, unit: integer, x: integer, y: integer, z: integer): number
---@overload fun(map: integer, x: integer, y: integer, z: integer, unit: integer): number
---@overload fun(map: integer, x1: integer, y1: integer, x2: integer, y2: integer): number
---@overload fun(map: integer, x1: integer, y1: integer, z1: integer, x2: integer, y2: integer, z2: integer): number
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.range(map, unit_a, unit_b) end

---Sets a map's cargo-transfer point, or clears it with nil.
---@param map DbRef|Object
---@param point BtechCargoTransferPoint|nil
---@return true success
function btech_map.set_cargo_transfer_point(map, point) end

---Atomically sets a child map link, or clears it with nil.
---@param child DbRef|Object
---@param link BtechMapLink|nil
---@return true success
function btech_map.set_link(child, link) end

---Places a live unit on a map at specified coordinates.
---@param unit integer
---@param map integer
---@param x integer
---@param y integer
---@param z integer Explicit altitude; explicit `nil` is rejected by the Lua bridge.
---@return true success
---@overload fun(unit: integer, map: integer, x: integer, y: integer): true
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.set_xy(unit, map, x, y, z) end

---Returns the terrain code of a map hex.
---@param map integer
---@param x integer
---@param y integer
---@return string terrain
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.terrain(map, x, y) end

---Tests line of sight between two live units.
---@param unit integer
---@param target integer
---@return boolean visible
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.unit_line_of_sight(unit, target) end

---Lists unit dbrefs on a map.
---@param map integer
---@return integer[] units
---@overload fun(map: integer, x: integer, y: integer, range: number): integer[]
---@overload fun(map: integer, x: integer, y: integer, z: number, range: number): integer[]
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.units(map) end

---Recursively updates links associated with a map.
---@param map integer
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_map.update_links(map) end

---Adds a quantity of a part to an object's stores.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@param target integer Stores-bearing object dbref.
---@param part_name string Recognized part name.
---@param quantity integer Quantity to add, subject to the server cap.
---@return true success
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.add_stores(target, part_name, quantity) end

---Lists canonical part categories accepted by [`btech.parts.list`](lua://btech.parts.list).
---@return string[] categories
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.categories() end

---Returns the configured cost of a recognized part.
---@param part_name string
---@return number cost
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.cost(part_name) end

---Lists parts installed on a live unit.
---@param unit integer
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.installed(unit) end

---Lists parts installed in a unit template.
---@param reference string
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.installed_ref(reference) end

---Lists canonical long part names in a category or accepted alias.
---@param category PartCategory
---@return string[] parts
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.list(category) end

---Finds packed part IDs whose names match text.
---@param query string
---@return integer[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.match(query) end

---Returns a selected name for a packed part ID.
---The `size` argument is required. The legacy handler does not safely reject
---its omission and may abort instead of returning a checked error.
---@param part integer
---@param size PartNameSize
---@return string name
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.name(part, size) end

---Removes a quantity of a part from an object's stores.
---@param target integer
---@param part_name string
---@param quantity integer
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.remove_stores(target, part_name, quantity) end

---Sets the configured unsigned cost of a recognized part. The native parser currently accepts a leading sign, so negative inputs wrap into the unsigned range.
---@param part_name string
---@param cost integer
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.set_cost(part_name, cost) end

---Returns a quantity for one part, or lists stored parts when the part is omitted.
---In list form, spaces in long display names split one serialized stack into
---multiple items in the shared legacy list adapter.
---@param target integer
---@param part_name string
---@return number[] result One-element quantity array.
---@overload fun(target: integer): BtechListItem[]
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.stores(target, part_name) end

---Returns a quantity or lists stored parts using short names.
---@param target integer
---@param part_name string
---@return number[] result One-element quantity array.
---@overload fun(target: integer): BtechListItem[]
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.stores_short(target, part_name) end

---Returns the broad category of a recognized part.
---@param part_name string
---@return PartType category
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.type(part_name) end

---Returns a selected numeric weapon-catalog statistic as serialized text.
---@param weapon string
---@param stat WeaponStat
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.weapon_stat(weapon, stat) end

---Returns a recognized part's weight in tons.
---@param part_name string
---@return number tons
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_parts.weight(part_name) end

---Returns the configured personal-combat loadout, or nil.
---@param player DbRef|Object
---@return BtechPersonalCombatLoadout|nil loadout
function btech_player.loadout(player) end

---Returns the configured MechWarrior template override, or nil.
---@param player DbRef|Object
---@return string|nil reference
function btech_player.mechwarrior_template(player) end

---Atomically sets a personal-combat loadout, or clears it with nil.
---@param player DbRef|Object
---@param loadout BtechPersonalCombatLoadout|nil
---@return true success
function btech_player.set_loadout(player, loadout) end

---Sets the MechWarrior template override, or clears it with nil.
---@param player DbRef|Object
---@param reference string|nil
---@return true success
function btech_player.set_mechwarrior_template(player, reference) end

---Atomically sets UI preferences, or restores defaults with nil.
---@param player DbRef|Object
---@param preferences BtechPlayerUiPreferences|nil
---@return true success
function btech_player.set_ui_preferences(player, preferences) end

---Returns effective UI preferences and whether they are explicitly configured.
---@param player DbRef|Object
---@return BtechPlayerUiPreferences preferences
---@return boolean configured
function btech_player.ui_preferences(player) end

---Returns the formatted repair-job description for a live unit.
---@param unit integer
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.damages(unit) end

---Returns the number of pending repair jobs on a live unit.
---@param unit integer
---@return number count
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.job_count(unit) end

---Lists parts needed to repair a live unit.
---@param unit integer
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.tech_list(unit) end

---Lists parts needed to repair a unit template.
---@param reference string
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.tech_list_ref(reference) end

---Returns formatted repair status for a live unit.
---@param unit integer
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.tech_status(unit) end

---Returns a player's remaining technician time in seconds.
---@param player integer
---@return number seconds Remaining technician time, or zero when the player has no pending technician time.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.tech_time(player) end

---Tests whether a live unit has an active repair event.
---@param unit integer
---@return boolean under_repair
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.under_repair(unit) end

---Tests whether a live unit can be repaired.
---@param unit integer
---@return boolean fixable
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_repair.unit_fixable(unit) end

---Tests whether a unit-template reference exists.
---@param reference string
---@return boolean exists
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_system.design_exists(reference) end

---Returns the current BattleTech event lag.
---@return number lag
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_system.lag() end

---Lists live unit dbrefs assigned to a zone. A trailing `-1` indicates that the legacy output was truncated.
---@param zone integer
---@return integer[] units Unit dbrefs, possibly followed by the `-1` truncation sentinel.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_system.zone_units(zone) end

---Returns serialized armor values for a live unit section, or aggregate totals for the exact lowercase selector `all`.
---@param unit integer
---@param section string Canonical section name or exact lowercase `all`; named-section matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.armor_status(unit, section) end

---Returns serialized armor values for a unit-template section, or aggregate totals for the exact lowercase selector `all`.
---@param reference string
---@param section string Canonical section name or exact lowercase `all`; named-section matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.armor_status_ref(reference, section) end

---Returns a unit's assigned pilot as an Object, or nil.
---@param unit DbRef|Object
---@return Object|nil pilot
function btech_unit.assigned_pilot(unit) end

---Calculates a live unit's battle value.
---@param unit integer
---@return number value
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.battle_value(unit) end

---Calculates a unit template's second-generation battle value.
---@param reference string
---@return number value
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.battle_value2_ref(reference) end

---Calculates a unit template's battle value.
---@param reference string
---@return number value
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.battle_value_ref(reference) end

---Describes one critical slot on a live unit.
---@param unit integer
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@param slot integer
---@param field CriticalSlotField Required field selector; native matching is ASCII-case-insensitive.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.crit_slot(unit, section, slot, field) end

---Describes one critical slot in a unit template.
---@param reference string
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@param slot integer
---@param field CriticalSlotField Required field selector; native matching is ASCII-case-insensitive.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.crit_slot_ref(reference, section, slot, field) end

---Returns serialized critical-slot status for one live-unit section.
---@param unit integer
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.crit_status(unit, section) end

---Returns serialized critical-slot status for one template section.
---@param reference string
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.crit_status_ref(reference, section) end

---Applies clustered damage and associated messages to a live unit.
---@param unit integer
---@param damage integer Total damage from 1 through 1000.
---@param cluster_size integer Damage per cluster, at least 1.
---@param direction integer Legacy attack-direction code.
---@param force_critical boolean|integer
---@param unit_message string
---@param los_message string
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.damage(unit, damage, cluster_size, direction, force_critical, unit_message, los_message) end

---Calculates a unit template's defensive battle-value component.
---@param reference string
---@return number value
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.defensive_battle_value_ref(reference) end

---Returns a registered unit's display-name override, or an empty string.
---@param unit integer
---@return string name
function btech_unit.display_name(unit) end

---Returns a live unit's engine rating.
---@param unit integer
---@return number rating
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.engine_rating(unit) end

---Returns a unit template's engine rating.
---@param reference string
---@return number rating
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.engine_rating_ref(reference) end

---Calculates a unit template's FASA base cost.
---@param reference string
---@return number cost
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.fasa_base_cost_ref(reference) end

---Lists configured radio channels for a live unit.
---The list adapter does not split the comma between serialized channel
---records, so adjacent records can be merged into one token.
---@param unit integer
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.frequencies(unit) end

---Loads a unit template into a live unit object.
---@param unit integer
---@param reference string
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.load(unit, reference) end

---Makes a piloting roll and causes a fall when it fails.
---@param unit integer
---@param roll_modifier integer
---@param damage_modifier integer
---@return boolean result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.make_pilot_roll(unit, roll_modifier, damage_modifier) end

---Returns a unit's markings, or nil.
---@param unit DbRef|Object
---@return string|nil markings
function btech_unit.markings(unit) end

---Calculates a unit template's offensive battle-value component.
---@param reference string
---@return number value
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.offensive_battle_value_ref(reference) end

---Returns the weapon and ammunition payload of a unit template.
---@param reference string
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.payload_ref(reference) end

---Returns a unit's preferred two-letter map identifier, or nil.
---@param unit DbRef|Object
---@return string|nil preferred_id
function btech_unit.preferred_id(unit) end

---Returns a live unit's effective maximum speed.
---@param unit integer
---@return number speed
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.real_max_speed(unit) end

---Returns serialized status for one live-unit section.
---@param unit integer
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.section_status(unit, section) end

---Sets one armor-status field on a live-unit section.
---@param unit integer
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@param field ArmorStatusField `0` changes current armor, `1` internal structure, and `2` rear armor.
---@param value integer New value from 0 through 255.
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.set_armor_status(unit, section, field, value) end

---Sets a unit's assigned pilot, or clears the assignment with nil.
---@param unit DbRef|Object
---@param pilot DbRef|Object|nil
---@return true success
function btech_unit.set_assigned_pilot(unit, pilot) end

---Sets a registered unit's display-name override; an empty name clears it.
---@param unit integer
---@param name string
---@return true success
function btech_unit.set_display_name(unit, name) end

---Sets a unit's markings, or clears them with nil.
---@param unit DbRef|Object
---@param markings string|nil
---@return true success
function btech_unit.set_markings(unit, markings) end

---Sets a live unit's maximum speed and corrects its current speed.
---@param unit integer
---@param speed number
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.set_max_speed(unit, speed) end

---Sets a unit's preferred map identifier, or clears it with nil.
---@param unit DbRef|Object
---@param preferred_id string|nil
---@return true success
function btech_unit.set_preferred_id(unit, preferred_id) end

---Sets a live unit's tonnage and original weight.
---@param unit integer
---@param tons integer
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.set_tons(unit, tons) end

---Writes a script-writable field on a live unit.
---@param unit integer
---@param name string Unit field name, matched ASCII-case-insensitively.
---@param value string|number
---@return true success
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.set_value(unit, name, value) end

---Requests a template's critical-status display for a player.
---@param reference string
---@param player integer
---@param section string Canonical section name; native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return "1" success Literal success text once template and recipient validation succeeds; it does not confirm display output.
---
---An invalid section or another renderer-level condition can produce no display and still return `"1"`.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable) during `@lua/check`, [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid) when too many arguments are supplied, or [`btech.error.codes.failed`](lua://btech.error.codes.failed) when template or recipient validation fails. Non-coercible scalar arguments raise an ordinary Lua type error.
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.show_crit_status_ref(reference, player, section) end

---Requests a unit template's status display for a player.
---@param reference string
---@param player integer
---@return "1" success Literal success text once template and recipient validation succeeds; it does not confirm display output.
---
---The legacy renderer's result is not reported, so the call can return `"1"` without displaying anything.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable) during `@lua/check`, [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid) when too many arguments are supplied, or [`btech.error.codes.failed`](lua://btech.error.codes.failed) when template or recipient validation fails. Non-coercible scalar arguments raise an ordinary Lua type error.
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.show_status_ref(reference, player) end

---Requests a unit template's weapon-specification display for a player.
---@param reference string
---@param player integer
---@return "1" success Literal success text once template and recipient validation succeeds; it does not confirm display output.
---
---A template with no reportable weapons can produce no display and still return `"1"`.
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable) during `@lua/check`, [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid) when too many arguments are supplied, or [`btech.error.codes.failed`](lua://btech.error.codes.failed) when template or recipient validation fails. Non-coercible scalar arguments raise an ordinary Lua type error.
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.show_weapon_specs_ref(reference, player) end

---Lists weapons assigned to a unit's zero-based target-interlock circuit.
---@param unit integer
---@param tic integer
---@return BtechListItem[] values
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.tic_weapons(unit, tic) end

---Reads a script-visible field from a live unit.
---@param unit integer
---@param name string Unit field name, matched ASCII-case-insensitively.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.value(unit, name) end

---Reads a script-visible field from a unit template.
---@param reference string
---@param name string Unit field name, matched ASCII-case-insensitively.
---@return string result
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.value_ref(reference, name) end

---Returns serialized weapon status for a live unit or optional section.
---@param unit integer
---@param section string Explicit section; `nil` is rejected. Native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---@overload fun(unit: integer): string
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.weapon_status(unit, section) end

---Returns serialized weapon status for a unit template or optional section.
---@param reference string
---@param section string Explicit section; `nil` is rejected. Native matching is case-insensitive and also uses class-dependent leading characters for legacy loose matches.
---@return string result
---@overload fun(reference: string): string
---
---Raises [`btech.error.codes.unavailable`](lua://btech.error.codes.unavailable), [`mux.error.codes.arg.invalid`](lua://mux.error.codes.arg.invalid), or [`btech.error.codes.failed`](lua://btech.error.codes.failed).
---@see btech.error.codes.unavailable
---@see mux.error.codes.arg.invalid
---@see btech.error.codes.failed
function btech_unit.weapon_status_ref(reference, section) end

return btech
