//! Legacy TOML names mapped to effective typed settings.
#[derive(Debug, Clone, Copy)]
/// Compatibility name, shape and validation bounds for one known leaf.
pub struct KeySpec {
    pub path: &'static str,
    pub legacy: &'static str,
    pub kind: &'static str,
    pub bounds: Option<(f64, f64)>,
}
/// Complete legacy mapping catalog followed by Rust-only operational settings.
pub const KEYS: &[KeySpec] = &[
    KeySpec {
        path: "database.game_database",
        legacy: "game_database",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "database.mech_database",
        legacy: "mech_database",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "database.map_database",
        legacy: "map_database",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "database.dump_interval",
        legacy: "dump_interval",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "database.fork_dump",
        legacy: "fork_dump",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "database.dump_message",
        legacy: "dump_message",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "database.postdump_message",
        legacy: "postdump_message",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "database.bootstrap.objects",
        legacy: "bootstrap_object",
        kind: "BTreeMap<BootstrapId, BootstrapObject>",
        bounds: None,
    },
    KeySpec {
        path: "lua.directory",
        legacy: "lua_directory",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "lua.memory_limit",
        legacy: "lua_memory_limit",
        kind: "usize",
        bounds: Some((1048576.0, 1073741824.0)),
    },
    KeySpec {
        path: "lua.error_reporting",
        legacy: "lua_error_reporting",
        kind: "ErrorReporting",
        bounds: None,
    },
    KeySpec {
        path: "lua.state_value_limit",
        legacy: "lua_state_value_limit",
        kind: "usize",
        bounds: Some((1.0, 10485760.0)),
    },
    KeySpec {
        path: "lua.state_entry_limit",
        legacy: "lua_state_entry_limit",
        kind: "usize",
        bounds: Some((1.0, 1000000.0)),
    },
    KeySpec {
        path: "lua.state_object_limit",
        legacy: "lua_state_object_limit",
        kind: "usize",
        bounds: Some((1.0, 1073741824.0)),
    },
    KeySpec {
        path: "server.port",
        legacy: "port",
        kind: "u16",
        bounds: Some((0.0, 65535.0)),
    },
    KeySpec {
        path: "server.mud_name",
        legacy: "mud_name",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "battletech.explode_reactor",
        legacy: "btech_explode_reactor",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.explode_time",
        legacy: "btech_explode_time",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.explode_ammo",
        legacy: "btech_explode_ammo",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.explode_stop",
        legacy: "btech_explode_stop",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.parts",
        legacy: "btech_parts",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.ic",
        legacy: "btech_ic",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.afterlife_dbref",
        legacy: "btech_afterlife_dbref",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.vcrit",
        legacy: "btech_vcrit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.slowdown",
        legacy: "btech_slowdown",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.fasaturn",
        legacy: "btech_fasaturn",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.fasaadvvtolcrit",
        legacy: "btech_fasaadvvtolcrit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.fasaadvvhlcrit",
        legacy: "btech_fasaadvvhlcrit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.fasaadvvhlfire",
        legacy: "btech_fasaadvvhlfire",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.divrotordamage",
        legacy: "btech_divrotordamage",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.moddamagewithrange",
        legacy: "btech_moddamagewithrange",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.moddamagewithwoods",
        legacy: "btech_moddamagewithwoods",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.hotloadaddshalfbthmod",
        legacy: "btech_hotloadaddshalfbthmod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.nofusionvtolfuel",
        legacy: "btech_nofusionvtolfuel",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.newcharge",
        legacy: "btech_newcharge",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.tl3_charge",
        legacy: "btech_tl3_charge",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.newterrain",
        legacy: "btech_newterrain",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xploss",
        legacy: "btech_xploss",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.critlevel",
        legacy: "btech_critlevel",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.newstagger",
        legacy: "btech_newstagger",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.newstaggertons",
        legacy: "btech_newstaggertons",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.newstaggertime",
        legacy: "btech_newstaggertime",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.skidcliff",
        legacy: "btech_skidcliff",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.extendedmovemod",
        legacy: "btech_extendedmovemod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.stacking",
        legacy: "btech_stacking",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.stackdamage",
        legacy: "btech_stackdamage",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.mw_losmap",
        legacy: "btech_mw_losmap",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.exile_stun_code",
        legacy: "btech_exile_stun_code",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.roll_on_backwalk",
        legacy: "btech_roll_on_backwalk",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.usedmechstore",
        legacy: "btech_usedmechstore",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.ooc_comsys",
        legacy: "btech_ooc_comsys",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.idf_requires_spotter",
        legacy: "btech_idf_requires_spotter",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.tsm_tow_bonus",
        legacy: "btech_tsm_tow_bonus",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.heatcutoff",
        legacy: "btech_heatcutoff",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.cost_debug",
        legacy: "btech_cost_debug",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.allow_cargo_commands",
        legacy: "btech_allow_cargo_commands",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "battletech.transported_unit_death",
        legacy: "btech_transported_unit_death",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.mwpickup_action",
        legacy: "btech_mwpickup_action",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.standcareful",
        legacy: "btech_standcareful",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.maxtechtime",
        legacy: "btech_maxtechtime",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.vtol_ice_causes_fire",
        legacy: "btech_vtol_ice_causes_fire",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.glancing_blows",
        legacy: "btech_glancing_blows",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.inferno_penalty",
        legacy: "btech_inferno_penalty",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.blzmapmode",
        legacy: "btech_blzmapmode",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.extended_piloting",
        legacy: "btech_extended_piloting",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.extended_gunnery",
        legacy: "btech_extended_gunnery",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xploss_for_mw",
        legacy: "btech_xploss_for_mw",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.variable_techtime",
        legacy: "btech_variable_techtime",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.techtime_mod",
        legacy: "btech_techtime_mod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.techtime_multiplier",
        legacy: "btech_techtime_multiplier",
        kind: "f64",
        bounds: Some((0.0, 10.0)),
    },
    KeySpec {
        path: "battletech.statengine_obj",
        legacy: "btech_statengine_obj",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.limitedrepairs",
        legacy: "btech_limitedrepairs",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.stackpole",
        legacy: "btech_stackpole",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.phys_use_pskill",
        legacy: "btech_phys_use_pskill",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.erange",
        legacy: "btech_erange",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.hit_arcs",
        legacy: "btech_hit_arcs",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.dig_only_fs",
        legacy: "btech_dig_only_fs",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.digbonus",
        legacy: "btech_digbonus",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.bthmod",
        legacy: "btech_xp_bthmod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.missilemod",
        legacy: "btech_xp_missilemod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.ammomod",
        legacy: "btech_xp_ammomod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.defaultweapdam",
        legacy: "btech_defaultweapdam",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.modifier",
        legacy: "btech_xp_modifier",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.defaultweapbv",
        legacy: "btech_defaultweapbv",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.use_pilot_bv_mod",
        legacy: "btech_xp_usePilotBVMod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.oldxpsystem",
        legacy: "btech_oldxpsystem",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.vrtmod",
        legacy: "btech_xp_vrtmod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.perunit_xpmod",
        legacy: "btech_perunit_xpmod",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.noisy_xpgain",
        legacy: "btech_noisy_xpgain",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.xp.xpgain_cap",
        legacy: "btech_xpgain_cap",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.badsite_file",
        legacy: "badsite_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.allow_chanlurking",
        legacy: "allow_chanlurking",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.cache_depth",
        legacy: "cache_depth",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.cache_trim",
        legacy: "cache_trim",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "mux.cache_width",
        legacy: "cache_width",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.check_interval",
        legacy: "check_interval",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.check_offset",
        legacy: "check_offset",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.command_quota_increment",
        legacy: "command_quota_increment",
        kind: "usize",
        bounds: Some((1.0, 100000.0)),
    },
    KeySpec {
        path: "mux.command_quota_max",
        legacy: "command_quota_max",
        kind: "usize",
        bounds: Some((1.0, 100000.0)),
    },
    KeySpec {
        path: "mux.conn_timeout",
        legacy: "conn_timeout",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.connect_dir",
        legacy: "connect_dir",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.connect_file",
        legacy: "connect_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.connect_reg_file",
        legacy: "connect_reg_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_home",
        legacy: "default_home",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.default_thing_lua_parent",
        legacy: "default_thing_lua_parent",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_room_lua_parent",
        legacy: "default_room_lua_parent",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_exit_lua_parent",
        legacy: "default_exit_lua_parent",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_player_lua_parent",
        legacy: "default_player_lua_parent",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_exit_flags",
        legacy: "default_exit_flags",
        kind: "Vec<Flag>",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_player_macros",
        legacy: "default_player_macros",
        kind: "Vec<usize>",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_player_flags",
        legacy: "default_player_flags",
        kind: "Vec<Flag>",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_room_flags",
        legacy: "default_room_flags",
        kind: "Vec<Flag>",
        bounds: None,
    },
    KeySpec {
        path: "mux.default_thing_flags",
        legacy: "default_thing_flags",
        kind: "Vec<Flag>",
        bounds: None,
    },
    KeySpec {
        path: "mux.down_file",
        legacy: "down_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.down_message",
        legacy: "down_message",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.dump_offset",
        legacy: "dump_offset",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.full_file",
        legacy: "full_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.full_message",
        legacy: "full_message",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.help_directory",
        legacy: "help_directory",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.idle_interval",
        legacy: "idle_interval",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.idle_timeout",
        legacy: "idle_timeout",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.initial_size",
        legacy: "initial_size",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.max_players",
        legacy: "max_players",
        kind: "i64",
        bounds: Some((-1.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.notify_recursion_limit",
        legacy: "notify_recursion_limit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.output_limit",
        legacy: "output_limit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.player_name_spaces",
        legacy: "player_name_spaces",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "mux.command_queue_limit",
        legacy: "command_queue_limit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.player_starting_home",
        legacy: "player_starting_home",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.player_starting_room",
        legacy: "player_starting_room",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.public_channel",
        legacy: "public_channel",
        kind: "String",
        bounds: None,
    },
    KeySpec {
        path: "mux.command_queue_active_chunk",
        legacy: "command_queue_active_chunk",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.command_queue_idle_chunk",
        legacy: "command_queue_idle_chunk",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.quit_file",
        legacy: "quit_file",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "mux.retry_limit",
        legacy: "retry_limit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.space_compress",
        legacy: "space_compress",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "mux.stack_limit",
        legacy: "stack_limit",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "mux.command_quota_interval",
        legacy: "command_quota_interval",
        kind: "u64",
        bounds: Some((1.0, 60000.0)),
    },
    KeySpec {
        path: "mux.unowned_safe",
        legacy: "unowned_safe",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "mux.player_zone",
        legacy: "player_zone",
        kind: "i64",
        bounds: Some((-2147483648.0, 2147483647.0)),
    },
    KeySpec {
        path: "names.maximum_length",
        legacy: "player_name_length_limit",
        kind: "usize",
        bounds: Some((2.0, 255.0)),
    },
    KeySpec {
        path: "security.player_password_length_limit",
        legacy: "player_password_length_limit",
        kind: "usize",
        bounds: Some((1.0, 4096.0)),
    },
    KeySpec {
        path: "security.password_hash_opslimit",
        legacy: "password_hash_opslimit",
        kind: "usize",
        bounds: Some((1.0, 100.0)),
    },
    KeySpec {
        path: "security.password_hash_memlimit",
        legacy: "password_hash_memlimit",
        kind: "usize",
        bounds: Some((1048576.0, 1073741824.0)),
    },
    KeySpec {
        path: "security.login_attempt_burst",
        legacy: "login_attempt_burst",
        kind: "usize",
        bounds: Some((1.0, 10000.0)),
    },
    KeySpec {
        path: "security.login_attempt_refill",
        legacy: "login_attempt_refill",
        kind: "u64",
        bounds: Some((1.0, 86400.0)),
    },
    KeySpec {
        path: "security.login_hash_limit",
        legacy: "login_hash_limit",
        kind: "usize",
        bounds: Some((1.0, 1000.0)),
    },
    KeySpec {
        path: "logging.topics.accounting",
        legacy: "accounting",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.all_commands",
        legacy: "all_commands",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.suspect_commands",
        legacy: "suspect_commands",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.bad_commands",
        legacy: "bad_commands",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.buffer_alloc",
        legacy: "buffer_alloc",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.bugs",
        legacy: "bugs",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.checkpoints",
        legacy: "checkpoints",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.config_changes",
        legacy: "config_changes",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.create",
        legacy: "create",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.logins",
        legacy: "logins",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.network",
        legacy: "network",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.problems",
        legacy: "problems",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.security",
        legacy: "security",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.shouts",
        legacy: "shouts",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.startup",
        legacy: "startup",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.topics.wizard",
        legacy: "wizard",
        kind: "bool",
        bounds: None,
    },
    KeySpec {
        path: "logging.log_options",
        legacy: "log_options",
        kind: "Vec<LogOption>",
        bounds: None,
    },
    KeySpec {
        path: "access.commands",
        legacy: "access",
        kind: "BTreeMap<String, Permissions>",
        bounds: None,
    },
    KeySpec {
        path: "access.lists",
        legacy: "list_access",
        kind: "BTreeMap<String, Permissions>",
        bounds: None,
    },
    KeySpec {
        path: "access.config",
        legacy: "config_access",
        kind: "BTreeMap<String, Permissions>",
        bounds: None,
    },
    KeySpec {
        path: "aliases.commands",
        legacy: "alias",
        kind: "BTreeMap<String, String>",
        bounds: None,
    },
    KeySpec {
        path: "aliases.flags",
        legacy: "flag_alias",
        kind: "BTreeMap<String, String>",
        bounds: None,
    },
    KeySpec {
        path: "colors",
        legacy: "named_color",
        kind: "BTreeMap<String, Rgb>",
        bounds: None,
    },
    KeySpec {
        path: "osc8.presets",
        legacy: "osc8_preset",
        kind: "BTreeMap<String, String>",
        bounds: None,
    },
    KeySpec {
        path: "names.bad",
        legacy: "bad_name",
        kind: "Vec<String>",
        bounds: None,
    },
    KeySpec {
        path: "names.good",
        legacy: "good_name",
        kind: "Vec<String>",
        bounds: None,
    },
    KeySpec {
        path: "sites.forbid",
        legacy: "forbid_site",
        kind: "Vec<SiteRule>",
        bounds: None,
    },
    KeySpec {
        path: "sites.suspect",
        legacy: "suspect_site",
        kind: "Vec<SiteRule>",
        bounds: None,
    },
    KeySpec {
        path: "sites.trust",
        legacy: "trust_site",
        kind: "Vec<SiteRule>",
        bounds: None,
    },
    KeySpec {
        path: "sites.permit",
        legacy: "permit_site",
        kind: "Vec<SiteRule>",
        bounds: None,
    },
    KeySpec {
        path: "database.legacy_game_database",
        legacy: "",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "database.busy_timeout_ms",
        legacy: "",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "database.clock_save_interval",
        legacy: "",
        kind: "u64",
        bounds: Some((0.0, 2147483647.0)),
    },
    KeySpec {
        path: "database.bootstrap.credentials_file",
        legacy: "",
        kind: "PathBuf",
        bounds: None,
    },
    KeySpec {
        path: "server.listen_address",
        legacy: "",
        kind: "IpAddr",
        bounds: None,
    },
    KeySpec {
        path: "lua.instruction_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "lua.output_entry_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "lua.output_byte_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "security.login_address_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "security.login_address_retention_seconds",
        legacy: "",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "security.login_hash_concurrency",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "security.login_history_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.max_connections",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.event_queue_capacity",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.session_output_queue_capacity",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.input_line_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.telnet_subnegotiation_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.output_message_limit",
        legacy: "",
        kind: "usize",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.write_timeout_ms",
        legacy: "",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.shutdown_timeout_ms",
        legacy: "",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "runtime.maintenance_interval_ms",
        legacy: "",
        kind: "u64",
        bounds: Some((1.0, 2147483647.0)),
    },
    KeySpec {
        path: "battletech.sensor_range",
        legacy: "",
        kind: "i64",
        bounds: Some((0.0, 60.0)),
    },
    KeySpec {
        path: "logging.min_level",
        legacy: "",
        kind: "LogLevel",
        bounds: None,
    },
];
