gravity = 100
temperature = 20

terrain = '''
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
%%........^.........
%%^^.............~~~
%...^^..........~~~~
.^^...^^^......~~~..
...^^....^^....~....
.....^^....^...~....
.......^^......~....
.........^^....~..^.
...........^...~....
...............~....
'''
level = '''
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000000000000000
00000000009000000000
00220000000000000000
00003200000000000000
02200032200000000000
00032000022000000000
00000320000200000000
00000002200000000000
00000000022000000010
00000000000200000000
00000000000000000000
'''
depth = '''
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
.................111
................1111
...............111..
...............1....
...............1....
...............1....
...............1....
...............1....
...............1....
'''
foliage = '''
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
................""""
................""""
................""."
................""""
................""""
'''
route = '''
...#................
....................
....................
...##...............
.....##.............
.......##...........
.........##......#..
...........##....#..
.............#####..
.................#..
.................#..
....................
.##.................
...##.............#.
.....##...........#.
.......##...........
.........##.........
...........##.......
.............##.....
....................
'''

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[2, 1], [3, 1], [4, 1], [2, 2], [3, 2], [4, 2], [15, 5], [16, 5], [17, 5]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[17, 11]]
