gravity = 100
temperature = 20

terrain = '''
^.^.^.^.^.^.^.^.^.^.^.......~.~.^.....^.^.^.^.^...
^^^^^^^^^^^^^^...^^^^^......~~~.^^^..^^^^^^.^^^...
^^^^.^.^^^^^^^...^^^^^......~~~..^^......^..^^^^^.
^^^......^^^^^...^^^^^.....~~~~.^^^.^^^^^..^.^^^^.
^^.........^.....^^^^^....~~~...^^...^^^^^....^^^^
................^^^^^^....~~~....^^..^^^^^..^^^^^^
.....^^.^.......^^^^^...~~~~......^..^^^^^^..^^^^^
..^^^^^^^^.......^.^.^~~~~..^^^.^....^^^^^^..^^^^^
^^^^^..^^^............~~~~.^^^^^^....^^^....^.....
.^.........^^.^.......~~~..^.^...^......^^^^^^^...
..^.....^.^^^^^^^.....~~~~..^...^^^.....^^^^^.....
.^^^^^^^^^^^^^^^^.....~~~~.^^^^^^^^....^^^^^^.....
^^^^^^^^^^^^^^^^......~~~~..^^^...............^^^^
^..^..^^^^^^.^........~~~~...^^..............^^^^^
^^..^..^.^^^..........~~~~.....^^.........^.^^^^^^
..^.^^..^^^^..........~~~~.......^^.......^^^^^^^^
..^^^^^....^..^.......~~~~................^.^...^^
^^^^^^.^^...^^........~~~~...^^.......^.^........^
^^^^^^...^.^........~~~~~~...^^^^...^.^.^.^.......
^^^^^..............~~~~~~~...^^^.....^^^^....^^^^.
..^...^^^^^^^.^...~~~~~~....^^^^^....^^.^....^^^^^
.^^.^^^^^^^^^^....~~~~....^^^^^^.........^....^^^^
^^^^^^^^^^^^^^^..~~~~.....^^^^^^......^......^^^..
^^^^^^^^^^^^^^..~~~~~~...^^^^^^^.....^^^^^^.......
^^^^^^^^^^^^^....~.~~~...............^^^^^^^^.....
^^^^^^^^^^^^..^^..~~~...^^^..........^^^^^.^^^....
^^^^^^^^....^^^^^.~~~...^^^............^.^.^...^^^
...^^.^...^^^^^^..~~~....^^^^........^^......^^^^.
.^^..^^.^^^^^^^^^.~~~~...^.^^^^......^^^^.^..^^^..
^^^^...^^^^^^^^^...~~~~...^^^^^^^.....^^^^^..^.^..
^^.^.^.^.^^^^^.....~~~~...^^.^^^^....^^^^^^.......
^^^....^............~~~~~..^.^^^.......^^^....^^^.
.^^^^................~~~~~~...^......^^..^..^^^^^^
.^^^^.................~~~~~...^......^.^...^^^^^^^
^.^^...................~~~~~...^^....^^^..^^^^^^^^
^.^....................~~~~~~..^^....^^..^^^^^^^^^
.^^^....................~~~~~..^^....^^...^^^^^^^^
.^.^..^.................~~~~~..^............^^....
.....^^^^...............~~~~~...^.................
.....^^^^^^.............~~~~~..^^^.......^.^....^^
^^^..^^^^^^.........%%%.~~~~..^............^^..^^^
^^^^....^^^.........%.%.~~~~.^^^...............^^^
^.^^..........^.^....%..~~~~..^^................^^
^^^^.........^^^^.......~~~~..^^^.^^...^^^^.....^^
.^^^..^......^^^^^......~~~~..^^^.^^..^^^^^.......
.....^^^....^^^^^^^.....~~~~..^^^^^^^.^^^^^.......
^...^^^^....^^^^^^^.....~~~...^^^^^^..^^^^.^......
^^^..^^^....^^^^^^^.....~~~..^^^^^^^..............
^^^^^......^.^^^^^^....~~~~..^^^^^....^^^^^...^.^.
^^^^^^^....^^^^^^^^...~~~~~..^^^....^^^^^^^..^^^^^
'''
level = '''
90604070709090301030300000000000200000103020201000
79653468457677000135110000000000222001123220321000
67430204353642000324310000000000031000000300222130
44200000022533000454230000000000232023333001012310
23000000000100000253230000000000120002232200003222
00000000000000003342230000000000011002343100113442
00000320200000003544300000000000001001251220021332
00223332320000000403030000001100200001223110012211
34333003230000000000000000013222200001120000200000
03000000000230200000000000010200030000001222222000
00200000202244321000000000001000241000001131100000
01533233524334331000000000011232111000012122100000
21453224334522220000000000002120000000000000001111
20040022233202000000000000000220000000000000002233
11002003023200000000000000000002100000000010212124
00203200112100000000000000000000023000000011221343
00221220000100200000000000000000000000000010100032
21333103300011000000000000000120000000202000000001
22232200020200000000000000000212300010302020000000
22122000000000000000000000000123000002212000024230
00100021221110100000000000003232200001101000013433
02202113222222000000000000222231000000000100003133
22121122323211100000000000132421000000300000032400
33231244332211000000000001132112000002322220000000
32311233243120000000000000000000000002232323300000
22311122121100320000000011100000000001112201230000
32211102000014322000000012300000000000010202000222
00011020001242340000000001212000000002300000022310
01100110312233243000000001023130000001231020022200
11210002321444220000000000122342200000234210010100
22010101022333000000000000120223100002163420000000
12200002000000000000000000010111000000042200001230
03333000000000000000000000000020000002100200213253
01242000000000000000000000000020000002020004333466
10220000000000000000000000000001100004320013443545
20100000000000000000000000000001200003200131452232
02310000000000000000000000000001100002200012242121
01010020000000000000000000000001000000000000210000
00000132200000000000000000000000100000000000000000
00000114432000000000000000000001120000000202000011
22200113542000000000111000000020000000000001100235
23220000222000000000101000000111000000000000000136
10110000000000302000010000000022000000000000000025
33220000000002543000000000000035201100021210000012
03220020000002444200000000000012102200213320000000
00000232000032443220000000000024515110233310000000
10002333000013665330000000000025452200212102000000
11200222000022764320000000000236441100000000000000
32212000000103334430000000000143310000222130002030
53221110000114364420000000000122000033435510012334
'''
depth = '''
............................2.2...................
............................243...................
............................152...................
...........................2351...................
..........................322.....................
..........................442.....................
........................2343......................
......................3353........................
......................4433........................
......................333.........................
......................2552........................
......................1252........................
......................3112........................
......................3551........................
......................3452........................
......................2652........................
......................2454........................
......................1443........................
....................114411........................
...................3335411........................
..................225522..........................
..................2132............................
.................2143.............................
................121163............................
.................1.243............................
..................222.............................
..................353.............................
..................321.............................
..................1111............................
...................1332...........................
...................2223...........................
....................34522.........................
.....................235513.......................
......................11452.......................
.......................22511......................
.......................112111.....................
........................13221.....................
........................12211.....................
........................13412.....................
........................32333.....................
........................3222......................
........................3233......................
........................2323......................
........................2223......................
........................2553......................
........................3534......................
........................332.......................
........................333.......................
.......................2222.......................
......................11111.......................
'''
foliage = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....................`.............................
..................``"`............................
..................``"`............................
..................`"``............................
...................```............................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
...............````...............................
.............`````"``.............................
.............```"""``.............................
..............`"""""``............................
.............``""""""`............................
.............``"```"``............................
...............`````..............................
...............`..................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
route = '''
..................................................
..................................................
...............#..................................
......#........#..................................
....##.##.....##..................................
..##.....##.##....................................
##.........##.....................................
.............##...................................
...............##.................................
.................##...............................
...................##.............................
....................##............................
..................##.................#............
................##........#.......#..#..#.........
...............#...........##......#####..........
.............................##......#............
...............................##...##............
.................................###..............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..............................#...#...............
...............................####...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
...................................##.............
....................................###...........
..................................##...##.........
.........................................##.......
...........................................##.....
.............................................#....
.............................................#....
.............................................##...
...............................................##.
..................................................
..................................................
..................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[15, 1], [33, 13], [41, 13]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[14, 14], [29, 25], [21, 41], [33, 41]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[37, 11]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[22, 11], [23, 12], [24, 12], [25, 13]]
