gravity = 100
temperature = 20

terrain = '''
~~~~~~~~..........................................
~~~~~~..........%.........................~~~.....
~~~~...............%...................~~~~~~.....
~~....................................~~.~~~~.....
~~......%........%%%%................~~.....~.....
~~......%............................~......~~~...
~......%%............................~...^....~...
~.....%%%............................~...^....~~..
~....%%%%.........................%%.~..^^^....~..
....%%%%%..........~~~...........%%%.~..^^^^...~..
...%%%.............~~~...........%%%.~..^^^^^..~~.
.%%%...............~~~...........%%%.~..^^^^^...~~
.%%................~~~...........%%..~..^^^^^....~
.%.................~~~...............~..^^^^^^...~
.....................................~..^^^^^^^..~
.....................................~..^^^^^^^..~
.....................................~..^^^^^^^..~
.....................................~..^^^^^^^..~
.............%.......................~..^^^^^^^..~
...............%.%...................~..^^^^^^...~
................%....................~..^^^^^....~
.............%......~................~..^^^^^...~~
...................~~................~...^^^^..~~.
..................~~~................~....^^^..~..
..............^^^^^..................~~....^^..~..
............^^^^^^^...................~~.......~..
^^^^^^^^^^^^^^^^^^^....................~~......~..
^^^^^^^^^^^^^^^^^^^....................~~~....~~..
^^^^^^^^^^^^^^^^^^^.................~~~~~~~..~~...
^^^^^^^^^^^^^^^^^^^...............~~~~~~~.~~~~....
^^^^^^^^^^^^^^^^^...............~~~~~~............
^^^^^^^^^^^^^^^^...............~~~~~..............
^^^^^^^^^^^...................~~~~................
^^^^^^^^^^^..................~~~~.................
^^^^^^^^^^.................~~~~~..................
^^^^^^^^^................~~~~~~...................
^^^^^^.................~~~~~~.....................
^^^^^.................~~~~~.......................
^^^^............~~~~~~~~~.........................
^^^^...........~~~~~~~~~..........................
^^............~~~.................................
^^........~~~~~~~.................................
^.......~~~~~~~~~.................................
^.......~~~~~.....................................
^.......~~........................................
.......~~~........................................
......~~~~........................................
....~~~.~~........................................
...~~...~~~.......................................
~~.~~...~~~.......................................
'''
level = '''
00000000000000000000000000000000000000000011111000
00000000000000000000000000000000000000000000001100
00000000000000000000000000000000000000000000000111
00000000000000000000000000000000000000000000000000
00000000000000000020200000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000001223322110000000000100000000
00000000000000000000000000000000000000000100000000
00000000000000000000000000000000001100001110000000
00000000000000000000000000000000012100001111000000
00000000000000000000000000000000013100001241100000
00000000000000000000000000000000012100001242100000
00000000000000000000000000000000011000001242100000
00000000000000000000000000000000000000001242110000
00000000000000000000000000000000000000001242211000
00000000000000000000000000000000000000001244221000
00002220000000000000000000000000000000001264321000
00022220000000000000000000000000000000001244221000
00022320000000000000000000000000000000001242211000
00033333000100000100000000000000000000001242110000
00003333000100001000000000000000000000001222100000
00003223011101000000000000000000000000001122100000
00022222010000000000000000000000000000000112100000
00022221110000000000000000000000000000000011100000
00011111000000111130000000000000000000000001100000
00000000000011133330000000000000000000000000000000
11111111111113333310000000000000000000000000000000
13333331111333334210000000000000000000000000000000
33333333333344433210000000000000000000000000000000
33333366443433332210000000000000000000000000000000
33333666344433322000000000000000000000000000000000
34436666333332220000000000000000000000000000000000
34366663332000000000000000000000000000000000000000
34334333322000000000000000000000000000000000000000
34333333220000000000000000000000000000000000000000
33333222200000000000000000000000000000000000000000
33332200000000000000000000000000000000000000000000
33322000000000000000000000000000000000000000000000
33320000000000000000000000000000000000000000000000
32220000000000000000000000000000000000000000000000
32000000000000000000000000000000000000000000000000
22000000000000000000000000000000000000000000000000
20000000000000000000111112222200000000000000000000
20000000000000000000222222333322211111111110000000
20000000000111122222233333444443333322221110000000
00000000000000000000002222333322210000000000000000
00000000000000000000111111111111110000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
'''
depth = '''
33220000..........................................
322200....................................222.....
2200...................................222332.....
20....................................22.2222.....
20...................................22.....2.....
00...................................2......222...
0....................................2........2...
0....................................2........22..
0....................................2.........2..
...................111...............2.........2..
...................131...............2.........22.
...................121...............2..........22
...................121...............2...........2
...................111...............2...........2
.....................................2...........2
.....................................2...........2
.....................................2...........2
.....................................2...........2
.....................................2...........2
.....................................2...........2
.....................................2...........2
....................1................2..........22
...................11................2.........22.
..................113................2.........2..
.....................................22........2..
......................................22.......2..
.......................................22......2..
.......................................222....22..
....................................1122122..22...
..................................2221111.2222....
................................222111............
...............................22111..............
..............................1111................
.............................2111.................
...........................22211..................
.........................222111...................
.......................221111.....................
......................22111.......................
................222222221.........................
...............222222211..........................
..............122.................................
..........2222221.................................
........222422211.................................
........21121.....................................
........21........................................
.......121........................................
......1111........................................
....111.11........................................
...11...122.......................................
11.11...122.......................................
'''
foliage = '''
..................................................
..................................................
..................................................
........................................`.........
.......................................`````......
......................................``"""`......
......................................`""."```....
......................................`"".""``....
......................................`"...""``...
......................................`"....""`...
......................................`"....."`...
......................................`"....."``..
......................................`".....""``.
......................................`"......""`.
...``.................................`"......."`.
...`````..............................`"......."`.
...`````..............................`"......."`.
.```````..............................`"......."`.
.````"`````...........................`"......."`.
.``"""``.```..........................`"......""`.
.```""``.`.`..........................`".....""``.
.```"```````..........................`"....."``..
..``````.`............................`""...."`...
...```````............................``""..."`...
...`````...............................``"".."`...
........................................``""""`...
.........................................``""``...
..........................................````....
..............................`"...........``.....
............................."".""................
...........................".."...................
........................."""```...................
.........................``.......................
......................."``".......................
...................`"``"."........................
.................```..............................
.............".."`".".............................
.............".``...............".................
............````..............""""............."""
..........".`"................""""........"...""""
......```"```...................""........".."""""
.....``...................................""""""".
....``....................................."""""".
....".........................................""".
....`.............................................
...``.............................................
.```..............................................
``................................................
..................................................
..................................................
'''
route = '''
..............#..................##############...
..............#..................#............##..
..............#..................#.............###
..............#..................#................
..............#..................#................
..............#..................#................
..............####################................
..............#...................................
..............#...................................
..............#...................................
..............#...................................
..............#...................................
..............#...................................
..............#...................................
..............##..................................
...............##.................................
................###################...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................#...............
..................................##..............
...................................##.............
..................................................
..................................................
......................................##..........
.......................................#########..
...............................................#..
...............................................###
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
condition = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
--................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[22, 0], [30, 0], [22, 1], [30, 1], [22, 2], [30, 2], [22, 3], [30, 3], [22, 4], [30, 4], [22, 5], [30, 5], [22, 7], [30, 7], [22, 8], [30, 8], [22, 9], [30, 9], [22, 10], [30, 10], [22, 11], [30, 11], [22, 12], [30, 12], [22, 13], [30, 13]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[23, 0], [29, 0], [23, 1], [29, 1], [23, 2], [29, 2], [23, 3], [29, 3], [23, 4], [29, 4], [23, 5], [29, 5], [23, 7], [29, 7], [23, 8], [29, 8], [23, 9], [29, 9], [23, 10], [29, 10], [23, 11], [29, 11], [23, 12], [29, 12], [23, 13], [29, 13], [21, 19], [22, 19], [23, 19], [24, 19], [25, 19], [27, 19], [28, 19], [29, 19], [21, 20], [29, 20], [21, 21], [29, 21], [21, 22], [29, 22], [21, 23], [29, 23], [29, 24], [21, 25], [29, 25], [21, 26], [29, 26], [21, 27], [22, 27], [23, 27], [24, 27], [25, 27], [26, 27], [27, 27], [28, 27], [29, 27]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[24, 0], [28, 0], [24, 1], [28, 1], [24, 2], [28, 2], [24, 3], [28, 3], [24, 4], [28, 4], [24, 5], [28, 5], [24, 7], [28, 7], [24, 8], [28, 8], [24, 9], [28, 9], [24, 10], [28, 10], [24, 11], [28, 11], [24, 12], [28, 12], [24, 13], [28, 13]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[25, 0], [27, 0], [25, 1], [27, 1], [25, 2], [27, 2], [25, 3], [27, 3], [25, 4], [27, 4], [25, 5], [27, 5], [25, 7], [27, 7], [25, 8], [27, 8], [25, 9], [27, 9], [25, 10], [27, 10], [25, 11], [27, 11], [25, 12], [27, 12], [25, 13], [27, 13], [22, 20], [23, 20], [24, 20], [25, 20], [27, 20], [28, 20], [22, 21], [28, 21], [22, 22], [28, 22], [22, 23], [28, 23], [28, 24], [22, 25], [28, 25], [22, 26], [23, 26], [24, 26], [25, 26], [26, 26], [27, 26], [28, 26]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[26, 0], [26, 1], [26, 2], [26, 3], [26, 4], [26, 5], [26, 7], [26, 8], [26, 9], [26, 10], [26, 11], [26, 12], [26, 13], [26, 19], [26, 20], [21, 24], [22, 24], [23, 25], [24, 25], [25, 25], [26, 25], [27, 25]]

[[structures]]
kind = "building"
class = "medium"
height = 6
hexes = [[25, 21], [23, 23], [27, 23]]

[[structures]]
kind = "building"
class = "medium"
height = 7
hexes = [[23, 21], [24, 21], [26, 21], [27, 21], [23, 22], [27, 22], [23, 24], [24, 24], [25, 24], [26, 24], [27, 24]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[24, 22], [25, 22], [26, 22], [24, 23], [25, 23], [26, 23]]

[[structures]]
kind = "wall"
class = "medium"
height = 5
hexes = [[26, 14], [26, 15], [26, 17], [26, 18], [19, 24], [20, 24]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[36, 28], [37, 28], [37, 29], [38, 29]]
