gravity = 100
temperature = 20

terrain = '''
%%%%..............................................
%%%%..%..%.%......................................
%...%.%...........................................
..%.%.......%....%................................
....%........................................%%...
..%......%..................................%%%...
............................................%%%...
.%.....%%.........................................
....%...%%.....%..................................
..................................................
.%%...............................................
.%..%.............................................
....%.........%...................................
..................................................
........%.........................................
.%................................................
..%...%......%....................................
..................................................
..%.%........................................%....
.%.......%...................................%....
.............................................%....
..................................................
...%..............................................
...................%..............................
.............%..%%%...............................
..........%%%....%................................
....%...%%%%~.~....%..............................
......%.%%~~~~~~~~~...............................
.........%~~~~~~~~~~..............................
.%....%..~~~~~~~~~~~~.............................
......%%.~~~~~~~~~~~~..%..%............^^^^^......
.......%.~~~~~~~~~~~~~~.................^^^^......
..........~~~~~~~~~~~~~~~...............^^^^......
..%...%....~~~~~.....~~~~~~..............^........
................%%.....~~~~~~~~...................
....%...........%%.......~~~~~~~~.................
...............%.............~~~~~~~~.............
...............................~~~~~~~~...........
...%.............................~.~~~~~~.~.......
.....................................~~~~~~~~.~~~~
.......................................~~~~~~~~~~~
.%.......................................~~~~~~~~~
...........................................~~~~~~~
..%.............................^...^........~~~~~
................................^^^^^..........~~~
...%............................^^^^.............~
%%..%............................^^^.............~
%.%...........%.......~...........................
.%...%...............~~...........................
%%%.%.%.%...%........~~...........................
'''
level = '''
11111000000000000000011222000000000000000000000000
11110010000000000000012322110000000000000000000000
11111000000000000000011222211000000000000000000000
11100010000000100000000122322110000000100000000000
10010000000000000000000012233221100010000000002000
10000000111000001100000001121222111000100000100000
01000001111100011100000000000113211001000000001000
00001001121110001100000000000112123121211100000000
01000011121110000000000000000001012222110000000000
00000011121100000000000000000000011211011000000000
01000001111100000000000000000000000000100000000000
10000001111000000000000000000000000101001000000000
00000000010000000000000000000000000000100000000000
00000000000000000000000000000000000001000000000000
00001100000001100000000000000000000000000000000000
00001110000001100000000000000000000000000000000000
00011100000000000000000000000000000000000000000000
00011110000000000000000000000000000000000000000000
00000100000000000000000000000000000000000000000000
00000100000000000000000000000000000000000000000000
00001000000000000000000000000000000000000000000000
00001000000000000000000000000000000000000000000000
00000000000000000000000000000000111120000000000000
00000000000000000000000000000000122221111000000000
00000000000000101010000000000000222222221000000000
00001100100101000000000000000001213333211011100000
00010000000000000001000000000000222233212222100000
00000100100000000000000000000000221212223232100000
10000000000000000000000000000001120122233322211000
10000100000000000000000000000000001123334332321000
00000010000000000000000010000000001223266555321000
00000000000000000000000000000010000123336764210000
00110011000000000000000000001110000112235644210000
01100000000000000000000000011100000001123533210000
11000000100000000000000000000000000000123322210000
00000000000000001000000000000000000000122322110000
00100000000001000000000000000000000000011211000000
00110000000000000000000000000000000000000100000000
00100000000000000000000000000000000000000000000000
00110000000000000000000000000000000000000000000000
11010000000000000000000000000011111111100000000000
11100000000000000000000000000012222222210000000000
01100000000000000000000000001123333333210000000000
11100000000000000000000000001133543353211000000000
21111000000000000000000000001223657543211000000000
22111000000000000000000000001232477623321000000000
22110000000000000000000000001233366623221000000000
22211000000001100000000000000122333333210000000000
31111111001111100000000000000112333222110000000000
43211101101111000000000000000012132111100000000000
'''
depth = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
............1.1...................................
..........111121111...............................
..........1232222211..............................
.........123222233111.............................
.........123222232211.............................
.........11232331211211...........................
..........122222211112211.........................
...........11111.....112111.......................
.......................11221211...................
.........................11212211.................
.............................11221111.............
...............................11222211...........
.................................1.112211.1.......
.....................................11221111.0100
.......................................11211110100
.........................................101101100
...........................................1101100
.............................................00100
...............................................100
.................................................0
.................................................0
......................0...........................
.....................00...........................
.....................00...........................
'''
foliage = '''
..................`````````.........``````.``.````
..................`````````````.....``````..`.````
...................`````````````...``````.`.`.````
.....................````````````..``````.`.....``
.....................``````````````````````.....``
.....................```````````````````.`......``
.....................``````````````````````.....``
.....................```````.``````````````.....``
.......................`.......````````````...````
...................................`````````"`.```
....................................````````.`````
.....................................```````..````
......................................````````````
.......................................`````"`````
.........................................```"`````
.........................................```"````.
...........................................``.``..
..................................................
..................................................
..................................................
..................................................
..................................................
................................`````.............
................................`````````.........
................................``````````........
................................````````..........
................................``````...``.`.....
.................................```..``.`````....
......................................``"`"````...
....................................```"""""```...
....................................``"....."``...
..............................`.....``""...."``...
............................```.....```"....``....
...........................```.......``"".""``....
......................................```````.....
.......................................`````......
..................................................
..................................................
..................................................
.........................``.......................
.........................```......................
...............................``````.............
.....................`........````"````...........
.....................`........``.""".``...........
.............................``"....."`...........
.............................``"....""`...........
......................`......``""...""`...........
.............................```""`""``...........
....................`..`......`````"``............
....................`..`.......```````............
'''
route = '''
.............................................#....
.............................................#....
.........................................#...#....
...........................................###....
..................................................
..........................................#.......
..................................................
.............................................#....
.............................................#....
..................................................
..................................................
.............................................#....
..................................................
..................................................
..................................................
..........................#.......................
........................#.#..................#....
.......................####..#..#............#....
......................########..#.................
....................#############.................
................######.#.....########.............
............########.............########....#....
........########.....................#########....
....########.............................########.
########..................................##.#####
####....................................##.....###
......................................##.......#.#
....................................##.........#..
..................................##...........#..
................................##.............#..
..............................##...............#..
............................##.................#..
..........................##...................#..
...............................................#..
......................#........................#..
....................##.........................#..
..................##.#.........................#..
................##...######....................#..
..............##.....#.........................#..
............##.......#............................
...........#.........#............................
..................#.###...........................
...................#...##.........................
...................#....#.........................
...................#....#.....................#...
...................#....#...................#.#...
...................#.........................##...
...................#..........................###.
..............................................#...
..................................................
'''
condition = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..............-...................................
................-.-...............................
..................................................
..................--..............................
..................................................
..................-...............................
..................................................
..................................................
........................-..-.-....................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.........................................--.......
...........................................-......
..................................................
..................................................
..................................................
.................................................-
..................................................
..................................................
..................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 0
hexes = [[42, 1], [41, 3], [40, 5], [43, 8], [44, 11], [25, 25], [10, 40]]

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[42, 0], [43, 1], [43, 2], [47, 3], [47, 4], [43, 5], [47, 6], [43, 7], [44, 7], [46, 7], [47, 7], [44, 8], [46, 9], [44, 10], [23, 36], [19, 37], [13, 38], [17, 38], [19, 38], [18, 40], [18, 42], [20, 43], [17, 44], [44, 44], [45, 44], [17, 45], [20, 45], [47, 45], [48, 45], [20, 46], [24, 46], [44, 46], [18, 47], [24, 47], [19, 48], [45, 48], [48, 48], [47, 49]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[46, 3], [43, 4], [44, 4], [22, 15], [23, 15], [22, 16], [22, 35], [23, 35], [20, 36], [22, 36], [27, 36], [20, 37], [27, 37], [29, 37], [22, 38], [29, 38], [11, 39], [22, 39], [19, 40], [23, 40], [11, 41], [19, 41], [23, 41], [17, 42], [20, 42], [25, 42], [11, 43], [25, 43], [18, 44], [22, 44], [25, 44], [18, 45], [23, 45], [45, 45], [47, 46], [48, 46], [25, 47], [45, 47], [47, 48]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[23, 16], [28, 36], [10, 39], [20, 39], [9, 40], [20, 40], [22, 40], [9, 41], [10, 41], [22, 42], [9, 43], [10, 43], [22, 43], [23, 43], [9, 44], [23, 44], [25, 46]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[26, 12], [25, 13], [26, 13], [25, 14], [26, 14], [31, 14], [32, 14], [25, 15], [31, 15], [32, 15], [31, 16], [32, 16], [22, 23], [28, 23], [25, 28], [26, 42], [26, 43]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[28, 13], [28, 14], [29, 14], [28, 15], [29, 15], [29, 16], [28, 37], [9, 42]]

[[structures]]
kind = "building"
class = "medium"
height = 6
hexes = [[25, 23], [23, 26], [27, 26]]

[[structures]]
kind = "wall"
class = "medium"
height = 1
hexes = [[26, 10], [24, 11], [25, 11], [27, 11], [28, 11], [23, 12], [29, 12], [30, 12], [31, 12], [32, 12], [22, 13], [23, 13], [33, 13], [34, 13], [20, 14], [21, 14], [34, 14], [20, 15], [34, 15], [20, 16], [34, 16], [20, 17], [27, 17], [28, 17], [34, 17], [21, 18], [30, 18], [31, 18], [34, 18], [33, 19]]

[[structures]]
kind = "wall"
class = "medium"
height = 2
hexes = [[24, 21], [26, 21], [22, 22], [23, 22], [24, 22], [25, 22], [26, 22], [27, 22], [28, 22], [23, 23], [24, 23], [26, 23], [27, 23], [21, 24], [22, 24], [23, 24], [27, 24], [28, 24], [29, 24], [21, 25], [22, 25], [23, 25], [27, 25], [28, 25], [29, 25], [21, 26], [22, 26], [24, 26], [26, 26], [28, 26], [29, 26], [22, 27], [23, 27], [24, 27], [25, 27], [26, 27], [27, 27], [28, 27], [23, 28], [24, 28], [26, 28], [27, 28], [10, 37], [11, 37], [12, 37], [8, 38], [9, 38], [7, 39], [7, 40], [13, 40], [7, 41], [13, 41], [7, 42], [13, 42], [7, 43], [13, 43], [7, 44], [12, 44], [13, 44], [7, 45], [8, 45], [10, 45], [11, 45], [9, 46]]

[[structures]]
kind = "bridge"
class = "medium"
height = 1
hexes = [[24, 33], [25, 33], [23, 34], [47, 39], [47, 40], [47, 41], [47, 42], [47, 43], [47, 44]]
