gravity = 100
temperature = 20

terrain = '''
........................................
..................................~.....
......................^^.........~~~....
......................^^.........~~~....
....................^^^^................
..................^^^^..................
...................^....................
......................~~~...............
....~~~...............~~~...............
....~~~................~................
.....~..................................
........................................
........................................
................~.......................
...............~~~......................
...............~~~......................
........................................
........................................
........................................
................................~~~.....
................................~~~.....
............^....................~......
..........^^^...........................
.........^^^^^..........................
...........^^...........................
............................~~~.........
............................~~~.........
.............................~..........
........................................
..............................^^^^^^^^^^
..............^^............^^^^^^^^^^^^
.............^^^..........^^^^^^^^^^^^^^
..............^^........^^^^^^^^^^^^^^^^
..............^^.......^^^^^^^^^^^^^^^^^
..............^^.......^^^^^^^^^^^^^^^^^
........~......^.......^^^^^^^^^^^^^^^^^
.......~~~.............^^^^^^^^^^^^^^^^^
.......~~~.............^^^^^^^^^^^^^^^^^
.......................^^^^^^^^^^^^^^^^^
.......................^^^^^^^^^^^^^^^^^
'''
level = '''
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000330000000000000000
0000000000000000000000330000000000000000
0000000000000000000033330000000000000000
0000000000000000003333000000000000000000
0000000000000000000300000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000100000000000
0000000000000000000000000011211000000000
0000000000000000000000000122322100000000
0000000000000000000000000123432100000000
0000000000000000000000000123430100000000
0000000000000000000000000123340000000000
0000000000000000000000000112000000000000
0000000000003000000000000001000000000000
0000000000233000000000000000000000000000
0000000001233200000000000000000000000000
0000000000033000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000000000000000
0000000000000000000000000000001421641658
0000000000000033000000000000352554525238
0000000000000333000000000025355635365548
0000000000000033000000005521133521353328
0000000000000033000000053135651595256558
0000000000000033000000033235255312125348
0000000000000003000000055515535333551538
0000000000000000000000022151521111152268
0000000000000000000000055355511325514578
0000000000000000000000035213532531332688
0000000000000000000000038283818185858788
'''
depth = '''
........................................
..................................2.....
.................................212....
.................................222....
........................................
........................................
........................................
......................111...............
....222...............121...............
....212................1................
.....2..................................
........................................
........................................
................3.......................
...............313......................
...............333......................
........................................
........................................
........................................
................................111.....
................................121.....
.................................1......
........................................
........................................
........................................
............................222.........
............................212.........
.............................2..........
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........3...............................
.......313..............................
.......333..............................
........................................
........................................
'''
foliage = '''
........................................
............""".........................
....`.......""".........................
...```......."..........................
...```..................................
........................................
........................................
........................................
..............`...............```.......
.............```..............```.......
.............```...............`........
........""".........`...................
........"""........```..................
.........".........```........""".......
......`.......................""".......
.....```......................."........
.....```...."...........................
..........."""..........................
..........."""..........................
..".....................................
."""....................................
."""................""".................
....................""".................
....................."..............`...
......`............................```..
.....```...........................```..
.....```........```.....................
................```.....................
.................`....```...............
......................```...............
.......................`................
........`...............................
.......```..............................
.......```..............................
........................................
................".......................
.."............"""......................
."""..........."""......................
."""....................................
........................................
'''
