gravity = 100
temperature = 20

terrain = '''
............................~.%...~.^.^.^.^.^.^.^.
...................~~~~~~.~~%%....^~.^^^^^^^^^^^^^
................~~~~~~~~~~%%......%~~^%^^^%^.^^^^^
..............~~~~~~.~.~.~%..........~~...%^..^^^^
............~~~~~~......%%........%.%%%~~...%.^.^^
............~~~~.......%........%....%%.~..%.^.^^^
............~~........%%....%.%.....%.%%~.^..%^^^.
............~~%.%....%%........%....%%^^~.^^^^^%^^
...........~~~%%%%%....%%..%.%..%.%%...^~^.%.....^
...........~~~%%%%%%%...%.........%...~~.%.......^
...........~~~%%%%%%%%..%...%..%%%%...~..........^
............~~~%%%%%%%..%...%.%.%.%....~~........^
............~~~%%%%%%%..%.......%%%......~.......^
..........~~~~%%%%%%%%...%%......%%......~.......^
.........~~~~~~%~%~%%%%....%%....%%......~~.......
...........~~~~~~~~~~%%%%....%....%%%%....~.......
................%%%~~~%%%%%..%....%%.......~......
...........%%%%%%%%%~~%%%%%..%%.%%.........~~~....
...........%%%%%%%%%~~%%%%%..%.%....%%.......~~...
...........%%%%%%%%%~~%%%%%.......%%%%%........~..
......%........%%%%%~~%%%%%%^.^.^%%%%%..%.....~~..
......%.........%%%%~~%%%%%%^^^^...%%.%%%.....~...
................%%%%^~^%%%%^^^........%%%.....~...
..............%.%%^^~^.^^%%^^^........%%%......~..
..............%.%^..~~...^^^^^........%%%......~~.
..............%.%%..~~...^^^^^........%%%.......~.
................%^..~~...^%^%%%.....%.%%%........~
..............%.%^..~~...^%%%%......%%%%..........
..............%.%%..~~...^^%%%......%%............
..............%.%^...~~...^..%%%..%.%.............
..............%.%%....~~.......%%%%%%.............
..............%.%%%....~~......%%%%%..............
..............%.%%^......~~.......................
..............%..%%^^......~~.....................
...............%%..%%........~~...................
...............%%%..%..^^....~~~..~.~~~.~.~.......
...............%%%.....%%^^.~~~~~.~~~~~~~~........
...............%%%%...%%%^^.~~~~~~~~~~~~~~~~~.....
...............%%%%%%%%%%^^.~~~~~~~~.~~~~~~~~.....
....^^^^^^^^^^^%%%%%%%%%%^^.~~~~~~~...~~~~~~~.....
....^..........^^%%%%%%%%^^.~~~~~~~...~~~~~~......
....^............^^%%%%%%^^.~~~~~~~~~~~~~~.~......
.^..^.............^%%%%%%^^.~~~~~~~~~~~~...~.~....
.^^^...............^%%%%%^^.~~~~~~~~~~~~....~.~...
...................^%%%%%^^.~~~~~~~~~~~......~....
%..................^%%%%%^^.~~~~~~~~~~~~..........
%%................^^%%%%%^^.~~~~~~~~~~~~~.........
.................^%%%%%%%...~~~~~~~~~~~~~~~.......
.................^%%%%%%...~~..~~~~~~~~~~~~~......
................^^%%%%%%........~~~~~~~~~~~~......
'''
level = '''
00000000101011111010000000000050500050505070505030
00000000111111111110000000005556556055445557777553
10000101111111110000000000666666666004544335352775
11101111111111000000303030666665566040053322232275
10111111111100000033333366666556665454400233332257
11211111111000002333333666666556665555550322223355
22212111111000222223336666666655556444330322233354
22222221212000626223366666656560666562420223035555
22222222222000676663333666666665066603430323550005
22222222222000667766633377755566666022003234550005
22222222222000676776764477706666666222020234550005
22222222222200066666664477705605656210100133550005
22223333322200066666664477776565066022222023550005
22333333330000666666664447777666566221111033555055
33333333300000060606666444477776656011212004555555
33333333333000000000076764444777766666002204354544
33333333333444555550006676644777777620000020243404
33333333434455555555007767744777773222000000000000
44434444444455555565006667644747333366000000000000
44444444444455655666006777744444336666603200000000
44444444445556066666006776774444366666546000000000
44444404555556006666006767774444999666666000000000
44444455555556006666603667744499999996666000000000
44444555555556666633061337744499888996666000000000
44444555555555666300000223444499807996666000000000
44444555555555666600001123444499989666666000000000
44444555555555666300001113646669999966666000000000
44445555555555666300000113666678898866661110100000
44445555555555666600000003666677787766001111110000
44445555555555666300000000900666776760001111222000
44445555555555666600000022000006666660011121122200
44445555555555666660002000000006666600111222222200
44444555555555666630002000000000000001112222222200
44444555555566066663301000000000000011225255525300
44444555666666666666622100000000000011225555555300
44444556666666666666522330000000000000010505555400
44445566666606666655322663310000000000000055555400
34445566666666667765327653310000000000000000054300
34455556666666667666666763310000000000000000044300
34453333333333366676767662210000000010000000033200
34553222221222133667666672210000000000000000233200
34553212211222211336767762210000000000000000222200
23553001020111211036766662210000000000000000001100
23331102000001111203677672210000000000000110000010
12111100000000022203776661110000000000000110000001
71110000000000002203667771110000000000001112100000
77200000000000000033766761110000000000000111000000
23322000000000000376767660010000000000000001000000
02233220202000000366676620300110000000000000000000
00022332121220003367666633011110000000000000000000
'''
depth = '''
............................1.....1...............
...................111111.11.......1..............
................1111111111.........11.............
..............111111.1.1.1...........11...........
............011111.....................11.........
............1011........................1.........
............11..........................1.........
............01..........................1.........
...........010..........................1.........
...........011........................00..........
...........001........................0...........
............011........................11.........
............011..........................0........
..........1011...........................2........
.........111111.1.1......................12.......
...........1111111111.....................2.......
...................111.....................1......
....................11.....................111....
....................11.......................00...
....................11.........................0..
....................11........................00..
....................11........................0...
.....................1........................0...
....................1..........................0..
....................11.........................00.
....................11..........................0.
....................10...........................0
....................10............................
....................11............................
.....................11...........................
......................11..........................
.......................11.........................
.........................11.......................
...........................11.....................
.............................01...................
.............................110..1.111.1.1.......
............................01111.11212121........
............................01113132123222221.....
............................01223311.11222221.....
............................0123331...1322111.....
............................0133331...131111......
............................01333331113111.1......
............................012333333331...1.1....
............................012333333331....1.1...
............................01223333333......1....
............................011213133311..........
............................0111111011113.........
............................110111111113322.......
...........................11..0111131333221......
................................103133333221......
'''
foliage = '''
........`.`.`.`.`.`.`.`.`.`.....`.................
........```````````......`....""``..`.............
.......`````````............""``"...........`.....
......````````......".".".."``.`"``"`..""`..""....
......``````......""""""..""`.."`.."......`".`.`..
.......`.`.`....."""""".""``..``..".".."."..`."...
...................""".."`.`.`..`"`".`...".".....`
..""".....`............""``.```.`.`".....`........
""."..```.`.............."`....`.`...`"..."..`....
""""...``.`.............."`.`````..`..............
..."...``.`.............."``.``...................
.........`.`............."``.`.`.`.`..............
..`.....`.``.............""```.`..................
.```....``.................""``.`.................
.`..".`.`....................""``.................
".""".`..``..................."```................
""`"".``"`"`````.............."`""................
".``".```""...................."..................
.`"`"..``"".......................................
.`.`.."``"`.......................................
.``....`"."```....................................
..`....""""```....................................
`"``..`""``"``....................................
.````.``"`""``........`...........................
`"``".``""`"``.....`..`...........................
`"`"`.````````.....`..`...........................
```"...`.`.`.`.....`..`...........................
""."..`.`.`.`......`..`.......```.``..............
``..`"````````.....`..`.......``````..............
".""```````"``.....``..``.......``.`..............
"."`"``"``````.......`..""........................
".```"`"``````.......`"..``.....................``
".`""`""`"""""........"``..``...................."
"."``````"`"."...........``..``.........`."``.`.""
".`"``"``.`"...............``.....`.```.`""``"`.`.
`."```."""`.`...................``.`...`.`.``"`."`
`..""`.`...`"....................`........``""`.`"
...``""`"....................................`"."`
....................................`........"".".
...................................`"`.......`".``
.......`...........................```......```.""
......`.``...`............................`.""..`"
.....`...`.`...`........................```...`.`"
...............``.......................``......"`
...............``......................`.."""...."
........................................`"`""`....
.."...`.`................................``"......
"``""..`.......`.........``................`......
"""``"".".".............```.......................
"""""``""""``...........```````...................
'''
route = '''
..................................................
..................................................
.....#............................................
.....#............................................
.....#............................................
.....##.#.#.....#.................................
.....#######..#####...............................
.....#.#.#.#...#.####.............................
.....#.............####...........................
.....#...............###..........................
.....#................##..........................
.....#................##..........................
.....#................##..........................
.....#................###.....................#...
.....#.................####...................#...
.....#...................####.........#.......#...
.....#.....................##.......#####.....#...
.....#.....................##.....####.####.......
.....#.....................##.#.####.....###......
.....#.....................#######......##.#......
.....#.......................#.#......##...#......
.....#...............................#.....#......
.....#...............................#.....#......
.....#.........#.....................#.....#......
.....#.........#..................#..#.....#......
.....#.........#...................###.....#......
.....##.#.#.#.##.....................#.....#......
....##.#.#.#.#.#...........................#......
..##...........#..........................###.....
.#.............#........................##...##...
.#.............#......................##.......#..
.#.............#....................##.........#..
.#.............#..................##...........#..
.#.............##.....#.........##.............#..
.#...............##..####......#...............#..
.#................##.##..##.#..................#..
.#................#####....#...................#..
##.................###.....#...................#..
#..........................#...................#..
#..........................#...................#..
#..........................#...................#..
#..........................#..................##..
#..........................#................#..#..
#..........................#..............##.#.#..
.########..................#............##.....#..
...........................#...................#..
...........................#......................
...........................#......................
.............................##...................
...............................#..................
'''

[[structures]]
kind = "building"
class = "medium"
height = 0
hexes = [[2, 0], [3, 1], [46, 46], [45, 47]]

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[48, 47], [46, 48], [47, 48], [49, 48], [45, 49]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[0, 0], [6, 0], [1, 1]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[10, 43], [11, 43], [12, 43], [9, 44], [13, 44], [46, 44], [48, 44], [9, 45], [13, 45], [46, 45], [49, 45], [9, 46], [10, 46], [12, 46], [13, 46], [44, 46], [45, 46], [11, 47], [44, 47], [44, 48], [48, 48], [44, 49], [46, 49], [47, 49]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[0, 1], [6, 1], [7, 1], [1, 2], [2, 2], [4, 2], [6, 2], [3, 3]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[10, 44], [11, 44], [12, 44], [10, 45], [12, 45], [11, 46], [48, 49], [49, 49]]

[[structures]]
kind = "building"
class = "medium"
height = 7
hexes = [[46, 8], [47, 8], [48, 8], [46, 9], [48, 9], [46, 10], [48, 10], [46, 11], [48, 11], [46, 12], [48, 12], [47, 13], [11, 45]]

[[structures]]
kind = "building"
class = "medium"
height = 8
hexes = [[14, 20], [14, 21], [15, 21], [14, 22], [15, 22]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[47, 9], [47, 10], [47, 11], [47, 12], [33, 24]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[12, 5], [12, 6], [44, 17], [30, 34], [38, 45], [39, 45], [36, 46], [37, 46], [34, 47], [35, 47], [32, 48], [33, 48]]

[[structures]]
kind = "bridge"
class = "medium"
height = 1
hexes = [[13, 6], [13, 7], [29, 35], [45, 42], [28, 47]]

[[structures]]
kind = "bridge"
class = "medium"
height = 2
hexes = [[14, 5], [45, 17]]
