gravity = 100
temperature = 20

terrain = '''
^.^......^................^...................~~~~~~~~~~~~~
%..^.....^^..............^%.^....................~~~~~~~~~~
%^.^.....^...............%..%....................~~~~~~~~~~
.%^^......................^.^.^...................~~~~~~~~~
%^%^...%.......%.%........%....%..................~~~~~~~~~
.............%..%%%.%..%...^%^....................~~~~~~~~~
........%...%..%.%...^%..%%...%.................~~~~~~~~~~~
......%..%..%%.%.%%^.^..%.%..^.^..................~~~~~~~~~
..........%.%.%.%..%^^^^.~~%..%...................~~~~~~~~~
.......%....%%%..%%..^^.%.%.....................~~~~~~~~~~~
........%.%%.%%%..%^%^^^%....................~~~~~~~~~~~~~~
........%.%...%%...%^^^^..................~~~~.~~~~~~~~~~~~
............%%..%%..%^.............~......~...~.~~~~~~~~~~~
...........%.%.%..%%..............~~~.....~....~~~~~~~~~~~~
............%.%.%.%.%.............~~~....~~.....~~~~~~~~~~~
.............%...................~~~.~.~~...........~~~~~~~
...............%..%.............~.~.~.~.............~~~~~~~
.....................................%..............~~~~~~~
..........................%%..................^^..~~~~~~~~~
............................................^^^...~~~~~~~~~
............................................^^....~~~~~~~~~
...........................................^^.....~~~~~~~~~
.................................................~~~~~~~~~~
..................................................~~~~~~~~~
....................................................~~~~~~~
...........................%..%.....................~~~~~~~
.............................%.%....................~~~~~~~
...............................%...................%.~~~~~~
......%%^^^^^^^^%.........%..%%......................~~~~~~
....%.^^^^^^^^^^^%%....%....%........~~~.~~~........~~~~~~~
..%^^^^^^^^~^~^^^^^%..%.%.%%%......~~~~~~~~~........~~~~~~~
..%^^^^^~^^^^^^^^^^%%%%%.%.%.......~~~~~~~~~.....~~~~~~~~~~
.^^^~^^^^^^~^^.^^~^^.%............~~~~~~~~~~~~~~~~~~~~~~~~~
~~^^^^^^~^^^..^^^^^%.............~~~~~~~~~~~~~~~~~~~~~~~~~~
^^^..^^^^^..^^^^^^%................~~~~~~~~~~~~~~~~~~~~~~~~
%^^^^..^..^^^^^~^%%..................~~~~~~~~~~~~~~~~~~~~~~
.^^^^^^.^^^~^^^^%...................~~~~~~~~~~~~~~~~~~~~~~~
.%^^^^^.^^^^%^%..................~~~~~~~~~~~~~~~~~~~~~~~~~~
..^^^^^.^^^^%....................~~~~~~~~~~~~~~~~~~~~~~~~~~
..~^^^^.^^^^....^................~~~~~~~~~~~~~~~~~~~~~~~~~~
..%^~^^.^^^%....^................%%%~~~~~~~~~~~~~~~~~~~~~~~
..%^^^^.^^^.....^........%.........%%~~~~~~~~~~~~~~~~~~~~~~
...^^^^.^^^...^^^^^.....%............%~~~~~~~~~~~~~~~~~~~~~
...^^~^.^^^%.^^^^^.......%............%~~~~~~~~~~~~~~~~~~~~
...%^^^.^^....^^^.^.....%...............~~~~~~~~~~~~~~~~~~~
.....^^........^^^^.......%..................~~~~~~~~~~~~~~
^^....^................%.%.%.................~~~~~~~~~~~~~~
^^....^.................%.%.%.................~~~~~~~~~~~~~
^^^...^...............%%..%...................~~~~~~~~~~~~~
'''
level = '''
23211211130000000000000012222222221000000000000000000000000
26431312212000000000000012202221210000000000000000000000000
16323312230000000000000001222220210000000000000000000000000
31531131110000000000000011222220221100000000000000000000000
16331222110000000000000001122221222111000000000000000000000
31121131210000000000000000112222222221000000000000000000000
12223233130000000000010000011112222021000000011100000000000
13122213120000000002010000000112222221000000111101000000000
11233323330000000000251100000011111111000001101111000000000
12313113110000000000053100000000001310000000111100000000000
23321233210000000002231100000000000000000000000000000000000
32332233220000000000241100000000000000000000000000000000000
13233222230000000000010000000000000000000000000000000000000
13321333120000000000000000000011000000000000000000000000000
33333332220000000000000000002231130002000000000000000000000
33223212220000000000000000011113300030000000000000000000000
23133111220000000000000000012312010201000000000000000000000
00002111000000000000000000012132311131100000000000000000000
00002322011100000000000000123131113233100000002100000000000
00000000110000001000000000111122223231100000121000000000000
00101111001102222000000000001221232111000000220000000000000
11111100111102222000000000002133223312000001100000000000000
11110011111102222000000000000000000000000000000000000000000
11001111110002222000000000000000000000000000000000000000000
10111111100000020010000000000000000000000000000000000000000
10111100000000000110000000000000000000000000000000020000000
10110000000000000111000000000000000000000000077770110000000
11000000000000000001000000000000000000000000076770021000000
00000001111111211111000000000000000000000000076670003000000
00001114333403611110000000000000121000000000077770540000000
00003131261010203310000000000001121000000000000000000000000
00111511016078821130000000000000121000000000000000000000000
01120214251088782000000000000000010000000000000000000000000
00888851018867881130000000000000000000000000000000000000000
12877883886688131410000000000000000000000000000000000000000
13288668668821002110000000000000000000000000000000000000000
01513876882020321000000000000000000000000000000000000000000
00141876825014100000000000000000000000000000000000000000000
00005886816300000000000000000000000000000000000000000000000
00021086842100001000000000000000000000000000000000000000000
00150286812000001000000000000000000000000000000000000000000
00015385811000002000000000000000000000000000000000000000000
00012184825000115230000000000000000000000000000000000000000
00011053612001246300000000000000000000000000000000000000000
00001222510000246010000000000000000000000000000000000000000
00000131100000022410000000000000000000000000000000000000000
21000010000000000000000000000000000000000000000000000000000
53000010000000000000000000000000000000000000000000000000000
12100010000000000000000001111121100000000000000000000000000
'''
depth = '''
..............................................1112223334445
.................................................1112223334
.................................................1112223334
..................................................111112223
..................................................111112223
..................................................111112223
................................................11122233344
..................................................011112223
.........................11.......................011112223
................................................01122233344
.............................................11111222333444
..........................................1111.111122233344
...................................1......1...1.11112223334
..................................121.....1....111222333444
..................................212....11.....11122233344
.................................121.1.11...........1112223
................................3.2.1.1.............1112223
....................................................1112223
..................................................111222333
..................................................111122233
..................................................223334445
..................................................223334445
.................................................1122233344
..................................................223334445
....................................................3334445
....................................................3334445
....................................................3334445
.....................................................112223
.....................................................122233
.....................................210.111........1112223
...........2.0.....................231232311........1122233
........1..........................213313122.....1112223334
....1......1.....1................3111321222322245111112223
14......0........................53514512115522214344200223
...................................141335551212231212244223
...............0.....................4245111342434034140334
...........2........................31152123114534022042223
.................................12532513115253212434420223
.................................33411134423343312003441344
..1..............................52332444425531211122233344
....1...............................12222222222222222222222
.....................................1222222222222222222222
......................................122222222222222222222
.....1.................................12222222222222222221
........................................1111111111213123122
.............................................11122222223222
.............................................11122222223332
..............................................1112222222333
..............................................1112222222333
'''
foliage = '''
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
....````......................"`...........................
....````....................``````...`.....................
....````....................`"```...`......................
....````....................````.`.`.`.....................
....````....................``````"``."....................
....````....................`````"````"....................
................`..........`````"`````.....................
.............`"""...........``````````.....................
.............""""...........``````````.....................
.............""""..........................................
.............`""`..........................................
..............."..`.....................""`................
.................`"......................```...............
.................```......................``...............
...................`............`"`........................
...................`............"""........................
...............................`...........................
...............................``..........................
...........................................................
...........................................................
.....................".....................................
....................."``...................................
.....................""`...................................
...................`"````..................................
...................`"``.`..................................
....................``.....................................
...........................................................
...........................................................
..............................`............................
..............................``...........................
.............................```...........................
............................````...........................
...........................................................
...........................................................
...........................................................
...........................................................
'''
route = '''
.......##..................................................
.......##..................................................
.......##..................................................
........###................................................
.........##................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
...........................................................
..............#............................................
............##.............................................
...##.....##...............................................
.....##.##.................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......#...................................................
.......##..................................................
.......#...................................................
.......#...................................................
.......#...................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[51, 28]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[50, 28]]

[[structures]]
kind = "building"
class = "medium"
height = 6
hexes = [[49, 28]]

[[structures]]
kind = "building"
class = "medium"
height = 8
hexes = [[45, 24], [46, 24], [47, 24], [46, 25], [47, 25], [44, 27], [49, 27], [44, 28], [44, 29], [49, 29], [46, 30], [47, 30], [45, 31], [46, 31], [47, 31]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[45, 25], [48, 25], [44, 26], [49, 26], [44, 30], [45, 30], [48, 30], [49, 30]]
