gravity = 100
temperature = 20

terrain = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........................^^^.......................
.......................^^^^^......................
.......................^^"^^......................
.......................^^"^^......................
.......................^^^^^......................
.........................^........................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
...................................~~.............
...................................~~~............
...................................~.~............
......................@@.@....@....~..............
...............@...@.@..`@....@....~~~~...........
...............@@..@.@...@....@.....^^~^^.........
...............@.@@@.@@@.@....@.....^^~^^.........
.@.............@...@.@...@....@.....^^^^^.........
...............@...@.@@@.@@...@.@@...^^^..........
...............@...@.@.....@@.@@..................
..................................................
'''
level = '''
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000012100000000000000000000000
00000000000000000000000134310000000000000000000000
00000000000000000000000120210000000000000000000000
00000000000000000000000120210000000000000000000000
00000000000000000000000111110000000000000000000000
00000000000000000000000001000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000011011000000000
00000000000000000000000000000000000012021000000000
00000000000000000000000000000000000012221000000000
00000000000000000000000000000000000001110000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
'''
depth = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
...................................12.............
...................................211............
...................................1.1............
...................................1..............
...................................1111...........
......................................2...........
......................................3...........
..................................................
..................................................
..................................................
..................................................
'''
structure_height = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
......................99.9....9...................
...............9...9.9...9....9...................
...............99..9.9...9....9...................
...............9.999.999.9....9...................
.9.............9...9.9...9....9...................
...............9...9.999.99...9.99................
...............9...9.9.....99.99..................
..................................................
'''
