gravity = 100
temperature = 20

terrain = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....................%.........%.....%.............
.........................................%........
........%....%....................................
................................................%.
........................%%%.......................
......................%%...%%.....................
....................%%.......%%...................
........%.........%%...........%%.................
................%%...............%%.............%.
...............%...................%..............
...............%...................%..............
........%......%...................%............%.
...............%...................%..............
.........%%%%%%%........%%%........%..............
..%............%........%.%........%............%.
...............%.........%.........%%%%%%%%.......
...............%...................%..............
.%.............%...................%.......%......
...............%...................%..............
...............%...................%.......%......
.%.............%%.................%%..............
.................%%.............%%................
...................%%.........%%...........%......
..%..................%%.....%%....................
.......................%%.%%......................
......%..................%........................
......................................%...........
............%....%......%.......%..........%......
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
level = '''
99999999999999999999999900099999999999999999999990
99999999999999999999999900099999999999999999999999
99999999999999999999999990999999999999999999999999
99999899999999999999999999999999999999999999999999
99999769999999999999999999999999999999999999999999
99999995499999999999999999999999999999999999999999
88898889398889899989887888988889899989998989898989
88877778288878788778788788877888887888888878888888
77777778197777776777778888878767776777886878878878
56574553015666553556575747577536565646554447234642
24331300000313242113030201030301140213332231010322
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000001000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000011000000000001100000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000011100000000000000000000000
00000000000000000010000010100000100000000000000000
00000000000000000000000001000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000010000000000000100000000000000000
00000000000000000001000000000001000000000000000000
00000000000000000000000001000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
10002030311021635000204053434243312240000000005330
45725565626466767562547676656565546564400000457664
78887777777777777798787877777688877777899910887777
88888887788887778888778787778788888778993299988777
88989988999988979998888887989899989889949999998789
99999999999999999999999999999999999999956999999999
99999999999999999999999999999999999999999789999999
99999999999999999999999999999999999999999999999999
99999999999999999999999900099999999999999999999999
99999999999999999999999900099999999999999999999999
99999999999999999999999990999999999999999999999999
'''
foliage = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
````````.`````````"``````````````````````````````.
`""`"```.``````"````````"``````""```"``"```"`"`""`
`"```"`".```"```.....................``"``````````
``""````.""`"`..""``"`"``"``"```"""`"........`"```
``"`"```.``"..```"```````````````````"``````"..`"`
`"```"``.`..`"``"```...........````````"```````..`
``````"`..`````"````...............`````"`````"`.`
""`"""``.```.```.......................`````"```.`
``"```"`.``............................`````"```.`
````````.``...............................``````.`
`"``"```.`................................``"`"`."
"```"`"`..................................````"`."
``"`````.`..............................``"`````.`
````"`"`.`..............................````````.`
`"``""...`..............................```"````.`
```"..```...............................``"``""`.`
"`.."`"``................................``"````.`
`.`"```"`..................................```.."`
`.``````..................................`..."```
`.```"```.................................`.`"``"`
`.""``"```..............................```.``"```
`.``"`"""`..............................```."`````
`.```"````..............................```.``"`"`
`.`"````................................`"`.``````
`.`"`""``..............................``"`."`"```
`..`"`````............................`"`"`.````"`
""`.."""```````.....................``"```.."`````
```"`..`"`"````""``.............```.`"`"..`.```""`
``"`"``..`"``"`"`"```"``"```"```"""`"`..```.`"`"``
`"```"`"".............................`"```.``````
```"`````"```""```"`"""``""`""`"""``````"``.``````
``````"`"`"````````````"```"```````````````.``````
.`...`............................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
route = '''
......................##...#......................
........################...#......................
......##...............##.##......................
.....#...................#........................
.....##...........................................
.......##.........................................
........#.........................................
........#.........................................
........#.........................................
........#.........................................
........#.........................................
........#.......####.#########.#####..............
........#.....##.....................####.###.....
............#................................##...
........#.##...................................#..
........##......................................#.
........#.......................................#.
........#.......................................#.
................................................#.
........#................#........................
........#................#......................#.
........#.........###....#....###...............#.
...................####.###.####..................
......###............#########..................#.
....##.................#...#....................#.
...#..............######...######.................
.#.................#...##.##...#..............##..
.#....................#######..............###....
....................####.#.####...................
.#................####...#...####..........#......
.#.................#.....#.....#..................
.........................#.................#......
.#.........................................#......
.#................................................
.#.........................................#......
...##.....................................##......
.....#..................................##.#......
.......##..............................#...#......
.........###.####.######.#######.#####............
...........................................#......
...........................................#......
..........................................##......
........................................##........
.......................................#..........
.......................................##.........
.........................................##.......
........................###...............#.......
.......................#...##...........##........
.......................#...#######################
.......................##.##......................
'''

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[25, 25]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[25, 1], [25, 48]]

[[structures]]
kind = "wall"
class = "medium"
height = 2
hexes = [[24, 18], [25, 18], [26, 18], [24, 19], [26, 19], [18, 20], [19, 20], [20, 20], [30, 20], [31, 20], [32, 20], [17, 21], [33, 21], [17, 22], [18, 22], [32, 22], [33, 22], [18, 24], [32, 24], [17, 25], [33, 25], [17, 26], [18, 26], [32, 26], [33, 26], [18, 28], [32, 28], [17, 29], [33, 29], [17, 30], [18, 30], [20, 30], [24, 30], [26, 30], [30, 30], [32, 30], [33, 30], [19, 31], [24, 31], [26, 31], [31, 31], [25, 32]]

[[structures]]
kind = "wall"
class = "medium"
height = 9
hexes = [[24, 0], [25, 0], [26, 0], [24, 1], [26, 1], [25, 2], [24, 47], [25, 47], [26, 47], [24, 48], [26, 48], [25, 49]]
