gravity = 100
temperature = 20

terrain = '''
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
....................................^^^.........................................
..................................^^^^^^^.......................................
.................................^^^^^^^^^......................................
.................................^^^^^^^^^......................................
.................................^^^^%^^^^......................................
......~~~........................^^^^^^^^^......................................
......~~~........................^^^^^^^^^......................................
.......~...........................^^^^^........................................
.....................................^..........................................
................................................................................
..........................................................................~.....
.........................................................................~~~....
.........................................................................~~~....
................................................................................
................................................................................
................................................................................
'''
level = '''
00000000000000000000000000100000000000001000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000001000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000010000000000000000000000000000000000000000000
00000000000000000000000000000000000000000100000000000000000000000000000001110010
00000000000000000000000000000000000000000000000000000000000000000000000011200000
00000000000000000000000000000000000000000000000000000000000000000000000011100000
00000000000000000000000000000000000000000000000000000000000000000000000011000012
00000000000000000000000000000000000000000000000000000000000000000000012112001111
00000000000000000000000000000000000000000000000000000000000000000000011111111211
00000000000000000000000000000000001000000000001000000000000000000000121221111121
00000000000000000000000000000000000000000000000000000000000000000012112211111111
00000000000000000000000000000000000000000000000000000000000000011100000000000021
00000000000000000000000000000000000000000000000000000000000011121104521222111011
00000000000000000000000000000000000011100000000000011111112111121105121111211011
00000000000000000000000000000000001122211000000000011111111121111101111211111011
00000000000000000000000000000000012233322110000111211112111111211101111111111011
00000000000000000000000000000000012344432100000112111111121111111201112111122011
00000000000000000000000000000000012343432100002121112121121211112111221111011012
00000000000000000000000000000000012334332101121221111111111211221111111110001012
00000000000000000000000000000000011223221101222121121112211121211111111110001011
00000000000000000000000000000000000112111000111121221121111212111201111111111011
00000000000000000000000000000000000001111000111211112112221111111101111111211011
00000000000000000000000000000000000000112000112111111111121112211101111121111011
00000000000000000000000000000000000000111000111111112111111121112101111111011021
00000000000000000000000000000000000011111011211111111111111111111101112110001012
00000000000000000000000000000000000011211112111111111111112121111100112120001012
00000000000000000000000000000000021111111211111111121111111111111100122111111021
00000000000000000000000000000000221211111111111111111111111111221100000000000012
00000000000000000000000000000001111111111111121111111111111121121111111111111222
'''
depth = '''
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
......111.......................................................................
......121.......................................................................
.......1........................................................................
................................................................................
................................................................................
..........................................................................1.....
.........................................................................121....
.........................................................................111....
................................................................................
................................................................................
................................................................................
'''
foliage = '''
................................................`"`""`""""`"``..................
..................``...........................""""""""`"""```..................
.............."``.""..........................""""""""""""`"....................
.............."```````........................`"""""""""`"``"...................
..............`""""""``........................``""""""""""``...................
.............."""""""`........................```"""""""""""`...................
.............`""""""""........................."""""""""`""`....................
.............`"""""""`"......................."`""""""""""".....................
............"``"""""""`........................`."``"""`"`......................
.............."""""""".............................`"""`........................
..............`"""""`.............................."``..........................
..............."""`"................................."..........................
......```........"..............................................................
......`"`.......................................................................
.......`........................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
..............`.`.".............................................................
..............""""`"".............................`.............................
...............`""""""..........................""""`.................`.........
..............`"""""""".......................`""""``................`"`........
............."`""""""``......................."""`"""``..............```........
.............""""""""""........................`""""""".........................
.............""""""""".`.......................`""""""."........................
...............``"""``.........................`""""""`.........................
'''
route = '''
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
......................................................................###.......
.....................................................................#..........
.....................................................................#..........
................................................................######..........
.....................................................................#..........
.....................................................................#..........
.....................................................................####.......
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 0
hexes = [[3, 17]]

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[2, 16], [3, 16], [4, 16], [2, 17], [4, 17], [3, 18], [74, 19]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[74, 18], [73, 19], [75, 19], [73, 20], [74, 20], [75, 20]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[12, 14], [12, 19]]

[[structures]]
kind = "wall"
class = "medium"
height = 3
hexes = [[66, 12], [67, 12], [66, 13], [66, 14], [66, 26]]

[[structures]]
kind = "wall"
class = "medium"
height = 4
hexes = [[0, 10], [11, 10], [11, 23]]

[[structures]]
kind = "wall"
class = "medium"
height = 5
hexes = [[1, 10], [2, 10], [3, 10], [4, 10], [5, 10], [6, 10], [7, 10], [8, 10], [9, 10], [10, 10], [0, 11], [1, 11], [11, 11], [0, 12], [11, 12], [68, 12], [69, 12], [70, 12], [71, 12], [72, 12], [73, 12], [74, 12], [75, 12], [76, 12], [77, 12], [0, 13], [11, 13], [77, 13], [0, 14], [11, 14], [77, 14], [0, 15], [11, 15], [66, 15], [77, 15], [0, 16], [66, 16], [77, 16], [0, 17], [66, 17], [77, 17], [0, 18], [77, 18], [0, 19], [11, 19], [77, 19], [0, 20], [11, 20], [77, 20], [0, 21], [11, 21], [66, 21], [77, 21], [0, 22], [1, 22], [10, 22], [11, 22], [66, 22], [77, 22], [0, 23], [1, 23], [2, 23], [3, 23], [4, 23], [5, 23], [6, 23], [7, 23], [8, 23], [9, 23], [10, 23], [66, 23], [77, 23], [66, 24], [77, 24], [66, 25], [77, 25], [67, 26], [77, 26], [66, 27], [67, 27], [77, 27], [66, 28], [67, 28], [68, 28], [69, 28], [70, 28], [71, 28], [72, 28], [73, 28], [74, 28], [75, 28], [76, 28], [77, 28]]
