gravity = 100
temperature = 20

terrain = '''
^^^^^^..^^^^^^^^^^^^^^^^^^^^....^^^^^^^^^^^^^^^^^^
^^^^^^..^^^^^^^^^^^^^^^^^^^.....^^^^^^^^^^^^^^^^^^
^^^^^^..^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
........^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
.............^.................^^^^^^^^^^^^^^^^^^^
.....^.........................^^^^^^^^^^^^^^^^^^^
^^...^^...^^....^^...^^^^......^^^^^^^^^^^^^^^^^^^
^^^.^^^^...^^^^^^^^..^^^^^^^...^^^^^^^^^^^^^^^^^^^
^^^^^^^^...^^^^^^^^^^^^^^^^....^^^^^^^^^^^^^^^^^^^
^^^^^^^^^.^^^^^^^^^^^^^^^^^....^^^^^^^^^^^^^^^^^^^
^^^^^^^%..^^^^^^^^^^^^^^^^^....^^^^^^^^^^^^^^^^^^^
^^^^^^^...^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
^^^^^^^..^^^^^.^^^^^^^^^^^^......^^^....^^^^^^^^^^
^^^^^^^.....%.%^^^^^^^^^^^^..............^^^^^^^^^
^^^^^.........%^^^^^^^^^^^............^....^^^^^^^
^^^^^..........^^^^^^^^^^^^^....^^^^^^^.......^^^^
^^^^...........^^^^^^^^^^^......^^^^^^^^^........^
^^^^............^^^^^^^^........^^^^^^^^^^^.......
^^^^^............^...^..........^^^^^^^^^^^^^^^...
^^^^^^.%.^^.%...........^^^^...^^^^^^^^^^^^^^^^^..
^^^^^^.^^^^^^^^^^.....^^^^^^^..^^^^^^^^^^^^^^^^^^^
^^^^...^^^^^^^^^^...^^^^^^^^^..^^^^^^^^^^^^^^^^^^^
^^^....^^^^^^^^^^^^^^^^^^^^^^..^^^^^^^^^^^^^^^^^^^
^^.....^^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
......^^^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
......^^^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
^^^^...^^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^^^^^^^^^^^
^^^^....^^^^^^^^^^^^^^...^.......^...^.....^^^^^^^
^^^^^....^^^^^^^^^^^^^.......................^^^^^
^^^^^^...^^^^^^^^^...........................^^^^^
^^^^^^...^^^^^.................................^.^
^^^^^...^^^^......................................
^^^^^....^........................................
^^^^^.............................................
^^................................................
...........................^^^^^^^^...^^^.........
............................^^^^^^^^^^^^^^^.......
.............................^^^^^^^^^^^^^^^^.....
.............................^^^^^^^^^^^^^^^^^^...
..............................^^....^^^^^^^^^^^^^^
.~~.~...............................^^^^^^^^^^^^^^
~~~~~~...............................^^^^^^^^^^^^^
~~~~~~~..............................^^^^^^^^^^^^^
~~~~~~~~~............................^^^^^^^^^^^^^
~~~~~~~~~~~.....~~~~~.................^^^^^^^^^^^^
~~~~~~~~~~~~~.~~~~~~~~................^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~~~~~...............^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~~~~~~~.~.~~~~~~~...^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
'''
level = '''
88888700686666677863367688870000469997998999899632
88888800777567876764567688800000476968784857477622
78687700788788888888888887870005454445453333332222
00000000887878788878887767870005545444443334322223
00000000000009000000000000000005554444544343332233
00000300000000000000000000000006555444443433333222
44000330004400004600056550000006555444454333342222
66805563000454445660088774490005978587878543332222
58748874000465757788878886400008999899899673633323
36887863308488888888887888700007687888489998976342
26566850004688776778685888500004555554489998897332
22248860004777555555556888560005655545477968489843
22688730054555055444454576700000055500005444479963
22787640000000066675747786400000000000000444444743
22786000000000047888888887000000000000400004443333
35862000000000047877675767460000655577500000003334
24850000000000044744444454000000544478854000000003
57880000000000004454444600000000444788887470000000
78873000000000000400040000000000447888888888764000
78432400044000000000000044440005788888787888887500
87255404544445445000004444655005788867554668788888
55550004445676744000444374555006788655554434367788
25500004447888844454468777575005788575554443336888
33000003446778877475659877560008885655556443334778
00000033337456685687987855660007888787777786633358
00000033346744476777675576760007888888887888766347
44440003344554455555656566760006676778786878887378
44540000333445555555550006000000000000000006678778
54544000045455665555500000000000000000000000067888
44545500054455667300000000000000000000000000000537
54555400044565000000000000000000000000000000000000
65445000555500000000000000000000000000000000000000
66545000050000000000000000000000000000000000000000
55556000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
12200000000000000000000000077000888000998000000000
20010000000000000000000000117788888889998970000000
11011000000000000000000011210777988889999888700000
00002100000000000000000012010777878889888887776000
02010000000000000000000000000070000088888887776667
00000100000000000000000000000000012077888887778777
00000000000000000000000000000000001207788888877796
00000000000000000000000000000000001008888888887777
00000000000000000000000000000000000100789898888777
00000000000000000000000000000000000200889889888787
00000000000000000000000000000000000110888888988988
00000000000000000000000000000000011010889888898898
00000000000000000000000000000000000000888898889888
00000000000000000000000000000000000007898888888989
00000000000000000000000000000000000008898888888988
'''
depth = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.01.0.............................................
112111............................................
2223321...........................................
232323110.........................................
22222221121.....00100.............................
2221232232210.11212110............................
12222333332111322232200...........................
2321323332222233233332101.1.1021112...............
3321332321122323133333222221333223321.............
1222122300112211132323333212233323321.............
'''
foliage = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........`.........................................
..................................................
..............`...................................
...........`.`....................................
.....`............................................
.....`........`...................................
....`.............................................
....`.............................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..```.............................................
`""``.............................................
"``""`....................``......................
``````..................`````.....................
""""``..................`````.....................
````""..........................````..............
"..`."".........................``"`..............
................................."```.............
.................................."``.............
..................................`"`.............
..................................`"``............
................................``""``............
.................................`````............
...................................```............
..................................................
..................................................
'''
route = '''
......##.....................#....................
......##.....................#....................
......##.....................#....................
......##.....................#....................
#########....................#....................
.......#.#####################....................
.........#...................#....................
.........#...................#....................
.........#...................#....................
.........#...................#....................
.........#...................#....................
........##...................#....................
........#....................#....................
........#....................##########...........
........#....................#.........##.........
........#....................#...........##.......
........#...................##.............##.....
........#######...........####...............##...
......##.......##.....####...#.................##.
......#..........#####.......#...................#
......#......................#....................
......#......................#....................
......#......................#....................
......#......................#....................
.....#.......................#....................
.....#.......................#....................
.....#.......................#....................
.....##......................#....................
.......#....................#####.................
.......#..................##.....##...............
.......#................##.........##.............
.......#..............##.............######.......
.......#............##.....................##.....
.......#..........##.........................####.
.......##.......##..#............................#
.........##...##..##..............................
...........##.#.##................................
.............####.................................
.................##...............................
...................##.............................
.....................##...........................
.......................##.........................
.........................######...................
..........................#####...................
...........................#.#....................
..................................................
..................................................
..................................................
..................................................
..................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[32, 41], [31, 42], [33, 42], [31, 43], [33, 43], [31, 44], [32, 44], [33, 44]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[32, 42], [32, 43]]

[[structures]]
kind = "wall"
class = "medium"
height = 5
hexes = [[20, 31], [18, 32], [19, 32], [16, 33], [17, 33], [20, 33], [14, 34], [15, 34], [18, 34], [19, 34], [11, 35], [12, 35], [13, 35], [16, 35], [17, 35], [20, 35], [13, 36], [15, 36], [18, 36], [19, 36], [11, 37], [12, 37], [17, 37], [18, 37], [13, 38], [14, 38], [15, 38], [16, 38], [19, 38], [17, 39], [18, 39], [19, 40]]
