gravity = 100
temperature = 20

terrain = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........................~~~.......................
......................~~~.~~~.....................
....................~~~~^.^~~~~...................
..................~~~~^^...^^~~~..................
.................~~.~^.......^....................
.................~~^~..........^..................
.................~~~~^^.....^^....................
...................~~~~^^.^^......................
.....................~~~~.........................
.......................~~.........................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
level = '''
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000060600000000000000000000000
00000000000000000000006600066000000000000000000000
00000000000000000000060000000600000000000000000000
00000000000000000006000000000006000000000000000000
00000000000000000000066000006600000000000000000000
00000000000000000000000660660000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000
'''
depth = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........................515.......................
......................555.555.....................
....................5555...5555...................
..................1555.......555..................
.................55.1.............................
.................55.1.............................
.................5115.............................
...................5555...........................
.....................5555.........................
.......................55.........................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
route = '''
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
#........................#........................
.##......................#......................##
...##....................#....................##..
.....##..................#..................##....
.......##................#................##......
.........##..............#..............##........
...........##.........................##..........
.............##..........#..........##............
...............##........#........##..............
.................#......###.....##................
...................#..##...##.##..................
.....................##.....###...................
.......................##.##...##.................
................##.......#.......##...............
..............##.........#.........##.............
............##...........#...........##...........
..........##.............#.............##.........
........##...............#...............##.......
......##.................#.................##.....
....##...................#..................###...
..##.....................#....................###.
##.......................#.......................#
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
.........................#........................
'''

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[23, 25], [27, 25]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[24, 24], [25, 24], [26, 24], [24, 25], [26, 25], [25, 26]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[25, 25]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[25, 20], [18, 23], [20, 24], [20, 25], [18, 26], [19, 26]]
