gravity = 100
temperature = 20

terrain = '''
................................^^^^^^^^^^^^^^^^^^
..................^^^...........^^^^^^^^^^^^^^^^^^
................^^^^^^.........^^^^^^^^^^^^^^^^^^^
...............^^^^^^^^.......^^^^^^^^^^^^^^^^^^^^
...............^^^^^^^^......^^^^^^^^^^^^^^^^^^^^^
...............^^^^^^^^^.....^^^^^^^^^^^^^^^^^^^^^
...............^^^^^^^^^......^^^^^^^^^^.^^^^^.^^^
.................^^^^^.......^^^^^^^^^^...^^.....^
.................^^^^^.......^^^^^^^^^^...^^.....^
....~.........................^^^^^^^^....^^.....^
..............................^^^^^^^^....^^^...^^
..............................^^^^^^^.....^^^^^.^^
...............................^^^^^..^...^^^^^^^^
...............................^^^..^^^^~~^^^^^^^^
..................................^^^^~~^^^^^^^^^^
..............................~~~~~~~~^^^^^^^^^^^^
~.........~~~..~~.......~~~~~~~~~~.~..^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~.~.~~~~~~~~~~......^^^^^^^^^^^^
~~~~~~~~~~...~~~.~~~~~~~...~.~.........^^^^^^^^^^^
~~~~~..............~.~.................^.^^^^^^^^^
~~~~.......................................^^^^^^^
...............................................^..
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................%...............................
..................................................
..................................................
%.%.%.%.........%.................................
^%^%^%%%%.............%...........................
...^...^^%........%............%............~.....
..........%%%...............~..............~......
...........^%.......%......~~~............~.......
...........^%...%.%........~............~~~.......
............^%..%...%...%.....%..........~~...~...
.............%%..........................~~~~.~...
.............^%...%................%.........~....
..............^.......%.................~...~.....
...............%..%....................~~...~.....
...............^%..%....%..%..........~..~........
...............^%.....................~~..........
..................%%...........%...%...~..........
...................%.%...%.%......................
.................%..%.............................
................%.%.%%.%..........................
'''
level = '''
11001111000000000000000000000000122234445566555655
11001121000000000021100000000000122334446566656555
00101121100000001132210000000001123343445455666666
01101122100000011243421000000012233432445566767666
01000111100000011245431000000112222333444677777786
10000001001000012334331100000112224443545677878787
00000000001100011212111100000022224444650678885877
00000000000000000212110000000112234444650088555558
10000000000011100111110000000122234444455685555558
10000000000012100000000000000012122444050086555558
10000000000001100110010001101011112334050077655568
00000000000000000000000001000010222224455668866588
00000000000000000000111110011001122222250056888767
10000000000000000010122110011001121222240035556666
10000000000000000010011100000000011112004434456665
10000000000000000000000000100000000000122434455555
00000000000000000000110000000000000000122223344534
00000000000000000001010000000000000000112223222333
00000000000000000000000000000000000000012222222223
00000000000000000000000000000000000000010112222212
00000000000000000000000000000000001000000001111111
11000000000000000000000000000000011100000000000100
11000000000000000000000000000000011111100000000000
00000000000000000000000000000000001210100000000011
00000010000001100000000000000000010110110000111101
00000111000001000000000000000000000111000000122111
01100111101110000000000000000000000110000000121110
01100112111110000000000000000000000000000000011110
01000111111100000000100000000010100010101000101110
00000000011000000010111000000001110001210011111000
00000000000000000011211000000011111001211121112100
10102110000000000001311011000001112111221121122110
11232121000000000012102000001000111111121121212110
22222222332100000001210001001110000100011121122110
32334332223230000001310000002110111010101121112100
76859684524222100201012111111111112110111111011000
98899889854222100110101120110111122100121110111000
98998888767442101121211310100012111010111102212100
99999887888422201111000111101101112110010001221001
99999999999842311011000010310000011110111001210111
99999999899973422000001012112000011111121000010112
89899998888994423000112001000000211211111111101111
78889999988887432110013100000011112221110121012221
78999999999889743210111100000011111212100121012232
88989999999989745221002102010012111111011011122232
89899989988988845332100001111111011011001121212333
99999888889889876422211000131111112101101211222333
98989999999899986552221001211012121111211211212332
99999999999999886545421000010000011111111211122233
99998889998998887555532100000000010001111122121334
'''
depth = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....0.............................................
..................................................
..................................................
..................................................
........................................46........
......................................33..........
..............................11112123............
0.........111..11.......1111112212.1..............
0000112121121211111.1.1122111111..................
0000111111...111.2121212...1.1....................
00000..............1.1............................
0000..............................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
............................................0.....
............................1..............0......
...........................110............1.......
...........................1............011.......
.........................................12...0...
.........................................1111.0...
.............................................1....
........................................1...0.....
.......................................01...0.....
......................................1..0........
......................................21..........
.......................................1..........
..................................................
..................................................
..................................................
'''
foliage = '''
.........````""````````.......``..................
.........```""""``...````...````..................
.........```""``......`````````...................
..........`````........```"```....................
...........````........``"""`.....................
............```.........`"""`.....................
........................`"`"``....................
......................```````.....................
....`.................````.`......................
.........`.............`..........................
....`....`........................................
.........`........................................
...`".............................................
...`"`........`.`.................................
...```..`.........................................
.....```..``......................................
........``........................................
..................................................
............`.....................................
.....`````.......``.`...................`.........
.....`""`........`.`..................`````.......
.....```..............................`````````.``
.......`.............................```"""""`````
.....................................```"""""""`""
.....................................````"`"""""""
.....................................````````"""""
.......................................`.`````""""
...........................................````"`"
...........................................```````
.............................................`.```
....................................```...........
....................................```...........
...................................`"""`..........
...................................`"""`..........
...................................`""``..`.......
..........................```......```...`"`......
..........................``........``...``.``....
..........................`.............``.`"``...
...........................................`""`...
........................................`..``"....
..........`.............................`....`....
........`````...........................`"""`.`...
........`````.........................``.""".`....
........``"``............................""".`..``
........``"```.........................`".``...```
......````""``.......................`..""``...```
......``""""``.......................``.``....````
....```"""""```...............................````
....``"""""""``.............................``````
....``"""""""``.............................``````
'''
route = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.......................................#..........
.......................................###........
.......................................#..........
.......................................#..........
.....................................#####........
....................................##.#..........
........###....#..................##..............
...........##..#................##................
.............###..................................
..................................................
..................................................
........................##........................
..........###..#......##..........................
.........#..#.###...##............................
.........#..##...###..............................
.........###......##..............................
..................#...............................
.................#................................
................##................................
................#.................................
...............#..................................
..............##..................................
..............#...................................
.............#....................................
............##....................................
............#.....................................
...........#......................................
..........##......................................
..........#.......................................
.........#........................................
........##........................................
........#.........................................
.......#..........................................
......##..........................................
......#...........................................
.....#............................................
....##............................................
....#.............................................
...#..............................................
..##..............................................
..#...............................................
.#................................................
##................................................
'''
condition = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.........................................-........
..................................................
................................-.................
............-.....................................
-..-...-....-.....-..........-....................
..-......-........................................
...--................-............................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.......................................-..........
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 0
hexes = [[24, 24], [26, 24], [25, 25], [25, 26]]

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[6, 8], [9, 12], [14, 12], [16, 12], [12, 13], [14, 14], [16, 14], [12, 15], [16, 15], [10, 18], [11, 18], [14, 19], [16, 19], [18, 20], [15, 21], [8, 22], [13, 22], [17, 22], [10, 23], [11, 23], [17, 23]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[5, 8], [6, 9], [7, 9], [5, 11], [6, 11], [7, 12], [15, 12], [6, 13], [6, 14], [7, 14], [13, 14], [13, 16], [16, 18], [11, 20], [13, 20], [8, 21], [11, 21], [14, 21]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[5, 9], [5, 10], [7, 10], [7, 11], [14, 16], [13, 19], [10, 21]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[6, 10], [10, 20], [22, 23], [28, 23], [25, 28]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[38, 9], [38, 10]]

[[structures]]
kind = "building"
class = "medium"
height = 6
hexes = [[40, 6], [40, 7], [40, 9], [41, 9], [40, 10], [40, 12], [25, 23], [23, 26], [27, 26]]

[[structures]]
kind = "building"
class = "medium"
height = 7
hexes = [[41, 7], [41, 10], [41, 12]]

[[structures]]
kind = "wall"
class = "medium"
height = 1
hexes = [[4, 6], [5, 6], [6, 6], [2, 7], [3, 7], [7, 7], [8, 7], [2, 8], [9, 8], [10, 8], [2, 9], [10, 9], [2, 10], [10, 10], [2, 11], [10, 11], [2, 12], [10, 12], [2, 13], [2, 14], [10, 14], [3, 15], [4, 15], [8, 15], [9, 15], [5, 16], [6, 16], [7, 16]]

[[structures]]
kind = "wall"
class = "medium"
height = 2
hexes = [[24, 21], [26, 21], [22, 22], [23, 22], [24, 22], [25, 22], [26, 22], [27, 22], [28, 22], [23, 23], [24, 23], [26, 23], [27, 23], [21, 24], [22, 24], [23, 24], [27, 24], [28, 24], [29, 24], [21, 25], [22, 25], [23, 25], [27, 25], [28, 25], [29, 25], [21, 26], [22, 26], [24, 26], [26, 26], [28, 26], [29, 26], [22, 27], [23, 27], [24, 27], [25, 27], [26, 27], [27, 27], [28, 27], [23, 28], [24, 28], [26, 28], [27, 28]]

[[structures]]
kind = "bridge"
class = "medium"
height = 0
hexes = [[30, 15], [31, 15], [15, 16], [28, 16], [29, 16], [15, 17], [26, 17], [27, 17], [15, 18]]
