gravity = 100
temperature = 20

terrain = '''
..................................................
..................................................
..................................................
.......................................~~~~~~.....
........................................~~~~~~~...
........................................~~~~~~~...
........................................~~~~~~~...
.........................................~~~~~~...
.........................................~~~~~~...
...........................................~~~~...
...........................................~~~~...
..............................^.%...%%......~~~...
...........................%^^^^^.^..........~~...
........................^.^.^^^^^%^%^..%......~...
......................^^^^^^^^^^^^^^^.............
......................^^^^^^^^^^^^^^%..%..........
......................^^^^^^....%^^^^^^%..........
.......................^^^^.......^^^^^%%.........
....................^....^^.....%.^^^^%..%%.......
....................^^^............^^^....%%......
..............%...^^^^^^^.........^^^^%%...%......
.........%%...%.%.^^^^^^^..........^^^^.%.%%......
.....%..%........%%^^^^^^..........^^^^^^....%....
.......%%........%^^^^.^%...........^^^^^^...%....
.......%.%.%...^^%^^^..............%.^^^^^%..%....
....%.........%^%^^^^................^^^^^%^%%....
....%%....%%.%^^%^^^^^..%..............^^^^^....%.
..%..%%%%..^^^^^%^^^^^^.................^^^^....%.
.%%%..%.^%^^%^^^^^^^^^^^%.^....%.........^^.....%.
....%...^^^^^^^^^^^^^^^^^^^^^%....................
...%..^^^^^^^^^^^^^^^^^^^^^^^^^.....%.............
..%%.^^^^^^^^^^^^^^^^^^^^^^^^^^^.^^..^^^^^^.......
.%%..^^^^^^^^^^^^^^^^^^^^^^^^^^...^^^^^^^^^%......
%%.%..^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^%^^%......
.%%...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^%^^^^%...%..
%.....^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^..^........
%..%...^^^^^^^^^^^^^^^^^^^^^^^^%^^^^^%.....%....%.
.%%.%%..^^^^^^^^^^^^^^^^^^^^^^^%^^^^%^.....%......
....%......^^^^^^^^^^^^^^^^^^^^^^^^^^...........%.
....%.%.......^^^^^^^^^^^^^^^^^^^................%
.%..%.%...%.%..^^^^^^^..%%.^^..^^.%..............%
.%...%%..%......^^^^^........%....%%%......%.....%
..%..%%.%.....%...^^.....%%%......%%%............%
...%...%..........^^^.%%.......%%%%%.............%
....%%.%%.^^..%...^^^.%.......%%%%%...............
.....%....^^......^^^^^......%%%%%................
......%.....^^^^^^^^^^^....%%%................%...
.%.%%%%.....^^^^^^^^^^^^.%%%%................%%..^
............^^^^^^^^^^^...%%%%.............%..^^^^
............^^^^^^^......%...........%%..%.^^^^^^^
'''
level = '''
43333333333333334455664333344433322221100000000000
33333333333333333455554433344433322211100000000000
33133333233333133445555444344443222221000000000000
33334300000000033314455544444332322221000000000000
33333303333333033333455545443332222221100000000000
43333303033403033433455644433332222211100000000000
33322203000003033334455553443333222211000000000000
33222203000004033341555556643334222111000000000000
32322203004004033346555555543333222111110000000000
22122203334233033334553555443333322231111000000000
22222303003003043334555555444433322222222100000000
22221203003003033345555555444433333222222210000000
22222303334443033345555554444533333333322221000000
22222303300544333334555443554553333333322221100000
22222303400303333334455443555455533333322222100011
22233330003033334334444455534444655533322222111112
33333343333333333334444454440443333553332222222222
33333333333333333335444444404444333353332222222223
34334333334333333335554444404444433453432232223332
34443333334444333345554444444454443633332223223333
33333433334444444455555444444445444553332222223333
34334443333454455555555554544456540453332222233333
33445443343455555566655565666445540444353332333333
33444444344555555566670766065555445044435333333443
55444444455555566677707776665555444444333444333443
44444455555555677888807070665455444446364544444444
44444555555556878899977766065444454444444554045544
44445555555667888999978666665444444444455555045543
44445655766778888999999775867445544445555650554443
44445555677898999999998997887655554455555556554443
44556566778899999989987887887665565565000455455444
56555666788898998768885898887776576556666665555544
55555666788888897658767678888870006667777765555555
55555566777887888787888888888877666666777765545555
55555566667888899888999989889897777666666665545555
45555566666788999999999887789888877767655655555555
44555556666788999999999877798888887766555555545555
44455555666678899999998876677778877766555565555655
44444465555677789999988776666677766665550505455555
43344445555555677989776666666677655555555050555655
33334445555555566776665555566556655555555545550555
33344555565555556666655655555655555555500505550555
33454455555555555566565555655445555454400400550655
44444565565555555566655555554333333445400334000555
54444455556755555566755554444433333333033300000555
44544455556665555566666564444333333333003030005565
44444445555566666666776555454333333333434340555555
33333355555566666666776656555445333333300555555556
33333335555566666666666555555554445433305555556668
33333334555566666665555555555656555444455556666677
'''
depth = '''
..................................................
..................................................
..................................................
.......................................111111.....
........................................1222211...
........................................1223321...
........................................1223321...
.........................................123321...
.........................................112221...
...........................................1221...
...........................................1121...
............................................121...
.............................................11...
..............................................1...
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
foliage = '''
""........".......................................
".".."."``.`".````````....................```.....
""".........."."......```...............``""".....
.""""............""...``.".```""..................
.""".`...........""...``."`.`""..."...............
.""..............".`.``````"`"`"".""..............
`"..`............"."`````."``"``..................
`"`..............."""``...""`.`.`...............`.
."`.`.............`"."`..".```...`............."`.
.`"`.`.............`..`""........`............."`.
.``................`...`..``...................`..
.`"`................``.".`........................
.```.`............................................
.```..............................................
.".`..............................................
.`"`..............................................
.``".`............................................
```"``.``.........................................
..`"`.`...........................................
.""`".."`.........................................
".................................................
."................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''
route = '''
.................................................#
.................................................#
................................................##
................................................#.
................................................#.
...............................................#..
..................................................
..................................................
..........#.......................................
..........#.......................................
..........#.......................................
..........#.......................................
.........####.....................................
...........####...................................
.............####.................................
...............####...............................
.................####.............................
...................####...........................
.....................####.........................
.......................###........................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.......................................##.........
.......................................####.......
.........................................####.....
...........................................###....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
............................................##....
..........................................##......
........................................##........
........................................#.........
......................................##..........
....................................##............
..................................##..............
................................##................
'''
condition = '''
..................................................
..................................................
..................................................
..................................................
..................................................
.........................................-........
..................................................
..................................................
.........................................-..-.....
..................................................
..................................................
..............................................-...
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
'''

[[structures]]
kind = "building"
class = "medium"
height = 1
hexes = [[46, 2], [48, 5], [48, 6]]

[[structures]]
kind = "building"
class = "medium"
height = 2
hexes = [[45, 2], [45, 3], [47, 3], [47, 4], [47, 6], [47, 7]]

[[structures]]
kind = "building"
class = "medium"
height = 3
hexes = [[46, 3]]

[[structures]]
kind = "building"
class = "medium"
height = 4
hexes = [[40, 43], [39, 45]]

[[structures]]
kind = "building"
class = "medium"
height = 5
hexes = [[8, 5], [12, 5], [8, 6], [12, 6], [8, 7], [10, 7], [12, 7], [8, 8], [12, 8], [8, 10], [9, 10], [11, 10], [12, 10], [8, 11], [9, 11], [11, 11], [12, 11], [9, 13], [26, 23], [26, 26], [40, 42], [39, 43], [38, 44], [38, 45], [41, 45], [39, 47]]

[[structures]]
kind = "building"
class = "medium"
height = 6
hexes = [[9, 6], [11, 6], [9, 7], [11, 7], [9, 8], [11, 8], [10, 13], [9, 14], [28, 16], [27, 18], [34, 21], [35, 23], [23, 25], [25, 25], [46, 40], [46, 41], [46, 42], [46, 43], [42, 44], [46, 44], [40, 47], [39, 48]]

[[structures]]
kind = "building"
class = "medium"
height = 7
hexes = [[10, 6], [27, 17], [34, 22], [44, 26], [43, 28], [39, 41], [40, 41], [42, 41], [39, 42], [42, 42], [43, 42], [44, 43], [45, 43], [43, 44], [44, 44], [45, 44], [43, 45], [44, 45], [45, 45], [43, 46]]

[[structures]]
kind = "building"
class = "medium"
height = 8
hexes = [[22, 23], [21, 25], [44, 27], [38, 30], [40, 30], [31, 32], [33, 32], [40, 38], [42, 38], [41, 39], [43, 39]]

[[structures]]
kind = "building"
class = "medium"
height = 9
hexes = [[21, 24], [39, 30], [32, 32]]

[[structures]]
kind = "wall"
class = "medium"
height = 5
hexes = [[6, 3], [7, 3], [8, 3], [9, 3], [10, 3], [11, 3], [12, 3], [13, 3], [14, 3], [6, 4], [14, 4], [6, 5], [14, 5], [6, 6], [14, 6], [6, 7], [14, 7], [6, 8], [14, 8], [6, 9], [14, 9], [6, 10], [14, 10], [6, 11], [14, 11], [6, 12], [14, 12], [6, 13], [6, 14], [10, 14], [12, 14], [7, 15], [8, 15], [9, 15], [11, 15]]
