#include "contracts.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include <string>
#include <string_view>
#include <tuple>
#include <utility>
#include <vector>

#include "llvm/ADT/SmallString.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace lua_types {
namespace {

constexpr std::string_view GENERATED_HEADER =
    "---@meta _\n\n"
    "---Generated by `lua-type-generator` from LuaLS contracts in native C.\n"
    "---Do not edit; run `just update-lua-types`.";

const std::map<std::string, int> SECTION_RANK = {
    {"alias", 0},     {"type", 1},     {"catalog", 2},
    {"namespace", 3}, {"callable", 4}, {"binding", 5},
};

std::string read_file(const std::filesystem::path &path, bool &exists) {
  std::ifstream input(path, std::ios::binary);
  exists = input.good();
  if (!exists)
    return {};
  return std::string(std::istreambuf_iterator<char>(input),
                     std::istreambuf_iterator<char>());
}

} // namespace

std::map<std::string, std::string> render_modules(Model &model) {
  std::map<std::string, std::vector<const Contract *>> by_module;
  for (const Contract &contract : model.contracts)
    by_module[contract.module].push_back(&contract);

  std::map<std::string, std::string> outputs;
  const std::vector<std::string> modules = {"mux", "btech"};
  for (const std::string &module : modules) {
    std::vector<const Contract *> &contracts = by_module[module];
    std::sort(contracts.begin(), contracts.end(),
              [](const Contract *left, const Contract *right) {
                return std::tuple(SECTION_RANK.at(left->section), left->key) <
                       std::tuple(SECTION_RANK.at(right->section), right->key);
              });
    std::string output(GENERATED_HEADER);
    for (const Contract *contract : contracts) {
      output += "\n\n";
      output += contract->payload;
    }
    output += "\n\nreturn ";
    output += module;
    output += '\n';
    outputs[module] = std::move(output);
  }
  return outputs;
}

bool check_outputs(Model &model,
                   const std::map<std::string, std::string> &outputs,
                   const std::filesystem::path &output_directory) {
  bool clean = true;
  for (const auto &[module, expected] : outputs) {
    const std::filesystem::path path = output_directory / (module + ".d.lua");
    bool exists = false;
    const std::string actual = read_file(path, exists);
    if (exists && actual == expected)
      continue;
    clean = false;
    model.diagnose({.path = path.string(), .line = 1, .column = 1},
                   "generated Lua type file is stale; run `just "
                   "update-lua-types`");
  }
  return clean;
}

bool write_outputs(Model &model,
                   const std::map<std::string, std::string> &outputs,
                   const std::filesystem::path &output_directory) {
  std::error_code directory_error;
  std::filesystem::create_directories(output_directory, directory_error);
  if (directory_error) {
    model.diagnose({.path = output_directory.string(), .line = 1, .column = 1},
                   "cannot create output directory: " +
                       directory_error.message());
    return false;
  }

  struct PendingWrite {
    std::filesystem::path destination;
    llvm::SmallString<256> temporary;
  };
  std::vector<PendingWrite> pending;
  for (const auto &[module, expected] : outputs) {
    const std::filesystem::path path = output_directory / (module + ".d.lua");
    bool exists = false;
    if (read_file(path, exists) == expected && exists)
      continue;
    int descriptor = -1;
    llvm::SmallString<256> temporary;
    const std::string pattern = path.string() + ".tmp-%%%%%%";
    if (const std::error_code error =
            llvm::sys::fs::createUniqueFile(pattern, descriptor, temporary)) {
      for (const PendingWrite &cleanup : pending)
        llvm::sys::fs::remove(cleanup.temporary);
      model.diagnose({.path = path.string(), .line = 1, .column = 1},
                     "cannot create temporary output: " + error.message());
      return false;
    }
    llvm::raw_fd_ostream stream(descriptor, true);
    stream << expected;
    stream.close();
    if (stream.has_error()) {
      llvm::sys::fs::remove(temporary);
      for (const PendingWrite &cleanup : pending)
        llvm::sys::fs::remove(cleanup.temporary);
      model.diagnose({.path = path.string(), .line = 1, .column = 1},
                     "cannot write temporary output");
      return false;
    }
    std::error_code status_error;
    std::filesystem::perms permissions = std::filesystem::perms::owner_read |
                                         std::filesystem::perms::owner_write |
                                         std::filesystem::perms::group_read |
                                         std::filesystem::perms::others_read;
    if (exists)
      permissions = std::filesystem::status(path, status_error).permissions();
    if (!status_error)
      std::filesystem::permissions(
          std::filesystem::path(temporary.c_str()), permissions,
          std::filesystem::perm_options::replace, status_error);
    if (status_error) {
      llvm::sys::fs::remove(temporary);
      for (const PendingWrite &cleanup : pending)
        llvm::sys::fs::remove(cleanup.temporary);
      model.diagnose({.path = path.string(), .line = 1, .column = 1},
                     "cannot set output permissions: " +
                         status_error.message());
      return false;
    }
    pending.push_back({.destination = path, .temporary = temporary});
  }
  for (const PendingWrite &write : pending) {
    if (const std::error_code error = llvm::sys::fs::rename(
            write.temporary, write.destination.string())) {
      model.diagnose(
          {.path = write.destination.string(), .line = 1, .column = 1},
          "cannot replace generated output: " + error.message());
      for (const PendingWrite &cleanup : pending)
        llvm::sys::fs::remove(cleanup.temporary);
      return false;
    }
  }
  return true;
}

void print_diagnostics(Model &model) {
  std::sort(model.diagnostics.begin(), model.diagnostics.end(),
            [](const Diagnostic &left, const Diagnostic &right) {
              return left.tie() < right.tie();
            });
  for (const Diagnostic &diagnostic : model.diagnostics) {
    llvm::errs() << diagnostic.location.path << ':' << diagnostic.location.line
                 << ':' << diagnostic.location.column << ": "
                 << diagnostic.message << '\n';
  }
}

} // namespace lua_types
