#!/bin/sh
#
#	Startmux - Kick off the netmux process.
#
export LD_LIBRARY_PATH=/usr/local/lib
PATH=/usr/ucb:/bin:/usr/bin:.; export PATH
#
. mux.config
#
#	Make sure there isn't aready a MUX running.
#

#nmux=`ps -C netmux l | egrep "netmux netmux.conf"`
numx=`ps ax | sed -e '/grep/d' | grep "netmux netmux.conf"`
if [ "$?" -ne 1 ]; then
    echo "Another copy of netmux is running"
    echo "Check ps ax"
	exit 0
fi

#
#	Make sure the indexes are up-to-date.
#
if [ -x $BIN/mkindx ]; then
	MKINDX=$BIN/mkindx
else
	echo "No mkindx. Did you forget to make install?"
	exit 1
fi

$MKINDX $TEXT/help.txt $TEXT/help.indx
$MKINDX $TEXT/wizhelp.txt $TEXT/wizhelp.indx

#
#	Kick off MUX
#
ulimit -c unlimited
if [ -x $BIN/netmux ]; then
	echo Starting netmux binary.
	$BIN/netmux $GAMENAME.conf
else
	echo No binary found!
	exit 1
fi
	
