#!/usr/bin/env bash
# Start the stompymux game server for this workspace.
#
# Each workspace gets its own listen port so several workspaces (and the root
# checkout, which keeps the stock 5555) can run the game at the same time.
# Override with STOMPYMUX_PORT=1234 if you want a specific one.
set -euo pipefail

workspace="${SUPERSET_WORKSPACE_PATH:-$PWD}"
cd "$workspace"

if [[ ! -x game/stompymux ]]; then
  echo "game/stompymux is missing; building it first" >&2
  just build install
fi

port="${STOMPYMUX_PORT:-}"
if [[ -z "$port" ]]; then
  name="${SUPERSET_WORKSPACE_NAME:-}"
  if [[ -z "$name" ]]; then
    port=5555
  else
    # Deterministic per-workspace port in the 15000-24999 range.
    hash=$(printf '%s' "$name" | cksum | cut -d' ' -f1)
    port=$((15000 + hash % 10000))
  fi
fi

# stompymux resolves relative includes against the including file's directory,
# and a file's own keys beat anything it pulls in - so this thin overlay reuses
# the checked-in configuration and only replaces the port. It is gitignored.
config=stompymux.local.toml
cat >"game/$config" <<EOF
# Generated by .superset/run.sh - do not edit, do not commit.
include = ["stompymux.toml"]

[server]
port = $port
EOF

echo "==> Starting stompymux on port $port (connect with: telnet localhost $port)"
mkdir -p game/logs
cd game
ulimit -c unlimited
echo $$ >logs/superset-run.pid
exec ./stompymux "$config"
