set(MUX_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

target_sources(stompymux PRIVATE
  ${MUX_MODULE_DIR}/commands/command.c
  ${MUX_MODULE_DIR}/commands/command_context.c
  ${MUX_MODULE_DIR}/commands/command_helpers.c
  ${MUX_MODULE_DIR}/commands/command_invocation.c
  ${MUX_MODULE_DIR}/commands/command_queue.c
  ${MUX_MODULE_DIR}/commands/builder_commands.c
  ${MUX_MODULE_DIR}/commands/command_parser.c
  ${MUX_MODULE_DIR}/commands/macro.c
  ${MUX_MODULE_DIR}/commands/verbs.c
  ${MUX_MODULE_DIR}/communication/commac.c
  ${MUX_MODULE_DIR}/communication/channel_registry.c
  ${MUX_MODULE_DIR}/communication/comsys_context.c
  ${MUX_MODULE_DIR}/communication/comsys.c
  ${MUX_MODULE_DIR}/communication/speech.c
  ${MUX_MODULE_DIR}/objects/db.c
  ${MUX_MODULE_DIR}/objects/flags.c
  ${MUX_MODULE_DIR}/objects/power_fields.c
  ${MUX_MODULE_DIR}/objects/powers.c
  ${MUX_MODULE_DIR}/help/help_command.c
  ${MUX_MODULE_DIR}/help/help_frontmatter.c
  ${MUX_MODULE_DIR}/help/help_index.c
  ${MUX_MODULE_DIR}/help/help_render.c
  ${MUX_MODULE_DIR}/lua/lua.c
  ${MUX_MODULE_DIR}/lua/btech_package.c
  ${MUX_MODULE_DIR}/lua/mux_package.c
  ${MUX_MODULE_DIR}/network/connect_flow.c
  ${MUX_MODULE_DIR}/network/descriptor.c
  ${MUX_MODULE_DIR}/network/input_flow.c
  ${MUX_MODULE_DIR}/network/mux_event.c
  ${MUX_MODULE_DIR}/network/netcommon.c
  ${MUX_MODULE_DIR}/network/telnet_handler.c
  ${MUX_MODULE_DIR}/network/telnet_socket.c
  ${MUX_MODULE_DIR}/persistence/commac_persistence_sqlite.c
  ${MUX_MODULE_DIR}/persistence/gamedb_sqlite.c
  ${MUX_MODULE_DIR}/persistence/persistence_registry.c
  ${MUX_MODULE_DIR}/server/configuration.c
  ${MUX_MODULE_DIR}/server/configuration_toml.c
  ${MUX_MODULE_DIR}/server/diagnostics.c
  ${MUX_MODULE_DIR}/server/file_cache.c
  ${MUX_MODULE_DIR}/server/game.c
  ${MUX_MODULE_DIR}/server/log.c
  ${MUX_MODULE_DIR}/server/maintenance.c
  ${MUX_MODULE_DIR}/server/mux_server.c
  ${MUX_MODULE_DIR}/server/server_lifecycle.c
  ${MUX_MODULE_DIR}/server/event_timer.c
  ${MUX_MODULE_DIR}/server/server_registries.c
  ${MUX_MODULE_DIR}/server/signals.c
  ${MUX_MODULE_DIR}/server/timer.c
  ${MUX_MODULE_DIR}/server/version.c
  ${MUX_MODULE_DIR}/support/doubly_linked_list.c
  ${MUX_MODULE_DIR}/support/fifo.c
  ${MUX_MODULE_DIR}/support/formatting.c
  ${MUX_MODULE_DIR}/support/name_table.c
  ${MUX_MODULE_DIR}/support/numeric_hash_table.c
  ${MUX_MODULE_DIR}/support/hash_table.c
  ${MUX_MODULE_DIR}/support/red_black_tree.c
  ${MUX_MODULE_DIR}/support/password.c
  ${MUX_MODULE_DIR}/support/stringutil.c
  ${MUX_MODULE_DIR}/support/validation.c
  ${MUX_MODULE_DIR}/support/wild.c
  ${MUX_MODULE_DIR}/commands/look.c
  ${MUX_MODULE_DIR}/world/match.c
  ${MUX_MODULE_DIR}/world/move.c
  ${MUX_MODULE_DIR}/world/object.c
  ${MUX_MODULE_DIR}/world/object_list.c
  ${MUX_MODULE_DIR}/world/player.c
  ${MUX_MODULE_DIR}/world/player_cache.c
  ${MUX_MODULE_DIR}/world/access.c
  ${MUX_MODULE_DIR}/world/match_helpers.c
  ${MUX_MODULE_DIR}/world/object_spatial.c
  ${MUX_MODULE_DIR}/commands/rob.c
  ${MUX_MODULE_DIR}/world/object_set.c
  ${MUX_MODULE_DIR}/world/walkdb.c
  ${MUX_MODULE_DIR}/commands/wiz.c)

if(BTECH_ENHANCED_LOGGING)
  target_sources(stompymux PRIVATE ${MUX_MODULE_DIR}/server/log_cache.c)
endif()
