baseURL = 'https://stompymux.com/'
locale = 'en-us'
title = 'StompyMUX Documentation'
description = 'Documentation for the StompyMUX game server.'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[[menu.main]]
  name = 'Documentation'
  url = '/docs/'
  weight = 10

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.164.0"
  [[module.imports]]
    path = "github.com/google/docsy/theme"

[params]
  github_repo = "https://github.com/gtaylor/stompymux"
  github_subdir = "docs"

[params.ui]
  sidebar_menu_compact = true
  sidebar_search_disable = false
  showLightDarkModeMenu = true
  sidebar_menu_foldable = true
  sidebar_root_enabled = true
