/** @file
 * Stable error codes raised by C-exposed Lua APIs.
 */
#pragma once

typedef enum LuaErrorCode : int {
  LUA_ERROR_CODE_ARG_INVALID,
  LUA_ERROR_CODE_CHECKING_UNAVAILABLE,
  LUA_ERROR_CODE_RUNTIME,
  LUA_ERROR_CODE_STATE_INVALID,
  LUA_ERROR_CODE_STATE_VALUE_TOO_LARGE,
  LUA_ERROR_CODE_STATE_UNAVAILABLE,
  LUA_ERROR_CODE_OBJECT_INVALID,
  LUA_ERROR_CODE_OBJECT_UNAVAILABLE,
  LUA_ERROR_CODE_ATTRIBUTE_INVALID,
  LUA_ERROR_CODE_FLAG_INVALID,
  LUA_ERROR_CODE_POWER_INVALID,
  LUA_ERROR_CODE_CONNECTION_INVALID,
  LUA_ERROR_CODE_CONNECTION_UNAVAILABLE,
  LUA_ERROR_CODE_TEXT_INVALID,
  LUA_ERROR_CODE_MODULE_INVALID,
  LUA_ERROR_CODE_MODULE_UNAVAILABLE,
  LUA_ERROR_CODE_CONFIG_NOT_FOUND,
  LUA_ERROR_CODE_CONFIG_UNSUPPORTED,
  LUA_ERROR_CODE_BTECH_UNAVAILABLE,
  LUA_ERROR_CODE_BTECH_FAILED,
  LUA_ERROR_CODE_TESTING_ASSERTION,
  LUA_ERROR_CODE_TESTING_RUNTIME,
  LUA_ERROR_CODE_INTERNAL,
  LUA_ERROR_CODE_COUNT,
} LuaErrorCode;

extern const char *const LUA_ERROR_CODE_NAMES[LUA_ERROR_CODE_COUNT];
