name = "Anubis"
class = "mech"
movement = "biped"
tons = 30
max_speed = 129.0
heat_sinks = 24
computer = 4
radio = 4
specials = ["DoubleHS", "StealthArmor_Tech", "EndoSteel_Tech", "XLEngine_Tech", "ECM"]

[sections.left_arm]
armor = 8
internals = 5
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = 5, item = "IS.ERSmallLaser" },
    { at = "6-7", item = "StealthArmor" },
    { at = "8-11", item = "EndoSteel" },
]

[sections.right_arm]
armor = 8
internals = 5
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-4", item = "IS.ERLargeLaser" },
    { at = 5, item = "IS.ERMediumLaser" },
    { at = "6-7", item = "StealthArmor" },
    { at = "8-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 9
internals = 7
rear = 3
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "HeatSink" },
    { at = "7-8", item = "StealthArmor" },
    { at = "9-11", item = "EndoSteel" },
]

[sections.right_torso]
armor = 9
internals = 7
rear = 3
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-9", item = "HeatSink" },
    { at = "10-11", item = "StealthArmor" },
    { at = 12, item = "EndoSteel" },
]

[sections.center_torso]
armor = 11
internals = 10
rear = 4
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "Ecm" },
]

[sections.left_leg]
armor = 12
internals = 7
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "StealthArmor" },
]

[sections.right_leg]
armor = 12
internals = 7
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "StealthArmor" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "EndoSteel" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
