name = "Arctic Fox"
class = "mech"
movement = "biped"
tons = 30
max_speed = 96.75
heat_sinks = 20
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 10
internals = 5
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-6", item = "EndoSteel" },
    { at = "7-12", item = "IS.LB10-XAC" },
]

[sections.right_arm]
armor = 10
internals = 5
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-8", item = "EndoSteel" },
]

[sections.left_torso]
armor = 11
internals = 7
rear = 3
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "HeatSink" },
    { at = 8, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 9, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
]

[sections.right_torso]
armor = 11
internals = 7
rear = 3
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-9", item = "HeatSink" },
    { at = 10, item = "IS.MediumLaser" },
]

[sections.center_torso]
armor = 15
internals = 10
rear = 4
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.left_leg]
armor = 10
internals = 7
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 10
internals = 7
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
