name = "Alacorn"
class = "vehicle"
movement = "track"
tons = 95
walk_mp = 5
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 0
specials = ["SearchLight"]

[construction]
engine = "xl"

[sections.left_side]
armor = 75

[sections.right_side]
armor = 75

[sections.front_side]
armor = 112
slots = [
    { at = "1-2", item = "IS.HeavyGaussRifle", brand = 3 },
    { at = "3-7", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
    { at = "9-12", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]

[sections.aft_side]
armor = 50
slots = [
    { at = "1-3", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]
