name = "Fireball"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 17
computer = 4
radio = 4

[construction]
engine = "xl"
structure = "endo_steel"
brand = 3

[sections.left_arm]
armor = 5
slots = [
    { at = 5, item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 5
slots = [
    { at = 5, item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 8
rear = 2
slots = [
    { at = 4, item = "IS.StreakSRM-2", brand = 3 },
    { at = 5, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
    { at = "6-9", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 8
rear = 2
slots = [
    { at = 4, item = "IS.MachineGun", brand = 3 },
    { at = 5, item = "Ammo_IS.MachineGun", rounds = 200 },
    { at = "6-9", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 9
rear = 2
slots = [
    { at = "11-12", item = "EndoSteel", brand = 3 },
]

[sections.left_leg]
armor = 7
slots = [
    { at = 5, item = "HeatSink", brand = 3 },
    { at = 6, item = "EndoSteel", brand = 3 },
]

[sections.right_leg]
armor = 7
slots = [
    { at = 5, item = "HeatSink", brand = 3 },
    { at = 6, item = "EndoSteel", brand = 3 },
]

[sections.head]
armor = 9
