name = "Archer"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
heat_sinks = 20
computer = 4
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 22
slots = [
    { at = 5, item = "IS.SRM-4", modes = ["Narc/Smoke"] },
    { at = 6, item = "Ammo_IS.SRM-4", rounds = 25, modes = ["Narc/Smoke"] },
]

[sections.right_arm]
armor = 22
slots = [
    { at = 5, item = "IS.SRM-4", modes = ["Narc/Smoke"] },
    { at = 6, item = "Ammo_IS.SRM-4", rounds = 25, modes = ["Narc/Smoke"] },
]

[sections.left_torso]
armor = 24
rear = 6
slots = [
    { at = 4, item = "IS.LRM-20", modes = ["Narc/Smoke"] },
    { at = "5-8", item = "IS.LRM-20" },
    { at = 9, item = "Ammo_IS.NarcBeacon", rounds = 6 },
    { at = "10-11", item = "Ammo_IS.LRM-20", rounds = 6, modes = ["Narc/Smoke"] },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 24
rear = 6
slots = [
    { at = 4, item = "IS.LRM-20", modes = ["Narc/Smoke"] },
    { at = "5-8", item = "IS.LRM-20" },
    { at = 9, item = "Ammo_IS.NarcBeacon", rounds = 6 },
    { at = "10-11", item = "Ammo_IS.LRM-20", rounds = 6, modes = ["Narc/Smoke"] },
    { at = 12, item = "Case" },
]

[sections.center_torso]
armor = 33
rear = 10
slots = [
    { at = "11-12", item = "IS.NarcBeacon" },
]

[sections.left_leg]
armor = 26

[sections.right_leg]
armor = 26

[sections.head]
armor = 9
