name = "Atlas"
class = "mech"
movement = "biped"
tons = 100
walk_mp = 5
heat_sinks = 21
radio = 4

[construction]
engine = "xl"

[sections.left_arm]
armor = 34
slots = [
    { at = "5-6", item = "HeatSink" },
    { at = "7-8", item = "IS.ERLargeLaser" },
    { at = 9, item = "IS.Anti-MissileSystem" },
]

[sections.right_arm]
armor = 34
slots = [
    { at = "5-6", item = "HeatSink" },
    { at = "7-8", item = "IS.ERLargeLaser" },
    { at = "9-10", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.left_torso]
armor = 32
rear = 10
slots = [
    { at = "4-8", item = "IS.LRM-20" },
    { at = "9-10", item = "Ammo_IS.LRM-20", rounds = 6 },
    { at = 11, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 32
rear = 10
slots = [
    { at = "4-10", item = "IS.GaussRifle" },
    { at = 11, item = "Case" },
]

[sections.center_torso]
armor = 47
rear = 14
slots = [
    { at = 11, item = "HeatSink" },
    { at = 12, item = "IS.MediumPulseLaser", modes = ["RearMount"] },
]

[sections.left_leg]
armor = 41
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 41
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "C3Slave" },
]
