name = "Atlas"
class = "mech"
movement = "biped"
tons = 100
walk_mp = 5
heat_sinks = 32
computer = 4
radio = 4
cargo_space = 0
max_suits = 0

[construction]
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 34
slots = [
    { at = "5-10", item = "HeatSink", brand = 3 },
    { at = "11-12", item = "IS.ERLargeLaser", brand = 3 },
]

[sections.right_arm]
armor = 34
slots = [
    { at = "5-10", item = "HeatSink", brand = 3 },
    { at = "11-12", item = "IS.ERLargeLaser", brand = 3 },
]

[sections.left_torso]
armor = 32
rear = 10
engine_slots = 2
slots = [
    { at = "3-5", item = "IS.LRM-15", brand = 3 },
    { at = 6, item = "ArtemisIV", brand = 3 },
    { at = "7-8", item = "Ammo_IS.LRM-15", rounds = 8, modes = ["Artemis/Mine"] },
    { at = "9-10", item = "Ecm", brand = 3 },
    { at = 11, item = "Case", brand = 3 },
]

[sections.right_torso]
armor = 32
rear = 10
slots = [
    { at = "1-11", item = "IS.HeavyGaussRifle", brand = 3 },
    { at = 12, item = "Case", brand = 3 },
]

[sections.center_torso]
armor = 47
rear = 14
engine_slots = 8

[sections.left_leg]
armor = 41
slots = [
    { at = "5-6", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]

[sections.right_leg]
armor = 41
slots = [
    { at = "5-6", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]

[sections.head]
armor = 9
