name = "Atlas"
class = "mech"
movement = "biped"
tons = 100
max_speed = 53.75
heat_sinks = 30
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-7", item = "HeatSink", brand = 3 },
    { at = 11, item = "IS.MediumLaser", brand = 3 },
]

[sections.right_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-10", item = "HeatSink", brand = 3 },
    { at = 11, item = "IS.MediumLaser", brand = 3 },
]

[sections.left_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-5", item = "IS.LRM-20", brand = 3 },
    { at = "6-7", item = "IS.SRM-6", brand = 3 },
    { at = "8-9", item = "IS.StreakSRM-2", modes = ["RearMount"], brand = 3 },
    { at = "10-11", item = "Ammo_IS.LRM-20", rounds = 6 },
    { at = 12, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.right_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-10", item = "IS.AC/20", brand = 3 },
    { at = "11-12", item = "Ammo_IS.AC/20", rounds = 5 },
]

[sections.center_torso]
armor = 47
internals = 31
rear = 14
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "IS.MediumLaser", modes = ["RearMount"], brand = 3 },
]

[sections.left_leg]
armor = 41
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.right_leg]
armor = 41
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "Ammo_IS.AC/20", rounds = 5 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
