name = "Assassin"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 11
jump_mp = 7
heat_sinks = 20
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 0
max_suits = 0

[construction]
engine = "light"
structure = "endo_steel"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 9
slots = [
    { at = "5-7", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 9
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.ERMediumLaser", brand = 3 },
    { at = "5-7", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 11
rear = 4
slots = [
    { at = "3-5", item = "JumpJet", brand = 3 },
    { at = "6-7", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 11
rear = 4
slots = [
    { at = "3-7", item = "IS.LB5-XAC", brand = 3 },
    { at = 8, item = "Ammo_IS.LB5-XAC", rounds = 20, modes = ["LBX/Cluster"] },
    { at = "9-11", item = "JumpJet", brand = 3 },
    { at = 12, item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 14
rear = 4
slots = [
    { at = 11, item = "JumpJet", brand = 3 },
    { at = 12, item = "EndoSteel", brand = 3 },
]

[sections.left_leg]
armor = 15
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.right_leg]
armor = 15
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.head]
armor = 8
