name = "Avatar"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
heat_sinks = 20
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 16
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "CL.GaussRifle" },
]

[sections.right_arm]
armor = 16
omit = ["hand_actuator"]
slots = [
    { at = "4-10", item = "IS.MRM-40" },
]

[sections.left_torso]
armor = 22
rear = 8
slots = [
    { at = 4, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.right_torso]
armor = 22
rear = 8
slots = [
    { at = 4, item = "CL.StreakSRM-4" },
    { at = "5-6", item = "Ammo_IS.MRM-40", rounds = 6 },
    { at = 7, item = "Ammo_CL.StreakSRM-4", rounds = 25 },
]

[sections.center_torso]
armor = 30
rear = 9
slots = [
    { at = "11-12", item = "IS.MediumLaser" },
]

[sections.left_leg]
armor = 26

[sections.right_leg]
armor = 26

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.ERLargeLaser" },
]
