name = "Barghest"
class = "mech"
movement = "quad"
tons = 70
max_speed = 86.0
heat_sinks = 20
specials = ["DoubleHS"]

[sections.front_left_leg]
armor = 27
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.front_right_leg]
armor = 27
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.left_torso]
armor = 21
internals = 15
rear = 6
slots = [
    { at = "1-5", item = "Engine", brand = 3 },
    { at = "6-9", item = "IS.ERLargeLaser", brand = 3 },
]

[sections.right_torso]
armor = 21
internals = 15
rear = 6
slots = [
    { at = 1, item = "Engine", brand = 3 },
    { at = "2-12", item = "IS.LB20-XAC", brand = 3 },
]

[sections.center_torso]
armor = 30
internals = 22
rear = 9
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
]

[sections.rear_left_leg]
armor = 26
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "Ammo_IS.LB20-XAC", rounds = 5 },
    { at = 6, item = "Ammo_IS.LB20-XAC", rounds = 5, modes = ["LBX/Cluster"] },
]

[sections.rear_right_leg]
armor = 26
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "Ammo_IS.LB20-XAC", rounds = 5 },
    { at = 6, item = "Ammo_IS.LB20-XAC", rounds = 5, modes = ["LBX/Cluster"] },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
