name = "Barghest"
class = "mech"
movement = "quad"
tons = 70
walk_mp = 8
heat_sinks = 20

[construction]
heat_sinks = "double"

[sections.front_left_leg]
armor = 27

[sections.front_right_leg]
armor = 27

[sections.left_torso]
armor = 21
rear = 6
engine_slots = 5
slots = [
    { at = "6-9", item = "IS.ERLargeLaser" },
]

[sections.right_torso]
armor = 21
rear = 6
engine_slots = 1
slots = [
    { at = "2-12", item = "IS.LB20-XAC" },
]

[sections.center_torso]
armor = 30
rear = 9

[sections.rear_left_leg]
armor = 26
slots = [
    { at = 5, item = "Ammo_IS.LB20-XAC", rounds = 5 },
    { at = 6, item = "Ammo_IS.LB20-XAC", rounds = 5, modes = ["LBX/Cluster"] },
]

[sections.rear_right_leg]
armor = 26
slots = [
    { at = 5, item = "Ammo_IS.LB20-XAC", rounds = 5 },
    { at = 6, item = "Ammo_IS.LB20-XAC", rounds = 5, modes = ["LBX/Cluster"] },
]

[sections.head]
armor = 9
