name = "Blackhawk-Ku"
class = "mech"
movement = "biped"
tons = 60
max_speed = 86.0
jump_speed = 53.75
heat_sinks = 28
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-9", item = "IS.GaussRifle" },
]

[sections.right_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 20
internals = 14
rear = 8
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "HeatSink" },
    { at = 7, item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.right_torso]
armor = 20
internals = 14
rear = 8
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "HeatSink" },
]

[sections.center_torso]
armor = 30
internals = 20
rear = 9
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "JumpJet" },
]

[sections.left_leg]
armor = 28
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 28
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
