name = "BlackHawk"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 8
jump_mp = 5
heat_sinks = 28
computer = 4

[construction]
tech_base = "clan"
engine = "xl"

[sections.left_arm]
armor = 16
omit = ["hand_actuator"]
slots = [
    { at = "4-9", item = "CL.GaussRifle" },
    { at = 10, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.right_arm]
armor = 16

[sections.left_torso]
armor = 15
rear = 8
engine_at = 3
slots = [
    { at = 1, item = "CL.SRM-4" },
    { at = 2, item = "Ammo_CL.SRM-4", rounds = 25 },
    { at = "5-8", item = "HeatSink" },
]

[sections.right_torso]
armor = 15
rear = 8
engine_at = 2
slots = [
    { at = 1, item = "CL.SmallPulseLaser" },
    { at = "4-7", item = "HeatSink" },
]

[sections.center_torso]
armor = 23
rear = 8
slots = [
    { at = 11, item = "JumpJet" },
]

[sections.left_leg]
armor = 20
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 20
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
