name = "Blizzard"
class = "vehicle"
movement = "hover"
tons = 25
walk_mp = 14
cargo_space = 6144
specials = ["CargoTech"]

[construction]
engine = "ice"

[sections.left_side]
armor = 10

[sections.right_side]
armor = 10

[sections.front_side]
armor = 10

[sections.aft_side]
armor = 9

[sections.turret]
armor = 9
slots = [
    { at = 1, item = "IS.LRM-5" },
    { at = 2, item = "Ammo_IS.LRM-5", rounds = 24 },
]
