name = "Blood Asp"
class = "mech"
movement = "biped"
tons = 90
max_speed = 64.5
heat_sinks = 32
specials = ["Clan", "FlipArms", "ArtemisIV"]

[sections.left_arm]
armor = 28
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "4-7", item = "CL.LRM-20" },
    { at = "8-9", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "10-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 28
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "4-7", item = "CL.LRM-20" },
    { at = "8-9", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "10-11", item = "HeatSink" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_torso]
armor = 24
internals = 19
rear = 11
slots = [
    { at = "1-2", item = "Engine" },
    { at = "3-6", item = "CL.MediumPulseLaser" },
    { at = 7, item = "EndoSteel" },
]

[sections.right_torso]
armor = 24
internals = 19
rear = 11
slots = [
    { at = "1-2", item = "Engine" },
    { at = "3-8", item = "CL.GaussRifle" },
    { at = "9-10", item = "HeatSink" },
    { at = 11, item = "EndoSteel" },
]

[sections.center_torso]
armor = 40
internals = 29
rear = 13
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 12, item = "Ecm" },
]

[sections.left_leg]
armor = 34
internals = 19
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.right_leg]
armor = 34
internals = 19
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "EndoSteel" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
