name = "Battlemaster"
class = "mech"
movement = "biped"
tons = 85
max_speed = 64.5
heat_sinks = 20
specials = ["Searchlight"]

[sections.left_arm]
armor = 24
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "IS.SRM-2" },
]

[sections.right_arm]
armor = 24
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-7", item = "IS.LRM-15" },
    { at = 8, item = "IS.LRM-5" },
]

[sections.left_torso]
armor = 28
internals = 18
rear = 8
slots = [
    { at = "1-2", item = "IS.MediumLaser" },
    { at = 3, item = "IS.SRM-2" },
    { at = 4, item = "Ammo_IS.SRM-2", rounds = 50 },
    { at = 5, item = "HeatSink" },
]

[sections.right_torso]
armor = 28
internals = 18
rear = 8
slots = [
    { at = "1-2", item = "IS.MediumLaser" },
    { at = 3, item = "Ammo_IS.LRM-15", rounds = 8 },
    { at = 4, item = "Ammo_IS.LRM-5", rounds = 24 },
]

[sections.center_torso]
armor = 40
internals = 27
rear = 11
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 26
internals = 18
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 26
internals = 18
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
