name = "Bombardier"
class = "mech"
movement = "biped"
tons = 65
walk_mp = 8
heat_sinks = 20
computer = 4
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 20

[sections.right_arm]
armor = 20
slots = [
    { at = 5, item = "IS.SRM-4" },
    { at = 6, item = "Ammo_IS.SRM-4", rounds = 25 },
]

[sections.left_torso]
armor = 20
rear = 10
slots = [
    { at = "4-8", item = "IS.LRM-20" },
]

[sections.right_torso]
armor = 20
rear = 10
slots = [
    { at = "4-8", item = "IS.LRM-20" },
    { at = "9-10", item = "Ammo_IS.LRM-20", rounds = 6 },
    { at = 11, item = "Case" },
]

[sections.center_torso]
armor = 24
rear = 15
slots = [
    { at = 11, item = "IS.Anti-MissileSystem" },
    { at = 12, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.left_leg]
armor = 26

[sections.right_leg]
armor = 26

[sections.head]
armor = 9
