name = "Bulldog"
class = "vehicle"
movement = "track"
tons = 60
max_speed = 64.5
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 20
internals = 6

[sections.right_side]
armor = 20
internals = 6

[sections.front_side]
armor = 24
internals = 6
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
    { at = 2, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
]

[sections.aft_side]
armor = 20
internals = 6

[sections.turret]
armor = 20
internals = 6
slots = [
    { at = 1, item = "IS.LRM-20", brand = 3 },
    { at = "2-3", item = "IS.SRM-4", brand = 3 },
    { at = "4-5", item = "Ammo_IS.SRM-4", rounds = 25 },
    { at = "6-8", item = "Ammo_IS.LRM-20", rounds = 6 },
]
