name = "Cicada"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 12
heat_sinks = 20
computer = 4
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 4
omit = ["lower_actuator", "hand_actuator"]

[sections.right_arm]
armor = 4
omit = ["lower_actuator", "hand_actuator"]

[sections.left_torso]
armor = 6
rear = 3
slots = [
    { at = 4, item = "IS.MediumLaser", brand = 3 },
    { at = "5-9", item = "IS.UltraAC/5", brand = 3 },
]

[sections.right_torso]
armor = 6
rear = 3
slots = [
    { at = 4, item = "IS.MediumLaser", brand = 3 },
    { at = 5, item = "Ammo_IS.UltraAC/5", rounds = 20 },
    { at = 6, item = "Case", brand = 3 },
]

[sections.center_torso]
armor = 11
rear = 6
slots = [
    { at = 11, item = "IS.SmallPulseLaser", brand = 3 },
]

[sections.left_leg]
armor = 6

[sections.right_leg]
armor = 6

[sections.head]
armor = 9
