name = "Cicada"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 11
heat_sinks = 11
computer = 4
radio = 4

[sections.left_arm]
armor = 4
omit = ["lower_actuator", "hand_actuator"]

[sections.right_arm]
armor = 4
omit = ["lower_actuator", "hand_actuator"]

[sections.left_torso]
armor = 6
rear = 3

[sections.right_torso]
armor = 6
rear = 3
slots = [
    { at = "1-3", item = "IS.PPC" },
]

[sections.center_torso]
armor = 11
rear = 6
slots = [
    { at = 11, item = "Ammo_IS.MachineGun", rounds = 200 },
]

[sections.left_leg]
armor = 6
slots = [
    { at = 5, item = "IS.MachineGun", brand = 2 },
]

[sections.right_leg]
armor = 6
slots = [
    { at = 5, item = "IS.MachineGun", brand = 2 },
]

[sections.head]
armor = 9
