name = "Chevalier"
class = "vehicle"
movement = "wheel"
tons = 35
max_speed = 96.75
heat_sinks = 12

[sections.left_side]
armor = 20
internals = 4

[sections.right_side]
armor = 20
internals = 4

[sections.front_side]
armor = 26
internals = 4
slots = [
    { at = "1-2", item = "IS.StreakSRM-2" },
    { at = 3, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 16
internals = 4

[sections.turret]
armor = 21
internals = 4
slots = [
    { at = 1, item = "IS.ERLargeLaser" },
]
