name = "Champion"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 8

[sections.left_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]

[sections.right_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]

[sections.left_torso]
armor = 16
rear = 5
slots = [
    { at = "1-2", item = "IS.SRM-6" },
    { at = 3, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = "4-5", item = "IS.MediumLaser" },
]

[sections.right_torso]
armor = 16
rear = 5
slots = [
    { at = "1-7", item = "IS.AC/10" },
    { at = "8-9", item = "Ammo_IS.AC/10", rounds = 10 },
]

[sections.center_torso]
armor = 22
rear = 9
slots = [
    { at = "11-12", item = "IS.SmallLaser" },
]

[sections.left_leg]
armor = 13

[sections.right_leg]
armor = 13

[sections.head]
armor = 9
