name = "Clint"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 9

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"

[sections.left_arm]
armor = 9

[sections.right_arm]
armor = 9
omit = ["hand_actuator"]
slots = [
    { at = "4-8", item = "CL.LB10-XAC" },
]

[sections.left_torso]
armor = 13
rear = 4
slots = [
    { at = 3, item = "JumpJet" },
    { at = 4, item = "CL.ERMediumLaser" },
    { at = "5-7", item = "EndoSteel" },
]

[sections.right_torso]
armor = 13
rear = 4
slots = [
    { at = "3-4", item = "HeatSink" },
    { at = "5-6", item = "Ammo_CL.LB10-XAC", rounds = 10 },
    { at = "7-8", item = "Ammo_CL.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = "9-11", item = "EndoSteel" },
    { at = 12, item = "JumpJet" },
]

[sections.center_torso]
armor = 15
rear = 4
slots = [
    { at = 11, item = "CL.ERMediumLaser" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "EndoSteel" },
]
