name = "Commando"
class = "mech"
movement = "biped"
tons = 25
walk_mp = 9
radio = 2

[sections.left_arm]
armor = 6
slots = [
    { at = 5, item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 6
slots = [
    { at = 5, item = "IS.SRM-4" },
]

[sections.left_torso]
armor = 6
rear = 3
slots = [
    { at = 1, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = "2-3", item = "HeatSink" },
]

[sections.right_torso]
armor = 6
rear = 3
slots = [
    { at = 1, item = "Ammo_IS.SRM-4", rounds = 25 },
    { at = "2-3", item = "HeatSink" },
]

[sections.center_torso]
armor = 8
rear = 4
slots = [
    { at = "11-12", item = "IS.SRM-6" },
]

[sections.left_leg]
armor = 8

[sections.right_leg]
armor = 8

[sections.head]
armor = 6
