name = "Commando"
class = "mech"
movement = "biped"
tons = 25
walk_mp = 9
radio = 2

[sections.left_arm]
armor = 4
slots = [
    { at = 7, item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 4
slots = [
    { at = "5-6", item = "IS.SRM-6" },
    { at = 7, item = "IS.Flamer" },
]

[sections.left_torso]
armor = 4
rear = 3

[sections.right_torso]
armor = 4
rear = 3
slots = [
    { at = 1, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.center_torso]
armor = 6
rear = 4
slots = [
    { at = "11-12", item = "IS.SRM-6" },
]

[sections.left_leg]
armor = 6
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 6
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 4
