name = "Condor"
class = "vehicle"
movement = "hover"
tons = 50
walk_mp = 12
heat_sinks = 12

[construction]
engine = "ice"

[sections.left_side]
armor = 23

[sections.right_side]
armor = 23

[sections.front_side]
armor = 38

[sections.aft_side]
armor = 22

[sections.turret]
armor = 30
slots = [
    { at = "1-4", item = "IS.MediumLaser" },
]
