name = "Condor"
class = "vehicle"
movement = "hover"
tons = 50
walk_mp = 11
heat_sinks = 20
tac_range = 30
lrs_range = 60
scan_range = 30

[sections.left_side]
armor = 24

[sections.right_side]
armor = 24

[sections.front_side]
armor = 36

[sections.aft_side]
armor = 16

[sections.turret]
armor = 20
slots = [
    { at = "1-4", item = "IS.ERMediumLaser" },
    { at = "5-7", item = "IS.SRM-2" },
    { at = "8-9", item = "Ammo_IS.SRM-2", rounds = 50 },
]
