name = "Cyclops"
class = "mech"
movement = "biped"
tons = 90
walk_mp = 6
heat_sinks = 22
radio = 4
radio_type = 127
cargo_space = 0
max_suits = 0

[construction]
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 29
slots = [
    { at = "5-10", item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 29
slots = [
    { at = "5-6", item = "IS.ERMediumLaser" },
    { at = "7-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 28
rear = 9
slots = [
    { at = "1-2", item = "IS.LRM-10" },
    { at = "3-10", item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.right_torso]
armor = 28
rear = 9
slots = [
    { at = "1-7", item = "IS.GaussRifle" },
    { at = "8-9", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = 10, item = "Ammo_IS.StreakSRM-4", rounds = 25 },
    { at = 11, item = "Ammo_IS.LRM-10", rounds = 12 },
    { at = 12, item = "Case" },
]

[sections.center_torso]
armor = 40
rear = 14
slots = [
    { at = 11, item = "IS.StreakSRM-4" },
]

[sections.left_leg]
armor = 37
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 37
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
