name = "Cyclops"
class = "mech"
movement = "biped"
tons = 90
walk_mp = 6
heat_sinks = 12
computer = 4
radio = 4
radio_type = 127

[construction]
brand = 3

[sections.left_arm]
armor = 15

[sections.right_arm]
armor = 15
slots = [
    { at = "5-6", item = "IS.MediumLaser", brand = 3 },
]

[sections.left_torso]
armor = 24
rear = 8
slots = [
    { at = "1-5", item = "C3Master", brand = 3 },
]

[sections.right_torso]
armor = 24
rear = 8
slots = [
    { at = "1-7", item = "IS.GaussRifle", brand = 3 },
    { at = "8-9", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.center_torso]
armor = 34
rear = 11
slots = [
    { at = 11, item = "IS.SRM-4", brand = 3 },
    { at = 12, item = "Ammo_IS.SRM-4", rounds = 25 },
]

[sections.left_leg]
armor = 22

[sections.right_leg]
armor = 22

[sections.head]
armor = 9
