name = "Catapult"
class = "mech"
movement = "biped"
tons = 65
max_speed = 64.5
jump_speed = 43.0
heat_sinks = 15
specials = ["FlipArms"]

[sections.left_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-5", item = "IS.LRM-15", brand = 4 },
]

[sections.right_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-5", item = "IS.LRM-15", brand = 4 },
]

[sections.left_torso]
armor = 21
internals = 15
rear = 9
slots = [
    { at = "1-2", item = "Ammo_IS.LRM-15", rounds = 8 },
    { at = "3-4", item = "JumpJet" },
]

[sections.right_torso]
armor = 21
internals = 15
rear = 9
slots = [
    { at = "1-2", item = "Ammo_IS.LRM-15", rounds = 8 },
    { at = "3-4", item = "JumpJet" },
]

[sections.center_torso]
armor = 24
internals = 21
rear = 11
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "HeatSink" },
]

[sections.left_leg]
armor = 24
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 24
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
