name = "Crusader"
class = "mech"
movement = "biped"
tons = 65
walk_mp = 6
jump_mp = 4
heat_sinks = 12

[sections.left_arm]
armor = 20
slots = [
    { at = "5-6", item = "IS.LRM-10" },
    { at = 7, item = "IS.MediumLaser" },
    { at = 8, item = "IS.MachineGun" },
]

[sections.right_arm]
armor = 20
slots = [
    { at = "5-6", item = "IS.LRM-10" },
    { at = 7, item = "IS.MediumLaser" },
    { at = 8, item = "IS.MachineGun" },
]

[sections.left_torso]
armor = 24
rear = 6
slots = [
    { at = 1, item = "Ammo_IS.LRM-10", rounds = 12 },
    { at = "2-3", item = "JumpJet" },
]

[sections.right_torso]
armor = 24
rear = 6
slots = [
    { at = 1, item = "Ammo_IS.LRM-10", rounds = 12 },
    { at = "2-3", item = "JumpJet" },
]

[sections.center_torso]
armor = 33
rear = 8
slots = [
    { at = 11, item = "Ammo_IS.SRM-4", rounds = 25 },
    { at = 12, item = "Ammo_IS.MachineGun", rounds = 200 },
]

[sections.left_leg]
armor = 21
slots = [
    { at = 5, item = "IS.SRM-4" },
    { at = 6, item = "HeatSink" },
]

[sections.right_leg]
armor = 21
slots = [
    { at = 5, item = "IS.SRM-4" },
    { at = 6, item = "HeatSink" },
]

[sections.head]
armor = 9
