name = "Katana"
class = "mech"
movement = "biped"
tons = 85
walk_mp = 5
jump_mp = 3
heat_sinks = 20
radio = 4

[construction]

[sections.left_arm]
armor = 19
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.LargeLaser" },
]

[sections.right_arm]
armor = 19
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.LargeLaser" },
]

[sections.left_torso]
armor = 23
rear = 8
slots = [
    { at = "1-4", item = "HeatSink" },
    { at = "5-6", item = "IS.SRM-6" },
    { at = "7-12", item = "IS.LB10-XAC" },
]

[sections.right_torso]
armor = 23
rear = 8
slots = [
    { at = "1-4", item = "HeatSink" },
    { at = "5-6", item = "IS.SRM-6" },
    { at = "7-8", item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 9, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 10, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
]

[sections.center_torso]
armor = 31
rear = 12
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "C3Slave" },
]

[sections.left_leg]
armor = 24
slots = [
    { at = 5, item = "HeatSink" },
    { at = 6, item = "JumpJet" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = 5, item = "HeatSink" },
    { at = 6, item = "JumpJet" },
]

[sections.head]
armor = 9
