name = "Cataphract"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
jump_mp = 4
heat_sinks = 16
radio = 4

[construction]
engine = "xl"

[sections.left_arm]
armor = 22
slots = [
    { at = 5, item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 22
omit = ["hand_actuator"]
slots = [
    { at = "4-8", item = "IS.UltraAC/5" },
    { at = 9, item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 16
rear = 9
slots = [
    { at = "4-5", item = "HeatSink" },
    { at = 6, item = "IS.MediumLaser", modes = ["RearMount"] },
    { at = 7, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 8, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 9, item = "Case" },
]

[sections.right_torso]
armor = 16
rear = 9
slots = [
    { at = "4-9", item = "IS.LB10-XAC" },
    { at = 10, item = "IS.MediumLaser", modes = ["RearMount"] },
    { at = 11, item = "Ammo_IS.UltraAC/5", rounds = 20 },
    { at = 12, item = "Case" },
]

[sections.center_torso]
armor = 26
rear = 9
slots = [
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 19
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 19
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "HeatSink" },
]
