name = "Cataphract"
class = "mech"
movement = "biped"
tons = 70
max_speed = 64.5
heat_sinks = 26
computer = 4
radio = 4
cargo_space = 0
max_suits = 0
specials = ["DoubleHS"]

[sections.left_arm]
armor = 22
internals = 11
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-5", item = "IS.ERMediumLaser", brand = 3 },
    { at = "8-12", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 22
internals = 11
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = "3-5", item = "IS.ERPPC", brand = 3 },
    { at = "8-12", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 22
internals = 15
rear = 8
slots = [
    { at = "1-6", item = "HeatSink", brand = 3 },
    { at = "7-8", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "9-10", item = "Ecm", brand = 3 },
]

[sections.right_torso]
armor = 22
internals = 15
rear = 8
slots = [
    { at = "1-7", item = "IS.GaussRifle", brand = 3 },
    { at = 8, item = "Case", brand = 3 },
    { at = "11-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 32
internals = 22
rear = 11
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "EndoSteel", brand = 3 },
]

[sections.left_leg]
armor = 30
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_leg]
armor = 30
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 4, item = "EndoSteel", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
