name = "Cestus"
class = "mech"
movement = "biped"
tons = 65
walk_mp = 6
heat_sinks = 32
computer = 4
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 20
slots = [
    { at = 5, item = "IS.MediumLaser", brand = 3 },
    { at = "6-7", item = "IS.LargeLaser", brand = 3 },
    { at = "8-10", item = "IS.PPC", brand = 3 },
]

[sections.right_arm]
armor = 20
slots = [
    { at = 5, item = "IS.MediumLaser", brand = 3 },
    { at = "6-7", item = "IS.LargeLaser", brand = 3 },
    { at = "8-10", item = "IS.PPC", brand = 3 },
]

[sections.left_torso]
armor = 22
rear = 8
slots = [
    { at = "4-12", item = "HeatSink", brand = 3 },
]

[sections.right_torso]
armor = 22
rear = 8
slots = [
    { at = "4-12", item = "HeatSink", brand = 3 },
]

[sections.center_torso]
armor = 32
rear = 10

[sections.left_leg]
armor = 30

[sections.right_leg]
armor = 30

[sections.head]
armor = 9
