name = "Cyrano"
class = "vtol"
movement = "vtol"
tons = 30
walk_mp = 18
radio = 3

[construction]
armor = "ferro_fibrous"

[sections.left_side]
armor = 2
slots = [
    { at = "1-2", item = "FerroFibrous" },
]

[sections.right_side]
armor = 2
slots = [
    { at = "1-2", item = "FerroFibrous" },
]

[sections.front_side]
armor = 3
rear = 2
slots = [
    { at = 1, item = "IS.LargeLaser" },
    { at = 2, item = "BeagleProbe" },
]

[sections.aft_side]
armor = 1
rear = 2

[sections.rotor]
armor = 1
