name = "Dasher"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 15
heat_sinks = 20
computer = 4
specials = ["Masc", "ECM"]

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 3
slots = [
    { at = 5, item = "CL.MediumPulseLaser" },
    { at = 7, item = "FerroFibrous" },
    { at = 8, item = "EndoSteel" },
]

[sections.right_arm]
armor = 3
slots = [
    { at = 5, item = "CL.MachineGun" },
    { at = 6, item = "Ammo_CL.MachineGun", rounds = 200 },
    { at = 7, item = "FerroFibrous" },
    { at = 8, item = "EndoSteel" },
    { at = 9, item = "Ecm" },
]

[sections.left_torso]
armor = 4
rear = 2
slots = [
    { at = "3-4", item = "HeatSink" },
    { at = "5-6", item = "FerroFibrous" },
    { at = 7, item = "EndoSteel" },
]

[sections.right_torso]
armor = 4
rear = 2
engine_at = 3
slots = [
    { at = 1, item = "CL.MediumPulseLaser" },
    { at = "5-6", item = "HeatSink" },
    { at = "7-8", item = "FerroFibrous" },
    { at = 9, item = "EndoSteel" },
]

[sections.center_torso]
armor = 5
rear = 2
slots = [
    { at = 11, item = "Masc" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 4
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.right_leg]
armor = 4
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "CL.A-Pod" },
]

[sections.head]
armor = 5
slots = [
    { at = 4, item = "FerroFibrous" },
]
