name = "Dasher"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 15
heat_sinks = 20
computer = 4
specials = ["CL_AMS", "Masc"]

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 3
slots = [
    { at = 5, item = "CL.LRM-5" },
    { at = 6, item = "Ammo_CL.LRM-5", rounds = 24 },
    { at = 7, item = "EndoSteel" },
    { at = 8, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 3
slots = [
    { at = 5, item = "CL.LRM-5" },
    { at = 6, item = "Ammo_CL.LRM-5", rounds = 24 },
    { at = 7, item = "EndoSteel" },
    { at = 8, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 4
rear = 2
slots = [
    { at = 3, item = "EndoSteel" },
    { at = "4-5", item = "FerroFibrous" },
    { at = "7-8", item = "HeatSink" },
]

[sections.right_torso]
armor = 4
rear = 2
slots = [
    { at = 3, item = "CL.Anti-MissileSystem" },
    { at = "4-5", item = "Ammo_CL.Anti-MissileSystem", rounds = 24 },
    { at = "6-7", item = "HeatSink" },
    { at = "8-9", item = "FerroFibrous" },
    { at = 10, item = "EndoSteel" },
]

[sections.center_torso]
armor = 5
rear = 2
slots = [
    { at = 11, item = "Masc" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 4
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.right_leg]
armor = 4
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.head]
armor = 5
slots = [
    { at = 4, item = "FerroFibrous" },
]
