name = "Donar"
class = "vtol"
movement = "vtol"
tons = 21
max_speed = 150.5
heat_sinks = 12
specials = ["Clan", "FerroFibrous_Tech"]

[sections.left_side]
armor = 14
internals = 2
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 14
internals = 2
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 16
internals = 2
slots = [
    { at = 1, item = "CL.ERLargeLaser" },
    { at = 2, item = "Ecm" },
    { at = 3, item = "BeagleProbe" },
    { at = 4, item = "TAG" },
]

[sections.aft_side]
armor = 12
internals = 2

[sections.rotor]
armor = 2
internals = 2
