name = "Dart"
class = "mech"
movement = "biped"
tons = 25
walk_mp = 14
computer = 4
radio = 4

[construction]
brand = 3

[sections.left_arm]
armor = 5

[sections.right_arm]
armor = 5

[sections.left_torso]
armor = 7
rear = 3

[sections.right_torso]
armor = 7
rear = 3
slots = [
    { at = 1, item = "HeatSink", brand = 3 },
]

[sections.center_torso]
armor = 7
rear = 3
slots = [
    { at = "11-12", item = "IS.SmallPulseLaser", brand = 3 },
]

[sections.left_leg]
armor = 5

[sections.right_leg]
armor = 5

[sections.head]
armor = 6
slots = [
    { at = 4, item = "IS.SmallPulseLaser", brand = 3 },
]
