name = "Epona"
class = "vehicle"
movement = "hover"
tons = 50
max_speed = 150.5
heat_sinks = 10
specials = ["Clan", "FerroFibrous_Tech"]

[sections.left_side]
armor = 20
internals = 5
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 20
internals = 5
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 21
internals = 5
slots = [
    { at = 1, item = "TAG" },
    { at = "2-3", item = "CL.ERMediumLaser" },
]

[sections.aft_side]
armor = 18
internals = 5

[sections.turret]
armor = 17
internals = 5
slots = [
    { at = "1-2", item = "CL.LRM-20" },
    { at = "3-6", item = "Ammo_CL.LRM-20", rounds = 6 },
]
