name = "Exterminator"
class = "mech"
movement = "biped"
tons = 65
max_speed = 96.75
jump_speed = 64.5
heat_sinks = 20
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 18
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 18
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 20
internals = 15
rear = 8
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "JumpJet" },
    { at = "7-8", item = "IS.LRM-10" },
]

[sections.right_torso]
armor = 20
internals = 15
rear = 8
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-6", item = "JumpJet" },
    { at = 7, item = "IS.Anti-MissileSystem" },
    { at = 8, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.center_torso]
armor = 21
internals = 21
rear = 8
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "Ammo_IS.LRM-10", rounds = 12 },
]

[sections.left_leg]
armor = 19
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
]

[sections.right_leg]
armor = 19
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "IS.SmallLaser" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
