name = "Fire Falcon"
class = "mech"
movement = "biped"
tons = 25
walk_mp = 12
heat_sinks = 20
computer = 4
radio = 5

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
brand = 5

[sections.left_arm]
armor = 6
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "CL.ERLargeLaser", modes = ["OnTC"], brand = 5 },
    { at = "9-12", item = "FerroFibrous", brand = 5 },
]

[sections.right_arm]
armor = 6
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "CL.ERLargeLaser", modes = ["OnTC"], brand = 5 },
    { at = "9-12", item = "EndoSteel", brand = 5 },
]

[sections.left_torso]
armor = 9
rear = 2
slots = [
    { at = "3-4", item = "TargetingComputer", brand = 5 },
    { at = "10-12", item = "FerroFibrous", brand = 5 },
]

[sections.right_torso]
armor = 9
rear = 2
slots = [
    { at = "10-12", item = "EndoSteel", brand = 5 },
]

[sections.center_torso]
armor = 11
rear = 3

[sections.left_leg]
armor = 10
slots = [
    { at = "5-6", item = "HeatSink", brand = 5 },
]

[sections.right_leg]
armor = 10
slots = [
    { at = "5-6", item = "HeatSink", brand = 5 },
]

[sections.head]
armor = 9
