name = "Flatbed Truck"
class = "vehicle"
movement = "wheel"
tons = 10
walk_mp = 8
specials = ["CargoTech"]

[construction]
engine = "ice"

[sections.left_side]
armor = 2

[sections.right_side]
armor = 2

[sections.front_side]
armor = 2
slots = [
    { at = 1, item = "IS.SRM-2" },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 2
