name = "Falcon Hawk"
class = "mech"
movement = "biped"
tons = 35
walk_mp = 8
heat_sinks = 26
computer = 4
radio = 4

[construction]
engine = "xl"
armor = "ferro_fibrous"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 12
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.LargeLaser", brand = 3 },
    { at = 6, item = "IS.MediumLaser", brand = 3 },
    { at = "7-11", item = "FerroFibrous", brand = 3 },
]

[sections.right_arm]
armor = 12
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.ERLargeLaser", brand = 3 },
    { at = "6-10", item = "FerroFibrous", brand = 3 },
]

[sections.left_torso]
armor = 12
rear = 4
slots = [
    { at = "4-12", item = "HeatSink", brand = 3 },
]

[sections.right_torso]
armor = 12
rear = 4
slots = [
    { at = "4-12", item = "HeatSink", brand = 3 },
]

[sections.center_torso]
armor = 16
rear = 6
slots = [
    { at = 12, item = "IS.MediumLaser", modes = ["RearMount"], brand = 3 },
]

[sections.left_leg]
armor = 16
slots = [
    { at = "5-6", item = "FerroFibrous", brand = 3 },
]

[sections.right_leg]
armor = 16
slots = [
    { at = "5-6", item = "FerroFibrous", brand = 3 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallPulseLaser", brand = 3 },
]
