name = "Firestarter"
class = "mech"
movement = "biped"
tons = 45
walk_mp = 9
jump_mp = 6
heat_sinks = 24
computer = 4
radio = 4

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-5", item = "IS.ERPPC", brand = 3 },
    { at = "6-10", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 12
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumLaser", brand = 3 },
    { at = 5, item = "IS.LRM-5", brand = 3 },
    { at = 6, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "7-9", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 16
rear = 6
slots = [
    { at = "4-6", item = "HeatSink", brand = 3 },
    { at = "7-9", item = "JumpJet", brand = 3 },
    { at = 10, item = "C3Slave", brand = 3 },
    { at = "11-12", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 16
rear = 6
slots = [
    { at = "4-6", item = "HeatSink", brand = 3 },
    { at = "7-9", item = "JumpJet", brand = 3 },
    { at = "10-11", item = "Ecm", brand = 3 },
]

[sections.center_torso]
armor = 18
rear = 7
slots = [
    { at = 11, item = "IS.Flamer", brand = 3 },
    { at = 12, item = "IS.Flamer", modes = ["RearMount"], brand = 3 },
]

[sections.left_leg]
armor = 16
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.right_leg]
armor = 16
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.head]
armor = 9
