name = "Fury"
class = "vehicle"
movement = "track"
tons = 80
walk_mp = 6
cargo_space = 768
specials = ["SearchLight"]

[sections.left_side]
armor = 40

[sections.right_side]
armor = 40

[sections.front_side]
armor = 60

[sections.aft_side]
armor = 40

[sections.turret]
armor = 60
slots = [
    { at = 1, item = "IS.GaussRifle" },
    { at = "2-3", item = "Ammo_IS.GaussRifle", rounds = 8 },
]
