name = "Galahad"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 6
heat_sinks = 32
computer = 4

[construction]
tech_base = "clan"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 20
slots = [
    { at = "5-6", item = "CL.LargePulseLaser", modes = ["OnTC"] },
    { at = "7-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 20
slots = [
    { at = "5-6", item = "CL.LargePulseLaser", modes = ["OnTC"] },
    { at = "7-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 20
rear = 8
slots = [
    { at = "1-2", item = "CL.MediumPulseLaser", modes = ["OnTC"] },
    { at = "3-6", item = "HeatSink" },
    { at = 7, item = "EndoSteel" },
    { at = "8-11", item = "HeatSink" },
]

[sections.right_torso]
armor = 20
rear = 8
slots = [
    { at = "1-4", item = "TargetingComputer" },
    { at = "5-7", item = "CL.SmallPulseLaser", modes = ["OnTC"] },
    { at = 8, item = "FerroFibrous" },
    { at = "9-12", item = "HeatSink" },
]

[sections.center_torso]
armor = 30
rear = 10
slots = [
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 28

[sections.right_leg]
armor = 28

[sections.head]
armor = 9
