name = "Galleon"
class = "vehicle"
movement = "track"
tons = 30
walk_mp = 9

[construction]
engine = "ice"

[sections.left_side]
armor = 13
slots = [
    { at = 1, item = "IS.MachineGun" },
]

[sections.right_side]
armor = 13
slots = [
    { at = 1, item = "IS.MachineGun" },
]

[sections.front_side]
armor = 14

[sections.aft_side]
armor = 14

[sections.turret]
armor = 20
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "Ammo_IS.MachineGun", rounds = 200 },
]
