name = "Galleon"
class = "vehicle"
movement = "track"
tons = 30
walk_mp = 11

[sections.left_side]
armor = 18
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 18
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 25
slots = [
    { at = 1, item = "BeagleProbe" },
]

[sections.aft_side]
armor = 19

[sections.turret]
armor = 28
slots = [
    { at = 1, item = "IS.MediumPulseLaser" },
]
