name = "Gladius"
class = "vehicle"
movement = "hover"
tons = 40
walk_mp = 12

[construction]
engine = "ice"

[sections.left_side]
armor = 24

[sections.right_side]
armor = 24

[sections.front_side]
armor = 30
slots = [
    { at = 1, item = "IS.AC/10", brand = 3 },
    { at = "2-3", item = "Ammo_IS.AC/10", rounds = 10 },
]

[sections.aft_side]
armor = 18
