name = "Glaive"
class = "vehicle"
movement = "wheel"
tons = 45
walk_mp = 8
computer = 4
radio = 4
cargo_space = 0
max_suits = 0

[sections.left_side]
armor = 17

[sections.right_side]
armor = 17

[sections.front_side]
armor = 27
slots = [
    { at = 1, item = "IS.LRM-15", brand = 0 },
    { at = 2, item = "ArtemisIV", brand = 0 },
]

[sections.aft_side]
armor = 12
slots = [
    { at = 1, item = "Ammo_IS.MachineGun", rounds = 200 },
    { at = "2-3", item = "Ammo_IS.LRM-15", rounds = 8, modes = ["Artemis/Mine"] },
]

[sections.turret]
armor = 15
slots = [
    { at = 1, item = "IS.ERLargeLaser", brand = 0 },
    { at = "2-3", item = "IS.MachineGun", brand = 0 },
]
