name = "Guillotine"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
jump_mp = 4
heat_sinks = 25
computer = 4
radio = 4
specials = ["SearchLight"]

[construction]
structure = "endo_steel"
brand = 3

[sections.left_arm]
armor = 20
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser", brand = 3 },
    { at = "5-11", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 20
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.MediumLaser", brand = 3 },
    { at = "6-12", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 22
rear = 8
slots = [
    { at = "1-6", item = "HeatSink", brand = 3 },
    { at = 7, item = "JumpJet", brand = 3 },
    { at = 8, item = "IS.MediumLaser", brand = 3 },
]

[sections.right_torso]
armor = 22
rear = 8
slots = [
    { at = "1-6", item = "HeatSink", brand = 3 },
    { at = 7, item = "JumpJet", brand = 3 },
    { at = 8, item = "IS.MediumLaser", brand = 3 },
    { at = 9, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 10, item = "Case", brand = 3 },
]

[sections.center_torso]
armor = 27
rear = 12
slots = [
    { at = "11-12", item = "IS.SRM-6", brand = 3 },
]

[sections.left_leg]
armor = 22
slots = [
    { at = 5, item = "JumpJet", brand = 3 },
    { at = 6, item = "HeatSink", brand = 3 },
]

[sections.right_leg]
armor = 22
slots = [
    { at = 5, item = "JumpJet", brand = 3 },
    { at = 6, item = "HeatSink", brand = 3 },
]

[sections.head]
armor = 9
