name = "Guillotine"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
jump_speed = 43.2
heat_sinks = 25
computer = 4
radio = 4
specials = ["SearchLight"]

[construction]
structure = "endo_steel"

[sections.left_arm]
armor = 20
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.LargeLaser" },
    { at = "5-8", item = "EndoSteel" },
]

[sections.right_arm]
armor = 20
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.MediumLaser" },
    { at = "6-9", item = "EndoSteel" },
]

[sections.left_torso]
armor = 22
rear = 8
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "JumpJet" },
    { at = "3-9", item = "HeatSink" },
    { at = "10-12", item = "EndoSteel" },
]

[sections.right_torso]
armor = 22
rear = 8
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 3, item = "Case" },
    { at = 4, item = "JumpJet" },
    { at = "5-9", item = "HeatSink" },
    { at = "10-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 27
rear = 12
slots = [
    { at = "11-12", item = "IS.SRM-6" },
]

[sections.left_leg]
armor = 22
slots = [
    { at = 5, item = "JumpJet" },
    { at = 6, item = "HeatSink" },
]

[sections.right_leg]
armor = 22
slots = [
    { at = 5, item = "JumpJet" },
    { at = 6, item = "HeatSink" },
]

[sections.head]
armor = 9
