name = "Guillotine"
class = "mech"
movement = "biped"
tons = 70
max_speed = 64.5
jump_speed = 43.0
heat_sinks = 25
computer = 4
radio = 4
specials = ["SearchLight"]

[sections.left_arm]
armor = 20
internals = 11
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = "3-4", item = "IS.ERLargeLaser", brand = 3 },
    { at = "5-11", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 20
internals = 11
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-5", item = "IS.MediumLaser", brand = 3 },
    { at = "6-12", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 22
internals = 15
rear = 8
slots = [
    { at = "1-6", item = "HeatSink", brand = 3 },
    { at = 7, item = "JumpJet", brand = 3 },
    { at = 8, item = "IS.MediumLaser", brand = 3 },
]

[sections.right_torso]
armor = 22
internals = 15
rear = 8
slots = [
    { at = "1-6", item = "HeatSink", brand = 3 },
    { at = 7, item = "JumpJet", brand = 3 },
    { at = 8, item = "IS.MediumLaser", brand = 3 },
    { at = 9, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 10, item = "Case", brand = 3 },
]

[sections.center_torso]
armor = 27
internals = 22
rear = 12
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "IS.SRM-6", brand = 3 },
]

[sections.left_leg]
armor = 22
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "JumpJet", brand = 3 },
    { at = 6, item = "HeatSink", brand = 3 },
]

[sections.right_leg]
armor = 22
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = 5, item = "JumpJet", brand = 3 },
    { at = 6, item = "HeatSink", brand = 3 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
