name = "Goblin"
class = "vehicle"
movement = "track"
tons = 45
walk_mp = 6
cargo_space = 300
specials = ["CargoTech"]

[sections.left_side]
armor = 32
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 32
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 40
slots = [
    { at = "1-2", item = "IS.MachineGun" },
    { at = 3, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
    { at = 4, item = "IS.Anti-MissileSystem" },
    { at = 5, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.aft_side]
armor = 26

[sections.turret]
armor = 40
slots = [
    { at = 1, item = "IS.LargePulseLaser" },
    { at = 2, item = "IS.SRM-6" },
    { at = 3, item = "Ammo_IS.SRM-6", rounds = 15 },
]
