name = "Grand Crusader"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 5
heat_sinks = 20
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"

[sections.left_arm]
armor = 26
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-5", item = "HeatSink" },
    { at = "6-7", item = "IS.LargePulseLaser" },
    { at = 8, item = "IS.MediumPulseLaser" },
    { at = "9-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 26
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.LargePulseLaser" },
    { at = 5, item = "IS.MediumPulseLaser" },
    { at = "6-11", item = "EndoSteel" },
]

[sections.left_torso]
armor = 24
rear = 10
slots = [
    { at = "4-8", item = "IS.LRM-20" },
    { at = 9, item = "ArtemisIV" },
    { at = "10-12", item = "Ammo_IS.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
]

[sections.right_torso]
armor = 24
rear = 10
slots = [
    { at = "4-8", item = "IS.LRM-20" },
    { at = 9, item = "ArtemisIV" },
    { at = "10-12", item = "Ammo_IS.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
]

[sections.center_torso]
armor = 35
rear = 15
slots = [
    { at = "11-12", item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.left_leg]
armor = 34
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 34
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.Anti-MissileSystem" },
]
