name = "Warrior"
class = "vtol"
movement = "vtol"
tons = 21
max_speed = 161.25
computer = 4
specials = ["Searchlight"]

[sections.left_side]
armor = 5
internals = 2

[sections.right_side]
armor = 5
internals = 2

[sections.front_side]
armor = 6
internals = 2
slots = [
    { at = 1, item = "IS.AC/5" },
    { at = "2-3", item = "Ammo_IS.AC/5", rounds = 20 },
    { at = 4, item = "IS.MachineGun" },
    { at = 5, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
]

[sections.aft_side]
armor = 6
internals = 2

[sections.rotor]
armor = 2
internals = 2
