name = "Hawk Moth"
class = "vtol"
movement = "vtol"
tons = 25
max_speed = 129.0

[sections.left_side]
armor = 6
internals = 3
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 6
internals = 3
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 9
internals = 3
slots = [
    { at = 1, item = "IS.LightGaussRifle" },
    { at = "2-3", item = "Ammo_IS.LightGaussRifle", rounds = 16 },
]

[sections.aft_side]
armor = 4
internals = 3

[sections.rotor]
armor = 2
internals = 3
