name = "Swayback"
class = "mech"
movement = "biped"
tons = 50
max_speed = 64.5
heat_sinks = 19
cargo_space = 0
max_suits = 0

[sections.left_arm]
armor = 16
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 16
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 20
internals = 12
rear = 4
slots = [
    { at = "1-2", item = "IS.SRM-6" },
    { at = "3-6", item = "HeatSink" },
]

[sections.right_torso]
armor = 20
internals = 12
rear = 4
slots = [
    { at = "1-2", item = "IS.SRM-6" },
    { at = "3-5", item = "HeatSink" },
]

[sections.center_torso]
armor = 26
internals = 16
rear = 5
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.left_leg]
armor = 20
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 20
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "IS.SmallLaser" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
