name = "Hellhound"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 9
jump_mp = 6
heat_sinks = 20
computer = 4

[construction]
tech_base = "clan"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 14
slots = [
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 14
slots = [
    { at = "5-6", item = "CL.LargePulseLaser" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 19
rear = 5
slots = [
    { at = "1-2", item = "CL.StreakSRM-2" },
    { at = "3-4", item = "JumpJet" },
    { at = 5, item = "Ammo_CL.StreakSRM-2", rounds = 50 },
    { at = "10-11", item = "FerroFibrous" },
    { at = 12, item = "EndoSteel" },
]

[sections.right_torso]
armor = 19
rear = 5
slots = [
    { at = "1-2", item = "CL.ERMediumLaser" },
    { at = "3-4", item = "JumpJet" },
    { at = 10, item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 23
rear = 7
slots = [
    { at = "11-12", item = "JumpJet" },
]

[sections.left_leg]
armor = 24
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
