name = "Hetzer"
class = "vehicle"
movement = "wheel"
tons = 40
max_speed = 64.5
computer = 3
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 22
internals = 4

[sections.right_side]
armor = 22
internals = 4

[sections.front_side]
armor = 30
internals = 4
slots = [
    { at = 1, item = "IS.AC/20", brand = 3 },
    { at = "2-5", item = "Ammo_IS.AC/20", rounds = 5 },
]

[sections.aft_side]
armor = 22
internals = 4
