name = "Hoplite"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 6
heat_sinks = 16
radio = 4
cargo_space = 0
max_suits = 0

[construction]

[sections.left_arm]
armor = 18
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.LRM-5" },
]

[sections.right_arm]
armor = 18
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "IS.LB10-XAC" },
]

[sections.left_torso]
armor = 18
rear = 8
slots = [
    { at = "1-2", item = "HeatSink" },
]

[sections.right_torso]
armor = 18
rear = 8
slots = [
    { at = "1-2", item = "HeatSink" },
    { at = 3, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 4, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
]

[sections.center_torso]
armor = 26
rear = 9
slots = [
    { at = 11, item = "Ammo_IS.LRM-5", rounds = 24 },
]

[sections.left_leg]
armor = 26
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 26
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
