name = "Hussar"
class = "mech"
movement = "biped"
tons = 30
walk_mp = 12
radio = 4

[construction]
engine = "xl"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 2
slots = [
    { at = "5-7", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 2
slots = [
    { at = "5-7", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 8
rear = 1
slots = [
    { at = "4-9", item = "IS.LB10-XAC" },
]

[sections.right_torso]
armor = 8
rear = 1
slots = [
    { at = "4-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 11
rear = 2
slots = [
    { at = 11, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_leg]
armor = 5
slots = [
    { at = 5, item = "HeatSink" },
]

[sections.right_leg]
armor = 5

[sections.head]
armor = 9
