name = "Hatamoto-Hi"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
heat_sinks = 18
computer = 4
radio = 4

[construction]
structure = "endo_steel"
brand = 3

[sections.left_arm]
armor = 26
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "IS.PPC", brand = 3 },
]

[sections.right_arm]
armor = 26
slots = [
    { at = "5-7", item = "IS.PPC", brand = 3 },
]

[sections.left_torso]
armor = 25
rear = 9
slots = [
    { at = "1-2", item = "IS.MediumPulseLaser", brand = 3 },
    { at = "3-9", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 25
rear = 9
slots = [
    { at = "1-5", item = "C3Master", brand = 3 },
    { at = "6-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 34
rear = 16
slots = [
    { at = "11-12", item = "HeatSink", brand = 3 },
]

[sections.left_leg]
armor = 34
slots = [
    { at = "5-6", item = "HeatSink", brand = 3 },
]

[sections.right_leg]
armor = 34
slots = [
    { at = "5-6", item = "HeatSink", brand = 3 },
]

[sections.head]
armor = 9
