name = "Icestorm"
class = "mech"
movement = "biped"
tons = 25
walk_mp = 18

[construction]
tech_base = "clan"
engine = "xl"

[sections.left_arm]
armor = 6

[sections.right_arm]
armor = 6
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "CL.ERMediumLaser" },
]

[sections.left_torso]
armor = 6
rear = 1

[sections.right_torso]
armor = 6
rear = 1
slots = [
    { at = 3, item = "Ammo_CL.SRM-2", rounds = 50 },
]

[sections.center_torso]
armor = 8
rear = 2
slots = [
    { at = 11, item = "TAG" },
]

[sections.left_leg]
armor = 7

[sections.right_leg]
armor = 7

[sections.head]
armor = 6
slots = [
    { at = 4, item = "CL.SRM-2" },
]
