name = "J-27"
class = "vehicle"
movement = "track"
tons = 20
walk_mp = 8
cargo_space = 3072
specials = ["CargoTech"]

[construction]
engine = "ice"

[sections.left_side]
armor = 5

[sections.right_side]
armor = 5

[sections.front_side]
armor = 6

[sections.aft_side]
armor = 6

[sections.turret]
armor = 2
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
    { at = 2, item = "Ammo_IS.MachineGun", rounds = 200 },
]
