name = "Jenner"
class = "mech"
movement = "biped"
tons = 35
walk_mp = 11
jump_mp = 5
computer = 2
radio = 2

[sections.left_arm]
armor = 11
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 11
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 11
rear = 5
slots = [
    { at = "1-2", item = "JumpJet" },
]

[sections.right_torso]
armor = 11
rear = 5
slots = [
    { at = "1-2", item = "JumpJet" },
]

[sections.center_torso]
armor = 15
rear = 6
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "HeatSink" },
]

[sections.left_leg]
armor = 15

[sections.right_leg]
armor = 15

[sections.head]
armor = 7
