name = "King Crab"
class = "mech"
movement = "biped"
tons = 100
max_speed = 53.75
heat_sinks = 15

[sections.left_arm]
armor = 33
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-12", item = "IS.AC/20" },
]

[sections.right_arm]
armor = 33
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-12", item = "IS.AC/20" },
]

[sections.left_torso]
armor = 29
internals = 21
rear = 10
slots = [
    { at = 3, item = "Ammo_IS.AC/20", rounds = 5 },
    { at = "4-6", item = "IS.LRM-15" },
    { at = 7, item = "Ammo_IS.LRM-15", rounds = 8 },
]

[sections.right_torso]
armor = 29
internals = 21
rear = 10
slots = [
    { at = 3, item = "Ammo_IS.AC/20", rounds = 5 },
    { at = "4-5", item = "IS.LargeLaser" },
]

[sections.center_torso]
armor = 39
internals = 31
rear = 12
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "HeatSink" },
]

[sections.left_leg]
armor = 34
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "HeatSink" },
]

[sections.right_leg]
armor = 34
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
