name = "Kintaro"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 8
heat_sinks = 20
computer = 4
radio = 4
cargo_space = 0

[construction]
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 17
slots = [
    { at = "5-6", item = "IS.SRM-6", brand = 3 },
    { at = 7, item = "FerroFibrous", brand = 3 },
    { at = "8-9", item = "FerroFibrous", brand = 0 },
    { at = "10-11", item = "EndoSteel", brand = 0 },
]

[sections.right_arm]
armor = 17
slots = [
    { at = "5-6", item = "IS.ERMediumLaser", brand = 3 },
    { at = "7-12", item = "EndoSteel", brand = 0 },
]

[sections.left_torso]
armor = 18
rear = 6
slots = [
    { at = "1-3", item = "IS.iNarcBeacon", brand = 3 },
    { at = "4-9", item = "FerroFibrous", brand = 3 },
    { at = "10-12", item = "FerroFibrous", brand = 0 },
]

[sections.right_torso]
armor = 18
rear = 6
slots = [
    { at = "1-2", item = "IS.SRM-6", brand = 3 },
    { at = "3-5", item = "Ammo_IS.iNarcBeacon", rounds = 4 },
    { at = "6-7", item = "Ammo_IS.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
    { at = "8-10", item = "EndoSteel", brand = 3 },
    { at = 11, item = "EndoSteel", brand = 0 },
    { at = 12, item = "Case", brand = 0 },
]

[sections.center_torso]
armor = 23
rear = 8
slots = [
    { at = "11-12", item = "C3i", brand = 3 },
]

[sections.left_leg]
armor = 24
slots = [
    { at = "5-6", item = "FerroFibrous", brand = 0 },
]

[sections.right_leg]
armor = 24
slots = [
    { at = "5-6", item = "EndoSteel", brand = 0 },
]

[sections.head]
armor = 9
