name = "LaoHu"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 8
heat_sinks = 20
computer = 4
radio = 4
specials = ["ArtemisIV", "C3MasterTech"]

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"

[sections.left_arm]
armor = 21
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.ERLargeLaser" },
    { at = "6-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 21
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "IS.LB10-XAC" },
]

[sections.left_torso]
armor = 21
rear = 7
slots = [
    { at = "4-5", item = "IS.LRM-10" },
    { at = "6-7", item = "Ammo_IS.LRM-10", rounds = 12, modes = ["Artemis/Mine"] },
    { at = "8-11", item = "EndoSteel" },
    { at = 12, item = "ArtemisIV" },
]

[sections.right_torso]
armor = 21
rear = 7
slots = [
    { at = "4-8", item = "C3Master" },
    { at = "9-10", item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 11, item = "Ammo_IS.LB10-XAC", rounds = 10 },
]

[sections.center_torso]
armor = 28
rear = 9

[sections.left_leg]
armor = 28
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 28
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.head]
armor = 9
