name = "Lightning"
class = "vehicle"
movement = "hover"
tons = 35
walk_mp = 17

[sections.left_side]
armor = 16
slots = [
    { at = 1, item = "IS.SRM-4", modes = ["OneShot"] },
]

[sections.right_side]
armor = 16
slots = [
    { at = 1, item = "IS.SRM-4", modes = ["OneShot"] },
]

[sections.front_side]
armor = 20
slots = [
    { at = "1-2", item = "IS.MediumPulseLaser" },
]

[sections.aft_side]
armor = 11
