name = "Linebacker"
class = "mech"
movement = "biped"
tons = 65
walk_mp = 9
heat_sinks = 28
computer = 4

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 20
explicit = true
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = "2-3", item = "CL.ERPPC" },
    { at = 4, item = "EndoSteel" },
    { at = 5, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 20
explicit = true
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = "2-3", item = "CL.ERPPC" },
    { at = 4, item = "EndoSteel" },
    { at = 5, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 22
rear = 8
engine_at = 3
slots = [
    { at = 1, item = "EndoSteel" },
    { at = 2, item = "FerroFibrous" },
    { at = 5, item = "CL.LRM-5" },
    { at = 6, item = "Ammo_CL.LRM-5", rounds = 24 },
]

[sections.right_torso]
armor = 22
rear = 8
engine_at = 3
slots = [
    { at = 1, item = "EndoSteel" },
    { at = 2, item = "FerroFibrous" },
    { at = 5, item = "CL.StreakSRM-4" },
    { at = 6, item = "Ammo_CL.StreakSRM-4", rounds = 25 },
    { at = 7, item = "CL.ERSmallLaser", modes = ["RearMount"] },
]

[sections.center_torso]
armor = 23
rear = 10
slots = [
    { at = 11, item = "EndoSteel" },
]

[sections.left_leg]
armor = 25
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.right_leg]
armor = 25
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
