name = "Lancelot"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 9
heat_sinks = 28
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 16
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser" },
    { at = "5-11", item = "EndoSteel" },
]

[sections.right_arm]
armor = 16
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser" },
    { at = "5-11", item = "EndoSteel" },
]

[sections.left_torso]
armor = 18
rear = 10
slots = [
    { at = "4-8", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 18
rear = 10
slots = [
    { at = "4-6", item = "IS.ERPPC" },
    { at = "7-11", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 23
rear = 16
slots = [
    { at = "11-12", item = "C3i" },
]

[sections.left_leg]
armor = 22
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.right_leg]
armor = 22
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.head]
armor = 9
