name = "Lynx"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 8
jump_mp = 5
heat_sinks = 30
computer = 4
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 18
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.MediumLaser", brand = 3 },
]

[sections.right_arm]
armor = 18
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-5", item = "IS.ERPPC", brand = 3 },
]

[sections.left_torso]
armor = 20
rear = 6
slots = [
    { at = "4-9", item = "HeatSink", brand = 3 },
    { at = 10, item = "IS.MediumLaser", brand = 3 },
]

[sections.right_torso]
armor = 20
rear = 6
slots = [
    { at = "4-9", item = "HeatSink", brand = 3 },
    { at = "10-11", item = "IS.LargeLaser", brand = 3 },
]

[sections.center_torso]
armor = 28
rear = 8
slots = [
    { at = 11, item = "JumpJet", brand = 3 },
    { at = 12, item = "IS.MediumLaser", brand = 3 },
]

[sections.left_leg]
armor = 26
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.right_leg]
armor = 26
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.head]
armor = 9
