name = "SRM Carrier"
class = "vehicle"
movement = "wheel"
tons = 40
walk_mp = 6

[sections.left_side]
armor = 14

[sections.right_side]
armor = 14

[sections.front_side]
armor = 16

[sections.aft_side]
armor = 16

[sections.turret]
armor = 14
slots = [
    { at = "1-5", item = "IS.SRM-6", brand = 3 },
    { at = "6-8", item = "Ammo_IS.SRM-6", rounds = 15 },
]
