name = "Mackie"
class = "mech"
movement = "biped"
tons = 100
max_speed = 53.75
heat_sinks = 15
radio = 2
cargo_space = 0

[sections.left_arm]
armor = 24
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-6", item = "IS.PPC", brand = 3 },
]

[sections.right_arm]
armor = 24
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-10", item = "IS.AC/10", brand = 3 },
]

[sections.left_torso]
armor = 20
internals = 21
rear = 10
slots = [
    { at = "1-2", item = "HeatSink", brand = 3 },
]

[sections.right_torso]
armor = 20
internals = 21
rear = 10
slots = [
    { at = 1, item = "HeatSink", brand = 3 },
    { at = "2-3", item = "Ammo_IS.AC/10", rounds = 10 },
]

[sections.center_torso]
armor = 30
internals = 31
rear = 10
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "IS.MediumLaser", brand = 3 },
]

[sections.left_leg]
armor = 28
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_leg]
armor = 28
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.head]
armor = 8
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
