name = "Marauder"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
heat_sinks = 32
radio = 4
specials = ["SearchLight"]

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 22
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = "7-9", item = "IS.ERPPC" },
    { at = 10, item = "IS.MediumPulseLaser" },
]

[sections.right_arm]
armor = 22
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = "7-9", item = "IS.ERPPC" },
    { at = 10, item = "IS.MediumPulseLaser" },
]

[sections.left_torso]
armor = 17
rear = 8
slots = [
    { at = "4-9", item = "HeatSink" },
    { at = 10, item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.right_torso]
armor = 17
rear = 8
slots = [
    { at = "4-10", item = "IS.GaussRifle" },
    { at = 11, item = "Case" },
]

[sections.center_torso]
armor = 35
rear = 10

[sections.left_leg]
armor = 18

[sections.right_leg]
armor = 18

[sections.head]
armor = 9
