name = "MadCat"
class = "mech"
movement = "biped"
tons = 75
max_speed = 86.0
heat_sinks = 30
specials = ["Clan", "ArtemisIV"]

[sections.left_arm]
armor = 24
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "4-5", item = "CL.LargePulseLaser" },
    { at = 6, item = "CL.SmallPulseLaser" },
    { at = 7, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 24
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-8", item = "CL.GaussRifle" },
    { at = 9, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 10, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 25
internals = 16
rear = 7
slots = [
    { at = "1-2", item = "Engine" },
    { at = 3, item = "CL.LRM-10" },
    { at = 4, item = "ArtemisIV" },
    { at = 5, item = "Ammo_CL.LRM-10", rounds = 12, modes = ["Artemis/Mine"] },
    { at = 6, item = "EndoSteel" },
    { at = "7-8", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 25
internals = 16
rear = 7
slots = [
    { at = "1-2", item = "Engine" },
    { at = 3, item = "CL.SRM-4" },
    { at = 4, item = "ArtemisIV" },
    { at = 5, item = "Ammo_CL.SRM-4", rounds = 25, modes = ["Artemis/Mine"] },
    { at = 6, item = "EndoSteel" },
    { at = "7-8", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 36
internals = 23
rear = 9
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "EndoSteel" },
]

[sections.left_leg]
armor = 32
internals = 16
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 32
internals = 16
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "FerroFibrous" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
