name = "ManO'War"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 8
heat_sinks = 32
computer = 4
specials = ["ArtemisIV"]

[construction]
tech_base = "clan"
engine = "xl"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 23
slots = [
    { at = 5, item = "CL.LRM-10" },
    { at = 6, item = "ArtemisIV" },
    { at = 7, item = "CL.SRM-4" },
    { at = 8, item = "ArtemisIV" },
    { at = 9, item = "Ammo_CL.LRM-10", rounds = 12 },
    { at = 10, item = "Ammo_CL.SRM-4", rounds = 25 },
]

[sections.right_arm]
armor = 23
omit = ["hand_actuator"]
slots = [
    { at = "4-9", item = "CL.GaussRifle" },
    { at = "10-11", item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.left_torso]
armor = 24
rear = 10
slots = [
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 24
rear = 10
slots = [
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 30
rear = 10

[sections.left_leg]
armor = 24
slots = [
    { at = 6, item = "FerroFibrous" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = 6, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
