name = "Manteuffel"
class = "vehicle"
movement = "track"
tons = 70
walk_mp = 8
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"

[sections.left_side]
armor = 40

[sections.right_side]
armor = 40

[sections.front_side]
armor = 56
slots = [
    { at = 1, item = "IS.ERSmallLaser" },
    { at = 2, item = "IS.HeavyGaussRifle" },
]

[sections.aft_side]
armor = 25
slots = [
    { at = "1-4", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
    { at = 5, item = "FerroFibrous" },
    { at = 12, item = "Case" },
]

[sections.turret]
armor = 45
slots = [
    { at = 1, item = "IS.MediumLaser" },
]
