name = "Masakari"
class = "mech"
movement = "biped"
tons = 85
walk_mp = 6
heat_sinks = 40

[construction]
tech_base = "clan"
engine = "xl"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 28
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "CL.GaussRifle", modes = ["OnTC"] },
    { at = "9-10", item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 11, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 28
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "CL.ERMediumLaser", modes = ["OnTC"] },
    { at = "7-11", item = "Ammo_CL.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 26
rear = 10
slots = [
    { at = "3-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 26
rear = 10
slots = [
    { at = "3-4", item = "HeatSink" },
    { at = "5-8", item = "TargetingComputer" },
    { at = "9-10", item = "CL.SRM-6" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 34
rear = 10
slots = [
    { at = 11, item = "CL.NarcBeacon" },
    { at = 12, item = "Ammo_CL.NarcBeacon", rounds = 6 },
]

[sections.left_leg]
armor = 35
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 35
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
