name = "MASH Truck"
class = "vehicle"
movement = "wheel"
tons = 35
max_speed = 86.0
cargo_space = 10000
max_suits = 0
max_ton = 100
specials = ["Carrier_Tech"]

[sections.left_side]
armor = 16
internals = 4

[sections.right_side]
armor = 16
internals = 4

[sections.front_side]
armor = 12
internals = 4

[sections.aft_side]
armor = 10
internals = 4

[sections.turret]
armor = 10
internals = 4
slots = [
    { at = "1-2", item = "IS.SmallLaser" },
]
