name = "Maultier"
class = "vehicle"
movement = "hover"
tons = 15
walk_mp = 14
cargo_space = 300
max_suits = 0
max_ton = 3
specials = ["CargoTech"]

[construction]
engine = "ice"

[sections.left_side]
armor = 10

[sections.right_side]
armor = 10

[sections.front_side]
armor = 15
slots = [
    { at = 1, item = "IS.StreakSRM-2" },
    { at = 2, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 10
