name = "Marshal"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 6
jump_mp = 4
heat_sinks = 18
computer = 4
radio = 4

[construction]
armor = "ferro_fibrous"
brand = 3

[sections.left_arm]
armor = 18
slots = [
    { at = 5, item = "IS.MediumLaser", brand = 3 },
    { at = "6-7", item = "FerroFibrous", brand = 3 },
]

[sections.right_arm]
armor = 18
slots = [
    { at = "5-6", item = "IS.LargeLaser", brand = 3 },
    { at = "7-8", item = "FerroFibrous", brand = 3 },
]

[sections.left_torso]
armor = 20
rear = 6
slots = [
    { at = "1-5", item = "HeatSink", brand = 3 },
    { at = "6-7", item = "IS.MachineGun", brand = 3 },
    { at = 8, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
    { at = "9-12", item = "FerroFibrous", brand = 3 },
]

[sections.right_torso]
armor = 20
rear = 6
slots = [
    { at = "1-5", item = "HeatSink", brand = 3 },
    { at = 6, item = "IS.MediumPulseLaser", brand = 3 },
    { at = 7, item = "IS.LRM-5", brand = 3 },
    { at = 8, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "9-12", item = "FerroFibrous", brand = 3 },
]

[sections.center_torso]
armor = 26
rear = 8
slots = [
    { at = 11, item = "IS.Flamer", brand = 3 },
    { at = 12, item = "FerroFibrous", brand = 3 },
]

[sections.left_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.right_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous", brand = 3 },
]
