name = "Mithras"
class = "vehicle"
movement = "track"
tons = 25
walk_mp = 6

[construction]
tech_base = "clan"
armor = "ferro_fibrous"

[sections.left_side]
armor = 14
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 14
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 16
slots = [
    { at = 1, item = "CL.ERMediumLaser" },
]

[sections.aft_side]
armor = 9

[sections.turret]
armor = 14
slots = [
    { at = 1, item = "CL.ERMediumLaser" },
    { at = 2, item = "CL.UltraAC/2" },
    { at = 3, item = "Ammo_CL.UltraAC/2", rounds = 45 },
]
