name = "Night Gyr"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
jump_mp = 4
heat_sinks = 32
computer = 5
radio = 5
cargo_space = 0
max_suits = 0

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "laser"

[sections.left_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "CL.LargePulseLaser" },
    { at = "5-6", item = "CL.MediumPulseLaser" },
    { at = "7-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-10", item = "CL.UltraAC/20" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 22
rear = 10
slots = [
    { at = "3-4", item = "CL.StreakSRM-6" },
    { at = 5, item = "Ammo_CL.StreakSRM-6", rounds = 15 },
    { at = "6-7", item = "HeatSink" },
    { at = "8-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 22
rear = 10
slots = [
    { at = "3-4", item = "CL.StreakSRM-6" },
    { at = "5-7", item = "Ammo_CL.UltraAC/20", rounds = 5 },
    { at = "8-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 34
rear = 10
slots = [
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.MediumPulseLaser" },
]
