name = "Night Gyr"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
jump_mp = 4
heat_sinks = 24
radio = 5
cargo_space = 0
max_suits = 0

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "laser"

[sections.left_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "CL.GaussRifle" },
    { at = "9-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "CL.GaussRifle" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 22
rear = 10
slots = [
    { at = "3-5", item = "CL.LB2-XAC" },
    { at = 6, item = "Ammo_CL.LB2-XAC", rounds = 45 },
    { at = 7, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = "8-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 22
rear = 10
slots = [
    { at = "3-5", item = "CL.LB2-XAC" },
    { at = "6-7", item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = "8-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 34
rear = 10

[sections.left_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
