name = "Night Gyr"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
jump_mp = 4
heat_sinks = 24
radio = 5
cargo_space = 0
max_suits = 0

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "laser"

[sections.left_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-6", item = "CL.LRM-20" },
    { at = 7, item = "ArtemisIV" },
    { at = "8-10", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 24
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-6", item = "CL.LRM-20" },
    { at = 7, item = "ArtemisIV" },
    { at = "8-10", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "11-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 22
rear = 10
slots = [
    { at = "3-6", item = "CL.LRM-20" },
    { at = 7, item = "ArtemisIV" },
    { at = "8-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 22
rear = 10
slots = [
    { at = "3-6", item = "CL.LRM-20" },
    { at = 7, item = "ArtemisIV" },
    { at = "8-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 34
rear = 10
slots = [
    { at = "11-12", item = "CL.LargePulseLaser" },
]

[sections.left_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 28
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.MediumPulseLaser" },
]
