name = "Nobori-nin"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 8
jump_mp = 5
heat_sinks = 24

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 16
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "FerroFibrous" },
    { at = "5-6", item = "EndoSteel" },
    { at = "7-8", item = "CL.LargePulseLaser" },
    { at = 9, item = "CL.LRM-10" },
]

[sections.right_arm]
armor = 16
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "EndoSteel" },
    { at = "5-6", item = "CL.LargePulseLaser" },
    { at = "7-9", item = "CL.LB2-XAC" },
]

[sections.left_torso]
armor = 18
rear = 6
slots = [
    { at = 3, item = "EndoSteel" },
    { at = "4-6", item = "FerroFibrous" },
    { at = 7, item = "JumpJet" },
    { at = 8, item = "Ammo_CL.LRM-10", rounds = 12 },
    { at = "9-10", item = "HeatSink" },
]

[sections.right_torso]
armor = 18
rear = 6
slots = [
    { at = 3, item = "EndoSteel" },
    { at = "4-5", item = "FerroFibrous" },
    { at = 6, item = "JumpJet" },
    { at = 7, item = "Ammo_CL.LB2-XAC", rounds = 45 },
    { at = "8-9", item = "HeatSink" },
]

[sections.center_torso]
armor = 25
rear = 7
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 24
slots = [
    { at = 5, item = "JumpJet" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = 5, item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
