name = "Ontos"
class = "vehicle"
movement = "track"
tons = 95
walk_mp = 5
specials = ["SearchLight"]

[construction]
engine = "ice"

[sections.left_side]
armor = 30

[sections.right_side]
armor = 30

[sections.front_side]
armor = 35
slots = [
    { at = "1-5", item = "Ammo_IS.LRM-20", rounds = 6 },
]

[sections.aft_side]
armor = 30

[sections.turret]
armor = 35
slots = [
    { at = "1-2", item = "IS.LRM-20" },
    { at = "3-7", item = "Ammo_IS.LRM-20", rounds = 6 },
    { at = "8-9", item = "IS.LRM-5" },
    { at = 10, item = "Ammo_IS.LRM-5", rounds = 24 },
]
