name = "Ostroc"
class = "mech"
movement = "biped"
tons = 60
max_speed = 86.0
heat_sinks = 30
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 8
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_arm]
armor = 8
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.left_torso]
armor = 22
internals = 14
rear = 4
slots = [
    { at = "1-2", item = "IS.ERLargeLaser", brand = 3 },
    { at = 3, item = "IS.MediumLaser", brand = 3 },
    { at = "4-9", item = "HeatSink", brand = 3 },
]

[sections.right_torso]
armor = 22
internals = 14
rear = 4
slots = [
    { at = 1, item = "IS.SRM-4", brand = 3 },
    { at = "2-3", item = "IS.ERLargeLaser", brand = 3 },
    { at = 4, item = "IS.MediumLaser", brand = 3 },
    { at = "5-7", item = "HeatSink", brand = 3 },
]

[sections.center_torso]
armor = 22
internals = 20
rear = 6
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = 11, item = "Ammo_IS.SRM-4", rounds = 25 },
]

[sections.left_leg]
armor = 20
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_leg]
armor = 20
internals = 14
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.head]
armor = 8
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
