name = "Ostsol"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 8
heat_sinks = 32
computer = 4
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 8
slots = [
    { at = "5-7", item = "HeatSink", brand = 3 },
]

[sections.right_arm]
armor = 8
slots = [
    { at = "5-7", item = "HeatSink", brand = 3 },
]

[sections.left_torso]
armor = 22
rear = 4
slots = [
    { at = "4-6", item = "HeatSink", brand = 3 },
    { at = "7-8", item = "IS.LargePulseLaser", brand = 3 },
    { at = 9, item = "IS.MediumPulseLaser", brand = 3 },
    { at = 10, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.right_torso]
armor = 22
rear = 4
slots = [
    { at = "4-6", item = "HeatSink", brand = 3 },
    { at = "7-8", item = "IS.LargePulseLaser", brand = 3 },
    { at = 9, item = "IS.MediumPulseLaser", brand = 3 },
    { at = 10, item = "IS.Anti-MissileSystem", brand = 3 },
]

[sections.center_torso]
armor = 22
rear = 6
slots = [
    { at = "11-12", item = "IS.MediumPulseLaser", modes = ["RearMount"], brand = 3 },
]

[sections.left_leg]
armor = 20

[sections.right_leg]
armor = 20

[sections.head]
armor = 8
