name = "Ostscout"
class = "mech"
movement = "biped"
tons = 35
max_speed = 129.0
jump_speed = 86.0
heat_sinks = 10
computer = 4
radio = 4
specials = ["FerroFibrous_Tech", "EndoSteel_Tech", "LightEngine_Tech", "BeagleProbe", "ECM"]

[sections.left_arm]
armor = 6
internals = 6
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = "5-7", item = "EndoSteel" },
    { at = "8-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 6
internals = 6
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = "5-7", item = "EndoSteel" },
    { at = "8-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 9
internals = 8
rear = 2
slots = [
    { at = "1-2", item = "Engine" },
    { at = "3-6", item = "JumpJet" },
    { at = "7-8", item = "Ecm" },
    { at = "9-10", item = "EndoSteel" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 9
internals = 8
rear = 2
slots = [
    { at = "1-2", item = "Engine" },
    { at = "3-6", item = "JumpJet" },
    { at = "7-8", item = "BeagleProbe" },
    { at = "9-10", item = "EndoSteel" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 11
internals = 11
rear = 4
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "TAG" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 8
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "IS.A-Pod" },
    { at = 6, item = "EndoSteel" },
]

[sections.right_leg]
armor = 8
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "IS.A-Pod" },
]

[sections.head]
armor = 7
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "EndoSteel" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
