name = "Ostscout"
class = "mech"
movement = "biped"
tons = 35
walk_mp = 12
jump_mp = 8
computer = 5
radio = 5
cargo_space = 0
max_suits = 0

[construction]
brand = 3

[sections.left_arm]
armor = 6

[sections.right_arm]
armor = 6

[sections.left_torso]
armor = 9
rear = 2
slots = [
    { at = "1-4", item = "JumpJet", brand = 3 },
]

[sections.right_torso]
armor = 9
rear = 2
slots = [
    { at = "1-4", item = "JumpJet", brand = 3 },
]

[sections.center_torso]
armor = 12
rear = 4
slots = [
    { at = 11, item = "TAG", brand = 3 },
]

[sections.left_leg]
armor = 8

[sections.right_leg]
armor = 8

[sections.head]
armor = 6
