name = "Partisan"
class = "vehicle"
movement = "track"
tons = 80
walk_mp = 5
tac_range = 30
lrs_range = 60
scan_range = 30
specials = ["AntiAircraft"]

[sections.left_side]
armor = 30
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 30
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 40

[sections.aft_side]
armor = 23
slots = [
    { at = 1, item = "C3Slave" },
]

[sections.turret]
armor = 38
slots = [
    { at = "1-2", item = "IS.RotaryAC/5" },
    { at = "3-4", item = "IS.LB2-XAC" },
    { at = "5-8", item = "Ammo_IS.RotaryAC/5", rounds = 20 },
    { at = 9, item = "Ammo_IS.LB2-XAC", rounds = 45 },
]
