name = "Partisan"
class = "vehicle"
movement = "track"
tons = 80
walk_mp = 5
specials = ["AntiAircraft"]

[construction]
engine = "ice"

[sections.left_side]
armor = 18

[sections.right_side]
armor = 18

[sections.front_side]
armor = 22
slots = [
    { at = "1-2", item = "IS.MachineGun", brand = 3 },
    { at = 3, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
]

[sections.aft_side]
armor = 16

[sections.turret]
armor = 22
slots = [
    { at = "1-5", item = "IS.AC/2", brand = 3 },
    { at = "6-9", item = "Ammo_IS.AC/2", rounds = 45 },
]
