name = "Patton"
class = "vehicle"
movement = "track"
tons = 65
max_speed = 64.5
computer = 3
cargo_space = 0
max_suits = 0

[sections.left_side]
armor = 46
internals = 7

[sections.right_side]
armor = 46
internals = 7

[sections.front_side]
armor = 52
internals = 7
slots = [
    { at = "1-2", item = "IS.MachineGun", brand = 0 },
    { at = 3, item = "Ammo_IS.MachineGun", rounds = 200 },
]

[sections.aft_side]
armor = 38
internals = 7
slots = [
    { at = 1, item = "FerroFibrous", brand = 0 },
]

[sections.turret]
armor = 51
internals = 7
slots = [
    { at = 1, item = "IS.UltraAC/10", brand = 0 },
    { at = "2-3", item = "IS.MediumLaser", brand = 0 },
    { at = "4-6", item = "Ammo_IS.UltraAC/10", rounds = 10 },
]
