name = "Patton"
class = "vehicle"
movement = "track"
tons = 65
walk_mp = 6
heat_sinks = 10
computer = 3

[sections.left_side]
armor = 46

[sections.right_side]
armor = 46

[sections.front_side]
armor = 51
slots = [
    { at = 1, item = "IS.SmallLaser", brand = 3 },
    { at = 2, item = "IS.Flamer", brand = 3 },
]

[sections.aft_side]
armor = 38

[sections.turret]
armor = 51
slots = [
    { at = 1, item = "IS.AC/10", brand = 3 },
    { at = "2-3", item = "Ammo_IS.AC/10", rounds = 10 },
    { at = 4, item = "IS.LRM-5", brand = 3 },
    { at = 5, item = "Ammo_IS.LRM-5", rounds = 24 },
]
