name = "Pegasus"
class = "vehicle"
movement = "hover"
tons = 35
walk_mp = 14
specials = ["SearchLight"]

[sections.left_side]
armor = 14

[sections.right_side]
armor = 14

[sections.front_side]
armor = 18
slots = [
    { at = 1, item = "IS.MediumPulseLaser" },
    { at = 2, item = "BeagleProbe" },
    { at = 3, item = "Ecm" },
    { at = 4, item = "TAG" },
]

[sections.aft_side]
armor = 19

[sections.turret]
armor = 16
slots = [
    { at = "1-2", item = "IS.SRM-6" },
    { at = 3, item = "Ammo_IS.SRM-6", rounds = 15 },
]
