name = "Phoenix Hawk"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 8
jump_mp = 5
heat_sinks = 20

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 20
slots = [
    { at = "5-6", item = "EndoSteel" },
    { at = "7-8", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 20
slots = [
    { at = "5-7", item = "EndoSteel" },
    { at = "8-9", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 20
rear = 10
slots = [
    { at = "3-4", item = "JumpJet" },
    { at = "5-8", item = "CL.LRM-10" },
    { at = "9-11", item = "Ammo_CL.LRM-10", rounds = 12 },
    { at = 12, item = "Ammo_CL.MachineGun", rounds = 100, modes = ["Hotload"] },
]

[sections.right_torso]
armor = 20
rear = 10
slots = [
    { at = "3-4", item = "JumpJet" },
    { at = "5-8", item = "CL.LRM-10" },
    { at = "9-11", item = "Ammo_CL.LRM-10", rounds = 12 },
    { at = 12, item = "FerroFibrous" },
]

[sections.center_torso]
armor = 26
rear = 15
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "CL.MachineGun" },
]

[sections.left_leg]
armor = 26
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.right_leg]
armor = 26
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.MachineGun" },
]
