name = "Pike"
class = "vehicle"
movement = "track"
tons = 60
max_speed = 53.75
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 25
internals = 6

[sections.right_side]
armor = 25
internals = 6

[sections.front_side]
armor = 33
internals = 6
slots = [
    { at = "1-2", item = "IS.SRM-2", brand = 3 },
    { at = 3, item = "Ammo_IS.SRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 25
internals = 6

[sections.turret]
armor = 36
internals = 6
slots = [
    { at = "1-3", item = "IS.AC/2", brand = 3 },
    { at = "4-8", item = "Ammo_IS.AC/2", rounds = 45 },
]
