name = "Pilum"
class = "vehicle"
movement = "wheel"
tons = 70
max_speed = 64.5

[sections.left_side]
armor = 33
internals = 7

[sections.right_side]
armor = 33
internals = 7

[sections.front_side]
armor = 40
internals = 7
slots = [
    { at = "1-2", item = "IS.MediumPulseLaser" },
]

[sections.aft_side]
armor = 33
internals = 7

[sections.turret]
armor = 40
internals = 7
slots = [
    { at = 1, item = "IS.ArrowIVSystem" },
    { at = "2-3", item = "IS.StreakSRM-2" },
    { at = "4-7", item = "Ammo_IS.ArrowIVSystem", rounds = 5 },
    { at = 8, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]
