name = "Plainsman"
class = "vehicle"
movement = "hover"
tons = 35
max_speed = 150.5
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 16
internals = 4

[sections.right_side]
armor = 16
internals = 4

[sections.front_side]
armor = 18
internals = 4
slots = [
    { at = 1, item = "IS.SRM-2", brand = 3 },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 12
internals = 4

[sections.turret]
armor = 18
internals = 4
slots = [
    { at = "1-2", item = "IS.SRM-6", brand = 3 },
    { at = "3-4", item = "Ammo_IS.SRM-6", rounds = 15 },
]
