name = "Pillager"
class = "mech"
movement = "biped"
tons = 100
walk_mp = 5
jump_mp = 3
heat_sinks = 20
computer = 4
radio = 4
cargo_space = 0
max_suits = 0

[construction]
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 34
slots = [
    { at = "5-6", item = "Ecm", brand = 3 },
    { at = "8-9", item = "StealthArmor", brand = 3 },
]

[sections.right_arm]
armor = 34
slots = [
    { at = "5-7", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "8-9", item = "StealthArmor", brand = 3 },
]

[sections.left_torso]
armor = 32
rear = 10
slots = [
    { at = "1-7", item = "IS.GaussRifle", brand = 3 },
    { at = 8, item = "JumpJet", brand = 3 },
    { at = 9, item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = 10, item = "Case", brand = 3 },
    { at = "11-12", item = "StealthArmor", brand = 3 },
]

[sections.right_torso]
armor = 32
rear = 10
slots = [
    { at = "1-7", item = "IS.GaussRifle", brand = 3 },
    { at = 8, item = "JumpJet", brand = 3 },
    { at = 9, item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = 10, item = "Case", brand = 3 },
    { at = "11-12", item = "StealthArmor", brand = 3 },
]

[sections.center_torso]
armor = 52
rear = 10
slots = [
    { at = 11, item = "JumpJet", brand = 3 },
    { at = 12, item = "IS.ERMediumLaser", brand = 3 },
]

[sections.left_leg]
armor = 42
slots = [
    { at = "5-6", item = "StealthArmor", brand = 3 },
]

[sections.right_leg]
armor = 42
slots = [
    { at = "5-6", item = "StealthArmor", brand = 3 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.ERMediumLaser", brand = 3 },
]
