name = "Po"
class = "vehicle"
movement = "track"
tons = 60
max_speed = 64.5
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 0
max_suits = 0
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 30
internals = 6
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
]

[sections.right_side]
armor = 30
internals = 6
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
]

[sections.front_side]
armor = 36
internals = 6

[sections.aft_side]
armor = 24
internals = 6

[sections.turret]
armor = 24
internals = 6
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
    { at = 2, item = "IS.LightGaussRifle", brand = 3 },
    { at = "3-5", item = "Ammo_IS.LightGaussRifle", rounds = 16 },
    { at = 6, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload", "Halfton"] },
    { at = 12, item = "Case", brand = 3 },
]
