name = "Red Shift"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 14
heat_sinks = 20
radio = 4
specials = ["ECM"]

[construction]
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 6
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
    { at = "5-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 6
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
    { at = "5-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 8
rear = 2
slots = [
    { at = "4-9", item = "HeatSink" },
    { at = "10-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 8
rear = 2
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = "7-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 9
rear = 3
slots = [
    { at = "11-12", item = "Ecm" },
]

[sections.left_leg]
armor = 8
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.right_leg]
armor = 8
slots = [
    { at = 5, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "TAG" },
]
