name = "Ripper"
class = "vtol"
movement = "vtol"
tons = 10
walk_mp = 18
cargo_space = 250
max_suits = 0
max_ton = 1

[sections.left_side]
armor = 5

[sections.right_side]
armor = 5

[sections.front_side]
armor = 10
slots = [
    { at = "1-2", item = "IS.MediumLaser" },
]

[sections.aft_side]
armor = 5

[sections.rotor]
armor = 2
