name = "Rotunda"
class = "vehicle"
movement = "wheel"
tons = 20
max_speed = 150.5
computer = 3
specials = ["FerroFibrous_Tech"]

[sections.left_side]
armor = 4
internals = 2

[sections.right_side]
armor = 4
internals = 2

[sections.front_side]
armor = 6
internals = 2
slots = [
    { at = 1, item = "IS.LargeLaser" },
    { at = 2, item = "IS.SRM-2" },
    { at = 3, item = "Ammo_IS.SRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 4
internals = 2
