name = "Razorback"
class = "mech"
movement = "biped"
tons = 30
walk_mp = 9
heat_sinks = 20
computer = 4
radio = 4

[construction]
engine = "light"
structure = "endo_steel"
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.StreakSRM-4" },
    { at = "4-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser" },
    { at = "5-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 10
rear = 4
slots = [
    { at = "3-4", item = "IS.MachineGun" },
    { at = 5, item = "Ammo_IS.StreakSRM-4", rounds = 25 },
    { at = 6, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Halfton"] },
    { at = "7-9", item = "HeatSink" },
    { at = "10-11", item = "EndoSteel" },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 10
rear = 4
slots = [
    { at = "3-4", item = "IS.MachineGun" },
    { at = "5-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 15
rear = 5
slots = [
    { at = "11-12", item = "FerroFibrous" },
]

[sections.left_leg]
armor = 14
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 14
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "EndoSteel" },
]
