name = "Sabutai"
class = "aerofighter"
movement = "fly"
tons = 75
walk_mp = 9
heat_sinks = 42
fuel = 450

[construction]
tech_base = "clan"
armor = "ferro_fibrous"

[sections.nose]
armor = 46
internals = 7
slots = [
    { at = 1, item = "CL.GaussRifle" },
    { at = 2, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 3, item = "CL.ERSmallLaser" },
]

[sections.left_wing]
armor = 35
internals = 7
slots = [
    { at = 1, item = "CL.ERPPC" },
    { at = 2, item = "CL.LargePulseLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_wing]
armor = 35
internals = 7
slots = [
    { at = 1, item = "CL.ERPPC" },
    { at = 2, item = "CL.LargePulseLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.cockpit]
armor = 16
internals = 7
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 30
internals = 7
slots = [
    { at = "1-2", item = "CL.ERSmallLaser" },
]

[sections.fuselage]
armor = 40
internals = 7
