name = "SalvageVTOL"
class = "vtol"
movement = "vtol"
tons = 100
walk_mp = 15
computer = 3
cargo_space = 0
specials = ["SalvageTech"]

[sections.left_side]
armor = 8
internals = 5
slots = [
    { at = 1, item = "IS.SmallLaser", brand = 3 },
]

[sections.right_side]
armor = 8
internals = 5
slots = [
    { at = 1, item = "IS.SmallLaser", brand = 3 },
]

[sections.front_side]
armor = 8
internals = 5
slots = [
    { at = 1, item = "BeagleProbe", brand = 3 },
]

[sections.aft_side]
armor = 8
internals = 5

[sections.rotor]
armor = 2
internals = 5
