name = "Schiltron"
class = "vehicle"
movement = "wheel"
tons = 80
max_speed = 53.75
heat_sinks = 32
specials = ["XLEngine_Tech"]

[sections.left_side]
armor = 34
internals = 8
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 34
internals = 8
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 46
internals = 8

[sections.aft_side]
armor = 25
internals = 8
slots = [
    { at = 1, item = "C3Master" },
    { at = 2, item = "Ecm" },
]

[sections.turret]
armor = 40
internals = 8
slots = [
    { at = "1-4", item = "IS.LargeLaser" },
]
