name = "Scimitar"
class = "vehicle"
movement = "hover"
tons = 35
max_speed = 129.0
computer = 3
specials = ["ICEEngine_Tech"]

[sections.left_side]
armor = 18
internals = 4

[sections.right_side]
armor = 18
internals = 4

[sections.front_side]
armor = 21
internals = 4

[sections.aft_side]
armor = 18
internals = 4

[sections.turret]
armor = 21
internals = 4
slots = [
    { at = 1, item = "IS.AC/5" },
    { at = "2-3", item = "IS.SRM-2" },
    { at = 4, item = "Ammo_IS.AC/5", rounds = 20 },
    { at = 5, item = "Ammo_IS.SRM-2", rounds = 50 },
]
