name = "Scytha"
class = "aerofighter"
movement = "fly"
tons = 90
max_speed = 96.75
heat_sinks = 48
fuel = 600
specials = ["Clan", "FerroFibrous_Tech"]

[sections.nose]
armor = 67
internals = 9
slots = [
    { at = 1, item = "CL.NarcBeacon" },
    { at = 2, item = "Ammo_CL.NarcBeacon", rounds = 6 },
    { at = 3, item = "CL.LRM-20" },
    { at = 4, item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Narc/Smoke"] },
    { at = 5, item = "CL.SRM-6" },
    { at = 6, item = "Ammo_CL.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
]

[sections.left_wing]
armor = 50
internals = 9
slots = [
    { at = 1, item = "CL.LRM-20" },
    { at = 2, item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Narc/Smoke"] },
    { at = 3, item = "CL.ERLargeLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_wing]
armor = 50
internals = 9
slots = [
    { at = 1, item = "CL.LRM-20" },
    { at = 2, item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Narc/Smoke"] },
    { at = 3, item = "CL.ERLargeLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.cockpit]
armor = 16
internals = 9
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 32
internals = 9
slots = [
    { at = 1, item = "CL.StreakSRM-6" },
    { at = 2, item = "Ammo_CL.StreakSRM-6", rounds = 15 },
]

[sections.fuselage]
armor = 64
internals = 9
