name = "Shadow Hawk"
class = "mech"
movement = "biped"
tons = 45
walk_mp = 9
jump_mp = 6
heat_sinks = 20
specials = ["SearchLight"]

[construction]
tech_base = "clan"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 12
slots = [
    { at = 5, item = "CL.MediumPulseLaser" },
]

[sections.right_arm]
armor = 12
slots = [
    { at = 5, item = "CL.MediumPulseLaser" },
    { at = 6, item = "EndoSteel" },
]

[sections.left_torso]
armor = 17
rear = 5
slots = [
    { at = "1-3", item = "JumpJet" },
    { at = "4-5", item = "CL.StreakSRM-2" },
    { at = 6, item = "Ammo_CL.StreakSRM-2", rounds = 50 },
    { at = "7-8", item = "EndoSteel" },
    { at = "9-10", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 17
rear = 5
slots = [
    { at = "1-3", item = "JumpJet" },
    { at = "4-5", item = "CL.StreakSRM-2" },
    { at = 6, item = "Ammo_CL.StreakSRM-2", rounds = 50 },
    { at = "7-8", item = "EndoSteel" },
    { at = "9-10", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 20
rear = 7
slots = [
    { at = 11, item = "CL.ERSmallLaser" },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_leg]
armor = 20
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.right_leg]
armor = 20
slots = [
    { at = 5, item = "EndoSteel" },
    { at = 6, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.ERMediumLaser" },
]
