name = "Sprint"
class = "vtol"
movement = "vtol"
tons = 10
max_speed = 215.0
cargo_space = 0
specials = ["CargoTech"]

[sections.left_side]
armor = 3
internals = 1
slots = [
    { at = "6-12", item = "FerroFibrous", brand = 3 },
]

[sections.right_side]
armor = 3
internals = 1
slots = [
    { at = "6-12", item = "FerroFibrous", brand = 3 },
]

[sections.front_side]
armor = 7
internals = 1

[sections.aft_side]
armor = 3
internals = 1

[sections.rotor]
armor = 2
internals = 1
