name = "Strider"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 9
radio = 4
cargo_space = 0

[construction]
structure = "endo_steel"

[sections.left_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.LRM-5" },
]

[sections.right_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.LRM-5" },
]

[sections.left_torso]
armor = 14
rear = 5
slots = [
    { at = 1, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "2-7", item = "EndoSteel" },
    { at = 8, item = "Case" },
]

[sections.right_torso]
armor = 14
rear = 5
slots = [
    { at = 1, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "2-7", item = "EndoSteel" },
    { at = 8, item = "Case" },
]

[sections.center_torso]
armor = 15
rear = 6
slots = [
    { at = "11-12", item = "IS.LargeLaser" },
]

[sections.left_leg]
armor = 14
slots = [
    { at = 5, item = "HeatSink" },
    { at = 6, item = "EndoSteel" },
]

[sections.right_leg]
armor = 14
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "C3Slave" },
]
