name = "SRM Carrier"
class = "vehicle"
movement = "track"
tons = 60
walk_mp = 5
specials = ["SearchLight"]

[construction]
engine = "ice"

[sections.left_side]
armor = 12
slots = [
    { at = 1, item = "Ammo_IS.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
]

[sections.right_side]
armor = 12
slots = [
    { at = 1, item = "Ammo_IS.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
]

[sections.front_side]
armor = 12
slots = [
    { at = 1, item = "IS.NarcBeacon" },
    { at = "2-10", item = "IS.SRM-6" },
    { at = 11, item = "Ammo_IS.NarcBeacon", rounds = 6 },
    { at = 12, item = "Ammo_IS.SRM-6", rounds = 15, modes = ["Narc/Smoke"] },
]

[sections.aft_side]
armor = 12
