name = "Shootist"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 6
heat_sinks = 26
radio = 4
specials = ["SearchLight"]

[construction]
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 22
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.MediumPulseLaser" },
    { at = "4-6", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 22
slots = [
    { at = "5-6", item = "IS.ERLargeLaser" },
    { at = "7-9", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 24
rear = 5
slots = [
    { at = "1-10", item = "IS.AC/20" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 24
rear = 5
slots = [
    { at = "1-6", item = "HeatSink" },
    { at = "7-8", item = "Ammo_IS.AC/20", rounds = 5 },
    { at = "9-10", item = "FerroFibrous" },
    { at = 11, item = "Case" },
]

[sections.center_torso]
armor = 34
rear = 10
slots = [
    { at = 11, item = "IS.MediumPulseLaser" },
]

[sections.left_leg]
armor = 30
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.right_leg]
armor = 30
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallLaser" },
]
