name = "Striker"
class = "mech"
movement = "biped"
tons = 80
max_speed = 64.5
heat_sinks = 24
computer = 4
radio = 4
specials = ["DoubleHS"]

[sections.left_arm]
armor = 26
internals = 13
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-7", item = "IS.AC/5", brand = 3 },
]

[sections.right_arm]
armor = 26
internals = 13
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
]

[sections.left_torso]
armor = 26
internals = 17
rear = 8
slots = [
    { at = "1-2", item = "IS.LargeLaser", brand = 3 },
    { at = 3, item = "Ammo_IS.AC/5", rounds = 20 },
]

[sections.right_torso]
armor = 26
internals = 17
rear = 8
slots = [
    { at = "1-3", item = "IS.ERPPC", brand = 3 },
]

[sections.center_torso]
armor = 40
internals = 25
rear = 10
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "IS.MediumPulseLaser", brand = 3 },
]

[sections.left_leg]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_leg]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
