name = "Striker"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
heat_sinks = 24
radio = 4

[construction]
heat_sinks = "double"

[sections.left_arm]
armor = 26
omit = ["hand_actuator"]
slots = [
    { at = "4-7", item = "IS.AC/5" },
]

[sections.right_arm]
armor = 26
omit = ["hand_actuator"]

[sections.left_torso]
armor = 26
rear = 8
slots = [
    { at = "1-2", item = "IS.LargeLaser" },
    { at = 3, item = "Ammo_IS.AC/5", rounds = 20 },
]

[sections.right_torso]
armor = 26
rear = 8
slots = [
    { at = "1-3", item = "IS.ERPPC" },
]

[sections.center_torso]
armor = 40
rear = 10
slots = [
    { at = "11-12", item = "IS.MediumPulseLaser" },
]

[sections.left_leg]
armor = 34

[sections.right_leg]
armor = 34

[sections.head]
armor = 9
