name = "Stinger"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 9
jump_mp = 6
specials = ["SearchLight"]

[sections.left_arm]
armor = 4
slots = [
    { at = 5, item = "IS.MachineGun" },
]

[sections.right_arm]
armor = 4
slots = [
    { at = 5, item = "IS.MachineGun" },
    { at = 6, item = "IS.MediumLaser", brand = 4 },
]

[sections.left_torso]
armor = 6
rear = 2
slots = [
    { at = "1-3", item = "JumpJet" },
    { at = "4-6", item = "HeatSink" },
]

[sections.right_torso]
armor = 6
rear = 2
slots = [
    { at = "1-3", item = "JumpJet" },
    { at = "4-6", item = "HeatSink" },
]

[sections.center_torso]
armor = 6
rear = 4
slots = [
    { at = 11, item = "Ammo_IS.MachineGun", rounds = 200 },
]

[sections.left_leg]
armor = 5

[sections.right_leg]
armor = 5

[sections.head]
armor = 4
