name = "Stalker"
class = "mech"
movement = "biped"
tons = 85
walk_mp = 5
heat_sinks = 26
computer = 4

[sections.left_arm]
armor = 22
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.MediumLaser", brand = 4 },
]

[sections.right_arm]
armor = 22
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.MediumLaser", brand = 4 },
    { at = "5-6", item = "IS.LRM-10" },
    { at = 7, item = "Ammo_IS.LRM-10", rounds = 12 },
]

[sections.left_torso]
armor = 25
rear = 5
slots = [
    { at = "1-5", item = "HeatSink" },
    { at = "6-7", item = "IS.LargeLaser", brand = 4 },
    { at = "8-9", item = "IS.SRM-6" },
    { at = 10, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.right_torso]
armor = 25
rear = 5
slots = [
    { at = "1-4", item = "HeatSink" },
    { at = "5-6", item = "IS.LargeLaser", brand = 4 },
    { at = "7-8", item = "IS.SRM-6" },
    { at = 9, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.center_torso]
armor = 36
rear = 9
slots = [
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 29
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 29
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "HeatSink" },
]
