name = "Striker"
class = "vehicle"
movement = "wheel"
tons = 35
max_speed = 86.0
computer = 3
specials = ["SearchLight", "ICEEngine_Tech"]

[sections.left_side]
armor = 20
internals = 4

[sections.right_side]
armor = 20
internals = 4

[sections.front_side]
armor = 24
internals = 4

[sections.aft_side]
armor = 18
internals = 4

[sections.turret]
armor = 22
internals = 4
slots = [
    { at = 1, item = "IS.SRM-6", brand = 3 },
    { at = 2, item = "IS.LRM-10", brand = 3 },
    { at = "3-4", item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 5, item = "Ammo_IS.LRM-10", rounds = 12 },
]
