name = "SturmFeur"
class = "vehicle"
movement = "track"
tons = 85
walk_mp = 5
specials = ["AntiAircraft"]

[construction]
engine = "ice"

[sections.left_side]
armor = 66

[sections.right_side]
armor = 66

[sections.front_side]
armor = 66
slots = [
    { at = 1, item = "IS.LRM-20" },
    { at = 2, item = "Ammo_IS.LRM-20", rounds = 6 },
]

[sections.aft_side]
armor = 48

[sections.turret]
armor = 66
slots = [
    { at = 1, item = "IS.LRM-20" },
    { at = "2-3", item = "Ammo_IS.LRM-20", rounds = 6 },
    { at = "4-5", item = "IS.MachineGun" },
    { at = 7, item = "Ammo_IS.MachineGun", rounds = 200 },
]
