name = "Supernova"
class = "mech"
movement = "biped"
tons = 90
max_speed = 53.75
jump_speed = 32.25
heat_sinks = 52
specials = ["Clan"]

[sections.left_arm]
armor = 26
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "5-7", item = "CL.ERLargeLaser" },
    { at = "8-11", item = "HeatSink" },
]

[sections.right_arm]
armor = 26
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "5-7", item = "CL.ERLargeLaser" },
    { at = "8-11", item = "HeatSink" },
]

[sections.left_torso]
armor = 26
internals = 19
rear = 8
slots = [
    { at = "1-10", item = "HeatSink" },
    { at = 11, item = "JumpJet" },
]

[sections.right_torso]
armor = 26
internals = 19
rear = 8
slots = [
    { at = "1-10", item = "HeatSink" },
    { at = 11, item = "JumpJet" },
]

[sections.center_torso]
armor = 33
internals = 29
rear = 10
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = 11, item = "JumpJet" },
]

[sections.left_leg]
armor = 30
internals = 19
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 30
internals = 19
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
