name = "Thunderhawk"
class = "mech"
movement = "biped"
tons = 100
walk_mp = 5
radio = 4

[construction]
engine = "xl"

[sections.left_arm]
armor = 34
slots = [
    { at = "5-6", item = "IS.MediumLaser" },
]

[sections.right_arm]
armor = 34
slots = [
    { at = "5-11", item = "IS.GaussRifle" },
    { at = 12, item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 32
rear = 10

[sections.right_torso]
armor = 32
rear = 10
slots = [
    { at = "4-10", item = "IS.GaussRifle" },
    { at = "11-12", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.center_torso]
armor = 50
rear = 12
slots = [
    { at = "11-12", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.left_leg]
armor = 42
slots = [
    { at = "5-6", item = "Ammo_IS.ArrowIVSystem", rounds = 5 },
]

[sections.right_leg]
armor = 42

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.MediumLaser" },
]
