name = "Thunderhawk"
class = "mech"
movement = "biped"
tons = 100
max_speed = 53.75
computer = 4
radio = 4

[sections.left_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-6", item = "IS.MediumLaser", brand = 3 },
]

[sections.right_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-11", item = "IS.GaussRifle", brand = 3 },
    { at = 12, item = "IS.MediumLaser", brand = 3 },
]

[sections.left_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-10", item = "IS.GaussRifle", brand = 3 },
    { at = "11-12", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.right_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-10", item = "IS.GaussRifle", brand = 3 },
    { at = "11-12", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.center_torso]
armor = 50
internals = 31
rear = 12
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.left_leg]
armor = 42
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.right_leg]
armor = 42
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 4, item = "IS.MediumLaser", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
