name = "Thunderbolt"
class = "mech"
movement = "biped"
tons = 65
max_speed = 64.5
jump_speed = 43.0
heat_sinks = 20
computer = 4
radio = 4
specials = ["DoubleHS", "FerroFibrous_Tech", "EndoSteel_Tech", "ECM"]

[sections.left_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "IS.MediumPulseLaser" },
    { at = "6-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 20
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-11", item = "IS.GaussRifle" },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 24
internals = 15
rear = 6
slots = [
    { at = "1-3", item = "IS.MediumPulseLaser" },
    { at = "4-10", item = "EndoSteel" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 24
internals = 15
rear = 6
slots = [
    { at = "1-2", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "3-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 32
internals = 21
rear = 9
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "Ecm" },
]

[sections.left_leg]
armor = 28
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 28
internals = 15
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "FerroFibrous" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
