name = "Typhoon"
class = "vehicle"
movement = "wheel"
tons = 70
max_speed = 53.75
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 0
max_suits = 0
specials = ["SearchLight"]

[sections.left_side]
armor = 40
internals = 7
slots = [
    { at = "6-12", item = "FerroFibrous", brand = 3 },
]

[sections.right_side]
armor = 40
internals = 7
slots = [
    { at = "6-12", item = "FerroFibrous", brand = 3 },
]

[sections.front_side]
armor = 43
internals = 7
slots = [
    { at = "1-2", item = "IS.StreakSRM-2", brand = 3 },
    { at = 3, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.aft_side]
armor = 32
internals = 7
slots = [
    { at = 1, item = "BeagleProbe", brand = 3 },
]

[sections.turret]
armor = 42
internals = 7
slots = [
    { at = "1-2", item = "IS.RotaryAC/5", brand = 3 },
    { at = "3-4", item = "IS.ERMediumLaser", brand = 3 },
    { at = "5-6", item = "IS.StreakSRM-2", brand = 3 },
    { at = "7-10", item = "Ammo_IS.RotaryAC/5", rounds = 20 },
]
