name = "Uziel"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 9
jump_mp = 6
heat_sinks = 20
computer = 4
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-5", item = "IS.PPC", brand = 3 },
    { at = "6-7", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-5", item = "IS.PPC", brand = 3 },
    { at = "6-7", item = "EndoSteel", brand = 3 },
]

[sections.left_torso]
armor = 14
rear = 4
slots = [
    { at = "4-6", item = "JumpJet", brand = 3 },
    { at = 7, item = "IS.MachineGun", brand = 3 },
    { at = 8, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 9, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload", "Halfton"] },
    { at = "10-11", item = "BeagleProbe", brand = 3 },
    { at = 12, item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 14
rear = 4
slots = [
    { at = "4-6", item = "JumpJet", brand = 3 },
    { at = 7, item = "IS.MachineGun", brand = 3 },
    { at = "8-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 17
rear = 6
slots = [
    { at = "11-12", item = "IS.SRM-6", brand = 3 },
]

[sections.left_leg]
armor = 18
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.right_leg]
armor = 18
slots = [
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.head]
armor = 9
