name = "Uziel"
class = "mech"
movement = "biped"
tons = 50
max_speed = 96.75
jump_speed = 64.5
heat_sinks = 22
computer = 4
radio = 4
cargo_space = 0
max_suits = 0
specials = ["DoubleHS"]

[sections.left_arm]
armor = 12
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-5", item = "IS.LargePulseLaser", brand = 3 },
    { at = "6-7", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 12
internals = 8
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = "4-7", item = "IS.LB2-XAC", brand = 3 },
    { at = 8, item = "IS.ERMediumLaser", brand = 3 },
]

[sections.left_torso]
armor = 14
internals = 12
rear = 4
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-6", item = "JumpJet", brand = 3 },
    { at = 7, item = "IS.ERSmallLaser", brand = 3 },
    { at = "8-12", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 14
internals = 12
rear = 4
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-6", item = "JumpJet", brand = 3 },
    { at = 7, item = "IS.ERSmallLaser", brand = 3 },
    { at = 8, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = 9, item = "Ammo_IS.LB2-XAC", rounds = 45, modes = ["LBX/Cluster"] },
    { at = "10-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 17
internals = 16
rear = 6
slots = [
    { at = "1-3", item = "Engine", brand = 3 },
    { at = "4-7", item = "Gyro", brand = 3 },
    { at = "8-10", item = "Engine", brand = 3 },
    { at = "11-12", item = "IS.SRM-6", brand = 3 },
]

[sections.left_leg]
armor = 18
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.right_leg]
armor = 18
internals = 12
slots = [
    { at = 1, item = "ShoulderOrHip", brand = 3 },
    { at = 2, item = "UpperActuator", brand = 3 },
    { at = 3, item = "LowerActuator", brand = 3 },
    { at = 4, item = "HandOrFootActuator", brand = 3 },
    { at = "5-6", item = "EndoSteel", brand = 3 },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport", brand = 3 },
    { at = 2, item = "Sensors", brand = 3 },
    { at = 3, item = "Cockpit", brand = 3 },
    { at = 5, item = "Sensors", brand = 3 },
    { at = 6, item = "LifeSupport", brand = 3 },
]
