name = "Vedette"
class = "vehicle"
movement = "track"
tons = 50
max_speed = 86.0
computer = 3
specials = ["SearchLight", "ICEEngine_Tech"]

[sections.left_side]
armor = 18
internals = 5

[sections.right_side]
armor = 18
internals = 5

[sections.front_side]
armor = 20
internals = 5
slots = [
    { at = 1, item = "IS.MachineGun", brand = 3 },
    { at = "2-3", item = "Ammo_IS.MachineGun", rounds = 200 },
]

[sections.aft_side]
armor = 20
internals = 5

[sections.turret]
armor = 20
internals = 5
slots = [
    { at = "1-2", item = "IS.MediumLaser", brand = 3 },
]
