name = "Visigoth"
class = "aerofighter"
movement = "fly"
tons = 60
max_speed = 118.25
heat_sinks = 32
fuel = 750
specials = ["Clan", "FerroFibrous_Tech"]

[sections.nose]
armor = 50
internals = 7
slots = [
    { at = "1-2", item = "CL.LargePulseLaser" },
]

[sections.left_wing]
armor = 36
internals = 7
slots = [
    { at = 1, item = "CL.LargePulseLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_wing]
armor = 36
internals = 7
slots = [
    { at = 1, item = "CL.LargePulseLaser" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.cockpit]
armor = 16
internals = 7
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 32
internals = 7
slots = [
    { at = 1, item = "CL.MediumPulseLaser" },
]

[sections.fuselage]
armor = 42
internals = 7
