name = "Vulcan"
class = "mech"
movement = "biped"
tons = 40
max_speed = 96.75
jump_speed = 64.5
heat_sinks = 12
specials = ["Searchlight"]

[sections.left_arm]
armor = 11
internals = 6
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.MachineGun" },
]

[sections.right_arm]
armor = 11
internals = 6
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "IS.Flamer" },
]

[sections.left_torso]
armor = 12
internals = 10
rear = 4
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "Ammo_IS.MachineGun", rounds = 200 },
    { at = "3-4", item = "JumpJet" },
    { at = 5, item = "HeatSink" },
]

[sections.right_torso]
armor = 12
internals = 10
rear = 4
slots = [
    { at = "1-3", item = "IS.MediumLaser" },
    { at = "4-5", item = "JumpJet" },
]

[sections.center_torso]
armor = 15
internals = 12
rear = 6
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "JumpJet" },
]

[sections.left_leg]
armor = 14
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "HeatSink" },
]

[sections.right_leg]
armor = 14
internals = 10
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "HeatSink" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
