name = "Vanquisher"
class = "mech"
movement = "biped"
tons = 100
max_speed = 53.75
heat_sinks = 24
computer = 4
radio = 4
specials = ["DoubleHS", "FlipArms", "EndoSteel_Tech"]

[sections.left_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-12", item = "IS.UltraAC/5" },
]

[sections.right_arm]
armor = 34
internals = 17
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = "3-12", item = "IS.UltraAC/5" },
]

[sections.left_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-3", item = "Ammo_IS.UltraAC/5", rounds = 20 },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = "5-9", item = "EndoSteel" },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 32
internals = 21
rear = 10
slots = [
    { at = "1-3", item = "Ammo_IS.UltraAC/5", rounds = 20 },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = "5-9", item = "EndoSteel" },
    { at = 12, item = "Case" },
]

[sections.center_torso]
armor = 47
internals = 31
rear = 15
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "C3i" },
]

[sections.left_leg]
armor = 42
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 42
internals = 21
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "IS.ERMediumLaser" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
