name = "Victor"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
jump_mp = 4
heat_sinks = 20
computer = 4
radio = 4
specials = ["ECM"]

[construction]
structure = "endo_steel"
armor = "stealth"
heat_sinks = "double"

[sections.left_arm]
armor = 26
slots = [
    { at = "5-6", item = "IS.ERMediumLaser" },
    { at = "7-10", item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.right_arm]
armor = 26
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-9", item = "IS.GaussRifle" },
    { at = 10, item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.left_torso]
armor = 26
rear = 8
slots = [
    { at = "1-2", item = "JumpJet" },
    { at = "3-4", item = "Ecm" },
    { at = "5-10", item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.right_torso]
armor = 26
rear = 8
slots = [
    { at = "1-2", item = "JumpJet" },
    { at = "3-4", item = "IS.SRM-6" },
    { at = 5, item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = "6-8", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = 9, item = "EndoSteel" },
    { at = 10, item = "Case" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.center_torso]
armor = 38
rear = 12
slots = [
    { at = 11, item = "IS.ERMediumLaser" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 34
slots = [
    { at = "5-6", item = "StealthArmor" },
]

[sections.right_leg]
armor = 34
slots = [
    { at = "5-6", item = "StealthArmor" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "EndoSteel" },
]
