name = "Wheeled_APC"
class = "vehicle"
movement = "wheel"
tons = 10
walk_mp = 9
cargo_space = 500
max_suits = 0
max_ton = 4

[construction]
engine = "ice"

[sections.left_side]
armor = 10

[sections.right_side]
armor = 10

[sections.front_side]
armor = 12

[sections.aft_side]
armor = 10

[sections.turret]
armor = 6
slots = [
    { at = "1-2", item = "IS.MachineGun" },
    { at = 3, item = "Ammo_IS.MachineGun", rounds = 200 },
]
