name = "Warhammer"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
heat_sinks = 40
computer = 4

[construction]
tech_base = "clan"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 24
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC" },
    { at = "9-11", item = "FerroFibrous" },
    { at = 12, item = "EndoSteel" },
]

[sections.right_arm]
armor = 24
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC" },
    { at = 6, item = "FerroFibrous" },
    { at = "9-10", item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 24
rear = 10
slots = [
    { at = "1-2", item = "CL.LRM-15" },
    { at = 3, item = "Ammo_CL.LRM-15", rounds = 8 },
    { at = "4-9", item = "HeatSink" },
    { at = 10, item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.right_torso]
armor = 24
rear = 10
slots = [
    { at = "1-2", item = "CL.LRM-15" },
    { at = 3, item = "Ammo_CL.LRM-15", rounds = 8 },
    { at = 4, item = "CL.SRM-6" },
    { at = 5, item = "Ammo_CL.SRM-6", rounds = 15 },
    { at = "6-9", item = "HeatSink" },
    { at = 10, item = "FerroFibrous" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 30
rear = 15
slots = [
    { at = "11-12", item = "HeatSink" },
]

[sections.left_leg]
armor = 30
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 30
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "CL.ERMediumLaser" },
]
