name = "War Dog"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
heat_sinks = 20
computer = 4
radio = 4

[construction]
engine = "xl"
armor = "ferro_fibrous"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 16
slots = [
    { at = "5-6", item = "IS.LargePulseLaser", brand = 3 },
    { at = "7-12", item = "FerroFibrous", brand = 3 },
]

[sections.right_arm]
armor = 24
omit = ["hand_actuator"]
slots = [
    { at = "4-10", item = "IS.GaussRifle", brand = 3 },
    { at = 11, item = "IS.MediumPulseLaser", brand = 3 },
    { at = 12, item = "FerroFibrous", brand = 3 },
]

[sections.left_torso]
armor = 23
rear = 9
slots = [
    { at = 4, item = "IS.MediumPulseLaser", brand = 3 },
    { at = "5-7", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "8-11", item = "FerroFibrous", brand = 3 },
]

[sections.right_torso]
armor = 23
rear = 9
slots = [
    { at = 4, item = "IS.Anti-MissileSystem", brand = 3 },
    { at = "5-6", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "7-8", item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
    { at = 9, item = "FerroFibrous", brand = 3 },
]

[sections.center_torso]
armor = 36
rear = 10
slots = [
    { at = "11-12", item = "Ecm", brand = 3 },
]

[sections.left_leg]
armor = 28
slots = [
    { at = 5, item = "IS.StreakSRM-2", modes = ["OneShot"], brand = 4 },
    { at = 6, item = "FerroFibrous", brand = 3 },
]

[sections.right_leg]
armor = 28
slots = [
    { at = 5, item = "IS.StreakSRM-2", modes = ["OneShot"], brand = 4 },
    { at = 6, item = "FerroFibrous", brand = 3 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallPulseLaser", modes = ["RearMount"], brand = 3 },
]
