name = "Wasp"
class = "mech"
movement = "biped"
tons = 20
walk_mp = 9
jump_mp = 6
computer = 4
radio = 4

[construction]
structure = "endo_steel"
armor = "ferro_fibrous"
brand = 3

[sections.left_arm]
armor = 5
slots = [
    { at = "5-11", item = "FerroFibrous", brand = 3 },
]

[sections.right_arm]
armor = 5
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumPulseLaser", brand = 3 },
    { at = "5-11", item = "FerroFibrous", brand = 3 },
]

[sections.left_torso]
armor = 6
rear = 2
slots = [
    { at = "1-3", item = "HeatSink", brand = 3 },
    { at = 4, item = "IS.Flamer", brand = 3 },
    { at = "5-11", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 6
rear = 2
slots = [
    { at = "1-3", item = "HeatSink", brand = 3 },
    { at = "4-5", item = "IS.SmallLaser", brand = 3 },
    { at = "6-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 7
rear = 3
slots = [
    { at = "11-12", item = "JumpJet", brand = 3 },
]

[sections.left_leg]
armor = 6
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.right_leg]
armor = 6
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.head]
armor = 6
