name = "Wasp"
class = "mech"
movement = "biped"
tons = 20
max_speed = 96.75
jump_speed = 64.5

[sections.left_arm]
armor = 4
internals = 3
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
]

[sections.right_arm]
armor = 4
internals = 3
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = "4-5", item = "IS.SmallLaser" },
]

[sections.left_torso]
armor = 6
internals = 5
rear = 2
slots = [
    { at = "1-2", item = "IS.SmallLaser" },
    { at = 7, item = "JumpJet" },
    { at = "8-9", item = "HeatSink" },
]

[sections.right_torso]
armor = 6
internals = 5
rear = 2
slots = [
    { at = "1-2", item = "IS.SmallLaser" },
    { at = 7, item = "JumpJet" },
    { at = "8-9", item = "HeatSink" },
]

[sections.center_torso]
armor = 6
internals = 6
rear = 4
slots = [
    { at = "1-3", item = "Engine" },
    { at = "4-7", item = "Gyro" },
    { at = "8-10", item = "Engine" },
    { at = "11-12", item = "JumpJet" },
]

[sections.left_leg]
armor = 5
internals = 4
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "JumpJet" },
    { at = 6, item = "HeatSink" },
]

[sections.right_leg]
armor = 5
internals = 4
slots = [
    { at = 1, item = "ShoulderOrHip" },
    { at = 2, item = "UpperActuator" },
    { at = 3, item = "LowerActuator" },
    { at = 4, item = "HandOrFootActuator" },
    { at = 5, item = "JumpJet" },
    { at = 6, item = "HeatSink" },
]

[sections.head]
armor = 4
internals = 3
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 5, item = "Sensors" },
    { at = 6, item = "LifeSupport" },
]
