name = "Wolverine"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 8
jump_mp = 5
heat_sinks = 26
computer = 4
radio = 4
specials = ["C3SlaveTech"]

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"

[sections.left_arm]
armor = 18
slots = [
    { at = "5-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 18
slots = [
    { at = "5-6", item = "IS.LargePulseLaser" },
    { at = 7, item = "IS.SmallPulseLaser" },
]

[sections.left_torso]
armor = 20
rear = 6
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = "7-8", item = "JumpJet" },
    { at = "9-10", item = "IS.StreakSRM-6" },
    { at = "11-12", item = "EndoSteel" },
]

[sections.right_torso]
armor = 20
rear = 6
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = "7-8", item = "JumpJet" },
    { at = "9-10", item = "IS.StreakSRM-6" },
    { at = 11, item = "Ammo_IS.StreakSRM-6", rounds = 15 },
]

[sections.center_torso]
armor = 26
rear = 9
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "C3Slave" },
]

[sections.left_leg]
armor = 26
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 26
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
]
