name = "Yu Huang"
class = "mech"
movement = "biped"
tons = 90
walk_mp = 6
jump_mp = 4
heat_sinks = 32
computer = 4
radio = 4

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"
brand = 3

[sections.left_arm]
armor = 29
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser", brand = 3 },
    { at = "5-6", item = "BeagleProbe", brand = 3 },
    { at = "7-9", item = "HeatSink", brand = 3 },
    { at = "10-12", item = "EndoSteel", brand = 3 },
]

[sections.right_arm]
armor = 29
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-9", item = "IS.GaussRifle", brand = 3 },
    { at = "10-12", item = "HeatSink", brand = 3 },
]

[sections.left_torso]
armor = 28
rear = 9
slots = [
    { at = "4-6", item = "IS.ERMediumLaser", brand = 3 },
    { at = "7-12", item = "EndoSteel", brand = 3 },
]

[sections.right_torso]
armor = 28
rear = 9
slots = [
    { at = "4-6", item = "IS.ERMediumLaser", brand = 3 },
    { at = "7-8", item = "Ammo_IS.GaussRifle", rounds = 8 },
    { at = "9-12", item = "EndoSteel", brand = 3 },
]

[sections.center_torso]
armor = 43
rear = 14
slots = [
    { at = "11-12", item = "Ecm", brand = 3 },
]

[sections.left_leg]
armor = 37
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.right_leg]
armor = 37
slots = [
    { at = "5-6", item = "JumpJet", brand = 3 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "EndoSteel", brand = 3 },
]
