name = "Yellow Jacket"
class = "vtol"
movement = "vtol"
tons = 30
max_speed = 96.75
specials = ["Searchlight"]

[sections.left_side]
armor = 9
internals = 3

[sections.right_side]
armor = 9
internals = 3

[sections.front_side]
armor = 15
internals = 3
slots = [
    { at = 1, item = "IS.GaussRifle" },
    { at = "2-5", item = "Ammo_IS.GaussRifle", rounds = 8 },
]

[sections.aft_side]
armor = 5
internals = 3

[sections.rotor]
armor = 2
internals = 3
