name = "Zephyr"
class = "vehicle"
movement = "hover"
tons = 40
max_speed = 150.5
heat_sinks = 11
cargo_space = 256
specials = ["XLEngine_Tech"]

[sections.left_side]
armor = 24
internals = 4

[sections.right_side]
armor = 24
internals = 4

[sections.front_side]
armor = 29
internals = 4
slots = [
    { at = 1, item = "IS.SRM-6", brand = 3 },
    { at = 2, item = "Ecm", brand = 3 },
    { at = "3-4", item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.aft_side]
armor = 19
internals = 4
slots = [
    { at = 1, item = "IS.SmallLaser", brand = 3 },
]

[sections.turret]
armor = 29
internals = 4
slots = [
    { at = "1-3", item = "IS.MediumPulseLaser", brand = 3 },
]
