name = "Zeus"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
heat_sinks = 20
computer = 4
specials = ["ArtemisIV"]

[construction]
tech_base = "clan"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 25
omit = ["hand_actuator"]
slots = [
    { at = "4-9", item = "CL.GaussRifle" },
    { at = "10-12", item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.right_arm]
armor = 25
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "FerroFibrous" },
    { at = "6-7", item = "CL.LRM-15" },
    { at = 8, item = "ArtemisIV" },
    { at = "9-11", item = "Ammo_CL.LRM-15", rounds = 8, modes = ["Artemis/Mine"] },
]

[sections.left_torso]
armor = 27
rear = 7
slots = [
    { at = 1, item = "FerroFibrous" },
    { at = "2-3", item = "CL.ERPPC" },
    { at = 4, item = "CL.ERMediumLaser", modes = ["RearMount"] },
]

[sections.right_torso]
armor = 27
rear = 7
slots = [
    { at = 1, item = "FerroFibrous" },
]

[sections.center_torso]
armor = 33
rear = 10
slots = [
    { at = 11, item = "CL.ERMediumLaser" },
]

[sections.left_leg]
armor = 30
slots = [
    { at = 5, item = "FerroFibrous" },
]

[sections.right_leg]
armor = 30
slots = [
    { at = 5, item = "FerroFibrous" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
