name = "Zeus"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 6
heat_sinks = 34
radio = 4

[construction]
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 22
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "IS.ERPPC" },
    { at = "7-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 22
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "IS.LRM-15" },
    { at = "7-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 25
rear = 6
slots = [
    { at = "1-9", item = "HeatSink" },
    { at = "10-11", item = "IS.ERLargeLaser" },
    { at = 12, item = "IS.MediumPulseLaser", modes = ["RearMount"] },
]

[sections.right_torso]
armor = 25
rear = 6
slots = [
    { at = "1-6", item = "HeatSink" },
    { at = 7, item = "Ammo_IS.LRM-15", rounds = 8 },
    { at = 8, item = "Case" },
    { at = "9-10", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 26
rear = 8
slots = [
    { at = 11, item = "IS.MediumPulseLaser" },
]

[sections.left_leg]
armor = 24

[sections.right_leg]
armor = 24

[sections.head]
armor = 9
