name = "Zhukov"
class = "vehicle"
movement = "track"
tons = 75
walk_mp = 5

[construction]
engine = "ice"

[sections.left_side]
armor = 32

[sections.right_side]
armor = 32

[sections.front_side]
armor = 44
slots = [
    { at = 1, item = "IS.SRM-6", brand = 3 },
    { at = 2, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.aft_side]
armor = 24

[sections.turret]
armor = 44
slots = [
    { at = "1-2", item = "IS.AC/10", brand = 3 },
    { at = "3-4", item = "Ammo_IS.AC/10", rounds = 10 },
]
