name = "Axeman"
class = "mech"
movement = "biped"
tons = 65
walk_mp = 6
jump_mp = 4
heat_sinks = 20
radio = 4
cargo_space = 0
max_suits = 0

[construction]
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 17
omit = ["hand_actuator"]
slots = [
    { at = "4-6", item = "IS.ERMediumLaser" },
    { at = "7-12", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 17
slots = [
    { at = "5-9", item = "Axe" },
    { at = "10-12", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 21
rear = 6
engine_slots = 2
slots = [
    { at = "3-4", item = "Ammo_IS.LB20-XAC", rounds = 5 },
    { at = "5-6", item = "Ammo_IS.LB20-XAC", rounds = 5, modes = ["LBX/Cluster"] },
    { at = "7-8", item = "Ecm" },
    { at = 9, item = "Case" },
    { at = "10-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 21
rear = 6
engine_slots = 1
slots = [
    { at = "2-12", item = "IS.LB20-XAC" },
]

[sections.center_torso]
armor = 28
rear = 6
engine_slots = 7
slots = [
    { at = 12, item = "FerroFibrous" },
]

[sections.left_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
