name = "Badger"
class = "vehicle"
movement = "track"
tons = 30
walk_mp = 9
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 4096
specials = ["CargoTech"]

[sections.left_side]
armor = 18

[sections.right_side]
armor = 18

[sections.front_side]
armor = 20

[sections.aft_side]
armor = 16

[sections.turret]
armor = 8
slots = [
    { at = 1, item = "IS.ERMediumLaser" },
    { at = 2, item = "IS.ERSmallLaser" },
]
