name = "Beagle"
class = "vehicle"
movement = "hover"
tons = 15
walk_mp = 18
cargo_space = 0
max_suits = 0

[sections.left_side]
armor = 12

[sections.right_side]
armor = 12

[sections.front_side]
armor = 15
slots = [
    { at = 1, item = "IS.SmallLaser" },
    { at = 2, item = "FerroFibrous" },
]

[sections.aft_side]
armor = 10

[sections.turret]
armor = 14
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "BeagleProbe" },
]
