name = "Blood Asp"
class = "mech"
movement = "biped"
tons = 90
walk_mp = 6
heat_sinks = 32
specials = ["ArtemisIV"]

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"

[sections.left_arm]
armor = 28
omit = ["hand_actuator"]
slots = [
    { at = "4-7", item = "CL.LRM-20" },
    { at = "8-9", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "10-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 28
omit = ["hand_actuator"]
slots = [
    { at = "4-7", item = "CL.LRM-20" },
    { at = "8-9", item = "Ammo_CL.LRM-20", rounds = 6, modes = ["Artemis/Mine"] },
    { at = "10-11", item = "HeatSink" },
    { at = 12, item = "EndoSteel" },
]

[sections.left_torso]
armor = 24
rear = 11
slots = [
    { at = "3-6", item = "CL.MediumPulseLaser" },
    { at = 7, item = "EndoSteel" },
]

[sections.right_torso]
armor = 24
rear = 11
slots = [
    { at = "3-8", item = "CL.GaussRifle" },
    { at = "9-10", item = "HeatSink" },
    { at = 11, item = "EndoSteel" },
]

[sections.center_torso]
armor = 40
rear = 13
slots = [
    { at = 11, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 12, item = "Ecm" },
]

[sections.left_leg]
armor = 34
slots = [
    { at = 5, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.right_leg]
armor = 34
slots = [
    { at = 5, item = "Ammo_CL.GaussRifle", rounds = 8 },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "EndoSteel" },
]
