name = "Banshee"
class = "mech"
movement = "biped"
tons = 95
walk_mp = 6
heat_sinks = 12

[sections.left_arm]
armor = 21

[sections.right_arm]
armor = 21

[sections.left_torso]
armor = 30
rear = 10
slots = [
    { at = "1-6", item = "Ammo_IS.AC/20", rounds = 5 },
]

[sections.right_torso]
armor = 30
rear = 10
slots = [
    { at = "1-10", item = "IS.AC/20" },
]

[sections.center_torso]
armor = 40
rear = 17

[sections.left_leg]
armor = 26

[sections.right_leg]
armor = 26

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallLaser" },
]
