name = "Bandersnatch"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 6
heat_sinks = 20
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 18
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.MediumLaser" },
    { at = "6-11", item = "IS.LB10-XAC" },
]

[sections.right_arm]
armor = 18
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "IS.MediumLaser" },
    { at = "6-11", item = "IS.LB10-XAC" },
]

[sections.left_torso]
armor = 23
rear = 8
slots = [
    { at = 4, item = "IS.LRM-5" },
    { at = 5, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 6, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 7, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = 8, item = "Case" },
]

[sections.right_torso]
armor = 23
rear = 8
slots = [
    { at = 4, item = "IS.LRM-5" },
    { at = 5, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 6, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 7, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = 8, item = "Case" },
]

[sections.center_torso]
armor = 23
rear = 10
slots = [
    { at = "11-12", item = "IS.MediumLaser", modes = ["RearMount"] },
]

[sections.left_leg]
armor = 18

[sections.right_leg]
armor = 18

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.LRM-5" },
]
