name = "Centipede"
class = "vehicle"
movement = "hover"
tons = 20
walk_mp = 12
heat_sinks = 3
cargo_space = 0
max_suits = 0

[construction]
engine = "ice"

[sections.left_side]
armor = 14

[sections.right_side]
armor = 14

[sections.front_side]
armor = 14
slots = [
    { at = 1, item = "IS.MediumLaser" },
    { at = 2, item = "BeagleProbe" },
]

[sections.aft_side]
armor = 14
slots = [
    { at = 1, item = "IS.VehicleFlamer" },
    { at = 2, item = "Ammo_IS.VehicleFlamer", rounds = 20 },
]
