name = "Chippewa"
class = "aerofighter"
movement = "fly"
tons = 90
walk_mp = 8
heat_sinks = 25
fuel = 750

[sections.nose]
armor = 39
internals = 10
slots = [
    { at = "1-2", item = "IS.MediumLaser" },
    { at = "3-4", item = "IS.LRM-15" },
]

[sections.left_wing]
armor = 30
internals = 10
slots = [
    { at = 1, item = "IS.LargeLaser" },
    { at = 3, item = "IS.LargeLaser" },
]

[sections.right_wing]
armor = 30
internals = 10
slots = [
    { at = 1, item = "IS.LargeLaser" },
    { at = 3, item = "IS.LargeLaser" },
]

[sections.cockpit]
armor = 16
internals = 10
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 34
internals = 10
slots = [
    { at = "1-2", item = "IS.SmallLaser" },
]

[sections.fuselage]
armor = 45
internals = 10
slots = [
    { at = "1-4", item = "Ammo_IS.LRM-15", rounds = 8 },
]
