name = "Champion"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 8
radio = 4
cargo_space = 0
max_suits = 0

[construction]
armor = "ferro_fibrous"

[sections.left_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]

[sections.right_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]

[sections.left_torso]
armor = 18
rear = 6
slots = [
    { at = 1, item = "IS.SRM-6", modes = ["Artemis/Mine"] },
    { at = 2, item = "IS.SRM-6" },
    { at = 3, item = "Ammo_IS.SRM-6", rounds = 15, modes = ["Artemis/Mine"] },
    { at = 4, item = "ArtemisIV" },
    { at = "5-6", item = "IS.MediumLaser" },
    { at = "7-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 18
rear = 6
slots = [
    { at = "1-6", item = "IS.LB10-XAC" },
    { at = 7, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 8, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = "9-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 24
rear = 8
slots = [
    { at = "11-12", item = "IS.SmallLaser" },
]

[sections.left_leg]
armor = 15
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.right_leg]
armor = 15
slots = [
    { at = "5-6", item = "FerroFibrous" },
]

[sections.head]
armor = 9
