name = "Chameleon"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 9
jump_mp = 6
heat_sinks = 20
radio = 4

[construction]
heat_sinks = "double"

[sections.left_arm]
armor = 16
slots = [
    { at = 5, item = "IS.MediumPulseLaser" },
]

[sections.right_arm]
armor = 16
slots = [
    { at = "5-6", item = "IS.ERLargeLaser" },
    { at = 7, item = "IS.MediumLaser" },
]

[sections.left_torso]
armor = 16
rear = 5
slots = [
    { at = 2, item = "JumpJet" },
]

[sections.right_torso]
armor = 16
rear = 5
slots = [
    { at = 1, item = "JumpJet" },
]

[sections.center_torso]
armor = 22
rear = 7

[sections.left_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
