name = "Centurion"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 9
radio = 4
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"
structure = "endo_steel"

[sections.left_arm]
armor = 16
slots = [
    { at = "5-7", item = "EndoSteel" },
]

[sections.right_arm]
armor = 16
omit = ["hand_actuator"]
slots = [
    { at = "4-9", item = "IS.LB10-XAC" },
    { at = "10-12", item = "EndoSteel" },
]

[sections.left_torso]
armor = 13
rear = 6
slots = [
    { at = 4, item = "IS.LRM-10", modes = ["Artemis/Mine"] },
    { at = 5, item = "IS.LRM-10" },
    { at = 6, item = "ArtemisIV" },
    { at = "7-10", item = "EndoSteel" },
]

[sections.right_torso]
armor = 13
rear = 6
slots = [
    { at = 4, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = 5, item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = "6-7", item = "Ammo_IS.LRM-10", rounds = 12, modes = ["Artemis/Mine"] },
    { at = 8, item = "Case" },
    { at = "9-12", item = "EndoSteel" },
]

[sections.center_torso]
armor = 18
rear = 7
slots = [
    { at = 11, item = "IS.MediumLaser" },
    { at = 12, item = "IS.MediumLaser", modes = ["RearMount"] },
]

[sections.left_leg]
armor = 16

[sections.right_leg]
armor = 16

[sections.head]
armor = 9
