name = "Crab"
class = "mech"
movement = "biped"
tons = 50
walk_mp = 8
heat_sinks = 24
cargo_space = 0
max_suits = 0

[construction]
armor = "ferro_fibrous"
heat_sinks = "double"

[sections.left_arm]
armor = 16
slots = [
    { at = "5-7", item = "IS.PPC" },
    { at = "8-10", item = "HeatSink" },
]

[sections.right_arm]
armor = 16
slots = [
    { at = "5-7", item = "IS.PPC" },
    { at = "8-10", item = "HeatSink" },
]

[sections.left_torso]
armor = 16
rear = 6
slots = [
    { at = "1-7", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 16
rear = 6
slots = [
    { at = "1-7", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 20
rear = 9
slots = [
    { at = 11, item = "IS.MediumLaser" },
]

[sections.left_leg]
armor = 24

[sections.right_leg]
armor = 24

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallLaser" },
]
