name = "Corsair"
class = "aerofighter"
movement = "fly"
tons = 50
walk_mp = 9
heat_sinks = 16
fuel = 750

[sections.nose]
armor = 49
internals = 10
slots = [
    { at = "1-2", item = "IS.SRM-6" },
]

[sections.left_wing]
armor = 34
internals = 10
slots = [
    { at = 1, item = "IS.SRM-4" },
]

[sections.right_wing]
armor = 34
internals = 10
slots = [
    { at = 1, item = "IS.SRM-4" },
]

[sections.cockpit]
armor = 16
internals = 10
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 28
internals = 10
slots = [
    { at = "1-2", item = "HeatSink" },
    { at = "4-10", item = "HeatSink" },
    { at = 12, item = "HeatSink" },
]

[sections.fuselage]
armor = 49
internals = 10
slots = [
    { at = "1-2", item = "Ammo_IS.SRM-6", rounds = 15 },
    { at = "3-4", item = "Ammo_IS.SRM-4", rounds = 25 },
]
