name = "Falcon_Hovertruck"
class = "vehicle"
movement = "hover"
tons = 15
walk_mp = 14
specials = ["CargoTech"]

[construction]
engine = "ice"

[sections.left_side]
armor = 12

[sections.right_side]
armor = 12

[sections.front_side]
armor = 14

[sections.aft_side]
armor = 10
