name = "Goliath"
class = "mech"
movement = "quad"
tons = 80
walk_mp = 6
heat_sinks = 20
radio = 4

[construction]
engine = "light"
heat_sinks = "double"

[sections.front_left_leg]
armor = 33

[sections.front_right_leg]
armor = 33

[sections.left_torso]
armor = 25
rear = 8
engine_slots = 0
slots = [
    { at = "1-11", item = "IS.HeavyGaussRifle" },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 25
rear = 8
slots = [
    { at = "3-4", item = "IS.ERMediumLaser" },
    { at = "5-6", item = "IS.LRM-10" },
    { at = "7-8", item = "Ammo_IS.LRM-10", rounds = 12 },
    { at = 12, item = "Case" },
]

[sections.center_torso]
armor = 37
rear = 12
engine_slots = 8

[sections.rear_left_leg]
armor = 33
slots = [
    { at = "5-6", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]

[sections.rear_right_leg]
armor = 33
slots = [
    { at = "5-6", item = "Ammo_IS.HeavyGaussRifle", rounds = 4 },
]

[sections.head]
armor = 9
