name = "Warrior"
class = "vtol"
movement = "vtol"
tons = 21
walk_mp = 15
specials = ["SearchLight"]

[construction]
engine = "ice"

[sections.left_side]
armor = 5

[sections.right_side]
armor = 5

[sections.front_side]
armor = 6
slots = [
    { at = 1, item = "IS.AC/2" },
    { at = 2, item = "IS.SRM-4" },
    { at = 3, item = "Ammo_IS.AC/2", rounds = 45 },
    { at = 4, item = "Ammo_IS.SRM-4", rounds = 25 },
]

[sections.aft_side]
armor = 6

[sections.rotor]
armor = 2
