name = "Hatamoto-Chi"
class = "mech"
movement = "biped"
tons = 80
walk_mp = 5
jump_mp = 3
heat_sinks = 34
radio = 4
cargo_space = 0
max_suits = 0

[construction]
heat_sinks = "double"

[sections.left_arm]
armor = 26
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "HeatSink" },
    { at = "9-11", item = "IS.ERPPC" },
    { at = 12, item = "IS.ERMediumLaser" },
]

[sections.right_arm]
armor = 26
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-8", item = "HeatSink" },
    { at = "9-11", item = "IS.ERPPC" },
    { at = 12, item = "IS.ERMediumLaser" },
]

[sections.left_torso]
armor = 25
rear = 9
slots = [
    { at = "1-6", item = "HeatSink" },
    { at = 7, item = "JumpJet" },
    { at = "8-9", item = "IS.StreakSRM-6" },
    { at = 10, item = "Ammo_IS.StreakSRM-6", rounds = 15 },
    { at = 11, item = "Case" },
]

[sections.right_torso]
armor = 25
rear = 9
slots = [
    { at = "1-6", item = "HeatSink" },
    { at = 7, item = "JumpJet" },
    { at = "8-9", item = "IS.StreakSRM-6" },
    { at = 10, item = "Ammo_IS.StreakSRM-6", rounds = 15 },
    { at = 11, item = "Case" },
]

[sections.center_torso]
armor = 34
rear = 16
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "C3Slave" },
]

[sections.left_leg]
armor = 34

[sections.right_leg]
armor = 34

[sections.head]
armor = 9
