name = "IS PowerArmor"
class = "battlesuit"
movement = "biped"
tons = 1
max_speed = 32.5
jump_speed = 32.5
max_suits = 4
infantry_specials = ["Swarm_Attack_Tech", "Mount_Friends_Tech", "AntiLeg_Attack_Tech"]

[sections.suit_1]
armor = 9
internals = 1
slots = [
    { at = 1, item = "IS.SRM-2" },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 2 },
]

[sections.suit_2]
armor = 9
internals = 1
slots = [
    { at = 1, item = "IS.SRM-2" },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 2 },
]

[sections.suit_3]
armor = 9
internals = 1
slots = [
    { at = 1, item = "IS.SRM-2" },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 2 },
]

[sections.suit_4]
armor = 9
internals = 1
slots = [
    { at = 1, item = "IS.SRM-2" },
    { at = 2, item = "Ammo_IS.SRM-2", rounds = 2 },
]
