name = "Javelin"
class = "mech"
movement = "biped"
tons = 30
walk_mp = 9
jump_mp = 6
radio = 4

[construction]

[sections.left_arm]
armor = 6

[sections.right_arm]
armor = 6

[sections.left_torso]
armor = 8
rear = 2
slots = [
    { at = 1, item = "HeatSink" },
    { at = "2-3", item = "IS.StreakSRM-2" },
    { at = 4, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.right_torso]
armor = 8
rear = 2
slots = [
    { at = 1, item = "HeatSink" },
    { at = "2-3", item = "IS.SRM-6" },
    { at = 4, item = "Ammo_IS.SRM-6", rounds = 15 },
]

[sections.center_torso]
armor = 8
rear = 2
slots = [
    { at = "11-12", item = "JumpJet" },
]

[sections.left_leg]
armor = 8
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 8
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 6
slots = [
    { at = 4, item = "HeatSink" },
]
