name = "Komodo"
class = "mech"
movement = "biped"
tons = 45
walk_mp = 8
jump_mp = 5
heat_sinks = 28
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 14
slots = [
    { at = 5, item = "IS.Anti-MissileSystem" },
    { at = "6-7", item = "IS.ERLargeLaser" },
    { at = 8, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.right_arm]
armor = 14
slots = [
    { at = 5, item = "IS.Anti-MissileSystem" },
    { at = "6-10", item = "IS.MediumLaser" },
    { at = 11, item = "Ammo_IS.Anti-MissileSystem", rounds = 12 },
]

[sections.left_torso]
armor = 12
rear = 4
slots = [
    { at = "4-12", item = "HeatSink" },
]

[sections.right_torso]
armor = 12
rear = 4
slots = [
    { at = "4-9", item = "HeatSink" },
    { at = "10-11", item = "Ecm" },
]

[sections.center_torso]
armor = 13
rear = 6
slots = [
    { at = 11, item = "JumpJet" },
]

[sections.left_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 16
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "TAG" },
]
