name = "MadCat"
class = "mech"
movement = "biped"
tons = 75
walk_mp = 8
heat_sinks = 30

[construction]
tech_base = "clan"
engine = "xl"
structure = "endo_steel"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 24
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC" },
    { at = 12, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 24
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC" },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 25
rear = 7
engine_at = 7
slots = [
    { at = "1-2", item = "CL.StreakSRM-6" },
    { at = "3-4", item = "Ammo_CL.StreakSRM-6", rounds = 15 },
    { at = "5-6", item = "CL.StreakSRM-6", modes = ["RearMount"] },
    { at = 10, item = "EndoSteel" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 25
rear = 7
engine_at = 7
slots = [
    { at = "1-2", item = "CL.StreakSRM-6" },
    { at = "3-4", item = "Ammo_CL.StreakSRM-6", rounds = 15 },
    { at = "5-6", item = "CL.StreakSRM-6", modes = ["RearMount"] },
    { at = 10, item = "EndoSteel" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 36
rear = 9
slots = [
    { at = 12, item = "EndoSteel" },
]

[sections.left_leg]
armor = 32
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 32
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
