name = "Masakari"
class = "mech"
movement = "biped"
tons = 85
walk_mp = 6
heat_sinks = 40

[construction]
tech_base = "clan"
engine = "xl"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 28
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC", modes = ["OnTC"] },
    { at = 6, item = "FerroFibrous" },
    { at = "7-8", item = "CL.ERPPC", modes = ["OnTC"] },
    { at = 9, item = "CL.LRM-10" },
    { at = 10, item = "Ammo_CL.LRM-10", rounds = 12 },
]

[sections.right_arm]
armor = 28
omit = ["hand_actuator"]
slots = [
    { at = "4-5", item = "CL.ERPPC", modes = ["OnTC"] },
    { at = 6, item = "FerroFibrous" },
    { at = "7-8", item = "CL.ERPPC", modes = ["OnTC"] },
]

[sections.left_torso]
armor = 26
rear = 10
slots = [
    { at = "3-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 26
rear = 10
engine_at = 7
slots = [
    { at = "1-5", item = "TargetingComputer" },
    { at = "9-10", item = "HeatSink" },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 42
rear = 10

[sections.left_leg]
armor = 35
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.right_leg]
armor = 35
slots = [
    { at = "5-6", item = "HeatSink" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
