name = "Marshal"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 6
jump_mp = 4
heat_sinks = 18
radio = 4

[construction]
armor = "ferro_fibrous"

[sections.left_arm]
armor = 18
slots = [
    { at = 5, item = "IS.MediumLaser" },
    { at = "6-7", item = "FerroFibrous" },
]

[sections.right_arm]
armor = 18
slots = [
    { at = "5-6", item = "IS.LargeLaser" },
    { at = "7-8", item = "FerroFibrous" },
]

[sections.left_torso]
armor = 20
rear = 6
slots = [
    { at = "1-5", item = "HeatSink" },
    { at = "6-7", item = "IS.MachineGun" },
    { at = 8, item = "Ammo_IS.MachineGun", rounds = 100, modes = ["Hotload"] },
    { at = "9-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 20
rear = 6
slots = [
    { at = "1-5", item = "HeatSink" },
    { at = 6, item = "IS.MediumPulseLaser" },
    { at = 7, item = "IS.LRM-5" },
    { at = 8, item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "9-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 26
rear = 8
slots = [
    { at = 11, item = "IS.Flamer" },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 24
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
