name = "Night Hawk"
class = "mech"
movement = "biped"
tons = 35
walk_mp = 9
heat_sinks = 24
radio = 4

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = 3, item = "IS.MediumPulseLaser" },
]

[sections.right_arm]
armor = 10
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.ERLargeLaser" },
]

[sections.left_torso]
armor = 13
rear = 3
slots = [
    { at = "4-9", item = "HeatSink" },
]

[sections.right_torso]
armor = 13
rear = 3
slots = [
    { at = "4-9", item = "HeatSink" },
]

[sections.center_torso]
armor = 17
rear = 4
slots = [
    { at = "11-12", item = "IS.LargeLaser" },
]

[sections.left_leg]
armor = 15

[sections.right_leg]
armor = 15

[sections.head]
armor = 9
