name = "Partisan"
class = "vehicle"
movement = "track"
tons = 80
walk_mp = 5
specials = ["AntiAircraft"]

[sections.left_side]
armor = 26

[sections.right_side]
armor = 26

[sections.front_side]
armor = 35
slots = [
    { at = 1, item = "C3Slave" },
]

[sections.aft_side]
armor = 21

[sections.turret]
armor = 35
slots = [
    { at = "1-2", item = "IS.LB10-XAC" },
    { at = "3-4", item = "IS.AC/2" },
    { at = 5, item = "Ammo_IS.LB10-XAC", rounds = 10 },
    { at = "6-7", item = "Ammo_IS.LB10-XAC", rounds = 10, modes = ["LBX/Cluster"] },
    { at = 8, item = "Ammo_IS.AC/2", rounds = 45 },
]
