name = "Rifleman"
class = "mech"
movement = "biped"
tons = 60
walk_mp = 6
heat_sinks = 24
radio = 4
specials = ["SearchLight", "AntiAircraft"]

[construction]
engine = "xl"
heat_sinks = "double"

[sections.left_arm]
armor = 15
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.LargeLaser" },
    { at = "5-9", item = "IS.UltraAC/5" },
]

[sections.right_arm]
armor = 15
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.LargeLaser" },
    { at = "5-9", item = "IS.UltraAC/5" },
]

[sections.left_torso]
armor = 15
rear = 8
slots = [
    { at = "4-9", item = "HeatSink" },
    { at = 10, item = "IS.MediumLaser" },
]

[sections.right_torso]
armor = 15
rear = 8
slots = [
    { at = "4-6", item = "HeatSink" },
    { at = 7, item = "IS.MediumLaser" },
    { at = 8, item = "Ammo_IS.UltraAC/5", rounds = 20 },
    { at = 9, item = "Case" },
]

[sections.center_torso]
armor = 22
rear = 8

[sections.left_leg]
armor = 12

[sections.right_leg]
armor = 12

[sections.head]
armor = 6
