name = "Schiltron"
class = "vehicle"
movement = "wheel"
tons = 80
walk_mp = 5
tac_range = 30
lrs_range = 60
scan_range = 30
cargo_space = 0
max_suits = 0

[construction]
engine = "xl"

[sections.left_side]
armor = 34
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_side]
armor = 34
slots = [
    { at = "6-12", item = "FerroFibrous" },
]

[sections.front_side]
armor = 46
slots = [
    { at = 1, item = "IS.LRM-15" },
    { at = 2, item = "ArtemisIV" },
    { at = "3-5", item = "Ammo_IS.LRM-15", rounds = 8, modes = ["Artemis/Mine"] },
]

[sections.aft_side]
armor = 25
slots = [
    { at = 1, item = "C3Master" },
    { at = 2, item = "Ecm" },
    { at = 3, item = "TargetingComputer" },
]

[sections.turret]
armor = 40
slots = [
    { at = "1-2", item = "IS.RotaryAC/5", modes = ["OnTC"] },
    { at = "3-8", item = "Ammo_IS.RotaryAC/5", rounds = 20 },
]
