name = "Scytha"
class = "aerofighter"
movement = "fly"
tons = 90
walk_mp = 9
heat_sinks = 40
fuel = 600

[construction]
tech_base = "clan"
armor = "ferro_fibrous"

[sections.nose]
armor = 67
internals = 9
slots = [
    { at = "1-2", item = "CL.MediumPulseLaser" },
]

[sections.left_wing]
armor = 50
internals = 9
slots = [
    { at = 1, item = "CL.GaussRifle" },
    { at = 2, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 3, item = "CL.ERPPC" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.right_wing]
armor = 50
internals = 9
slots = [
    { at = 1, item = "CL.GaussRifle" },
    { at = 2, item = "Ammo_CL.GaussRifle", rounds = 8 },
    { at = 3, item = "CL.ERPPC" },
    { at = "6-12", item = "FerroFibrous" },
]

[sections.cockpit]
armor = 16
internals = 9
slots = [
    { at = 1, item = "LifeSupport" },
    { at = 2, item = "Sensors" },
    { at = 3, item = "Cockpit" },
    { at = 4, item = "Sensors" },
    { at = 5, item = "LifeSupport" },
]

[sections.engine]
armor = 32
internals = 9
slots = [
    { at = 1, item = "CL.ERSmallLaser" },
]

[sections.fuselage]
armor = 64
internals = 9
