name = "ShadowHawk"
class = "mech"
movement = "biped"
tons = 55
walk_mp = 8
jump_mp = 5
heat_sinks = 20
radio = 4

[construction]
engine = "xl"
structure = "endo_steel"
heat_sinks = "double"

[sections.left_arm]
armor = 18
slots = [
    { at = "5-12", item = "EndoSteel" },
]

[sections.right_arm]
armor = 18
slots = [
    { at = 5, item = "IS.ERMediumLaser" },
]

[sections.left_torso]
armor = 19
rear = 7
slots = [
    { at = "4-5", item = "JumpJet" },
    { at = "6-10", item = "IS.LightGaussRifle" },
    { at = 11, item = "Ammo_IS.LightGaussRifle", rounds = 16 },
    { at = 12, item = "Case" },
]

[sections.right_torso]
armor = 19
rear = 7
slots = [
    { at = "4-5", item = "JumpJet" },
    { at = "6-8", item = "IS.LRM-15" },
    { at = 9, item = "Ammo_IS.LRM-15", rounds = 8 },
    { at = "10-11", item = "EndoSteel" },
]

[sections.center_torso]
armor = 23
rear = 8
slots = [
    { at = 11, item = "JumpJet" },
    { at = 12, item = "Ammo_IS.StreakSRM-2", rounds = 50 },
]

[sections.left_leg]
armor = 20
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.right_leg]
armor = 20
slots = [
    { at = "5-6", item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.StreakSRM-2" },
]
