name = "Strider"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 9
radio = 4

[construction]
structure = "endo_steel"

[sections.left_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.NarcBeacon" },
]

[sections.right_arm]
armor = 12
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-4", item = "IS.NarcBeacon" },
]

[sections.left_torso]
armor = 14
rear = 5
config = "Case"
slots = [
    { at = 1, item = "TAG" },
    { at = 2, item = "Ammo_IS.NarcBeacon", rounds = 6 },
    { at = "3-8", item = "EndoSteel" },
    { at = 9, item = "Case" },
]

[sections.right_torso]
armor = 14
rear = 5
config = "Case"
slots = [
    { at = 1, item = "C3Slave" },
    { at = 2, item = "Ammo_IS.NarcBeacon", rounds = 6 },
    { at = "3-8", item = "EndoSteel" },
    { at = 9, item = "Case" },
]

[sections.center_torso]
armor = 15
rear = 6
slots = [
    { at = "11-12", item = "BeagleProbe" },
]

[sections.left_leg]
armor = 14
slots = [
    { at = 5, item = "HeatSink" },
    { at = 6, item = "EndoSteel" },
]

[sections.right_leg]
armor = 14
slots = [
    { at = 5, item = "EndoSteel" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.SmallLaser" },
]
