name = "Sentinel"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 9
radio = 4

[sections.left_arm]
armor = 8
omit = ["lower_actuator", "hand_actuator"]
slots = [
    { at = "3-6", item = "IS.AC/5" },
]

[sections.right_arm]
armor = 8

[sections.left_torso]
armor = 10
rear = 5
slots = [
    { at = "1-2", item = "Ammo_IS.AC/5", rounds = 20 },
    { at = 3, item = "HeatSink" },
]

[sections.right_torso]
armor = 10
rear = 5
slots = [
    { at = 1, item = "IS.SmallLaser" },
    { at = 2, item = "IS.SRM-2" },
    { at = 3, item = "Ammo_IS.SRM-2", rounds = 50 },
]

[sections.center_torso]
armor = 12
rear = 7

[sections.left_leg]
armor = 11

[sections.right_leg]
armor = 11

[sections.head]
armor = 9
