name = "ShaYu"
class = "mech"
movement = "biped"
tons = 40
walk_mp = 11
heat_sinks = 22
radio = 4
specials = ["ECM", "C3SlaveTech"]

[construction]
engine = "xl"
structure = "endo_steel"
armor = "stealth"
heat_sinks = "double"

[sections.left_arm]
armor = 12
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
    { at = "5-10", item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.right_arm]
armor = 12
omit = ["hand_actuator"]
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.left_torso]
armor = 15
rear = 5
slots = [
    { at = 4, item = "IS.ERMediumLaser" },
    { at = 5, item = "C3Slave" },
    { at = "6-10", item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.right_torso]
armor = 15
rear = 5
slots = [
    { at = 4, item = "IS.ERMediumLaser" },
    { at = 5, item = "IS.LRM-5" },
    { at = "6-7", item = "Ammo_IS.LRM-5", rounds = 24 },
    { at = "8-10", item = "EndoSteel" },
    { at = "11-12", item = "StealthArmor" },
]

[sections.center_torso]
armor = 17
rear = 6
slots = [
    { at = "11-12", item = "Ecm" },
]

[sections.left_leg]
armor = 20
slots = [
    { at = "5-6", item = "StealthArmor" },
]

[sections.right_leg]
armor = 20
slots = [
    { at = "5-6", item = "StealthArmor" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "IS.MediumPulseLaser" },
]
