name = "Thor"
class = "mech"
movement = "biped"
tons = 70
walk_mp = 8
jump_mp = 5
heat_sinks = 28

[construction]
tech_base = "clan"
engine = "xl"
armor = "ferro_fibrous"

[sections.left_arm]
armor = 17
omit = ["hand_actuator"]
slots = [
    { at = "4-11", item = "CL.UltraAC/20" },
    { at = 12, item = "FerroFibrous" },
]

[sections.right_arm]
armor = 17
slots = [
    { at = 5, item = "CL.ERLargeLaser" },
    { at = 6, item = "CL.ERSmallLaser" },
    { at = 12, item = "FerroFibrous" },
]

[sections.left_torso]
armor = 22
rear = 7
engine_at = 7
slots = [
    { at = "1-2", item = "Ammo_CL.UltraAC/20", rounds = 5 },
    { at = "3-4", item = "CL.StreakSRM-6" },
    { at = 5, item = "Ammo_CL.StreakSRM-6", rounds = 15 },
    { at = "11-12", item = "FerroFibrous" },
]

[sections.right_torso]
armor = 22
rear = 7
engine_at = 7
slots = [
    { at = "11-12", item = "FerroFibrous" },
]

[sections.center_torso]
armor = 27
rear = 8
slots = [
    { at = 11, item = "JumpJet" },
]

[sections.left_leg]
armor = 23
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.right_leg]
armor = 23
slots = [
    { at = "5-6", item = "JumpJet" },
]

[sections.head]
armor = 9
slots = [
    { at = 4, item = "FerroFibrous" },
]
